@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_965_2009158
	.thumb_func
	.type	 OvlFunc_965_2009158,function
OvlFunc_965_2009158:
	push	{lr}
	mov	r0, #1
	mov	r1, #1
	mov	r2, #1
	mov	r3, #0
	neg	r0, r0
	neg	r1, r1
	neg	r2, r2
	bl	__Func_80933f8
	mov	r0, #0
	mov	r1, #6
	mov	r2, #0
	bl	__Func_8092708
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_965_2009158,.Lfe1-OvlFunc_965_2009158

	.text
	.align	2, 0
