@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_928_2008e4c
	.thumb_func
	.type	 OvlFunc_928_2008e4c,function
OvlFunc_928_2008e4c:
	push	{r5, lr}
	ldr	r3, .L14
	ldr	r5, [r3]
	bl	__CutsceneStart
	mov	r2, #182
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	sub	r3, r3, #1
	cmp	r3, #6
	bhi	.L3
	ldr	r2, .L14+4
	lsl	r3, r3, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L11:
	.word	.L4
	.word	.L5
	.word	.L6
	.word	.L7
	.word	.L8
	.word	.L9
	.word	.L10
.L4:
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L14+8
	mov	r1, #81
	mov	r2, #18
	bl	__Func_8010560
	b	.L3
.L5:
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L14+12
	mov	r1, #83
	b	.L13
.L6:
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L14+12
	mov	r1, #86
	b	.L13
.L7:
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L14+16
	mov	r1, #84
	mov	r2, #24
	bl	__Func_8010560
	b	.L3
.L8:
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L14+16
	mov	r1, #72
	mov	r2, #7
	bl	__Func_8010560
	b	.L3
.L9:
	mov	r0, #188
	bl	__PlaySound
	ldr	r0, .L14+20
	mov	r1, #69
.L13:
	mov	r2, #11
	bl	__Func_8010560
	b	.L3
.L10:
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L14+24
	mov	r1, #83
	mov	r2, #7
	bl	__Func_8010560
.L3:
	mov	r2, #182
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r0, [r3, r2]
	bl	OvlFunc_928_2008de8
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L15:
	.align	2, 0
.L14:
	.word	iwram_3001ebc
	.word	.L11
	.word	.L1778
	.word	.L178e
	.word	.L17a4
	.word	.L17ba
	.word	.L17d0
.Lfe1:
	.size	 OvlFunc_928_2008e4c,.Lfe1-OvlFunc_928_2008e4c

	.text
	.align	2, 0
