@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_953_20091ac
	.thumb_func
	.type	 OvlFunc_953_20091ac,function
OvlFunc_953_20091ac:
	push	{lr}
	ldr	r0, .L3
	bl	__ClearFlag
	mov	r0, #141
	lsl	r0, r0, #2
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	565
.Lfe1:
	.size	 OvlFunc_953_20091ac,.Lfe1-OvlFunc_953_20091ac

	.text
	.align	2, 0
