@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_c_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_896_200a6e0
	.thumb_func
	.type	 OvlFunc_896_200a6e0,function
OvlFunc_896_200a6e0:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr	r0, .L7+4
	bl	__MessageID
	mov	r0, #5
	mov	r1, #0
	bl	__ActorMessage
	b	.L4
.L3:
	ldr	r0, .L7+8
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	ldr	r0, .L7+12
	bl	__MessageID
	b	.L6
.L5:
	ldr	r0, .L7+16
	bl	__MessageID
.L6:
	mov	r1, #0
	mov	r0, #5
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #5
	mov	r1, #0
	bl	__ActorMessage
.L4:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	2110
	.word	4297
	.word	2108
	.word	4218
	.word	4220
.Lfe1:
	.size	 OvlFunc_896_200a6e0,.Lfe1-OvlFunc_896_200a6e0

	.text
	.align	2, 0
