@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_a_c_c_a_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_939_2008c74
	.thumb_func
	.type	 OvlFunc_939_2008c74,function
OvlFunc_939_2008c74:
	push	{r5, r6, lr}
	ldr	r0, .L3
	sub	sp, sp, #8
	bl	__SetFlag
	bl	__CutsceneStart
	ldr	r2, .L3+4
	ldr	r1, .L3+8
	mov	r0, #0
	bl	__MapActor_SetSpeed
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #85
	strb	r3, [r0]
	mov	r1, #2
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r2, #8
	mov	r1, #0
	neg	r2, r2
	mov	r0, #0
	bl	__Func_80922c4
	mov	r0, #158
	bl	__PlaySound
	mov	r5, #41
	mov	r6, #4
	mov	r1, #4
	mov	r2, #2
	mov	r3, #2
	mov	r0, #53
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_80105d4
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #6
	mov	r2, #2
	mov	r3, #2
	mov	r0, #53
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_80105d4
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	bl	__Func_8091e9c
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	578
	.word	6553
	.word	13107
.Lfe1:
	.size	 OvlFunc_939_2008c74,.Lfe1-OvlFunc_939_2008c74

	.text
	.align	2, 0
