@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_a_c_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_939_2008884
	.thumb_func
	.type	 OvlFunc_939_2008884,function
OvlFunc_939_2008884:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L3
	bl	__MessageID
	mov	r1, #0
	mov	r0, #15
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	7088
.Lfe1:
	.size	 OvlFunc_939_2008884,.Lfe1-OvlFunc_939_2008884

	.text
	.align	2, 0
