@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_925_200856c
	.thumb_func
	.type	 OvlFunc_925_200856c,function
OvlFunc_925_200856c:
	push	{lr}
	bl	__CutsceneStart
	bl	__Func_8078144
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #1
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #2
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #3
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #152
	mov	r1, #1
	mov	r2, #240
	mov	r3, #0
	neg	r1, r1
	lsl	r2, r2, #15
	lsl	r0, r0, #17
	bl	__Func_80933f8
	mov	r0, #1
	bl	__WaitFrames
	bl	__Func_800fe9c
	mov	r0, #1
	bl	__WaitFrames
	mov	r0, #141
	bl	__PlaySound
	mov	r0, #160
	mov	r1, #160
	mov	r2, #128
	lsl	r1, r1, #11
	lsl	r2, r2, #9
	lsl	r0, r0, #11
	bl	__Func_8012330
	ldr	r0, .L6
	bl	__PlaySound
	mov	r0, #1
	mov	r1, #1
	neg	r1, r1
	neg	r0, r0
	ldr	r2, .L6+4
	bl	__Func_8012330
	ldr	r3, .L6+8
	mov	r2, #224
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	sub	r2, r2, #192
	str	r2, [r3]
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	bl	__Func_8012350
	mov	r0, #30
	bl	__CutsceneWait
	bl	__Func_8093554
	mov	r3, #0
	add	r0, r0, #85
	strb	r3, [r0]
	ldr	r1, .L6+12
	ldr	r0, .L6+16
	bl	__Func_80933d4
	mov	r0, #128
	mov	r2, #160
	mov	r3, #1
	lsl	r2, r2, #16
	lsl	r0, r0, #18
	ldr	r1, .L6+20
	bl	__Func_80933f8
	bl	__Func_8093530
	mov	r0, #128
	lsl	r0, r0, #9
	mov	r1, #0
	bl	__Func_8091220
	mov	r1, #0
	ldr	r0, .L6+24
	bl	__Func_8091200
	mov	r0, #50
	bl	__Func_8091254
	mov	r0, #50
	bl	__CutsceneWait
	mov	r1, #0
	ldr	r0, .L6+28
	bl	__Func_8091200
	mov	r0, #30
	bl	__Func_8091254
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #252
	mov	r2, #168
	mov	r0, #0
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #132
	mov	r2, #144
	mov	r0, #1
	lsl	r1, r1, #18
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #244
	mov	r2, #144
	mov	r0, #2
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #128
	mov	r2, #152
	lsl	r2, r2, #16
	mov	r0, #3
	lsl	r1, r1, #18
	bl	__MapActor_SetPos
	mov	r0, #0
	mov	r1, #19
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #19
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #19
	bl	__MapActor_SetAnim
	mov	r1, #19
	mov	r0, #3
	bl	__MapActor_SetAnim
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #128
	mov	r1, #0
	lsl	r0, r0, #9
	bl	__Func_8091200
	mov	r0, #30
	bl	__Func_8091254
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #80
	bl	__CutsceneWait
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #4
	bl	__MapActor_DoAnim
	mov	r1, #192
	mov	r2, #20
	mov	r0, #0
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r1, #2
	mov	r0, #0
	bl	__Func_809259c
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #1
	bl	__MapActor_GetActor
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r1, #1
	mov	r0, #1
	bl	__MapActor_SetAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #6
	mov	r2, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #192
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #0
	mov	r1, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #2
	bl	__MapActor_GetActor
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r0, #2
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #3
	bl	__MapActor_GetActor
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r1, #1
	mov	r0, #3
	bl	__MapActor_SetAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #1
	ldr	r1, .L6+16
	ldr	r2, .L6+32
	bl	__MapActor_SetSpeed
	mov	r0, #2
	ldr	r1, .L6+16
	ldr	r2, .L6+32
	bl	__MapActor_SetSpeed
	ldr	r2, .L6+32
	mov	r0, #3
	ldr	r1, .L6+16
	bl	__MapActor_SetSpeed
	mov	r0, #1
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L3
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #1
	bl	__MapActor_TravelTo
.L3:
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L4
	mov	r2, #10
	ldrsh	r1, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #2
	bl	__MapActor_TravelTo
.L4:
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L5
	mov	r2, #10
	ldrsh	r1, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #3
	bl	__MapActor_TravelTo
.L5:
	mov	r0, #3
	bl	__MapActor_WaitMovement
	mov	r1, #0
	mov	r2, #0
	mov	r0, #3
	bl	__MapActor_SetPos
	mov	r0, #2
	bl	__MapActor_WaitMovement
	mov	r1, #0
	mov	r2, #0
	mov	r0, #2
	bl	__MapActor_SetPos
	mov	r0, #1
	bl	__MapActor_WaitMovement
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	289
	.word	58982
	.word	iwram_3001ebc
	.word	6553
	.word	52428
	.word	-1572864
	.word	65541
	.word	32767
	.word	26214
.Lfe1:
	.size	 OvlFunc_925_200856c,.Lfe1-OvlFunc_925_200856c

	.text
	.align	2, 0
