@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_930_2009144
	.thumb_func
	.type	 OvlFunc_930_2009144,function
OvlFunc_930_2009144:
	push	{lr}
	sub	sp, sp, #8
	bl	__CutsceneStart
	mov	r3, #21
	mov	r2, #11
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r1, #6
	mov	r2, #1
	mov	r3, #2
	mov	r0, #14
	bl	__Func_8010704
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r3, #254
	add	r0, r0, #89
	strb	r3, [r0]
	ldr	r0, .L3
	bl	__SetFlag
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	513
.Lfe1:
	.size	 OvlFunc_930_2009144,.Lfe1-OvlFunc_930_2009144

	.text
	.align	2, 0
