@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_930_20080b8
	.thumb_func
	.type	 OvlFunc_930_20080b8,function
OvlFunc_930_20080b8:
	push	{lr}
	ldr	r3, .L4
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L4+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L4+8
	b	.L2
.L3:
	ldr	r0, .L4+12
.L2:
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	gState
	.word	_ID_4a
	.word	.L1a38
	.word	.L1918
.Lfe1:
	.size	 OvlFunc_930_20080b8,.Lfe1-OvlFunc_930_20080b8

	.text
	.align	2, 0
