@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_930_2008fcc
	.thumb_func
	.type	 OvlFunc_930_2008fcc,function
OvlFunc_930_2008fcc:
	push	{lr}
	bl	__CutsceneStart
	mov	r0, #0
	mov	r1, #1
	bl	__MapActor_SetAnim
	ldr	r0, .L3
	mov	r1, #1
	bl	__Func_801776c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	6674
.Lfe1:
	.size	 OvlFunc_930_2008fcc,.Lfe1-OvlFunc_930_2008fcc

	.text
	.align	2, 0
