@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_930_20080ac
	.thumb_func
	.type	 OvlFunc_930_20080ac,function
OvlFunc_930_20080ac:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_930_20080ac,.Lfe1-OvlFunc_930_20080ac

	.text
	.align	2, 0
