@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_942_200819c
	.thumb_func
	.type	 OvlFunc_942_200819c,function
OvlFunc_942_200819c:
	push	{lr}
	ldr	r3, .L10
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L10+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L10+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	ldr	r0, .L10+12
	b	.L2
.L4:
	ldr	r0, .L10+16
	b	.L2
.L3:
	ldr	r3, .L10+20
	cmp	r2, r3
	bne	.L5
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	ldr	r0, .L10+24
	b	.L2
.L6:
	ldr	r0, .L10+28
	b	.L2
.L5:
	ldr	r3, .L10+32
	cmp	r2, r3
	bne	.L7
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L8
	ldr	r0, .L10+36
	b	.L2
.L8:
	ldr	r0, .L10+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L9
	ldr	r0, .L10+40
	b	.L2
.L9:
	ldr	r0, .L10+44
	b	.L2
.L7:
	ldr	r0, .L10+48
.L2:
	pop	{r1}
	bx	r1
.L11:
	.align	2, 0
.L10:
	.word	gState
	.word	_AREA_6b
	.word	2366
	.word	GFX_Thermometer
	.word	.L1e80
	.word	_AREA_70
	.word	.L2120
	.word	.L2018
	.word	_AREA_6c
	.word	.L2390
	.word	.L230c
	.word	.L224c
	.word	.L1e74
.Lfe1:
	.size	 OvlFunc_942_200819c,.Lfe1-OvlFunc_942_200819c

	.text
	.align	2, 0
