@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_942_2008144
	.thumb_func
	.type	 OvlFunc_942_2008144,function
OvlFunc_942_2008144:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L3
	bl	__SetFlag
	mov	r1, #196
	mov	r2, #148
	mov	r0, #0
	lsl	r1, r1, #1
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r0, #8
	ldr	r1, .L3+4
	ldr	r2, .L3+8
	bl	__MapActor_SetSpeed
	mov	r1, #204
	mov	r2, #148
	mov	r0, #8
	lsl	r1, r1, #1
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r1, #128
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #8
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	2218
	.word	78643
	.word	39321
.Lfe1:
	.size	 OvlFunc_942_2008144,.Lfe1-OvlFunc_942_2008144

	.text
	.align	2, 0
