@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_886_20082bc
	.thumb_func
	.type	 OvlFunc_886_20082bc,function
OvlFunc_886_20082bc:
	push	{r5, lr}
	mov	r5, r0
	ldr	r0, .L4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	bl	__Func_8095214
.L3:
	mov	r0, #123
	bl	__PlaySound
	ldr	r3, .L4+4
	ldr	r1, [r3]
	mov	r3, #224
	lsl	r3, r3, #1
	add	r2, r1, r3
	add	r3, r3, #73
	str	r3, [r2]
	sub	r3, r3, #65
	add	r2, r1, r3
	mov	r3, #16
	str	r3, [r2]
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	mov	r0, r5
	bl	__Func_8091e9c
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	2100
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_886_20082bc,.Lfe1-OvlFunc_886_20082bc

	.text
	.align	2, 0
