@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_886_2008088
	.thumb_func
	.type	 OvlFunc_886_2008088,function
OvlFunc_886_2008088:
	mov	r1, r0
	add	r1, r1, #100
	mov	r3, #0
	ldrsh	r2, [r1, r3]
	ldr	r3, [r0, #8]
	lsl	r2, r2, #8
	add	r3, r3, r2
	str	r3, [r0, #8]
	mov	r4, #102
	add	r4, r4, r0
	mov	r3, #0
	ldrsh	r2, [r4, r3]
	ldr	r3, [r0, #12]
	lsl	r2, r2, #8
	add	r3, r3, r2
	str	r3, [r0, #12]
	ldr	r2, .L3
	ldr	r3, [r0, #24]
	add	r3, r3, r2
	str	r3, [r0, #24]
	ldr	r3, [r0, #28]
	add	r3, r3, r2
	str	r3, [r0, #28]
	ldrh	r3, [r1]
	add	r3, r3, #5
	strh	r3, [r1]
	ldrh	r3, [r4]
	sub	r3, r3, #1
	strh	r3, [r4]
	mov	r0, #0
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	1638
.Lfe1:
	.size	 OvlFunc_886_2008088,.Lfe1-OvlFunc_886_2008088

	.text
	.align	2, 0
