@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_f9080_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	PauseSound
	.thumb_func
	.type	 PauseSound,function
PauseSound:
	push	{lr}
	bl	m4aMPlayAllStop
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 PauseSound,.Lfe1-PauseSound
	.align	2, 0
	.global	ContinueSound
	.thumb_func
	.type	 ContinueSound,function
ContinueSound:
	push	{lr}
	bl	m4aMPlayAllContinue
	pop	{r0}
	bx	r0
.Lfe2:
	.size	 ContinueSound,.Lfe2-ContinueSound

	.text
	.align	2, 0
