@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	UIBox_WaitAnim
	.thumb_func
	.type	 UIBox_WaitAnim,function
UIBox_WaitAnim:
	push	{r5, lr}
	mov	r5, r0
	ldrh	r2, [r5, #22]
	mov	r3, #2
	and	r3, r3, r2
	cmp	r3, #0
	bne	.L3
	mov	r2, #26
	ldrsh	r3, [r5, r2]
	cmp	r3, #0
	beq	.L3
.L6:
	mov	r0, #1
	bl	WaitFrames
	mov	r2, #26
	ldrsh	r3, [r5, r2]
	cmp	r3, #0
	bne	.L6
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 UIBox_WaitAnim,.Lfe1-UIBox_WaitAnim

	.text
	.align	2, 0
