@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_20198_c_c_c_a_c_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8021b80
	.thumb_func
	.type	 Func_8021b80,function
Func_8021b80:
	push	{r5, lr}
	sub	sp, sp, #16
	mov	r5, r0
	str	r1, [sp, #12]
	cmp	r5, #7
	bls	.L3
	mov	r5, #0
.L3:
	mov	r0, #32
	bl	_GetFlag
	cmp	r0, #0
	beq	.L4
	cmp	r5, #0
	beq	.L6
	cmp	r5, #1
	beq	.L7
	b	.L4
.L6:
	mov	r5, #56
	b	.L4
.L7:
	mov	r5, #57
.L4:
	mov	r1, #14
	str	r1, [sp]
	mov	r1, #1
	add	r2, sp, #12
	add	r3, sp, #8
	str	r1, [sp, #4]
	mov	r0, r5
	mov	r1, #0
	bl	LoadPortrait
	ldr	r0, [sp, #8]
	add	sp, sp, #16
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_8021b80,.Lfe1-Func_8021b80

	.text
	.align	2, 0
