@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1ca1c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801ce90
	.thumb_func
	.type	 Func_801ce90,function
Func_801ce90:
	push	{lr}
	ldr	r2, .L12
	add	r0, r0, r2
	ldrh	r3, [r0]
	cmp	r3, #1
	beq	.L5
	cmp	r3, #1
	bgt	.L9
	cmp	r3, #0
	beq	.L4
	b	.L2
.L9:
	cmp	r3, #2
	beq	.L6
	b	.L2
.L4:
	ldr	r3, .L12+4
	mov	r2, #131
	lsl	r2, r2, #2
	b	.L11
.L5:
	ldr	r3, .L12+4
	ldr	r2, .L12+8
	b	.L11
.L6:
	ldr	r3, .L12+4
	ldr	r2, .L12+12
.L11:
	add	r1, r3, r2
	ldrb	r2, [r1]
	mov	r3, r2
	cmp	r3, #0
	beq	.L2
	add	r3, r3, #255
	strb	r3, [r1]
.L2:
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	1396
	.word	gState
	.word	517
	.word	518
.Lfe1:
	.size	 Func_801ce90,.Lfe1-Func_801ce90

	.text
	.align	2, 0
