@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1de5c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801e7c0
	.thumb_func
	.type	 Func_801e7c0,function
Func_801e7c0:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r6, r3
	ldr	r3, .L4+4
	mov	sl, r1
	ldr	r7, [r3]
	mov	r9, r2
	ldr	r1, .L4+8
	mov	r2, #0
	mov	r8, r2
	add	r5, r7, r1
	mov	r3, r8
	strh	r3, [r5]
	mov	r1, #1
	bl	BufferString
	ldrh	r3, [r5]
	mov	r4, #235
	lsl	r4, r4, #4
	lsl	r3, r3, #1
	add	r3, r3, r4
	mov	r0, r8
	strh	r0, [r7, r3]
	ldrh	r3, [r5]
	ldrh	r2, .L4
	add	r3, r3, #1
	and	r3, r3, r2
	strh	r3, [r5]
	mov	r1, sl
	ldrh	r3, [r1, #14]
	lsr	r6, r6, #3
	ldrh	r2, [r1, #12]
	add	r3, r3, r6
	mov	r4, r9
	lsr	r1, r4, #3
	add	r3, r3, #1
	add	r2, r2, r1
	lsl	r3, r3, #5
	add	r3, r3, r2
	mov	r0, #160
	add	r1, r3, #1
	lsl	r0, r0, #2
	cmp	r1, r0
	bcs	.L3
	ldr	r3, .L4+12
	mov	r4, #235
	lsl	r1, r1, #1
	lsl	r4, r4, #4
	add	r2, r1, r3
	add	r0, r7, r4
	b	.L5
.L6:
	.align	2, 0
.L4:
	.word	511
	.word	iwram_3001e8c
	.word	4786
	.word	100671488
.L5:
	mov	r3, #7
	mov	r4, r9
	add	r1, r7, r1
	and	r3, r3, r4
	bl	Func_801de5c
.L3:
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_801e7c0,.Lfe1-Func_801e7c0

	.text
	.align	2, 0
