@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_19ebc_a_c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	LoadItemIconID
	.thumb_func
	.type	 LoadItemIconID,function
LoadItemIconID:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r7, r1
	mov	r1, #0
	mov	sl, r1
	mov	r1, #193
	mov	r6, r0
	lsl	r1, r1, #3
	mov	r0, #17
	mov	r8, r2
	mov	r9, r3
	bl	galloc_iwram
	mov	r5, r0
	bl	NumItemIcons
	cmp	r6, r0
	bcc	.L3
	mov	r6, #0
.L3:
	cmp	r7, #0
	beq	.L4
	ldr	r3, .L6
	add	r2, r5, r3
	ldr	r3, .L6+4
	mov	r1, #192
	ldr	r3, [r3, #8]
	lsl	r1, r1, #3
	str	r3, [r2]
	mov	r2, #2
	add	r3, r5, r1
	add	r1, r1, #2
	strh	r2, [r3]
	add	r3, r5, r1
	strh	r2, [r3]
	mov	r0, r5
	mov	r1, #0
	bl	LoadIcon
	mov	r2, #1
	mov	sl, r2
.L4:
	ldr	r3, .L6
	ldr	r2, .L6+8
	add	r1, r5, r3
	lsl	r3, r6, #2
	ldr	r3, [r2, r3]
	str	r3, [r1]
	mov	r1, #192
	lsl	r1, r1, #3
	mov	r2, #2
	add	r3, r5, r1
	add	r1, r1, #2
	strh	r2, [r3]
	add	r3, r5, r1
	strh	r2, [r3]
	mov	r0, r5
	mov	r1, sl
	bl	LoadIcon
	ldr	r2, [sp, #28]
	cmp	r2, #0
	bne	.L5
	bl	AllocSpriteSlot
	mov	r3, r8
	str	r0, [r3]
.L5:
	mov	r3, #128
	mov	r1, r8
	lsl	r3, r3, #3
	ldr	r0, [r1]
	add	r2, r5, r3
	mov	r1, #128
	bl	UploadSpriteGFX
	mov	r1, r9
	str	r0, [r1]
	mov	r0, #17
	bl	gfree
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	1540
	.word	.L29a10
	.word	.L29ee4
.Lfe1:
	.size	 LoadItemIconID,.Lfe1-LoadItemIconID

	.text
	.align	2, 0
