@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_c_a_a_a_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80170c4
	.thumb_func
	.type	 Func_80170c4,function
Func_80170c4:
	push	{r5, lr}
	mov	r4, r2
	sub	sp, sp, #4
	mov	r5, r0
	cmp	r4, #0
	ble	.L10
	mov	r0, sp
	mov	r2, #129
	add	r0, r0, #2
	lsl	r2, r2, #24
	strh	r1, [r0]
	ldr	r3, .L12
	mov	r1, r5
	orr	r2, r2, r4
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	lsl	r3, r4, #1
	add	r5, r5, r3
.L10:
	mov	r0, r5
	add	sp, sp, #4
	pop	{r5}
	pop	{r1}
	bx	r1
.L13:
	.align	2, 0
.L12:
	.word	67109076
.Lfe1:
	.size	 Func_80170c4,.Lfe1-Func_80170c4
	.align	2, 0
	.global	Func_80170f8
	.thumb_func
	.type	 Func_80170f8,function
Func_80170f8:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r7, r3
	ldr	r3, .L35+12
	ldr	r3, [r3]
	mov	fp, r3
	lsl	r3, r1, #5
	add	r3, r3, r0
	mov	r8, r2
	lsl	r3, r3, #1
	mov	r2, fp
	add	r5, r3, r2
	mov	r3, r8
	cmp	r3, #1
	bhi	.LCB64
	b	.L15	@long jump
.LCB64:
	cmp	r7, #1
	bhi	.LCB66
	b	.L15	@long jump
.LCB66:
	cmp	r3, #30
	bls	.LCB68
	b	.L15	@long jump
.LCB68:
	cmp	r7, #30
	bls	.LCB70
	b	.L15	@long jump
.LCB70:
	mov	r3, r7
	mov	r2, r8
	bl	Func_801e260
	ldr	r3, .L35+16
	add	r3, r3, fp
	ldrb	r3, [r3]
	cmp	r3, #0
	beq	.L16
	ldrh	r3, .L35
	b	.L31
.L16:
	ldrh	r3, .L35+4
.L31:
	strh	r3, [r5]
	add	r5, r5, #2
	mov	r2, #2
	neg	r2, r2
	add	r2, r2, r8
	mov	r0, r5
	ldr	r1, .L35+20
	mov	sl, r2
	bl	Func_80170c4
	ldr	r3, .L35+16
	add	r3, r3, fp
	ldrb	r3, [r3]
	mov	r5, r0
	cmp	r3, #0
	beq	.L18
	ldrh	r3, .L35+8
	b	.L32
.L36:
	.align	2, 0
.L35:
	.word	61468
	.word	61456
	.word	62492
	.word	iwram_3001e8c
	.word	3748
	.word	-267259887
.L18:
	ldrh	r3, .L37
.L32:
	strh	r3, [r5]
	add	r5, r5, #2
	mov	r3, #32
	mov	r2, r8
	sub	r3, r3, r2
	lsl	r3, r3, #1
	mov	r6, #1
	sub	r7, r7, #1
	add	r5, r5, r3
	cmp	r6, r7
	bcs	.L30
	mov	r9, r3
.L23:
	ldr	r3, .L37+4
	mov	r2, r8
	strh	r3, [r5]
	add	r5, r5, #2
	cmp	r2, #2
	beq	.L24
	mov	r0, r5
	ldr	r1, .L37+8
	mov	r2, sl
	bl	Func_80170c4
	b	.L38
.L39:
	.align	2, 0
.L37:
	.word	61458
	.word	61462
	.word	-266276832
.L38:
	mov	r5, r0
.L24:
	ldrh	r3, .L40
	add	r6, r6, #1
	strh	r3, [r5]
	add	r5, r5, #2
	add	r5, r5, r9
	cmp	r6, r7
	bcc	.L23
.L30:
	ldr	r3, .L40+8
	add	r3, r3, fp
	ldrb	r3, [r3]
	cmp	r3, #0
	beq	.L26
	ldrh	r3, .L40+4
	b	.L33
.L41:
	.align	2, 0
.L40:
	.word	61463
	.word	63516
	.word	3748
.L26:
	ldrh	r3, .L42
.L33:
	strh	r3, [r5]
	add	r5, r5, #2
	mov	r0, r5
	ldr	r1, .L42+8
	mov	r2, sl
	bl	Func_80170c4
	ldr	r3, .L42+12
	add	r3, r3, fp
	ldrb	r3, [r3]
	mov	r5, r0
	cmp	r3, #0
	beq	.L28
	ldrh	r3, .L42+4
	b	.L34
.L43:
	.align	2, 0
.L42:
	.word	61459
	.word	64540
	.word	-267063276
	.word	3748
.L28:
	ldrh	r3, .L44
.L34:
	strh	r3, [r5]
	ldr	r2, .L44+4
	mov	r3, #1
	add	r2, r2, fp
	strb	r3, [r2]
.L15:
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L45:
	.align	2, 0
.L44:
	.word	61461
	.word	3747
.Lfe2:
	.size	 Func_80170f8,.Lfe2-Func_80170f8
	.align	2, 0
	.global	Func_8017248
	.thumb_func
	.type	 Func_8017248,function
Func_8017248:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	lr, r3
	ldr	r3, .L72+8
	lsl	r1, r1, #5
	ldr	r3, [r3]
	add	r1, r1, r0
	sub	sp, sp, #4
	lsl	r1, r1, #1
	mov	r6, r2
	ldr	r4, [sp, #36]
	str	r3, [sp]
	add	r1, r1, r3
	cmp	r6, #1
	bls	.L47
	mov	r2, lr
	cmp	r2, #1
	bls	.L47
	cmp	r6, #30
	bhi	.L47
	cmp	r2, #30
	bhi	.L47
	add	r1, r1, #64
	cmp	r4, #0
	bne	.L48
	mov	r3, #1
	neg	r3, r3
	add	r3, r3, lr
	mov	r5, #1
	mov	r8, r3
	cmp	r5, r8
	bcs	.L59
	mov	r3, #32
	sub	r3, r3, r6
	lsl	r3, r3, #1
	sub	r2, r6, #1
	mov	sl, r3
	ldr	r3, .L72+12
	mov	ip, r2
	mov	r9, ip
	mov	fp, r3
.L52:
	mov	r4, #1
	add	r1, r1, #2
	cmp	r4, r9
	bcs	.L70
	mov	r3, lr
	sub	r3, r3, #2
	mov	r2, r3
	ldrh	r7, .L72
	mov	r3, fp
	ldrh	r6, .L72+4
	add	r0, r3, r5
.L56:
	mov	r3, r0
	and	r3, r3, r7
	orr	r3, r3, r6
	add	r4, r4, #1
	strh	r3, [r1]
	add	r0, r0, r2
	add	r1, r1, #2
	cmp	r4, ip
	bcc	.L56
.L70:
	add	r1, r1, #2
	add	r5, r5, #1
	add	r1, r1, sl
	cmp	r5, r8
	bcc	.L52
	b	.L59
.L73:
	.align	2, 0
.L72:
	.word	4095
	.word	61440
	.word	iwram_3001e8c
	.word	295
.L48:
	mov	r0, lr
	mov	r5, #1
	sub	r0, r0, #1
	cmp	r5, r0
	bcs	.L59
	mov	r3, #32
	sub	r3, r3, r6
	ldr	r2, .L74+4
	lsl	r3, r3, #1
	mov	sl, r3
	mov	r9, r2
	mov	r8, r0
.L63:
	mov	r4, #0
	cmp	r4, r6
	bcs	.L71
	mov	r3, #2
	neg	r3, r3
	add	r3, r3, lr
	ldr	r2, .L74+8
	mov	fp, r3
	ldrh	r7, .L74
	mov	r3, r9
	mov	ip, r2
	add	r0, r5, r3
.L67:
	mov	r3, r0
	mov	r2, ip
	and	r3, r3, r2
	orr	r3, r3, r7
	add	r4, r4, #1
	strh	r3, [r1]
	add	r0, r0, fp
	add	r1, r1, #2
	cmp	r4, r6
	bcc	.L67
.L71:
	add	r5, r5, #1
	add	r1, r1, sl
	cmp	r5, r8
	bcc	.L63
.L59:
	ldr	r3, [sp]
	ldr	r1, .L74+12
	add	r2, r3, r1
	mov	r3, #1
	strb	r3, [r2]
	b	.L75
.L76:
	.align	2, 0
.L74:
	.word	61440
	.word	295
	.word	4095
	.word	3747
.L75:
.L47:
	add	sp, sp, #4
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe3:
	.size	 Func_8017248,.Lfe3-Func_8017248

	.text
	.align	2, 0
