@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1aeec_a_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801b010
	.thumb_func
	.type	 Func_801b010,function
Func_801b010:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r3, .L19
	ldr	r6, [r3]
	mov	sl, r0
	mov	r0, r6
	sub	sp, sp, #4
	mov	r5, r1
	bl	Func_801b36c
	mov	r2, #212
	lsl	r2, r2, #2
	add	r2, r2, r6
	mov	r9, r0
	ldr	r0, [r2]
	mov	r8, r2
	cmp	r0, #0
	bne	.L3
	mov	r3, sl
	cmp	r3, #6
	bne	.L4
	mov	r2, #238
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldrh	r3, [r3]
	cmp	r3, #0
	beq	.L5
	mov	r3, sl
	str	r3, [sp]
	mov	r2, #5
	mov	r0, #17
	mov	r1, #17
	b	.L17
.L5:
	mov	r3, sl
	str	r3, [sp]
	mov	r2, #5
	mov	r0, #17
	mov	r1, #0
.L17:
	mov	r3, #3
	bl	CreateUIBox
	mov	r2, r8
	str	r0, [r2]
	mov	r3, #232
	lsl	r3, r3, #2
	add	r2, r6, r3
	mov	r3, #0
	strh	r3, [r2]
	mov	r3, #238
	lsl	r3, r3, #2
	add	r2, r6, r3
	add	r3, r3, #47
	strh	r3, [r2]
	b	.L7
.L4:
	mov	r0, #9
	sub	r0, r0, r5
	mov	r3, #6
	lsr	r0, r0, #1
	add	r2, r5, #2
	str	r3, [sp]
	add	r0, r0, #19
	mov	r1, #17
	mov	r3, #3
	bl	CreateUIBox
	mov	r2, r8
	str	r0, [r2]
.L7:
	mov	r2, #212
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldr	r0, [r3]
	bl	Func_8016478
	b	.L8
.L3:
	cmp	r5, #0
	beq	.L9
	ldrh	r3, [r0, #8]
	add	r7, r5, #2
	cmp	r3, r7
	beq	.L9
	mov	r1, #2
	bl	CloseUIBox
	mov	r0, #9
	sub	r0, r0, r5
	mov	r3, #6
	lsr	r0, r0, #1
	str	r3, [sp]
	add	r0, r0, #19
	mov	r3, #3
	mov	r1, #17
	mov	r2, r7
	bl	CreateUIBox
	mov	r3, r8
	str	r0, [r3]
.L9:
	mov	r2, #212
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldr	r0, [r3]
	bl	Func_8016478
.L8:
	mov	r2, #229
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldrh	r3, [r3]
	cmp	r3, #0
	beq	.L10
	mov	r3, r9
	sub	r2, r2, #68
	ldrh	r0, [r3, #32]
	add	r3, r6, r2
	ldr	r1, [r3]
	b	.L18
.L10:
	mov	r3, sl
	cmp	r3, #2
	beq	.L14
	cmp	r3, #4
	bne	.L11
	mov	r2, #212
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldr	r1, [r3]
	ldr	r0, .L19+4
.L18:
	mov	r2, #0
	mov	r3, #0
	bl	Func_801e7c0
	b	.L11
.L14:
	mov	r2, #212
	lsl	r2, r2, #2
	add	r3, r6, r2
	ldr	r1, [r3]
	ldr	r0, .L19+8
	mov	r2, #0
	mov	r3, #0
	bl	Func_801e7c0
.L11:
	add	sp, sp, #4
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L20:
	.align	2, 0
.L19:
	.word	iwram_3001e98
	.word	_MSG_51
	.word	_MSG_50
.Lfe1:
	.size	 Func_801b010,.Lfe1-Func_801b010

	.text
	.align	2, 0
