@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_178b0_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8017c8c
	.thumb_func
	.type	 Func_8017c8c,function
Func_8017c8c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r4, r3
	ldr	r3, .L28+8
	ldr	r3, [r3]
	mov	r7, r2
	mov	r8, r3
	lsl	r3, r7, #16
	asr	r3, r3, #16
	mov	r6, r0
	sub	sp, sp, #8
	mov	r9, r1
	mov	sl, r3
	cmp	r6, #0
	bne	.L3
	ldr	r1, .L28+12
	add	r1, r1, r8
	ldrh	r3, [r1]
	mov	r2, #235
	lsl	r2, r2, #4
	mov	r0, r8
	lsl	r3, r3, #1
	add	r3, r3, r2
	add	r6, r0, r2
	ldrh	r2, .L28
	strh	r2, [r0, r3]
	ldrh	r3, [r1]
	ldrh	r2, .L28+4
	add	r3, r3, #1
	and	r3, r3, r2
	strh	r3, [r1]
.L3:
	mov	r2, #0
	ldrsh	r3, [r6, r2]
	lsl	r1, r3, #16
	add	r6, r6, #2
	cmp	r1, #0
	beq	.L27
.L7:
	lsr	r5, r1, #16
	cmp	r5, #30
	bhi	.L8
	sub	r1, r5, #3
	cmp	r1, #26
	bhi	.L4
	ldr	r2, .L28+16
	lsl	r3, r1, #2
	ldr	r3, [r3, r2]
	b	.L29
.L30:
	.align	2, 0
.L28:
	.word	0
	.word	511
	.word	iwram_3001e8c
	.word	4786
	.word	.L22
.L29:
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L22:
	.word	.L10
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L21
	.word	.L21
	.word	.L21
	.word	.L21
	.word	.L21
	.word	.L21
	.word	.L4
	.word	.L13
	.word	.L13
	.word	.L4
	.word	.L21
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L13
	.word	.L21
.L10:
	mov	r7, sl
	add	r4, r4, #1
	b	.L4
.L13:
	add	r6, r6, #2
.L21:
	add	r6, r6, #2
	b	.L4
.L8:
	mov	r3, #0
	str	r3, [sp]
	mov	r2, r7
	mov	r3, r4
	mov	r0, r9
	mov	r1, r5
	str	r4, [sp, #4]
	bl	Func_8018efc
	ldr	r0, .L31
	mov	r2, #128
	add	r3, r5, r0
	lsl	r3, r3, #16
	lsl	r2, r2, #9
	ldr	r4, [sp, #4]
	cmp	r3, r2
	bls	.L4
	add	r7, r7, #1
.L4:
	mov	r0, #0
	ldrsh	r3, [r6, r0]
	lsl	r3, r3, #16
	add	r6, r6, #2
	mov	r1, r3
	cmp	r3, #0
	bne	.L7
.L27:
	ldr	r2, .L31+4
	mov	r3, #1
	add	r2, r2, r8
	strb	r3, [r2]
	add	sp, sp, #8
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L32:
	.align	2, 0
.L31:
	.word	65314
	.word	3747
.Lfe1:
	.size	 Func_8017c8c,.Lfe1-Func_8017c8c

	.text
	.align	2, 0
