@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_a_c_c_c_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8016758
	.thumb_func
	.type	 Func_8016758,function
Func_8016758:
	push	{r5, lr}
	ldr	r3, .L11
	mov	r1, #196
	ldr	r3, [r3]
	lsl	r1, r1, #3
	add	r2, r3, r1
	mov	r5, #0
	mov	r1, #0
	b	.L3
.L6:
	add	r2, r2, #40
	add	r1, r1, #1
.L3:
	cmp	r1, #3
	beq	.L4
	ldr	r3, [r2]
	cmp	r3, #0
	beq	.L7
	ldrh	r3, [r3, #20]
	cmp	r3, #0
	beq	.L6
.L7:
	mov	r5, r2
.L4:
	cmp	r5, #0
	beq	.L2
	ldr	r3, [r5]
	cmp	r3, #0
	beq	.L10
	bl	Func_801671c
	mov	r3, #0
	strh	r3, [r5, #6]
.L10:
	mov	r3, #0
	strh	r3, [r5, #4]
	strh	r3, [r5, #20]
	mov	r2, #15
	strh	r3, [r5, #24]
	mov	r3, #10
	strh	r2, [r5, #22]
	strh	r3, [r5, #26]
.L2:
	pop	{r5}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	iwram_3001e8c
.Lfe1:
	.size	 Func_8016758,.Lfe1-Func_8016758

	.text
	.align	2, 0
