@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_23178_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Debug_FlagEditor
	.thumb_func
	.type	 Debug_FlagEditor,function
Debug_FlagEditor:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #32
	mov	r3, #8
	str	r3, [sp, #4]
	add	r6, sp, #12
	mov	r5, #0
	mov	r3, #2
	str	r5, [sp, #12]
	mov	r2, #28
	str	r5, [r6, #4]
	mov	r1, #0
	str	r3, [sp]
	mov	r0, #1
	mov	r3, #20
	bl	CreateUIBox
	ldr	r1, [sp, #4]
	mov	r5, r0
	bl	Func_80292c4
	add	r7, sp, #20
	add	r1, sp, #8
	mov	r0, r7
	bl	Func_801c0dc
	add	r3, sp, #4
	mov	r8, r3
	b	.L3
.L6:
	cmp	r0, #1
	bne	.L7
	ldr	r1, [sp, #4]
	mov	r0, r5
	bl	Func_80292c4
.L7:
	ldr	r1, [sp, #12]
	ldr	r2, [r6, #4]
	lsl	r1, r1, #3
	lsl	r2, r2, #3
	add	r1, r1, #58
	add	r2, r2, #20
	mov	r0, r7
	bl	Func_801c154
.L3:
	mov	r0, #1
	bl	WaitFrames
	mov	r0, r5
	mov	r1, r8
	mov	r2, r6
	bl	Func_802938c
	mov	r3, #1
	neg	r3, r3
	cmp	r0, r3
	bne	.L6
	ldr	r0, [sp, #8]
	bl	Func_801c17c
	mov	r0, r5
	mov	r1, #2
	bl	CloseUIBox
	mov	r0, #0
	add	sp, sp, #32
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Debug_FlagEditor,.Lfe1-Debug_FlagEditor

	.text
	.align	2, 0
