@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1de5c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801e9a0
	.thumb_func
	.type	 Func_801e9a0,function
Func_801e9a0:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #16
	mov	r4, r0
	ldr	r7, [sp, #36]
	mov	r5, r1
	mov	r8, r3
	mov	r1, r4
	mov	r6, r2
	mov	r0, sp
	mov	r2, r5
	bl	PrintNum
	mov	r1, r6
	mov	r2, r8
	mov	r3, r7
	bl	Func_801e858
	add	sp, sp, #16
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_801e9a0,.Lfe1-Func_801e9a0

	.text
	.align	2, 0
