@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801776c
	.thumb_func
	.type	 Func_801776c,function
Func_801776c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L22
	ldr	r3, [r3]
	sub	sp, sp, #28
	mov	r8, r3
	mov	r3, #0
	mov	r4, #0
	mov	r6, r1
	str	r3, [sp, #4]
	str	r4, [sp, #8]
	mov	r3, #2
	mov	r5, #0
	mov	r2, #1
	mov	r7, r6
	and	r3, r3, r6
	mov	sl, r0
	str	r5, [sp, #24]
	str	r5, [sp, #20]
	and	r7, r7, r2
	cmp	r3, #0
	beq	.L3
	ldr	r3, .L22+4
	add	r3, r3, r8
	strb	r2, [r3]
.L3:
	add	r0, sp, #12
	add	r2, sp, #20
	add	r3, sp, #16
	str	r0, [sp]
	add	r1, sp, #24
	mov	r0, sl
	bl	TextBox
	ldr	r2, [sp, #16]
	mov	r3, #30
	sub	r3, r3, r2
	asr	r3, r3, #1
	ldr	r2, [sp, #12]
	str	r3, [sp, #24]
	mov	r3, #12
	sub	r3, r3, r2
	asr	r2, r3, #1
	mov	r3, #8
	and	r3, r3, r6
	str	r2, [sp, #20]
	cmp	r3, #0
	beq	.L4
	add	r3, r2, #4
	b	.L21
.L4:
	mov	r3, #64
	and	r3, r3, r6
	cmp	r3, #0
	beq	.L6
	mov	r3, r2
	add	r3, r3, #12
	b	.L21
.L6:
	ldr	r3, .L22+8
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	add	r5, sp, #4
	ldr	r0, [r3]
	mov	r1, r5
	bl	_Func_8094154
	ldr	r3, [r5, #4]
	asr	r3, r3, #3
	cmp	r3, #9
	ble	.L8
	sub	r3, r3, #5
	b	.L21
.L8:
	add	r3, r3, #4
.L21:
	str	r3, [sp, #20]
	ldr	r1, [sp, #24]
	ldr	r2, [sp, #20]
	mov	r0, sl
	mov	r3, r7
	bl	Func_8017658
	mov	r5, r0
	cmp	r5, #0
	beq	.L10
	b	.L11
.L13:
	mov	r0, #1
	bl	WaitFrames
.L11:
	bl	Func_8017364
	cmp	r0, #0
	beq	.L13
	mov	r3, #32
	and	r3, r3, r6
	cmp	r3, #0
	beq	.L15
	ldr	r3, .L22
	ldr	r2, .L22+12
	ldr	r3, [r3]
	add	r3, r3, r2
	mov	r2, #1
	strb	r2, [r3]
.L15:
	mov	r3, #4
	and	r3, r3, r6
	cmp	r3, #0
	bne	.L10
	mov	r0, r5
	mov	r1, r7
	bl	CloseUIBox
	b	.L17
.L19:
	mov	r0, #1
	bl	WaitFrames
.L17:
	mov	r0, r5
	bl	Func_8017394
	cmp	r0, #0
	beq	.L19
.L10:
	ldr	r3, .L22+4
	mov	r2, #0
	add	r3, r3, r8
	strb	r2, [r3]
	ldr	r3, .L22+16
	add	r3, r3, r8
	strh	r2, [r3]
	ldr	r3, .L22+20
	add	r3, r3, r8
	strh	r2, [r3]
	mov	r0, #3
	bl	WaitFrames
	add	sp, sp, #28
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L23:
	.align	2, 0
.L22:
	.word	iwram_3001e8c
	.word	4857
	.word	gState
	.word	3750
	.word	4852
	.word	4854
.Lfe1:
	.size	 Func_801776c,.Lfe1-Func_801776c

	.text
	.align	2, 0
