@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1ca1c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801d980
	.thumb_func
	.type	 Func_801d980,function
Func_801d980:
	push	{lr}
	mov	r1, #197
	lsl	r1, r1, #3
	mov	r0, #20
	sub	sp, sp, #4
	bl	galloc_ewram
	mov	r3, #0
	mov	r1, r0
	mov	r0, sp
	str	r3, [r0]
	ldr	r2, .L11
	ldr	r3, .L11+4
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L11+8
	bl	StartTask
	add	sp, sp, #4
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	-2063597174
	.word	67109076
	.word	Func_801d94c
.Lfe1:
	.size	 Func_801d980,.Lfe1-Func_801d980

	.text
	.align	2, 0
