@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1908c_c_c_b_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8019d0c
	.thumb_func
	.type	 Func_8019d0c,function
Func_8019d0c:
	ldr	r3, .L3+4
	ldr	r0, .L3+8
	ldr	r3, [r3]
	ldrh	r2, .L3
	add	r1, r3, r0
	add	r0, r0, #2
	strh	r2, [r1]
	add	r1, r3, r0
	strh	r2, [r1]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	999
	.word	iwram_3001e8c
	.word	4844
.Lfe1:
	.size	 Func_8019d0c,.Lfe1-Func_8019d0c

	.text
	.align	2, 0
