@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_c_a_a_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8016f2c
	.thumb_func
	.type	 Func_8016f2c,function
Func_8016f2c:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L13
	mov	r1, #160
	ldr	r7, [r3]
	lsl	r1, r1, #3
	mov	r2, #0
	add	r5, r7, r1
	mov	r8, r2
.L3:
	ldrh	r6, [r5, #22]
	cmp	r6, #0
	beq	.L4
	mov	r4, #24
	ldrsh	r3, [r5, r4]
	cmp	r3, #0
	beq	.L5
	mov	r0, r5
	mov	r1, #0
	bl	Func_8017004
	ldrh	r3, [r5, #24]
	sub	r3, r3, #1
	strh	r3, [r5, #24]
	b	.L8
.L5:
	mov	r1, #26
	ldrsh	r3, [r5, r1]
	cmp	r3, #0
	beq	.L8
	mov	r0, r5
	bl	Func_8016230
	b	.L8
.L4:
	mov	r3, #26
	ldrsh	r2, [r5, r3]
	cmp	r2, #0
	beq	.L8
	mov	r4, #24
	ldrsh	r3, [r5, r4]
	cmp	r3, r2
	beq	.L10
	mov	r1, #28
	ldrsh	r0, [r5, r1]
	mov	r2, #30
	ldrsh	r1, [r5, r2]
	mov	r3, #32
	ldrsh	r2, [r5, r3]
	mov	r4, #34
	ldrsh	r3, [r5, r4]
	bl	ClearUIRegion
	mov	r1, #1
	mov	r0, r5
	bl	Func_8017004
	ldrh	r3, [r5, #24]
	ldr	r1, .L13+4
	add	r3, r3, #1
	strh	r3, [r5, #24]
	mov	r2, #1
	add	r3, r7, r1
	strb	r2, [r3]
	b	.L8
.L10:
	mov	r3, #30
	ldrsh	r1, [r5, r3]
	mov	r2, #28
	ldrsh	r0, [r5, r2]
	mov	r4, #34
	ldrsh	r3, [r5, r4]
	mov	r4, #32
	ldrsh	r2, [r5, r4]
	bl	ClearUIRegion
	ldr	r1, .L13+4
	mov	r3, #1
	add	r2, r7, r1
	str	r6, [r5]
	str	r6, [r5, #4]
	strh	r6, [r5, #8]
	strh	r6, [r5, #10]
	strh	r6, [r5, #12]
	strh	r6, [r5, #14]
	strh	r6, [r5, #16]
	strh	r6, [r5, #18]
	strh	r6, [r5, #20]
	strh	r6, [r5, #22]
	strh	r6, [r5, #24]
	strh	r6, [r5, #26]
	strh	r6, [r5, #28]
	strh	r6, [r5, #30]
	strh	r6, [r5, #32]
	strh	r6, [r5, #34]
	strb	r3, [r2]
.L8:
	mov	r2, #1
	add	r8, r8, r2
	mov	r3, r8
	add	r5, r5, #36
	cmp	r3, #8
	bne	.L3
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	iwram_3001e8c
	.word	3747
.Lfe1:
	.size	 Func_8016f2c,.Lfe1-Func_8016f2c

	.text
	.align	2, 0
