@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1ca1c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801d94c
	.thumb_func
	.type	 Func_801d94c,function
Func_801d94c:
	push	{r5, lr}
	ldr	r3, .L3
	ldr	r2, .L3+4
	ldr	r5, [r3]
	add	r0, r5, r2
	bl	_Func_80b08b8
	ldr	r2, .L3+8
	add	r3, r5, r2
	ldrh	r3, [r3]
	add	r2, r2, #156
	lsl	r3, r3, #2
	add	r3, r3, r2
	ldr	r0, [r5, r3]
	bl	Func_80217a4
	pop	{r5}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001ea0
	.word	1444
	.word	1396
.Lfe1:
	.size	 Func_801d94c,.Lfe1-Func_801d94c

	.text
	.align	2, 0
