@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_a_c_c_a_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	CloseUIBox
	.thumb_func
	.type	 CloseUIBox,function
CloseUIBox:
	push	{r5, r6, r7, lr}
	mov	r5, r0
	mov	r7, r1
	cmp	r5, #0
	beq	.L3
	bl	Func_8016478
	ldrh	r3, [r5, #12]
	strh	r3, [r5, #28]
	ldrh	r3, [r5, #14]
	strh	r3, [r5, #30]
	ldrh	r3, [r5, #8]
	strh	r3, [r5, #32]
	ldrh	r3, [r5, #10]
	mov	r6, #0
	strh	r6, [r5, #22]
	strh	r3, [r5, #34]
	cmp	r7, #0
	beq	.L4
	ldrh	r0, [r5, #12]
	ldrh	r1, [r5, #14]
	ldrh	r2, [r5, #8]
	ldrh	r3, [r5, #10]
	bl	ClearUIRegion
	str	r6, [r5]
	str	r6, [r5, #4]
	strh	r6, [r5, #8]
	strh	r6, [r5, #10]
	strh	r6, [r5, #12]
	strh	r6, [r5, #14]
	strh	r6, [r5, #16]
	strh	r6, [r5, #18]
	strh	r6, [r5, #20]
	strh	r6, [r5, #22]
	strh	r6, [r5, #24]
	strh	r6, [r5, #26]
	strh	r6, [r5, #28]
	strh	r6, [r5, #30]
	strh	r6, [r5, #32]
	strh	r6, [r5, #34]
	b	.L3
.L4:
	mov	r3, #4
	strh	r7, [r5, #24]
	strh	r3, [r5, #26]
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 CloseUIBox,.Lfe1-CloseUIBox

	.text
	.align	2, 0
