@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_23178_a_a_a_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	AddMenuBarOption
	.thumb_func
	.type	 AddMenuBarOption,function
AddMenuBarOption:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L4
	ldr	r3, [r3]
	mov	r8, r3
	mov	r2, r8
	add	r2, r2, #142
	mov	r1, #0
	ldrsh	r7, [r2, r1]
	mov	sl, r0
	ldrh	r3, [r2]
	cmp	r7, #5
	bgt	.L2
	add	r3, r3, #1
	strh	r3, [r2]
	bl	AllocSpriteSlot
	mov	r1, sl
	mov	r6, r0
	lsl	r5, r7, #2
	bl	LoadUIIcon
	lsl	r3, r7, #1
	add	r5, r5, r7
	add	r3, r3, r7
	lsl	r5, r5, #2
	lsl	r3, r3, #3
	add	r5, r5, r8
	add	r3, r3, #32
	strh	r3, [r5, #12]
	mov	r3, #136
	strh	r3, [r5, #14]
	mov	r3, r7
	add	r3, r3, #132
	mov	r1, sl
	mov	r2, r8
	strh	r6, [r5, #18]
	strb	r1, [r2, r3]
.L2:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001f38
.Lfe1:
	.size	 AddMenuBarOption,.Lfe1-AddMenuBarOption

	.text
	.align	2, 0
