@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_21dfc_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_802281c
	.thumb_func
	.type	 Func_802281c,function
Func_802281c:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L15
	mov	r5, r0
	mov	r1, #0
	mov	r0, #1
	sub	sp, sp, #4
	ldr	r7, [r3]
	bl	_Func_80b6c08
	mov	r8, r0
	lsl	r3, r0, #1
	add	r3, r3, r8
	lsl	r3, r3, #1
	mov	r0, #29
	sub	r0, r0, r3
	mov	r3, #15
	str	r3, [sp]
	mov	r1, #0
	mov	r3, #5
	mov	r2, #25
	bl	Func_8022768
	ldrh	r3, [r5]
	mov	r6, #0
	cmp	r3, #255
	beq	.L3
	mov	r0, #0
.L4:
	mov	r3, #88
	ldrsh	r2, [r7, r3]
	ldrh	r3, [r0, r5]
	mov	r1, #0
	b	.L14
.L7:
	add	r1, r1, #1
	cmp	r1, #3
	bgt	.L6
	lsl	r3, r1, #1
	add	r3, r3, #88
	ldrsh	r2, [r7, r3]
	ldrh	r3, [r0, r5]
.L14:
	cmp	r2, r3
	beq	.L6
	cmp	r2, #255
	bne	.L7
	mov	r1, #4
.L6:
	cmp	r1, #4
	beq	.L12
	mov	r3, r8
	sub	r2, r3, r1
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #1
	mov	r0, #29
	sub	r0, r0, r3
	mov	r3, #14
	str	r3, [sp]
	mov	r1, #0
	mov	r2, #7
	mov	r3, #5
	bl	Func_8022768
.L12:
	add	r6, r6, #1
	cmp	r6, #3
	bgt	.L3
	lsl	r3, r6, #1
	mov	r0, r3
	ldrh	r3, [r0, r5]
	cmp	r3, #255
	bne	.L4
.L3:
	mov	r0, #0
	add	sp, sp, #4
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	iwram_3001e74
.Lfe1:
	.size	 Func_802281c,.Lfe1-Func_802281c

	.text
	.align	2, 0
