@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1de5c_c_c_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801ea3c
	.thumb_func
	.type	 Func_801ea3c,function
Func_801ea3c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r8, r3
	ldr	r3, .L13
	sub	sp, sp, #32
	mov	r4, r0
	ldr	r5, [sp, #56]
	ldr	r3, [r3]
	mov	r6, r1
	mov	r7, r2
	add	r0, sp, #16
	mov	r1, r4
	mov	r2, #4
	mov	sl, r3
	bl	PrintNum
	cmp	r5, #0
	bne	.L3
	ldr	r3, .L13+4
	b	.L12
.L3:
	ldr	r3, .L13+8
.L12:
	mov	r4, sp
	strh	r3, [r4]
	ldr	r3, .L13+12
	strh	r3, [r4, #2]
	add	r2, r4, #4
	mov	r1, #4
.L8:
	ldrb	r3, [r0]
	sub	r1, r1, #1
	strh	r3, [r2]
	add	r0, r0, #1
	add	r2, r2, #2
	cmp	r1, #0
	bge	.L8
	mov	r3, #0
	mov	r1, r8
	strh	r3, [r4, #12]
	ldrh	r3, [r6, #14]
	lsr	r2, r1, #3
	add	r3, r3, r2
	ldrh	r2, [r6, #12]
	lsr	r1, r7, #3
	add	r3, r3, #1
	add	r2, r2, r1
	lsl	r3, r3, #5
	add	r3, r3, r2
	add	r1, r3, #1
	mov	r3, #160
	lsl	r3, r3, #2
	cmp	r1, r3
	bcs	.L10
	ldr	r3, .L13+16
	lsl	r1, r1, #1
	add	r2, r1, r3
	mov	r3, #7
	add	r1, r1, sl
	and	r3, r3, r7
	mov	r0, r4
	bl	Func_801de5c
.L10:
	add	sp, sp, #32
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	iwram_3001e8c
	.word	61469
	.word	61471
	.word	61470
	.word	100671488
.Lfe1:
	.size	 Func_801ea3c,.Lfe1-Func_801ea3c

	.text
	.align	2, 0
