@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1fe2c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8020088
	.thumb_func
	.type	 Func_8020088,function
Func_8020088:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L8
	ldr	r0, .L8+4
	ldr	r7, [r3]
	mov	r5, #137
	bl	StopTask
	mov	r3, #0
	mov	r8, r3
	lsl	r5, r5, #2
	mov	r6, #3
.L7:
	ldr	r0, [r5, r7]
	cmp	r0, #0
	beq	.L6
	bl	_DeleteSprite
	mov	r3, r8
	str	r3, [r5, r7]
.L6:
	sub	r6, r6, #1
	add	r5, r5, #4
	cmp	r6, #0
	bge	.L7
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001f2c
	.word	Func_80200cc
.Lfe1:
	.size	 Func_8020088,.Lfe1-Func_8020088

	.text
	.align	2, 0
