@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_21dfc_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8022a38
	.thumb_func
	.type	 Func_8022a38,function
Func_8022a38:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	sub	sp, sp, #4
	mov	r8, r0
	mov	sl, r1
	mov	r7, r2
	mov	r6, r3
	bl	AllocSpriteSlot
	mov	r5, r0
	cmp	r5, #96
	beq	.L3
	mov	r1, r5
	mov	r0, r6
	bl	Func_8021b30
	mov	r1, #128
	lsl	r1, r1, #23
	mov	r0, r5
	mov	r2, r8
	mov	r3, sl
	str	r7, [sp]
	bl	Func_801eadc
.L3:
	add	sp, sp, #4
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_8022a38,.Lfe1-Func_8022a38

	.text
	.align	2, 0
