@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_23178_a_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80251d4
	.thumb_func
	.type	 Func_80251d4,function
Func_80251d4:
	mov	r3, r0
	ldr	r0, .L10
	mov	r2, #192
	and	r1, r1, r0
	and	r0, r0, r3
	lsl	r2, r2, #19
	lsl	r0, r0, #5
	lsl	r1, r1, #5
	add	r0, r0, r2
	add	r1, r1, r2
	ldr	r3, .L10+4
	ldr	r2, .L10+8
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	bx	lr
.L11:
	.align	2, 0
.L10:
	.word	1023
	.word	67109076
	.word	-2080374776
.Lfe1:
	.size	 Func_80251d4,.Lfe1-Func_80251d4

	.text
	.align	2, 0
