@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_15e8c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8015ec0
	.thumb_func
	.type	 Func_8015ec0,function
Func_8015ec0:
	push	{lr}
	ldr	r3, .L5
	mov	r1, #211
	ldr	r2, [r3]
	lsl	r1, r1, #3
	add	r3, r2, r1
	cmp	r0, r3
	bcc	.L2
	ldr	r1, .L5+4
	add	r3, r2, r1
	cmp	r0, r3
	bcs	.L2
	add	r1, r1, #4
	add	r3, r2, r1
	ldr	r2, [r3]
	str	r0, [r3]
	mov	r3, #0
	str	r0, [r2]
	str	r3, [r0]
.L2:
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001e8c
	.word	3480
.Lfe1:
	.size	 Func_8015ec0,.Lfe1-Func_8015ec0
	.align	2, 0
	.global	Func_8015ef4
	.thumb_func
	.type	 Func_8015ef4,function
Func_8015ef4:
	push	{lr}
	ldr	r3, .L14
	mov	r1, #211
	ldr	r0, [r3]
	lsl	r1, r1, #3
	add	r2, r0, r1
	ldr	r1, .L14+4
	add	r3, r0, r1
	str	r2, [r3]
	mov	r3, #62
.L11:
	mov	r1, r2
	add	r1, r1, #28
	sub	r3, r3, #1
	str	r1, [r2]
	mov	r2, r1
	cmp	r3, #0
	bge	.L11
	ldr	r2, .L14+8
	mov	r3, #0
	str	r3, [r1]
	add	r3, r0, r2
	str	r1, [r3]
	pop	{r0}
	bx	r0
.L15:
	.align	2, 0
.L14:
	.word	iwram_3001e8c
	.word	3480
	.word	3484
.Lfe2:
	.size	 Func_8015ef4,.Lfe2-Func_8015ef4

	.text
	.align	2, 0
