@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_1aeec_c_a_a_a_a_a_c_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_801c188
	.thumb_func
	.type	 Func_801c188,function
Func_801c188:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L6
	ldr	r5, [r3]
	mov	r0, r5
	bl	Func_801b36c
	mov	r6, r0
	ldrh	r3, [r6, #10]
	cmp	r3, #1
	beq	.L4
	cmp	r3, #6
	bne	.L3
.L4:
	mov	r1, #193
	lsl	r1, r1, #3
	mov	r0, #17
	bl	galloc_iwram
	mov	r3, #195
	lsl	r3, r3, #2
	add	r5, r5, r3
	ldrh	r3, [r6, #8]
	mov	r7, r0
	ldr	r0, .L6+4
	mov	r8, r3
	bl	GetFile
	ldr	r3, .L6+8
	add	r2, r7, r3
	ldrh	r3, [r6, #8]
	lsl	r3, r3, #1
	ldrh	r3, [r3, r0]
	add	r0, r0, r3
	str	r0, [r2]
	mov	r1, r7
	bl	DecompressLZ1
	ldrh	r3, [r5, #10]
	cmp	r3, #0
	bne	.L5
	bl	AllocSpriteSlot
	strh	r0, [r5, #12]
.L5:
	mov	r1, #128
	ldrh	r0, [r5, #12]
	lsl	r1, r1, #3
	mov	r2, r7
	bl	UploadSpriteGFX
	mov	r3, #1
	strh	r3, [r5, #10]
	mov	r3, r8
	strh	r3, [r5, #8]
	mov	r3, #40
	strh	r3, [r5, #34]
	strh	r3, [r5, #36]
	mov	r3, #240
	strh	r0, [r5, #14]
	strh	r3, [r5, #38]
	mov	r0, #17
	bl	gfree
.L3:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	iwram_3001e98
	.word	_FILE_f1
	.word	1540
.Lfe1:
	.size	 Func_801c188,.Lfe1-Func_801c188

	.text
	.align	2, 0
