@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_20198_c_c_c_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8021360
	.thumb_func
	.type	 Func_8021360,function
Func_8021360:
	push	{r5, lr}
	mov	r5, r0
	mov	r0, #0
	cmp	r5, #8
	bhi	.L2
	mov	r0, #32
	bl	_GetFlag
	cmp	r0, #0
	bne	.L4
	ldr	r3, .L6
	lsl	r2, r5, #1
	ldrsh	r0, [r3, r2]
	b	.L2
.L4:
	ldr	r3, .L6+4
	lsl	r2, r5, #1
	ldrsh	r0, [r3, r2]
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	.L37206
	.word	.L37216
.Lfe1:
	.size	 Func_8021360,.Lfe1-Func_8021360

	.text
	.align	2, 0
