@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_23178_a_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8028aa8
	.thumb_func
	.type	 Func_8028aa8,function
Func_8028aa8:
	push	{r5, r6, lr}
	ldr	r3, .L11
	ldr	r6, [r3]
	mov	r0, r6
	mov	r5, r6
	add	r5, r5, #140
	add	r0, r0, #150
	mov	r3, #0
	ldrsh	r2, [r0, r3]
	mov	r4, #0
	ldrsh	r3, [r5, r4]
	sub	sp, sp, #4
	ldrh	r1, [r5]
	cmp	r2, r3
	beq	.L3
	strh	r1, [r0]
	mov	r3, #80
	ldr	r0, [r6, #124]
	mov	r2, #40
	str	r3, [sp]
	mov	r1, #8
	mov	r3, #144
	bl	Func_80164d4
	mov	r2, #0
	ldrsh	r3, [r5, r2]
	cmp	r3, #1
	beq	.L6
	cmp	r3, #1
	bgt	.L8
	cmp	r3, #0
	bne	.L8
	ldr	r5, .L11+4
	ldr	r1, [r6, #124]
	mov	r0, r5
	mov	r2, #18
	mov	r3, #40
	bl	Func_801e7c0
	add	r0, r5, #1
	ldr	r1, [r6, #124]
	mov	r2, #18
	mov	r3, #48
	bl	Func_801e7c0
	add	r0, r5, #2
	ldr	r1, [r6, #124]
	mov	r2, #18
	mov	r3, #56
	bl	Func_801e7c0
	add	r0, r5, #3
	ldr	r1, [r6, #124]
	mov	r2, #18
	mov	r3, #64
	add	r5, r5, #4
	bl	Func_801e7c0
	ldr	r1, [r6, #124]
	mov	r0, r5
	mov	r2, #18
	mov	r3, #72
	bl	Func_801e7c0
	b	.L3
.L6:
	ldr	r5, .L11+4
	ldr	r1, [r6, #124]
	mov	r0, r5
	mov	r2, #18
	mov	r3, #40
	bl	Func_801e7c0
	add	r0, r5, #1
	ldr	r1, [r6, #124]
	mov	r2, #18
	mov	r3, #48
	add	r5, r5, #2
	bl	Func_801e7c0
	ldr	r1, [r6, #124]
	mov	r0, r5
	mov	r2, #18
	mov	r3, #56
	bl	Func_801e7c0
	b	.L3
.L8:
	ldr	r5, .L11+4
	ldr	r1, [r6, #124]
	mov	r0, r5
	mov	r2, #18
	mov	r3, #40
	add	r5, r5, #1
	bl	Func_801e7c0
	ldr	r1, [r6, #124]
	mov	r0, r5
	mov	r2, #18
	mov	r3, #48
	bl	Func_801e7c0
.L3:
	add	sp, sp, #4
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	iwram_3001f38
	.word	_MSG_c7b
.Lfe1:
	.size	 Func_8028aa8,.Lfe1-Func_8028aa8

	.text
	.align	2, 0
