# Default target. Verify the checksums of the built ROM and overlays.

ROM := goldensun.gba
OVERLAYS := $(patsubst %.ld,%.bin,$(wildcard overlays/*/overlay.ld))

# 1. Enable 'pipefail' so Make catches errors anywhere in the command chain
SHELL := /bin/bash
.SHELLFLAGS := -o pipefail -c
# agbcc-gs is our own build of agbcc with Thumb register-offset addressing
# enabled -- see tools/agbcc-gs/README.md. Stock agbcc is left untouched at
# tools/agbcc/bin/agbcc so this project cannot disturb an agbcc installation
# another project depends on.
CC1 := tools/agbcc-gs/bin/agbcc-gs
CPP := arm-none-eabi-cpp
AS := arm-none-eabi-as
GBA_CPPFLAGS := -Iinclude -nostdinc -undef -std=gnu89
# -fcall-used-r4: Golden Sun's original compiler treated r4 as call-clobbered.
# Evidence: 727 of 2202 Thumb functions in the ROM use r4 without ever pushing
# it, while r5/r6/r7 are used unsaved in 1 function between them. agbcc defaults
# to r4 being callee-saved, so without this flag its prologue is `push {r4, lr}`
# where the ROM has `push {lr}` -- a mismatch in roughly a third of all
# functions. Re-derive with: tools/asmdiff.py --help (see docs/matching.md).
#
# -O rather than -O2: the ROM re-materialises the same address repeatedly
# (`mov r3, ip; adds r3, #39` ... `mov r4, ip; adds r4, #40` ... `mov r2, ip;
# adds r2, #37` inside one function) instead of computing it once. -O2 CSEs
# those into a single value, which is why it scores worse against the ROM. This
# is a working default from one converted function -- re-check with
# `tools/asmdiff.py <func> <src> --sweep` as more functions are converted, and
# add per-file overrides (as pokeemerald does) if some units disagree.
GBA_CFLAGS := -O -mthumb-interwork -fhex-asm -fcall-used-r4

.PHONY: compare compare-rom compare-overlays check-layouts
compare: compare-rom compare-overlays

# The struct layouts in include/ carry sizeof assertions -- a wrong offset makes
# an array size negative and agbcc refuses the file. Nothing links this; it is
# compiled purely so the layouts cannot drift unnoticed.
check-layouts: tools/layout_check.c
	@$(CPP) $(GBA_CPPFLAGS) $< | $(CC1) $(GBA_CFLAGS) -o /dev/null && \
	  echo "struct layouts OK"

compare-rom: goldensun.sha1 $(ROM)
	sha1sum -c $<

COMPARE_OVERLAYS := $(OVERLAYS:%/overlay.bin=compare-%)

compare-overlays: $(COMPARE_OVERLAYS)

$(COMPARE_OVERLAYS): compare-%: %/orig.bin %/overlay.bin
	cmp $*/orig.bin $*/overlay.bin


# Empty clean target. Recipes will be added below.
.PHONY: clean
clean::


# The ROM image includes compressed code overlays.
# The overlays reference symbols defined in the main executable.
# We partially link the main executable; build the overlays against it;
# compress the overlays; and then link the final image.

ARM_LDFLAGS :=
ARM_LDLIBS :=

# Partially linked relocatable object
STAGE1 := stage1.o
$(STAGE1): %.o: %.ld
$(STAGE1): ARM_LDFLAGS += -r

# Overlays reference symbols defined in main code
OVERLAY_ELFS := $(OVERLAYS:.bin=.elf)
$(OVERLAY_ELFS): %.elf: %.ld $(STAGE1)
$(OVERLAY_ELFS): ARM_LDLIBS += -R $(STAGE1)

# Final fully linked executable
ELF := $(ROM:.gba=.elf)
$(ELF): %.elf: %.ld

# All of the above
ELFS := $(STAGE1) $(ELF) $(OVERLAY_ELFS)
$(ELFS):
	arm-none-eabi-ld $(ARM_LDFLAGS) -T $< $(ARM_LDLIBS) -Map $(<:.ld=.map) -o $@

# Read dependencies from the linker scripts
define elf_deps
$(1): $(shell grep -o '[A-Za-z0-9/_-]\+\.o' $(addsuffix .ld,$(basename $(1))))
endef
$(foreach elf,$(ELFS),$(eval $(call elf_deps,$(elf))))


# Convert executables to free-standing binaries
$(ROM) $(OVERLAYS):
	arm-none-eabi-objcopy -O binary $< $@

$(ROM): %.gba: %.elf

$(OVERLAYS): %.bin: %.elf


# Delete a target if its recipe fails. Without this, a C compile that fails
# still leaves the .o behind: the pipeline in the %.o: %.c rule runs `as` on
# whatever agbcc emitted before erroring, so a broken source produces a small
# but valid-looking object that the next build happily links.
.DELETE_ON_ERROR:

# Assemble ARM code and generate dependencies
%.o: %.s
	arm-none-eabi-as -mcpu=arm7tdmi -Iinclude -MD $(@:.o=.d) -o $@ $<
# NOTE: agbcc must be given -mthumb-interwork. Without it the epilogue comes out
# as `pop {..., pc}`, which does not switch modes on ARMv4T, instead of the
# `pop {r0}; bx r0` the original ROM uses -- so no function can ever match.
# GBA_CPPFLAGS/GBA_CFLAGS were declared above but not referenced here; they are
# now, which is what actually applies that flag.
%.o: %.c
	$(CPP) $(GBA_CPPFLAGS) $< | \
	$(CC1) $(GBA_CFLAGS) -o - | \
	cat - <(printf '.text\n\t.align\t2, 0\n') | \
	$(AS) -mcpu=arm7tdmi -o $@

# Read additional dependencies (besides .o => .s) from .d files
# generated by the assembler.
SRCS_S := $(wildcard *.s */*.s */*/*.s)
SRCS_C := $(wildcard *.c */*.c */*/*.c)

OBJS := $(SRCS_S:.s=.o) $(SRCS_C:.c=.o)

DEPS := $(SRCS_S:.s=.d) $(SRCS_C:.c=.d)
-include $(DEPS)


# Clean target.
.PHONY: clean
LDS  := $(wildcard *.ld */*/*.ld)
MAPS := $(LDS:.ld=.map)
OBJS := $(SRCS:.s=.o)
clean::
	-$(RM) $(ROM) $(OVERLAYS) $(ELFS) $(MAPS) $(OBJS) $(DEPS)


# Tools are compiled for the host and used during the build.

TOOLS := tools/pack_overlay \
	 tools/pack_strings \
	 tools/unpack_overlay \
	 tools/unpack_strings

CPPFLAGS += -MMD
CFLAGS ?= -O2 -Wall

$(TOOLS):

TOOL_SRCS := $(wildcard tools/*.c)
TOOL_OBJS := $(TOOL_SRCS:.c=.o)
TOOL_DEPS := $(TOOL_OBJS:.o=.d)

-include $(TOOL_DEPS)

clean::
	-$(RM) $(TOOLS) $(TOOL_OBJS) $(TOOL_DEPS)


rom_15000/data/strings/strings.s: rom_15000/data/strings/strings.txt tools/pack_strings
	tools/pack_strings -i $< -o $(dir $@)

rom_15000/data/strings/strings.txt: baserom.gba tools/unpack_strings
	mkdir -p $(dir $@)
	tools/unpack_strings -r $< -o $@


OVERLAY_LZS := $(OVERLAYS:.bin=.lz)

$(OVERLAY_LZS): %.lz: %.bin tools/pack_overlay
	tools/pack_overlay -i $< -o $@

rom_320000/src/rom_320000.s: $(OVERLAY_LZS)

clean::
	-$(RM) -r rom_15000/data $(OVERLAY_LZS)


# We need the uncompressed overlays for incbin statements in overlay
# sources. They're also convenient for comparing our build outputs.

OVERLAY_DIRS := $(dir $(OVERLAYS))

define overlay_orig_deps
$(patsubst %.s,%.o,$(wildcard $(1)*.s)): %.o: $(1)orig.bin
endef
$(foreach overlay_dir,$(OVERLAY_DIRS),$(eval $(call overlay_orig_deps, $(overlay_dir))))

overlays/common/common0.o: overlays/rom_78ef88/orig.bin

overlays/common/common1.o: overlays/rom_7db0c8/orig.bin

overlays/common/common2.o: overlays/rom_7bf5a8/orig.bin

overlays/rom_%/orig.bin: baserom.gba tools/unpack_overlay
	tools/unpack_overlay -r $< -a 0x$* -o $@

clean::
	-$(RM) $(addsuffix orig.bin,$(OVERLAY_DIRS))
