@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_936_2009f14
	.thumb_func
	.type	 OvlFunc_936_2009f14,function
OvlFunc_936_2009f14:
	push	{lr}
	ldr	r3, .L16
	ldr	r3, [r3]
	cmp	r3, #4
	bhi	.L2
	ldr	r2, .L16+4
	lsl	r3, r3, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L13:
	.word	.L4
	.word	.L5
	.word	.L7
	.word	.L9
	.word	.L11
.L4:
	mov	r0, #21
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #100
	strh	r3, [r0]
	ldr	r1, .L16+8
	mov	r0, #21
	bl	__MapActor_SetBehavior
	ldr	r2, .L16
	ldr	r3, [r2]
	add	r3, r3, #1
	b	.L15
.L5:
	mov	r0, #21
	bl	__MapActor_GetActor
	add	r0, r0, #100
	mov	r2, #0
	ldrsh	r3, [r0, r2]
	cmp	r3, #0
	beq	.L2
	mov	r0, #20
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #100
	strh	r3, [r0]
	ldr	r1, .L16+12
	mov	r0, #20
	bl	__MapActor_SetBehavior
	ldr	r2, .L16
	ldr	r3, [r2]
	add	r3, r3, #1
	b	.L15
.L7:
	mov	r0, #20
	bl	__MapActor_GetActor
	add	r0, r0, #100
	mov	r2, #0
	ldrsh	r3, [r0, r2]
	cmp	r3, #0
	beq	.L2
	mov	r0, #20
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #100
	strh	r3, [r0]
	ldr	r1, .L16+8
	mov	r0, #20
	bl	__MapActor_SetBehavior
	ldr	r2, .L16
	ldr	r3, [r2]
	add	r3, r3, #1
	b	.L15
.L9:
	mov	r0, #20
	bl	__MapActor_GetActor
	add	r0, r0, #100
	mov	r2, #0
	ldrsh	r3, [r0, r2]
	cmp	r3, #0
	beq	.L2
	mov	r0, #21
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #100
	strh	r3, [r0]
	ldr	r1, .L16+12
	mov	r0, #21
	bl	__MapActor_SetBehavior
	ldr	r2, .L16
	ldr	r3, [r2]
	add	r3, r3, #1
	b	.L15
.L11:
	mov	r0, #21
	bl	__MapActor_GetActor
	add	r0, r0, #100
	mov	r2, #0
	ldrsh	r3, [r0, r2]
	cmp	r3, #0
	beq	.L2
	ldr	r2, .L16
	mov	r3, #0
.L15:
	str	r3, [r2]
.L2:
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	.L5144
	.word	.L13
	.word	gScript_936__0200bec0
	.word	gScript_936__0200bfb0
.Lfe1:
	.size	 OvlFunc_936_2009f14,.Lfe1-OvlFunc_936_2009f14

	.text
	.align	2, 0
