@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_936_200a008
	.thumb_func
	.type	 OvlFunc_936_200a008,function
OvlFunc_936_200a008:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #8
	bl	__CutsceneStart
	mov	r0, #1
	mov	r1, #1
	mov	r2, #1
	mov	r3, #0
	neg	r1, r1
	neg	r2, r2
	neg	r0, r0
	bl	__Func_80933f8
	mov	r0, #1
	bl	__WaitFrames
	mov	r1, #192
	mov	r2, #171
	lsl	r2, r2, #17
	lsl	r1, r1, #16
	mov	r0, #0
	bl	__MapActor_SetPos
	mov	r0, #1
	bl	__WaitFrames
	ldr	r0, .L6
	ldr	r1, .L6+4
	bl	__Func_80933d4
	mov	r0, #192
	mov	r1, #1
	mov	r2, #252
	lsl	r0, r0, #16
	neg	r1, r1
	lsl	r2, r2, #16
	mov	r3, #1
	bl	__Func_80933f8
	ldr	r2, .L6+8
	ldr	r3, [r2]
	mov	r8, r2
	mov	r2, #228
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #40
	str	r2, [r3]
	bl	__MapTransitionIn
	mov	r0, #0
	ldr	r1, .L6+12
	ldr	r2, .L6+16
	bl	__MapActor_SetSpeed
	mov	r2, #139
	mov	r0, #0
	mov	r1, #192
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r1, #128
	mov	r2, #128
	mov	r0, #8
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r1, #128
	mov	r2, #128
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	mov	r0, #9
	bl	__MapActor_SetSpeed
	mov	r0, #8
	bl	__MapActor_GetActor
	mov	r7, #192
	lsl	r7, r7, #6
	strh	r7, [r0, #6]
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r6, #160
	lsl	r6, r6, #7
	strh	r6, [r0, #6]
	mov	r0, #1
	bl	__WaitFrames
	mov	r0, #8
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r5, #254
	mov	r3, r5
	and	r3, r3, r2
	strb	r3, [r0]
	mov	r0, #9
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r3, [r0]
	and	r5, r5, r3
	strb	r5, [r0]
	mov	r1, #184
	mov	r0, #8
	mov	r2, #232
	bl	__Func_809218c
	mov	r2, #232
	mov	r0, #9
	mov	r1, #198
	bl	__Func_80921c4
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #8
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r3, [r0]
	mov	r5, #1
	orr	r3, r3, r5
	strb	r3, [r0]
	mov	r0, #9
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r3, [r0]
	orr	r5, r5, r3
	strb	r5, [r0]
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #8
	bl	__MapActor_DoAnim
	ldr	r0, .L6+20
	bl	__MessageID
	mov	r0, #8
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r2, #10
	mov	r0, #9
	mov	r1, r6
	bl	__Func_8092adc
	mov	r0, #9
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r2, #10
	mov	r0, #9
	mov	r1, #0
	bl	__Func_8093040
	mov	r1, #129
	mov	r0, #0
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L3
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, #2
	bl	__MapActor_SetPos
.L3:
	mov	r0, #2
	ldr	r1, .L6+12
	ldr	r2, .L6+16
	bl	__MapActor_SetSpeed
	mov	r2, #134
	mov	r0, #2
	mov	r1, #212
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r1, #224
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #7
	mov	r2, #20
	bl	__Func_8092adc
	ldr	r0, .L6+24
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r2, #254
	mov	r1, #202
	mov	r0, #2
	bl	__Func_80921c4
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #2
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r0, #8
	ldr	r1, .L6+28
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #9
	ldr	r1, .L6+28
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #9
	lsl	r1, r1, #8
	mov	r2, #40
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, r7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #9
	mov	r1, r7
	mov	r2, #20
	bl	__Func_8092adc
	mov	r1, #129
	mov	r2, #60
	mov	r0, #2
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r0, #2
	mov	r1, #1
	bl	__Func_80925cc
	mov	r2, #10
	mov	r0, #2
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #8
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #8
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r2, #60
	mov	r0, #8
	ldr	r1, .L6+32
	bl	__MapActor_Emote
	mov	r0, #8
	mov	r1, #2
	bl	__Func_809259c
	mov	r2, #10
	mov	r0, #8
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #9
	mov	r1, #2
	bl	__Func_80925cc
	mov	r2, #20
	mov	r0, #9
	mov	r1, #0
	bl	__Func_8093040
	mov	r1, #1
	mov	r0, #2
	bl	__Func_80925cc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #192
	mov	r2, #10
	mov	r0, #2
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r1, #0
	ldr	r0, .L6+24
	bl	__Func_8093054
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #8
	mov	r1, #1
	bl	__Func_80925cc
	mov	r0, #8
	mov	r1, #4
	bl	__MapActor_DoAnim
	mov	r0, #8
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r0, #2
	ldr	r1, .L6+28
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #160
	mov	r2, #20
	mov	r0, #2
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #9
	mov	r1, #1
	bl	__Func_80925cc
	mov	r0, #9
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #9
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #7
	mov	r2, #60
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #10
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #9
	lsl	r1, r1, #8
	mov	r2, #40
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, r7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r2, #10
	mov	r0, #9
	mov	r1, r7
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, #1
	bl	__Func_80925cc
	mov	r1, #0
	mov	r0, #8
	bl	__Func_8092c40
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L4
	mov	r0, #2
	mov	r1, #2
	bl	__Func_80925cc
	mov	r2, #10
	ldr	r0, .L6+24
	mov	r1, #0
	bl	__Func_8093040
	mov	r3, r8
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L5
.L7:
	.align	2, 0
.L6:
	.word	13107
	.word	1638
	.word	iwram_3001ebc
	.word	52428
	.word	26214
	.word	6917
	.word	16386
	.word	257
	.word	261
.L4:
	mov	r3, r8
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #2
	mov	r1, #4
	bl	__MapActor_DoAnim
	ldr	r0, .L8
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
.L5:
	mov	r0, #9
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #9
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r1, #192
	mov	r2, #10
	mov	r0, #2
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, #4
	bl	__MapActor_DoAnim
	mov	r2, #10
	mov	r0, #2
	mov	r1, #0
	bl	__Func_8093040
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #8
	bl	__MapActor_Surprise
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #8
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r1, #160
	mov	r2, #10
	mov	r0, #2
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r2, #10
	mov	r0, #2
	mov	r1, #0
	bl	__Func_8093040
	mov	r1, #129
	mov	r0, #8
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #9
	bl	__MapActor_Surprise
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #8
	mov	r1, #2
	bl	__Func_80925cc
	mov	r2, #10
	mov	r0, #8
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #9
	mov	r1, #2
	bl	__Func_80925cc
	mov	r1, #128
	mov	r0, #9
	lsl	r1, r1, #8
	mov	r2, #10
	bl	__Func_8092adc
	mov	r0, #9
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r2, #10
	mov	r0, #8
	mov	r1, #0
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #192
	mov	r2, #10
	mov	r0, #8
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #192
	mov	r2, #10
	mov	r0, #9
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #192
	mov	r2, #10
	mov	r0, #2
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r1, #0
	ldr	r0, .L8
	bl	__Func_8093054
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #2
	mov	r1, #1
	bl	__Func_80925cc
	mov	r2, #10
	ldr	r0, .L8
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #192
	mov	r2, #10
	mov	r0, #2
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #8
	ldr	r1, .L8+4
	ldr	r2, .L8+8
	bl	__MapActor_SetSpeed
	ldr	r1, .L8+4
	ldr	r2, .L8+8
	mov	r0, #9
	bl	__MapActor_SetSpeed
	mov	r0, #8
	bl	__MapActor_GetActor
	mov	r3, #0
	strh	r3, [r0, #6]
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r3, #128
	lsl	r3, r3, #8
	strh	r3, [r0, #6]
	mov	r0, #8
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r5, #254
	mov	r3, r5
	and	r3, r3, r2
	strb	r3, [r0]
	mov	r0, #9
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r3, [r0]
	and	r5, r5, r3
	strb	r5, [r0]
	mov	r1, #168
	mov	r0, #8
	mov	r2, #232
	bl	__Func_809218c
	mov	r2, #232
	mov	r0, #9
	mov	r1, #212
	bl	__Func_80921c4
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #8
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r3, [r0]
	mov	r5, #1
	orr	r3, r3, r5
	strb	r3, [r0]
	mov	r0, #9
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r3, [r0]
	orr	r5, r5, r3
	strb	r5, [r0]
	mov	r1, #192
	mov	r0, #2
	mov	r2, #232
	bl	__Func_80921c4
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #188
	bl	__PlaySound
	mov	r5, #2
	mov	r1, #23
	mov	r2, #43
	mov	r3, #12
	mov	r0, #36
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #5
	bl	__WaitFrames
	mov	r3, #12
	mov	r1, #23
	mov	r2, #43
	mov	r0, #39
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #5
	bl	__WaitFrames
	mov	r0, #2
	mov	r1, #192
	mov	r2, #222
	bl	__Func_80921c4
	mov	r0, #2
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #0
	ldr	r1, .L8+12
	ldr	r2, .L8+16
	bl	__MapActor_SetSpeed
	mov	r0, #0
	mov	r1, #192
	mov	r2, #222
	bl	__Func_80921c4
	mov	r2, #0
	mov	r0, #0
	mov	r1, #0
	bl	__MapActor_SetPos
	mov	r0, #8
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #9
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #8
	mov	r1, #184
	mov	r2, #232
	bl	__Func_809218c
	mov	r0, #9
	mov	r1, #198
	mov	r2, #232
	bl	__Func_80921c4
	mov	r0, #8
	mov	r1, #188
	mov	r2, #212
	bl	__Func_809218c
	mov	r0, #9
	mov	r1, #194
	mov	r2, #212
	bl	__Func_80921c4
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r3, .L8+20
	ldr	r1, [r3]
	mov	r3, #228
	lsl	r3, r3, #1
	add	r2, r1, r3
	mov	r3, #24
	str	r3, [r2]
	mov	r3, #224
	lsl	r3, r3, #1
	add	r2, r1, r3
	add	r3, r3, #65
	str	r3, [r2]
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	mov	r0, #5
	bl	__Func_8091e9c
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	16386
	.word	52428
	.word	26214
	.word	78643
	.word	39321
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_936_200a008,.Lfe1-OvlFunc_936_200a008

	.text
	.align	2, 0
