@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_936_200b970
	.thumb_func
	.type	 OvlFunc_936_200b970,function
OvlFunc_936_200b970:
	push	{r5, r6, lr}
	mov	r0, #11
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r3, #14
	mov	r6, r0
	mov	r5, #9
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r1, #0
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	mov	r3, #45
	str	r3, [sp, #4]
	mov	r0, #0
	mov	r1, #0
	mov	r2, #1
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	cmp	r6, #0
	beq	.L3
	mov	r0, r6
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r3, [r6, #12]
	ldr	r2, .L4
	add	r3, r3, r2
	mov	r2, r6
	str	r3, [r6, #12]
	add	r2, r2, #35
	mov	r3, #2
	strb	r3, [r2]
.L3:
	ldr	r0, .L4+4
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	-2097152
	.word	513
.Lfe1:
	.size	 OvlFunc_936_200b970,.Lfe1-OvlFunc_936_200b970

	.text
	.align	2, 0
