@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_909_2008094
	.thumb_func
	.type	 OvlFunc_909_2008094,function
OvlFunc_909_2008094:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200a920
.Lfe1:
	.size	 OvlFunc_909_2008094,.Lfe1-OvlFunc_909_2008094

	.text
	.align	2, 0
