@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_909_2009958
	.thumb_func
	.type	 OvlFunc_909_2009958,function
OvlFunc_909_2009958:
	push	{lr}
	mov	r1, #224
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #160
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_909_2009958,.Lfe1-OvlFunc_909_2009958

	.text
	.align	2, 0
