@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_909_200979c
	.thumb_func
	.type	 OvlFunc_909_200979c,function
OvlFunc_909_200979c:
	push	{lr}
	bl	__CutsceneStart
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	mov	r1, #192
	mov	r0, #19
	lsl	r1, r1, #6
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #0
	ldr	r1, .L3
	ldr	r2, .L3+4
	bl	__MapActor_SetSpeed
	mov	r1, #128
	mov	r2, #165
	lsl	r1, r1, #1
	lsl	r2, r2, #2
	mov	r0, #0
	bl	__Func_80921c4
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #1
	.code	16
	mov	r1, #1
	mov	r2, #1
	mov	r3, #0
	neg	r1, r1
	neg	r2, r2
	neg	r0, r0
	bl	__Func_80933f8
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__SetFlag
	mov	r0, #188
	bl	__PlaySound
	mov	r0, #1
	bl	__Func_80118a8
	mov	r0, #2
	bl	__Func_80118a8
	mov	r1, #128
	mov	r2, #158
	lsl	r1, r1, #17
	lsl	r2, r2, #18
	mov	r0, #19
	bl	__MapActor_SetPos
	mov	r0, #1
	bl	__WaitFrames
	mov	r0, #19
	ldr	r1, .L3
	ldr	r2, .L3+4
	bl	__MapActor_SetSpeed
	mov	r1, #128
	.code	16
	mov	r2, #161
	lsl	r2, r2, #2
	lsl	r1, r1, #1
	mov	r0, #19
	bl	__Func_80921c4
	mov	r0, #1
	bl	__Func_80118c0
	mov	r0, #2
	bl	__Func_80118c0
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #19
	bl	__Func_80925cc
	ldr	r0, .L3+8
	bl	__MessageID
	mov	r0, #19
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #132
	mov	r2, #165
	mov	r0, #0
	lsl	r1, r1, #1
	lsl	r2, r2, #2
	bl	__Func_80921c4
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r2, #165
	mov	r0, #19
	mov	r1, #248
	lsl	r2, r2, #2
	bl	__Func_80921c4
	mov	r1, #128
	mov	r2, #40
	mov	r0, #19
	lsl	r1, r1, #5
	bl	__Func_8092adc
	mov	r0, #19
	mov	r1, #4
	bl	__MapActor_DoAnim
	mov	r0, #19
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #19
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #0
	mov	r0, #19
	bl	__Func_8093054
	mov	r0, #19
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #19
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r2, #60
	mov	r0, #0
	ldr	r1, .L3+12
	bl	__MapActor_Emote
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #19
	bl	__MapActor_Surprise
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #19
	mov	r1, #1
	bl	__Func_80925cc
	mov	r2, #10
	mov	r0, #19
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #19
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #19
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #19
	ldr	r1, .L3+16
	ldr	r2, .L3+20
	bl	__MapActor_SetSpeed
	mov	r2, #193
	mov	r0, #19
	mov	r1, #248
	lsl	r2, r2, #2
	bl	__Func_80921c4
	mov	r1, #0
	mov	r2, #0
	mov	r0, #19
	bl	__MapActor_SetPos
	ldr	r0, .L3+24
	bl	__ClearFlag
	ldr	r0, .L3+28
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	39321
	.word	19660
	.word	5214
	.word	257
	.word	52428
	.word	26214
	.word	303
	.word	2127
.Lfe1:
	.size	 OvlFunc_909_200979c,.Lfe1-OvlFunc_909_200979c

	.text
	.align	2, 0
