@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_956_20085d0
	.thumb_func
	.type	 OvlFunc_956_20085d0,function
OvlFunc_956_20085d0:
	bx	lr
.Lfe1:
	.size	 OvlFunc_956_20085d0,.Lfe1-OvlFunc_956_20085d0

	.text
	.align	2, 0
