@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_956_200a4d0
	.thumb_func
	.type	 OvlFunc_956_200a4d0,function
OvlFunc_956_200a4d0:
	push	{r5, r6, lr}
	ldr	r3, .L7
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	mov	r5, r0
	cmp	r3, #2
	bne	.L3
	bl	OvlFunc_common1_2c4
	b	.L2
.L3:
	bl	__CutsceneStart
	mov	r0, r5
	mov	r1, #6
	bl	OvlFunc_common1_4cc
	mov	r6, r0
	cmp	r6, #0
	bne	.L4
	ldr	r0, .L7+4
	bl	__MessageID
	mov	r0, #192
	mov	r1, #192
	lsl	r0, r0, #10
	lsl	r1, r1, #7
	bl	__Func_80933d4
	mov	r0, #161
	mov	r1, #1
	mov	r2, #152
	mov	r3, #1
	lsl	r2, r2, #16
	neg	r1, r1
	lsl	r0, r0, #19
	bl	__Func_80933f8
	bl	__Func_8093530
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r2, #0
	mov	r1, #88
	mov	r0, #180
	bl	OvlFunc_common1_1490
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r2, #10
	mov	r1, #84
	mov	r0, #32
	bl	OvlFunc_common1_14f4
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r2, #30
	mov	r1, #84
	mov	r0, #96
	bl	OvlFunc_common1_14f4
	mov	r0, #60
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, r5
	bl	__ActorMessage
	bl	OvlFunc_common1_1550
	mov	r0, #2
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #0
	bl	__SetCameraTarget
	mov	r0, r5
	mov	r1, #6
	bl	OvlFunc_common1_588
	b	.L5
.L4:
	cmp	r6, #1
	bne	.L5
	ldr	r0, .L7+8
	bl	__MessageID
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
.L5:
	mov	r1, r5
	mov	r2, #6
	mov	r0, r6
	bl	OvlFunc_common1_5e4
	bl	__CutsceneEnd
.L2:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	gState
	.word	8391
	.word	8390
.Lfe1:
	.size	 OvlFunc_956_200a4d0,.Lfe1-OvlFunc_956_200a4d0

	.text
	.align	2, 0
