@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_c_c_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_891_20095d4
	.thumb_func
	.type	 OvlFunc_891_20095d4,function
OvlFunc_891_20095d4:
	push	{lr}
	mov	r1, #208
	mov	r2, #224
	mov	r0, #2
	lsl	r1, r1, #16
	lsl	r2, r2, #15
	mov	r3, #0
	bl	__Func_8012078
	mov	r0, #10
	mov	r1, #14
	mov	r2, #7
	bl	OvlFunc_891_2009be8
	cmp	r0, #0
	beq	.L3
	bl	OvlFunc_891_200a244
.L3:
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_891_20095d4,.Lfe1-OvlFunc_891_20095d4

	.text
	.align	2, 0
