@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_891_2009a44
	.thumb_func
	.type	 OvlFunc_891_2009a44,function
OvlFunc_891_2009a44:
	push	{lr}
	sub	sp, sp, #4
	mov	r3, #12
	str	r3, [sp]
	mov	r0, #15
	mov	r1, #40
	mov	r2, #12
	mov	r3, #41
	bl	OvlFunc_891_2009b44
	bl	OvlFunc_891_2009f0c
	add	sp, sp, #4
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_891_2009a44,.Lfe1-OvlFunc_891_2009a44

	.text
	.align	2, 0
