@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_891_20096a4
	.thumb_func
	.type	 OvlFunc_891_20096a4,function
OvlFunc_891_20096a4:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	mov	r0, #0
	asr	r5, r3, #20
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	asr	r3, r3, #20
	cmp	r3, #7
	bne	.L3
	mov	r3, r5
	sub	r3, r3, #21
	cmp	r3, #1
	bhi	.L3
	mov	r1, #176
	mov	r2, #224
	mov	r0, #2
	lsl	r1, r1, #17
	lsl	r2, r2, #15
	mov	r3, #255
	bl	__Func_8012078
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_891_20096a4,.Lfe1-OvlFunc_891_20096a4

	.text
	.align	2, 0
