@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_899_200af98
	.thumb_func
	.type	 OvlFunc_899_200af98,function
OvlFunc_899_200af98:
	push	{lr}
	bl	__Func_80bf65c
	mov	r0, #2
	bl	__GetUnit
	add	r0, r0, #248
	ldr	r3, [r0]
	mov	r2, #1
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L3
	mov	r1, #0
	mov	r2, #0
	mov	r3, #0
	mov	r0, #2
	bl	__Func_807a498
	mov	r0, #126
	bl	__PlaySound
	mov	r0, #0
	bl	__CalcStats
	mov	r0, #2
	bl	__CalcStats
.L3:
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_899_200af98,.Lfe1-OvlFunc_899_200af98

	.text
	.align	2, 0
