@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_a_a_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_899_200819c
	.thumb_func
	.type	 OvlFunc_899_200819c,function
OvlFunc_899_200819c:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldrh	r5, [r0, #6]
	bl	__CutsceneStart
	ldr	r3, .L7
	add	r5, r5, r3
	ldr	r3, .L7+4
	cmp	r5, r3
	bhi	.L3
	mov	r0, #5
	mov	r1, #20
	bl	__Func_80b0278
	b	.L4
.L3:
	ldr	r0, .L7+8
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	ldr	r0, .L7+12
	bl	__MessageID
	b	.L6
.L5:
	ldr	r0, .L7+16
	bl	__MessageID
.L6:
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
.L4:
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	-40961
	.word	16382
	.word	2133
	.word	4738
	.word	4978
.Lfe1:
	.size	 OvlFunc_899_200819c,.Lfe1-OvlFunc_899_200819c

	.text
	.align	2, 0
