@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_899_2009e80
	.thumb_func
	.type	 OvlFunc_899_2009e80,function
OvlFunc_899_2009e80:
	push	{lr}
	mov	r0, #30
	sub	sp, sp, #8
	bl	__CutsceneWait
	mov	r1, #1
	mov	r0, #24
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r0, .L3
	bl	__MessageID
	mov	r0, #24
	mov	r1, #20
	bl	OvlFunc_899_200c5f4
	mov	r2, #20
	.code	16
	mov	r0, #25
	mov	r1, #0
	bl	__Func_8092adc
	mov	r1, #129
	mov	r0, #25
	.code	16
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r0, #25
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #25
	mov	r1, #20
	bl	OvlFunc_899_200c5f4
	mov	r1, #4
	mov	r0, #24
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #24
	mov	r1, #20
	bl	OvlFunc_899_200c5f4
	mov	r1, #128
	mov	r2, #128
	mov	r0, #24
	.code	16
	lsl	r1, r1, #11
	.code	16
	lsl	r2, r2, #10
	bl	__MapActor_SetSpeed
	mov	r1, #224
	.code	16
	mov	r2, #224
	lsl	r2, r2, #9
	mov	r0, #25
	.code	16
	lsl	r1, r1, #10
	bl	__MapActor_SetSpeed
	ldr	r1, .L3+4
	mov	r0, #25
	bl	__MapActor_SetBehavior
	ldr	r1, .L3+8
	mov	r0, #24
	bl	__MapActor_SetBehavior
	mov	r0, #24
	bl	__MapActor_WaitScript
	mov	r0, #24
	bl	__MapActor_GetActor
	mov	r3, #1
	add	r0, r0, #100
	strh	r3, [r0]
	mov	r0, #25
	bl	__MapActor_GetActor
	mov	r3, #3
	add	r0, r0, #100
	strh	r3, [r0]
	mov	r2, #44
	mov	r3, #14
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #14
	mov	r1, #48
	mov	r2, #4
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	_MSG_12a0
	.word	gScript_899__0200d830
	.word	gScript_899__0200d560
.Lfe1:
	.size	 OvlFunc_899_2009e80,.Lfe1-OvlFunc_899_2009e80

	.text
	.align	2, 0
