@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_899_200c684
	.thumb_func
	.type	 OvlFunc_899_200c684,function
OvlFunc_899_200c684:
	push	{lr}
	mov	r0, #2
	bl	__FieldMove
	bl	__Func_8097174
	bl	__Func_8097194
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_899_200c684,.Lfe1-OvlFunc_899_200c684

	.text
	.align	2, 0
