@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_915_2008aac
	.thumb_func
	.type	 OvlFunc_915_2008aac,function
OvlFunc_915_2008aac:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r5, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r7, r6
	add	r7, r7, #85
	ldrb	r3, [r7]
	mov	r1, r5
	mov	sl, r3
	bl	__TestCollision
	mov	r8, r0
	cmp	r0, #0
	bne	.L3
	bl	__CutsceneStart
	mov	r1, #6
	mov	r0, r6
	bl	__Actor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #152
	bl	__PlaySound
	mov	r0, r6
	mov	r1, #7
	bl	__Actor_SetAnim
	mov	r3, #192
	lsl	r3, r3, #10
	str	r3, [r6, #48]
	mov	r3, #128
	lsl	r3, r3, #10
	str	r3, [r6, #52]
	mov	r3, #128
	lsl	r3, r3, #11
	str	r3, [r6, #40]
	ldrb	r2, [r7]
	mov	r3, #126
	and	r3, r3, r2
	strb	r3, [r7]
	mov	r0, r6
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r3, #10
	ldrsh	r2, [r5, r3]
	mov	r3, #2
	ldrsh	r1, [r5, r3]
	mov	r0, #0
	bl	__Func_8092158
	mov	r0, r6
	mov	r1, #6
	bl	__Actor_SetAnim
	mov	r0, r6
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r3, r8
	mov	r1, #7
	strb	r3, [r7]
	mov	r0, #10
	bl	__MapActor_SetAnim
	ldr	r5, .L4
	ldr	r3, [r6, #12]
	add	r3, r3, r5
	str	r3, [r6, #12]
	ldr	r3, [r6, #20]
	add	r3, r3, r5
	str	r3, [r6, #20]
	mov	r0, #2
	bl	__WaitFrames
	ldr	r3, [r6, #12]
	add	r3, r3, r5
	str	r3, [r6, #12]
	ldr	r3, [r6, #20]
	add	r3, r3, r5
	str	r3, [r6, #20]
	mov	r0, #10
	bl	__WaitFrames
	mov	r5, #128
	ldr	r3, [r6, #12]
	lsl	r5, r5, #9
	add	r3, r3, r5
	str	r3, [r6, #12]
	ldr	r3, [r6, #20]
	add	r3, r3, r5
	mov	r0, #4
	str	r3, [r6, #20]
	bl	__WaitFrames
	ldr	r3, [r6, #12]
	add	r3, r3, r5
	str	r3, [r6, #12]
	ldr	r3, [r6, #20]
	add	r3, r3, r5
	str	r3, [r6, #20]
	mov	r3, sl
	strb	r3, [r7]
	bl	__CutsceneEnd
	mov	r0, #1
	b	.L2
.L3:
	mov	r0, #0
.L2:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	-65536
.Lfe1:
	.size	 OvlFunc_915_2008aac,.Lfe1-OvlFunc_915_2008aac

	.text
	.align	2, 0
