@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_915_2008ba4
	.thumb_func
	.type	 OvlFunc_915_2008ba4,function
OvlFunc_915_2008ba4:
	push	{r5, lr}
	ldr	r3, .L3
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r0, [r3]
	sub	sp, sp, #12
	bl	__MapActor_GetActor
	ldr	r5, .L3+4
	ldr	r2, [r0, #8]
	mov	r4, #128
	lsl	r4, r4, #12
	and	r2, r2, r5
	mov	r1, sp
	add	r3, r2, r4
	str	r3, [r1]
	ldr	r3, [r0, #12]
	str	r3, [r1, #4]
	ldr	r3, [r0, #16]
	and	r3, r3, r5
	add	r3, r3, r4
	str	r3, [r1, #8]
	mov	r3, #160
	lsl	r3, r3, #14
	add	r2, r2, r3
	str	r2, [r1]
	mov	r0, r1
	bl	OvlFunc_915_2008aac
	add	sp, sp, #12
	pop	{r5}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	gState
	.word	-1048576
.Lfe1:
	.size	 OvlFunc_915_2008ba4,.Lfe1-OvlFunc_915_2008ba4

	.text
	.align	2, 0
