@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_920_2008168
	.thumb_func
	.type	 OvlFunc_920_2008168,function
OvlFunc_920_2008168:
	push	{lr}
	sub	sp, sp, #8
	mov	r3, #21
	mov	r2, #14
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #0
	mov	r1, #0
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_920_2008168,.Lfe1-OvlFunc_920_2008168

	.text
	.align	2, 0
