@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_a_c_c_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_920_20081bc
	.thumb_func
	.type	 OvlFunc_920_20081bc,function
OvlFunc_920_20081bc:
	push	{lr}
	sub	sp, sp, #8
	mov	r3, #1
	mov	r2, #3
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #95
	mov	r1, #21
	mov	r2, #97
	mov	r3, #21
	bl	__CopyMapTiles
	mov	r3, #32
	mov	r2, #25
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #46
	mov	r1, #38
	mov	r2, #3
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_920_20081bc,.Lfe1-OvlFunc_920_20081bc

	.text
	.align	2, 0
