@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b798_c_a_a_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Sprite_AddLayer
	.thumb_func
	.type	 Sprite_AddLayer,function
Sprite_AddLayer:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	ldr	r5, [r6, #40]
	mov	r8, r1
	mov	r7, #0
	cmp	r5, #0
	beq	.L4
	mov	r3, r6
	add	r3, r3, #40
.L5:
	add	r7, r7, #1
	cmp	r7, #3
	bgt	.L4
	add	r3, r3, #4
	ldr	r5, [r3]
	cmp	r5, #0
	bne	.L5
.L4:
	cmp	r7, #4
	bne	.L9
	mov	r0, #1
	neg	r0, r0
	b	.L2
.L9:
	mov	r0, r8
	bl	CreateSpriteLayer
	mov	r5, r0
	mov	r0, #0
	cmp	r5, #0
	beq	.L2
	lsl	r3, r7, #2
	add	r3, r3, #40
	mov	r0, r8
	str	r5, [r6, r3]
	bl	_GetSpriteInfo
	mov	r2, #39
	add	r2, r2, r6
	ldrb	r3, [r2]
	mov	ip, r2
	cmp	r3, #0
	bne	.L11
	ldrb	r2, [r0]
	mov	r3, r6
	add	r3, r3, #32
	strb	r2, [r3]
	ldrb	r3, [r0, #1]
	mov	r2, r6
	add	r2, r2, #33
	strb	r3, [r2]
	ldrh	r3, [r0, #2]
	lsl	r3, r3, #8
	str	r3, [r6, #24]
	ldrb	r3, [r0, #7]
	add	r2, r2, #2
	strb	r3, [r2]
	mov	r1, r6
	ldrb	r3, [r0, #6]
	add	r1, r1, #34
	strb	r3, [r1]
.L11:
	mov	r2, ip
	ldrb	r3, [r2]
	cmp	r7, r3
	bne	.L12
	add	r3, r7, #1
	strb	r3, [r2]
.L12:
	mov	r0, r5
.L2:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Sprite_AddLayer,.Lfe1-Sprite_AddLayer

	.text
	.align	2, 0
