@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_d924_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	ActorCmd_Unused
	.thumb_func
	.type	 ActorCmd_Unused,function
ActorCmd_Unused:
	push	{r5, lr}
	sub	sp, sp, #12
	mov	r5, r0
	mov	r0, sp
	ldr	r3, [r0]
	ldr	r1, [r5, #8]
	ldr	r2, [r5, #12]
	add	r1, r1, r3
	ldr	r3, [r0, #4]
	ldr	r0, [r0, #8]
	add	r2, r2, r3
	ldr	r3, [r5, #16]
	add	r3, r3, r0
	mov	r0, r5
	bl	Actor_TravelTo
	ldrh	r3, [r5, #4]
	add	r3, r3, #3
	mov	r0, #1
	strh	r3, [r5, #4]
	add	sp, sp, #12
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 ActorCmd_Unused,.Lfe1-ActorCmd_Unused

	.text
	.align	2, 0
