@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_11ce0_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	HeightTile_C
	.thumb_func
	.type	 HeightTile_C,function
HeightTile_C:
	ldr	r3, .L3
	lsl	r2, r2, #4
	add	r1, r1, r2
	ldrb	r3, [r3, r1]
	ldrsb	r0, [r0, r3]
	lsl	r0, r0, #19
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	.L133fc
.Lfe1:
	.size	 HeightTile_C,.Lfe1-HeightTile_C

	.text
	.align	2, 0
