@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_c004_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	InitActors
	.thumb_func
	.type	 InitActors,function
InitActors:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r7, r0
	mov	r1, #92
	mov	r0, #6
	sub	sp, sp, #4
	bl	galloc_ewram
	mov	r1, #224
	lsl	r1, r1, #5
	mov	r8, r0
	mov	r0, #5
	bl	galloc_ewram
	mov	r6, r0
	mov	r0, r7
	bl	InitSprites
	mov	r5, #0
	mov	r4, sp
	str	r5, [r4]
	ldr	r3, .L18
	mov	r0, r4
	mov	r1, r6
	ldr	r2, .L18+4
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	str	r5, [r4]
	mov	r0, r4
	mov	r1, r8
	ldr	r2, .L18+8
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	cmp	r7, #4
	bne	.L14
	ldr	r0, .L18+12
	ldr	r1, .L18+16
	bl	StartTask
	b	.L15
.L14:
	ldr	r0, .L18+20
	ldr	r1, .L18+16
	bl	StartTask
.L15:
	sub	r3, r7, #3
	cmp	r3, #1
	bhi	.L16
	mov	r1, #200
	ldr	r0, .L18+24
	lsl	r1, r1, #4
	bl	StartTask
	b	.L17
.L16:
	mov	r1, #200
	ldr	r0, .L18+28
	lsl	r1, r1, #4
	bl	StartTask
	ldr	r3, .L18+32
	mov	r2, #0
	str	r2, [r3]
	ldr	r3, .L18+36
	str	r2, [r3]
.L17:
	mov	r1, r8
	mov	r2, #0
	mov	r3, #15
	strb	r3, [r1, #6]
	strb	r2, [r1, #7]
	add	sp, sp, #4
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L19:
	.align	2, 0
.L18:
	.word	67109076
	.word	-2063595776
	.word	-2063597545
	.word	Func_800d340
	.word	3210
	.word	UpdateActors
	.word	Func_800c880
	.word	Func_800c62c
	.word	iwram_3001d1c
	.word	iwram_3001cc0
.Lfe1:
	.size	 InitActors,.Lfe1-InitActors

	.text
	.align	2, 0
