@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_ea54_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_800ea60
	.thumb_func
	.type	 Func_800ea60,function
Func_800ea60:
	push	{r5, r6, r7, lr}
	ldr	r7, .L16
	ldr	r3, .L16+4
	lsr	r6, r0, #14
	and	r7, r7, r0
	ldr	r0, .L16+8
	ldr	r5, [r3]
	bl	_GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r3, #193
	lsl	r3, r3, #1
	add	r2, r5, r3
	mov	r3, #250
	strh	r3, [r2]
	b	.L4
.L3:
	mov	r2, #207
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #3
	bne	.L5
	ldr	r1, .L16+12
	mov	r2, #128
	ldr	r3, [r1]
	lsl	r2, r2, #1
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L6
	mov	r3, #193
	lsl	r3, r3, #1
	add	r2, r5, r3
	ldr	r3, .L16+16
	strh	r3, [r2]
	b	.L4
.L6:
	ldr	r3, [r1]
	mov	r2, #128
	lsl	r2, r2, #2
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L4
	mov	r3, #193
	lsl	r3, r3, #1
	add	r2, r5, r3
	ldr	r3, .L16+20
	strh	r3, [r2]
	b	.L4
.L5:
	cmp	r6, #0
	beq	.L11
	cmp	r6, #1
	beq	.L12
	b	.L4
.L11:
	mov	r2, #191
	b	.L15
.L12:
	mov	r2, #192
.L15:
	lsl	r2, r2, #1
	add	r3, r5, r2
	strh	r7, [r3]
.L4:
	mov	r0, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L17:
	.align	2, 0
.L16:
	.word	16383
	.word	iwram_3001ebc
	.word	263
	.word	gKeyPress
	.word	64648
	.word	64647
.Lfe1:
	.size	 Func_800ea60,.Lfe1-Func_800ea60

	.text
	.align	2, 0
