@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_ca6c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Actor_IsNotMoving
	.thumb_func
	.type	 Actor_IsNotMoving,function
Actor_IsNotMoving:
	push	{lr}
	mov	r3, r0
	add	r3, r3, #85
	ldrb	r3, [r3]
	cmp	r3, #0
	bne	.L3
	mov	r2, #128
	ldr	r3, [r0, #56]
	lsl	r2, r2, #24
	cmp	r3, r2
	bne	.L6
	ldr	r2, [r0, #60]
	b	.L5
.L3:
	mov	r3, #128
	ldr	r2, [r0, #56]
	lsl	r3, r3, #24
.L5:
	cmp	r2, r3
	bne	.L6
	ldr	r3, [r0, #64]
	mov	r0, #1
	cmp	r3, r2
	beq	.L2
.L6:
	mov	r0, #0
.L2:
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Actor_IsNotMoving,.Lfe1-Actor_IsNotMoving

	.text
	.align	2, 0
