@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_108e4_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8010d48
	.thumb_func
	.type	 Func_8010d48,function
Func_8010d48:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r5, r0
	mov	r0, r3
	ldr	r3, .L12
	ldr	r3, [r3]
	mov	r8, r3
	ldr	r3, [r3]
	mov	r6, #0
	sub	sp, sp, #4
	mov	r4, r2
	mov	ip, r6
	cmp	r3, #0
	beq	.L3
	ldmia	r3!, {r6}
	ldr	r3, [r3, #4]
	mov	ip, r3
.L3:
	asr	r1, r1, #4
	lsl	r3, r1, #4
	mov	r2, ip
	asr	r5, r5, #4
	asr	r0, r0, #3
	asr	r4, r4, #3
	add	r7, r3, r5
	asr	r2, r2, #24
	asr	r3, r0, #31
	mov	ip, r2
	asr	r5, r4, #31
	lsr	r2, r3, #31
	mov	lr, r3
	add	r2, r0, r2
	lsr	r3, r5, #31
	mov	r1, #15
	asr	r2, r2, #1
	add	r3, r4, r3
	and	r2, r2, r1
	asr	r3, r3, #1
	and	r3, r3, r1
	lsl	r2, r2, #4
	add	r2, r2, r3
	mov	r3, #156
	lsl	r3, r3, #1
	lsl	r2, r2, #1
	add	r2, r2, r3
	asr	r6, r6, #24
	mov	r3, r8
	strh	r7, [r3, r2]
	sub	r3, r6, r4
	cmp	r3, #0
	blt	.L4
	cmp	r3, #1
	ble	.L6
	b	.L2
.L4:
	sub	r3, r4, r6
	cmp	r3, #1
	bgt	.L2
.L6:
	mov	r2, ip
	sub	r3, r2, r0
	cmp	r3, #0
	blt	.L8
	cmp	r3, #1
	ble	.L10
	b	.L2
.L8:
	mov	r2, ip
	sub	r3, r0, r2
	cmp	r3, #1
	bgt	.L2
.L10:
	mov	r3, lr
	lsr	r6, r5, #31
	lsr	r5, r3, #31
	add	r6, r4, r6
	add	r5, r0, r5
	mov	r2, #1
	asr	r6, r6, #1
	asr	r5, r5, #1
	mov	r8, r2
	str	r2, [sp]
	mov	r1, r6
	mov	r2, r5
	mov	r3, r7
	mov	r0, #0
	bl	Func_80108e4
	mov	r2, #160
	lsl	r2, r2, #1
	add	r3, r7, r2
	mov	r2, r8
	str	r2, [sp]
	mov	r0, #1
	mov	r1, r6
	mov	r2, r5
	bl	Func_80108e4
.L2:
	add	sp, sp, #4
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	iwram_3001e70
.Lfe1:
	.size	 Func_8010d48,.Lfe1-Func_8010d48

	.text
	.align	2, 0
