@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_927_2008d90
	.thumb_func
	.type	 OvlFunc_927_2008d90,function
OvlFunc_927_2008d90:
	push	{r5, r6, lr}
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6}
	mov	r6, r8
	push	{r6}
	mov	r6, r0
	mov	sl, r2
	mov	r9, r3
	mov	r8, r1
	bl	__MapActor_GetActor
	mov	r1, #1
	mov	r5, r0
	mov	r0, r6
	bl	__Func_8092b08
	mov	r1, #192
	mov	r2, #192
	lsl	r2, r2, #9
	mov	r0, r6
	lsl	r1, r1, #10
	bl	__MapActor_SetSpeed
	mov	r0, #152
	bl	__PlaySound
	mov	r3, r9
	str	r3, [r5, #40]
	mov	r3, #128
	lsl	r3, r3, #8
	str	r3, [r5, #72]
	mov	r3, #0
	str	r3, [r5, #68]
	mov	r0, r5
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, r6
	mov	r1, r8
	mov	r2, sl
	bl	__Func_8092158
	mov	r3, r8
	lsl	r3, r3, #16
	mov	r8, r3
	mov	r3, sl
	lsl	r3, r3, #16
	mov	sl, r3
	mov	r0, r6
	mov	r1, r8
	mov	r2, sl
	bl	__MapActor_SetPos
	mov	r0, r5
	mov	r1, #1
	bl	__Actor_SetSpriteFlags
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r5, #72]
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_927_2008d90,.Lfe1-OvlFunc_927_2008d90

	.text
	.align	2, 0
