@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_927_2009328
	.thumb_func
	.type	 OvlFunc_927_2009328,function
OvlFunc_927_2009328:
	push	{r5, r6, lr}
	mov	r0, #12
	sub	sp, sp, #16
	bl	__MapActor_GetActor
	mov	r6, #172
	mov	r5, r0
	bl	__CutsceneStart
	mov	r0, #12
	mov	r1, #1
	bl	OvlFunc_927_2008ea8
	lsl	r6, r6, #1
	mov	r1, #134
	mov	r3, #224
	mov	r2, r6
	lsl	r1, r1, #2
	lsl	r3, r3, #11
	mov	r0, #12
	bl	OvlFunc_927_2008d90
	ldr	r2, [r5, #16]
	mov	r3, #128
	lsl	r3, r3, #13
	add	r2, r2, r3
	mov	r3, #1
	mov	r4, #0
	ldr	r0, [r5, #8]
	ldr	r1, [r5, #12]
	str	r3, [sp, #8]
	mov	r3, #0
	str	r4, [sp]
	str	r4, [sp, #4]
	str	r4, [sp, #12]
	bl	OvlFunc_927_2008ae8
	mov	r0, #12
	mov	r1, #1
	bl	__SetCameraTarget
	mov	r2, #0
	mov	r1, #0
	mov	r0, #12
	bl	__Func_8092848
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #12
	mov	r1, #2
	bl	__Func_809259c
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #12
	bl	__MapActor_Surprise
	mov	r5, #192
	mov	r0, #60
	bl	__CutsceneWait
	lsl	r5, r5, #10
	mov	r1, #146
	mov	r3, r5
	mov	r2, r6
	lsl	r1, r1, #2
	mov	r0, #12
	bl	OvlFunc_927_2008d90
	mov	r1, #12
	mov	r2, #0
	mov	r0, #0
	bl	__Func_809280c
	mov	r0, #6
	bl	__CutsceneWait
	mov	r1, #158
	mov	r3, r5
	mov	r2, r6
	lsl	r1, r1, #2
	mov	r0, #12
	bl	OvlFunc_927_2008d90
	mov	r1, #12
	mov	r2, #0
	mov	r0, #0
	bl	__Func_809280c
	mov	r0, #6
	bl	__CutsceneWait
	mov	r1, #170
	mov	r3, r5
	mov	r2, r6
	lsl	r1, r1, #2
	mov	r0, #12
	bl	OvlFunc_927_2008d90
	mov	r1, #12
	mov	r2, #0
	mov	r0, #0
	bl	__Func_809280c
	mov	r0, #6
	bl	__CutsceneWait
	ldr	r0, .L3
	bl	__SetFlag
	mov	r0, #15
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	bl	__CutsceneEnd
	add	sp, sp, #16
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	770
.Lfe1:
	.size	 OvlFunc_927_2009328,.Lfe1-OvlFunc_927_2009328

	.text
	.align	2, 0
