@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_a_a_a_a_a_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_945_200b364
	.thumb_func
	.type	 OvlFunc_945_200b364,function
OvlFunc_945_200b364:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r0, .L15
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	bl	OvlFunc_945_200c5d0
	b	.L2
.L16:
	.align	2, 0
.L15:
	.word	2321
.L3:
	ldr	r0, .L17+4
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	bl	OvlFunc_945_200c5d0
.L4:
	ldr	r0, .L17+8
	bl	__GetFlag
	mov	r7, r0
	cmp	r7, #0
	beq	.LCB39
	b	.L2	@long jump
.LCB39:
	mov	r0, #138
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r1, #0
	mov	r6, r0
	mov	r2, #0
	mov	r0, #13
	bl	OvlFunc_945_200c8e8
	mov	r1, #228
	mov	r2, #163
	lsl	r1, r1, #1
	lsl	r2, r2, #2
	mov	r0, #8
	mov	r3, #0
	bl	OvlFunc_945_200c890
	mov	r3, #240
	lsl	r3, r3, #1
	mov	r8, r3
	mov	r2, #150
	mov	r3, #176
	lsl	r3, r3, #8
	lsl	r2, r2, #2
	mov	r0, #9
	mov	r1, r8
	bl	OvlFunc_945_200c890
	mov	r0, #9
	ldr	r1, .L17+12
	ldr	r2, .L17+16
	bl	__MapActor_SetSpeed
	mov	r3, r6
	add	r3, r3, #102
	ldrh	r5, .L17
	strh	r7, [r3]
	sub	r3, r3, #3
	strb	r5, [r3]
	mov	r1, r6
	add	r1, r1, #89
	ldrb	r2, [r1]
	mov	r3, #128
	orr	r3, r3, r2
	strb	r3, [r1]
	ldr	r3, .L17+20
	mov	r0, #8
	str	r3, [r6, #108]
	bl	__MapActor_GetActor
	mov	r3, r0
	add	r3, r3, #98
	strb	r5, [r3]
	ldr	r3, .L17+24
	str	r3, [r0, #108]
	ldr	r0, .L17+28
	bl	__GetFlag
	cmp	r0, #0
	beq	.L2
	mov	r3, #160
	ldr	r2, .L17+32
	lsl	r3, r3, #8
	b	.L18
.L19:
	.align	2, 0
.L17:
	.word	0
	.word	2344
	.word	2366
	.word	52428
	.word	26214
	.word	OvlFunc_945_200812c
	.word	OvlFunc_945_2008284
	.word	265
	.word	666
.L18:
	mov	r0, #0
	mov	r1, r8
	bl	OvlFunc_945_200c890
	b	.L2
.L6:
	ldr	r0, .L20
	bl	__GetFlag
	cmp	r0, #0
	beq	.L9
	mov	r1, #222
	mov	r3, #208
	lsl	r1, r1, #1
	ldr	r2, .L20+4
	mov	r0, #8
	lsl	r3, r3, #8
	b	.L14
.L9:
	ldr	r0, .L20+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L11
	mov	r1, #228
	mov	r2, #162
	lsl	r1, r1, #1
	lsl	r2, r2, #2
	mov	r0, #8
	mov	r3, #0
.L14:
	bl	OvlFunc_945_200c890
	mov	r0, #13
	mov	r1, #0
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	b	.L2
.L11:
	ldr	r0, .L20+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L2
	mov	r3, #128
	ldr	r1, .L20+16
	ldr	r2, .L20+20
	lsl	r3, r3, #8
	mov	r0, #8
	mov	r5, #176
	bl	OvlFunc_945_200c890
	lsl	r5, r5, #8
	mov	r1, #231
	lsl	r1, r1, #1
	ldr	r2, .L20+24
	mov	r3, r5
	mov	r0, #9
	bl	OvlFunc_945_200c890
	mov	r0, #12
	bl	__MapActor_GetActor
	mov	r3, #192
	lsl	r3, r3, #6
	strh	r3, [r0, #6]
	mov	r0, #11
	bl	__MapActor_GetActor
	mov	r1, #219
	mov	r3, #208
	strh	r5, [r0, #6]
	lsl	r1, r1, #1
	ldr	r2, .L20+28
	lsl	r3, r3, #8
	mov	r0, #13
	bl	OvlFunc_945_200c890
	mov	r1, #244
	mov	r2, #172
	lsl	r1, r1, #1
	lsl	r2, r2, #2
	mov	r0, #10
	mov	r3, r5
	bl	OvlFunc_945_200c890
.L2:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	2344
	.word	614
	.word	2341
	.word	2337
	.word	475
	.word	598
	.word	618
	.word	659
.Lfe1:
	.size	 OvlFunc_945_200b364,.Lfe1-OvlFunc_945_200b364

	.text
	.align	2, 0
