@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_945_2008284
	.thumb_func
	.type	 OvlFunc_945_2008284,function
OvlFunc_945_2008284:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r5, r0
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r3, r5
	add	r3, r3, #91
	ldrb	r6, [r3]
	cmp	r6, #0
	bne	.L2
	mov	r7, r0
	add	r7, r7, #99
	ldrb	r1, [r7]
	cmp	r1, #1
	bne	.L4
	mov	r2, #208
	lsl	r2, r2, #8
	strh	r2, [r5, #6]
	ldrh	r3, .L11
	mov	r2, r5
	add	r2, r2, #98
	strb	r1, [r2]
	b	.L10
.L4:
	cmp	r1, #2
	bne	.L6
	mov	r2, #98
	add	r2, r2, r5
	ldrb	r3, [r2]
	mov	r8, r2
	cmp	r3, #0
	beq	.L7
	mov	r0, r5
	mov	r1, #3
	bl	__Actor_SetAnim
.L7:
	mov	r3, r8
	strb	r6, [r3]
	strb	r6, [r7]
	b	.L2
.L12:
	.align	2, 0
.L11:
	.word	0
.L6:
	cmp	r1, #3
	bne	.L2
	ldrh	r3, .L13
	strh	r6, [r5, #6]
.L10:
	strb	r3, [r7]
.L2:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	0
.Lfe1:
	.size	 OvlFunc_945_2008284,.Lfe1-OvlFunc_945_2008284

	.text
	.align	2, 0
