@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_a_c_c_a_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_945_200c8e8
	.thumb_func
	.type	 OvlFunc_945_200c8e8,function
OvlFunc_945_200c8e8:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r7, r1
	mov	r6, r2
.L3:
	cmp	r0, #25
	bls	.LCB10
	b	.L4	@long jump
.LCB10:
	ldr	r2, .L72
	lsl	r3, r0, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L64:
	.word	.L5
	.word	.L6
	.word	.L7
	.word	.L10
	.word	.L11
	.word	.L17
	.word	.L18
	.word	.L19
	.word	.L21
	.word	.L23
	.word	.L25
	.word	.L27
	.word	.L30
	.word	.L33
	.word	.L34
	.word	.L35
	.word	.L38
	.word	.L39
	.word	.L45
	.word	.L46
	.word	.L47
	.word	.L53
	.word	.L54
	.word	.L55
	.word	.L56
	.word	.L58
.L5:
	mov	r0, #0
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #3
	lsl	r1, r1, #8
	b	.L66
.L6:
	mov	r0, #0
	mov	r1, r7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #1
	mov	r1, r7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #2
	mov	r1, r7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #3
	mov	r1, r7
.L66:
	mov	r2, r6
	bl	__Func_8092adc
	b	.L4
.L7:
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #3
	bl	__MapActor_SetAnim
	cmp	r7, #0
	beq	.L8
	mov	r0, #3
	bl	__Func_8092504
.L8:
	cmp	r6, #0
	bne	.LCB84
	b	.L4	@long jump
.LCB84:
	b	.L67
.L10:
	mov	r1, #129
	mov	r0, #0
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #129
	mov	r0, #1
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #129
	mov	r0, #2
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #129
	mov	r0, #3
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
.L67:
	mov	r0, r6
	bl	__CutsceneWait
	b	.L4
.L11:
	mov	r5, #0
	cmp	r5, r7
	bcc	.LCB115
	b	.L4	@long jump
.LCB115:
.L15:
	mov	r0, r5
	add	r0, r0, #10
	mov	r1, #0
	mov	r2, #0
	add	r5, r5, #1
	bl	__MapActor_SetPos
	cmp	r5, r7
	bcc	.L15
	b	.L4
.L17:
	mov	r0, r7
	bl	__MapActor_GetActor
	mov	r3, #160
	lsl	r3, r3, #7
	strh	r3, [r0, #6]
	mov	r1, #5
	b	.L68
.L18:
	mov	r0, r7
	bl	__MapActor_GetActor
	mov	r3, #160
	lsl	r3, r3, #7
	strh	r3, [r0, #6]
	ldr	r3, .L72+4
	mov	r1, #5
	str	r3, [r0, #24]
.L68:
	mov	r0, r7
	bl	__MapActor_SetAnim
	mov	r0, r7
	mov	r1, r6
	bl	__MapActor_SetAnimSpeed
	b	.L4
.L19:
	mov	r0, r7
	bl	__MapActor_GetActor
	mov	r3, #160
	lsl	r3, r3, #7
	strh	r3, [r0, #6]
	mov	r0, r7
	bl	OvlFunc_945_200c7cc
	cmp	r6, #0
	beq	.LCB183
	b	.L4	@long jump
.LCB183:
	mov	r0, r7
	mov	r1, #0
	bl	__MapActor_SetAnimSpeed
	b	.L4
.L21:
	ldr	r3, .L72+8
	mov	r2, #224
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	add	r2, r2, #66
	str	r2, [r3]
	bl	__MapTransitionIn
	cmp	r7, #0
	beq	.L22
	bl	__WaitMapTransition
.L22:
	mov	r0, #0
	bl	__CutsceneWait
	b	.L4
.L23:
	bl	__MapTransitionOut
	bl	__WaitMapTransition
	cmp	r7, #0
	bne	.LCB215
	b	.L4	@long jump
.LCB215:
	mov	r0, r7
	bl	__Func_8091e9c
	b	.L4
.L25:
	mov	r0, #24
	mov	r1, #1
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r1, #0
	mov	r2, #0
	mov	r0, #25
	bl	OvlFunc_945_200c8e8
	mov	r5, #128
	mov	r0, #0
	bl	OvlFunc_945_200b7d8
	lsl	r5, r5, #7
	mov	r1, #216
	lsl	r1, r1, #1
	mov	r0, #0
	mov	r2, #168
	mov	r3, r5
	bl	OvlFunc_945_200c890
	mov	r1, #224
	lsl	r1, r1, #1
	mov	r0, #1
	mov	r2, #168
	mov	r3, r5
	bl	OvlFunc_945_200c890
	mov	r1, #212
	lsl	r1, r1, #1
	mov	r0, #2
	mov	r2, #152
	mov	r3, r5
	bl	OvlFunc_945_200c890
	mov	r1, #229
	lsl	r1, r1, #1
	mov	r0, #3
	mov	r2, #152
	mov	r3, r5
	bl	OvlFunc_945_200c890
	b	.L4
.L27:
	cmp	r7, #0
	beq	.L28
	mov	r1, #1
	mov	r0, #13
	bl	__MapActor_SetAnim
	mov	r0, #13
	bl	__MapActor_GetActor
	mov	r3, #192
	lsl	r3, r3, #6
	strh	r3, [r0, #6]
	mov	r0, #13
	bl	__MapActor_GetActor
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r0, #24]
.L28:
	mov	r1, #1
	mov	r0, #14
	bl	__MapActor_SetAnim
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r3, #160
	lsl	r3, r3, #7
	mov	r8, r3
	mov	r2, r8
	strh	r2, [r0, #6]
	mov	r1, #1
	mov	r0, #15
	bl	__MapActor_SetAnim
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r3, #192
	lsl	r3, r3, #6
	mov	sl, r3
	mov	r2, sl
	strh	r2, [r0, #6]
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r5, #128
	lsl	r5, r5, #9
	mov	r1, #1
	str	r5, [r0, #24]
	mov	r0, #16
	bl	__MapActor_SetAnim
	mov	r0, #16
	bl	__MapActor_GetActor
	mov	r3, r8
	strh	r3, [r0, #6]
	mov	r1, #1
	mov	r0, #17
	bl	__MapActor_SetAnim
	mov	r0, #17
	bl	__MapActor_GetActor
	mov	r2, sl
	strh	r2, [r0, #6]
	mov	r0, #17
	bl	__MapActor_GetActor
	mov	r1, #205
	mov	r2, #174
	str	r5, [r0, #24]
	lsl	r1, r1, #17
	mov	r0, #28
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #235
	mov	r2, #174
	mov	r0, #29
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #205
	mov	r2, #206
	mov	r0, #30
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #235
	mov	r2, #206
	mov	r0, #31
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	mov	r1, #205
	mov	r2, #143
	mov	r0, #32
	lsl	r1, r1, #17
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
	mov	r1, #235
	mov	r2, #143
	mov	r0, #33
	lsl	r1, r1, #17
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
	mov	r1, #205
	mov	r2, #158
	mov	r0, #34
	lsl	r1, r1, #17
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
	mov	r1, #235
	mov	r2, #158
	mov	r0, #35
	lsl	r1, r1, #17
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
	mov	r0, #1
	bl	__WaitFrames
	cmp	r7, #0
	beq	.L29
	mov	r1, #176
	mov	r0, #13
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
.L29:
	mov	r1, #208
	mov	r0, #14
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #176
	mov	r0, #15
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #208
	mov	r0, #16
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #176
	lsl	r1, r1, #8
	mov	r0, #17
	bl	OvlFunc_945_200c880
	b	.L4
.L30:
	mov	r0, r7
	bl	__MapActor_GetActor
	mov	r1, #1
	mov	r5, r0
	mov	r0, r7
	bl	__MapActor_SetAnim
	cmp	r6, #0
	beq	.L31
	mov	r3, #192
	lsl	r3, r3, #6
	b	.L69
.L31:
	mov	r3, #160
	lsl	r3, r3, #7
.L69:
	strh	r3, [r5, #6]
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r5, #24]
	b	.L4
.L33:
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #12
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #11
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #13
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #10
	b	.L70
.L73:
	.align	2, 0
.L72:
	.word	.L64
	.word	-65536
	.word	iwram_3001ebc
.L34:
	mov	r0, #14
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #13
.L70:
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	b	.L4
.L35:
	mov	r0, #24
	mov	r1, #1
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #10
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r1, #222
	mov	r3, #208
	lsl	r1, r1, #1
	ldr	r2, .L74
	mov	r0, #8
	lsl	r3, r3, #8
	bl	OvlFunc_945_200c890
	mov	r0, #0
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	cmp	r7, #0
	beq	.L36
	bl	OvlFunc_945_200c5d0
.L36:
	mov	r0, #224
	mov	r1, #128
	mov	r2, #156
	lsl	r0, r0, #17
	lsl	r1, r1, #14
	lsl	r2, r2, #18
	ldr	r3, .L74+4
	bl	OvlFunc_945_200c8ac
	cmp	r6, #0
	bne	.LCB553
	b	.L4	@long jump
.LCB553:
	ldr	r3, .L74+8
	mov	r2, #224
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	add	r2, r2, #66
	str	r2, [r3]
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	mov	r0, #20
	bl	__CutsceneWait
	b	.L4
.L38:
	mov	r0, #8
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #9
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r1, #219
	mov	r2, #152
	mov	r0, #27
	lsl	r1, r1, #17
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	b	.L4
.L39:
	mov	r5, #0
.L43:
	mov	r0, r5
	add	r0, r0, #28
	mov	r1, #0
	mov	r2, #0
	add	r5, r5, #1
	bl	__MapActor_SetPos
	cmp	r5, #7
	bls	.L43
	b	.L4
.L45:
	mov	r2, #133
	mov	r3, #176
	lsl	r2, r2, #2
	lsl	r3, r3, #8
	mov	r0, #12
	mov	r1, #152
	mov	r5, #245
	bl	OvlFunc_945_200c890
	lsl	r5, r5, #1
	mov	r3, #192
	lsl	r3, r3, #6
	mov	r2, r5
	mov	r0, #8
	mov	r1, #134
	mov	r8, r3
	bl	OvlFunc_945_200c890
	mov	r3, #160
	mov	r2, r5
	mov	r0, #9
	mov	r1, #166
	lsl	r3, r3, #7
	bl	OvlFunc_945_200c890
	add	r5, r5, #14
	mov	r3, #160
	mov	r0, #10
	mov	r1, #182
	mov	r2, r5
	lsl	r3, r3, #7
	bl	OvlFunc_945_200c890
	mov	r0, #11
	mov	r1, #118
	mov	r2, r5
	mov	r3, r8
	bl	OvlFunc_945_200c890
	mov	r7, #0
	mov	r0, #14
	mov	r6, #0
	b	.L3
.L46:
	mov	r1, #208
	mov	r2, #164
	lsl	r1, r1, #1
	lsl	r2, r2, #1
	mov	r0, #8
	mov	r3, #0
	bl	OvlFunc_945_200c890
	mov	r2, #224
	lsl	r2, r2, #1
	mov	sl, r2
	mov	r3, #208
	lsl	r3, r3, #8
	sub	r2, r2, #96
	mov	r0, #9
	mov	r1, sl
	mov	r9, r3
	bl	OvlFunc_945_200c890
	mov	r2, #192
	lsl	r2, r2, #6
	mov	r8, r2
	mov	r1, #227
	lsl	r1, r1, #1
	mov	r0, #10
	mov	r2, #248
	mov	r3, r8
	mov	r5, #204
	bl	OvlFunc_945_200c890
	lsl	r5, r5, #1
	mov	r2, #145
	mov	r1, r5
	lsl	r2, r2, #1
	mov	r0, r7
	mov	r3, #0
	bl	OvlFunc_945_200c890
	mov	r2, #171
	mov	r1, r5
	lsl	r2, r2, #1
	mov	r0, r6
	mov	r3, #0
	bl	OvlFunc_945_200c890
	mov	r1, #210
	mov	r2, #178
	lsl	r1, r1, #1
	lsl	r2, r2, #1
	mov	r0, #13
	mov	r3, r9
	bl	OvlFunc_945_200c890
	mov	r2, #152
	mov	r1, r5
	lsl	r2, r2, #1
	mov	r0, #14
	mov	r3, #0
	bl	OvlFunc_945_200c890
	sub	r5, r5, #30
	mov	r1, #209
	lsl	r1, r1, #1
	mov	r0, #15
	mov	r2, r5
	mov	r3, r9
	bl	OvlFunc_945_200c890
	mov	r1, #220
	mov	r2, #131
	lsl	r1, r1, #1
	lsl	r2, r2, #1
	mov	r0, #16
	mov	r3, r8
	bl	OvlFunc_945_200c890
	mov	r0, #17
	mov	r1, sl
	mov	r2, r5
	mov	r3, r9
	bl	OvlFunc_945_200c890
	b	.L4
.L47:
	mov	r5, r7
	cmp	r7, r6
	bhi	.L4
.L51:
	mov	r0, r5
	add	r5, r5, #1
	bl	__ClearFlag
	cmp	r5, r6
	bls	.L51
	b	.L4
.L53:
	ldr	r1, .L74+12
	ldr	r2, .L74+16
	mov	r0, #20
	bl	OvlFunc_945_200c8e8
	ldr	r1, .L74+20
	ldr	r2, .L74+24
	mov	r0, #20
	bl	OvlFunc_945_200c8e8
	mov	r1, #153
	lsl	r1, r1, #4
	ldr	r2, .L74+28
	mov	r0, #20
	bl	OvlFunc_945_200c8e8
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L74+32
	bl	__ClearFlag
	ldr	r0, .L74+36
	bl	__ClearFlag
	b	.L4
.L54:
	mov	r0, #1
	bl	__WaitFrames
	mov	r0, #23
	mov	r1, #0
	mov	r2, #0
	bl	OvlFunc_945_200c8e8
	ldr	r1, .L74+40
	mov	r0, #12
	bl	__MapActor_SetBehavior
	b	.L4
.L55:
	mov	r0, #1
	bl	__DeleteFieldActor
	mov	r0, #2
	bl	__DeleteFieldActor
	mov	r0, #3
	bl	__DeleteFieldActor
	b	.L4
.L56:
	mov	r0, #1
	mov	r1, #1
	mov	r2, #1
	neg	r0, r0
	neg	r1, r1
	neg	r2, r2
	mov	r3, #0
	bl	__Func_80933f8
	mov	r0, #1
	bl	__WaitFrames
	cmp	r7, #0
	beq	.L4
	bl	__Func_8093554
	mov	r3, #0
	add	r0, r0, #85
	strb	r3, [r0]
	b	.L4
.L58:
	ldr	r0, .L74+44
	bl	__LoadFieldActors
	mov	r0, #1
	bl	__WaitFrames
	cmp	r7, #1
	bne	.L59
	ldr	r0, .L74+48
	b	.L71
.L59:
	cmp	r7, #2
	bne	.L61
	ldr	r0, .L74+52
.L71:
	bl	__LoadFieldActors
	mov	r0, #1
	bl	__WaitFrames
	b	.L4
.L61:
	cmp	r7, #3
	bne	.L4
	ldr	r0, .L74+56
	bl	__LoadFieldActors
	mov	r0, #1
	bl	__WaitFrames
.L4:
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L75:
	.align	2, 0
.L74:
	.word	614
	.word	16777217
	.word	iwram_3001ebc
	.word	2348
	.word	2365
	.word	2327
	.word	2335
	.word	2456
	.word	769
	.word	770
	.word	gScript_945__0200e840
	.word	.L72a0
	.word	.L7300
	.word	.L7360
	.word	.L73c0
.Lfe1:
	.size	 OvlFunc_945_200c8e8,.Lfe1-OvlFunc_945_200c8e8

	.text
	.align	2, 0
