@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_a_a_a_a_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_945_2009978
	.thumb_func
	.type	 OvlFunc_945_2009978,function
OvlFunc_945_2009978:
	push	{lr}
	bl	__CutsceneStart
	bl	__Func_808e118
	ldr	r3, .L8
	ldr	r2, .L8+4
	add	r3, r3, r2
	mov	r2, #3
	strb	r2, [r3]
	mov	r0, #143
	lsl	r0, r0, #4
	bl	__ClearFlag
	ldr	r0, .L8+8
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r0, .L8+12
	mov	r1, #16
	bl	__Func_8091f90
	mov	r0, #62
	mov	r1, #0
	bl	__Func_8091eb0
	b	.L4
.L3:
	ldr	r0, .L8+16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	ldr	r0, .L8+12
	mov	r1, #18
	bl	__Func_8091f90
	mov	r0, #62
	mov	r1, #1
	bl	__Func_8091eb0
	b	.L4
.L5:
	ldr	r0, .L8+20
	bl	__GetFlag
	cmp	r0, #0
	bne	.L4
	ldr	r0, .L8+12
	mov	r1, #20
	bl	__Func_8091f90
	mov	r0, #62
	mov	r1, #2
	bl	__Func_8091eb0
.L4:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	gState
	.word	555
	.word	2344
	.word	_AREA_6f
	.word	2345
	.word	2346
.Lfe1:
	.size	 OvlFunc_945_2009978,.Lfe1-OvlFunc_945_2009978

	.text
	.align	2, 0
