@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_a_a_a_a_a_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_945_2009b34
	.thumb_func
	.type	 OvlFunc_945_2009b34,function
OvlFunc_945_2009b34:
	push	{r5, r6, lr}
	mov	r6, fp
	mov	r5, sl
	push	{r5, r6}
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6}
	ldr	r0, .L4
	bl	__GetFlag
	cmp	r0, #0
	bne	.LCB10
	b	.L3	@long jump
.LCB10:
	bl	__CutsceneStart
	bl	__Func_808e118
	ldr	r0, .L4+4
	ldr	r1, .L4+8
	bl	__Func_80933d4
	mov	r1, #1
	mov	r2, #232
	lsl	r2, r2, #17
	ldr	r3, .L4+12
	ldr	r0, .L4+16
	neg	r1, r1
	bl	OvlFunc_945_200c8ac
	mov	r1, #1
	mov	r0, #13
	bl	__Func_80925cc
	ldr	r0, .L4+20
	bl	__MessageID
	ldr	r3, .L4+24
	mov	r8, r3
	mov	r0, r8
	bl	OvlFunc_945_200c86c
	mov	r3, #208
	lsl	r3, r3, #8
	mov	sl, r3
	mov	r0, #12
	mov	r1, sl
	bl	OvlFunc_945_200c880
	mov	r1, #129
	ldr	r6, .L4+28
	mov	r2, #20
	mov	r0, #12
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #2
	mov	r0, #12
	bl	__Func_809259c
	mov	r0, r6
	bl	OvlFunc_945_200c86c
	mov	r0, #14
	mov	r1, #1
	bl	__Func_80925cc
	mov	r2, #20
	ldr	r0, .L4+32
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #12
	mov	r1, #0
	bl	OvlFunc_945_200c880
	mov	r0, #12
	ldr	r1, .L4+36
	mov	r2, #40
	ldr	r5, .L4+32
	bl	__MapActor_Emote
	mov	r2, #40
	mov	r0, #14
	ldr	r1, .L4+40
	bl	__MapActor_Emote
	mov	r1, #3
	mov	r0, #14
	bl	__Func_809259c
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #12
	bl	__MapActor_Surprise
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #12
	bl	__Func_809259c
	mov	r0, r6
	bl	OvlFunc_945_200c86c
	mov	r1, #1
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r3, #176
	lsl	r3, r3, #8
	mov	r9, r3
	mov	r1, r9
	mov	r0, #14
	bl	OvlFunc_945_200c880
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r0, #12
	mov	r1, sl
	bl	OvlFunc_945_200c880
	mov	r1, #128
	mov	r2, #30
	mov	r0, #12
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #1
	mov	r0, #12
	bl	__Func_809259c
	mov	r0, r6
	bl	OvlFunc_945_200c86c
	mov	r1, #4
	mov	r0, #13
	bl	__MapActor_DoAnim
	mov	r0, r8
	bl	OvlFunc_945_200c86c
	mov	r1, #2
	mov	r0, #13
	bl	__Func_809259c
	mov	r0, r8
	bl	OvlFunc_945_200c86c
	mov	r1, #4
	mov	r0, #12
	bl	__MapActor_SetAnim
	mov	r0, r6
	bl	OvlFunc_945_200c86c
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r3, #128
	lsl	r3, r3, #8
	mov	fp, r3
	mov	r0, #14
	mov	r1, fp
	bl	OvlFunc_945_200c880
	mov	r0, #14
	mov	r1, #2
	bl	__Func_809259c
	mov	r0, r5
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r0, #12
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #129
	mov	r0, #12
	lsl	r1, r1, #1
	mov	r2, #80
	bl	__MapActor_Emote
	mov	r0, r6
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r0, #14
	ldr	r1, .L4+40
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r2, #60
	mov	r0, #13
	ldr	r1, .L4+40
	bl	__MapActor_Emote
	mov	r1, #2
	mov	r0, #14
	bl	__Func_809259c
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r0, #14
	mov	r1, r9
	bl	OvlFunc_945_200c880
	mov	r1, #1
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r3, #192
	lsl	r3, r3, #6
	mov	r8, r3
	mov	r0, #13
	mov	r1, r8
	bl	OvlFunc_945_200c880
	mov	r0, #13
	ldr	r1, .L4+36
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r2, #60
	mov	r0, #12
	ldr	r1, .L4+36
	bl	__MapActor_Emote
	mov	r1, #1
	mov	r0, #13
	bl	__Func_80925cc
	mov	r0, #13
	bl	OvlFunc_945_200c86c
	mov	r2, #40
	mov	r0, #14
	ldr	r1, .L4+40
	bl	__MapActor_Emote
	mov	r1, #1
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r0, #12
	mov	r1, sl
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #160
	mov	r0, #13
	lsl	r1, r1, #7
	mov	r2, #40
	bl	__Func_8092adc
	mov	r2, #0
	mov	r0, #12
	mov	r1, #0
	bl	__Func_8092adc
	mov	r0, #13
	mov	r1, r8
	bl	OvlFunc_945_200c880
	mov	r0, #12
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, r6
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r1, #128
	mov	r2, #40
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r0, #12
	mov	r1, #2
	bl	__Func_809259c
	mov	r1, #2
	mov	r0, #13
	bl	__Func_80925cc
	mov	r0, #60
	bl	__CutsceneWait
	mov	r1, #1
	mov	r0, #13
	bl	__Func_80925cc
	mov	r0, #13
	bl	OvlFunc_945_200c86c
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, r5
	bl	OvlFunc_945_200c86c
	mov	r1, #129
	mov	r2, #40
	mov	r0, #12
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #2
	mov	r0, #12
	bl	__Func_80925cc
	mov	r0, r6
	bl	OvlFunc_945_200c86c
	mov	r1, #3
	mov	r0, #13
	bl	__MapActor_DoAnim
	mov	r0, #13
	bl	OvlFunc_945_200c86c
	mov	r2, #40
	mov	r0, #14
	mov	r1, r9
	bl	__Func_8092adc
	mov	r0, #14
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #13
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #14
	ldr	r1, .L4+44
	ldr	r2, .L4+48
	bl	__MapActor_SetSpeed
	ldr	r2, .L4+48
	mov	r0, #13
	ldr	r1, .L4+44
	bl	__MapActor_SetSpeed
	ldr	r5, .L4+52
	mov	r0, #14
	mov	r1, r5
	bl	__MapActor_SetBehavior
	mov	r1, r5
	mov	r0, #13
	bl	__MapActor_SetBehavior
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #12
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	ldr	r1, .L4+4
	ldr	r2, .L4+56
	mov	r0, #0
	bl	__MapActor_SetSpeed
	mov	r0, #0
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r3, #254
	and	r3, r3, r2
	mov	r2, #130
	strb	r3, [r0]
	mov	r1, #184
	lsl	r2, r2, #2
	mov	r0, #0
	bl	__Func_80921c4
	mov	r0, #1
	bl	__CutsceneWait
	mov	r0, #0
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r3, #1
	orr	r3, r3, r2
	strb	r3, [r0]
	mov	r1, fp
	mov	r0, #0
	mov	r2, #20
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #12
	mov	r1, #4
	mov	r2, #20
	bl	__MapActor_Jump
	mov	r1, #160
	mov	r2, #20
	mov	r0, #0
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r1, #2
	mov	r0, #12
	bl	__Func_809259c
	mov	r0, #12
	bl	OvlFunc_945_200c86c
	ldr	r2, .L4+48
	mov	r0, #12
	ldr	r1, .L4+44
	bl	__MapActor_SetSpeed
	mov	r1, r5
	mov	r0, #12
	bl	__MapActor_SetBehavior
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #0
	bl	__Func_8092adc
	mov	r0, #12
	bl	__MapActor_WaitScript
	ldr	r0, .L4+60
	bl	__SetFlag
	bl	__CutsceneEnd
.L3:
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r3}
	mov	fp, r3
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	2321
	.word	157286
	.word	19660
	.word	268435476
	.word	95879168
	.word	7510
	.word	8205
	.word	32780
	.word	40974
	.word	257
	.word	259
	.word	104857
	.word	52428
	.word	gScript_945__0200e6a8
	.word	78643
	.word	2338
.Lfe1:
	.size	 OvlFunc_945_2009b34,.Lfe1-OvlFunc_945_2009b34

	.text
	.align	2, 0
