@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_1440_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_2009440
	.thumb_func
	.type	 OvlFunc_947_2009440,function
OvlFunc_947_2009440:
	push	{lr}
	ldr	r3, .L8
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L8+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L8+8
	b	.L2
.L3:
	ldr	r3, .L8+12
	cmp	r2, r3
	bne	.L4
	ldr	r0, .L8+16
	b	.L2
.L4:
	ldr	r3, .L8+20
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L8+24
	b	.L2
.L5:
	ldr	r3, .L8+28
	cmp	r2, r3
	bne	.L6
	ldr	r0, .L8+32
	b	.L2
.L6:
	ldr	r3, .L8+36
	cmp	r2, r3
	bne	.L7
	ldr	r0, .L8+40
	b	.L2
.L7:
	ldr	r0, .L8+44
.L2:
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	gState
	.word	_AREA_73
	.word	.L2eac
	.word	_AREA_74
	.word	.L2ef4
	.word	_AREA_77
	.word	.L2f3c
	.word	_AREA_79
	.word	.L2f84
	.word	_AREA_7a
	.word	.L2fcc
	.word	.L2e7c
.Lfe1:
	.size	 OvlFunc_947_2009440,.Lfe1-OvlFunc_947_2009440

	.text
	.align	2, 0
