@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_1528_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_200a15c
	.thumb_func
	.type	 OvlFunc_947_200a15c,function
OvlFunc_947_200a15c:
	push	{r5, r6, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #13
	bl	__MapActor_GetActor
	ldr	r3, .L5
	ldr	r2, [r0, #8]
	ldr	r6, [r3]
	ldr	r3, [r5, #8]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L3
	ldr	r2, [r0, #16]
	ldr	r3, [r5, #16]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L5+4
	bl	__SetFlag
	mov	r2, r6
	add	r2, r2, #53
	mov	r3, #1
	strb	r3, [r2]
	b	.L4
.L3:
	ldr	r0, .L5+4
	bl	__ClearFlag
.L4:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001f30
	.word	515
.Lfe1:
	.size	 OvlFunc_947_200a15c,.Lfe1-OvlFunc_947_200a15c

	.text
	.align	2, 0
