@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_1528_a_a_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_20095fc
	.thumb_func
	.type	 OvlFunc_947_20095fc,function
OvlFunc_947_20095fc:
	push	{r5, r6, lr}
	mov	r0, #128
	lsl	r0, r0, #2
	sub	sp, sp, #12
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	str	r0, [sp]
	mov	r6, #10
	mov	r5, #31
	mov	r0, #10
	mov	r1, #19
	mov	r2, #16
	mov	r3, #5
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	bl	OvlFunc_947_2008cc0
	mov	r3, #1
	str	r3, [sp]
	mov	r0, #10
	mov	r1, #51
	mov	r2, #16
	mov	r3, #5
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	bl	OvlFunc_947_2008cc0
	mov	r3, #2
	str	r3, [sp]
	mov	r0, #42
	mov	r1, #51
	mov	r2, #16
	mov	r3, #5
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	bl	OvlFunc_947_2008cc0
	b	.L4
.L3:
	mov	r3, #0
	str	r3, [sp]
	mov	r6, #10
	mov	r5, #31
	mov	r0, #10
	mov	r1, #19
	mov	r2, #16
	mov	r3, #5
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	bl	OvlFunc_947_2008cc0
	mov	r3, #1
	str	r3, [sp]
	mov	r0, #10
	mov	r1, #83
	mov	r2, #16
	mov	r3, #5
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	bl	OvlFunc_947_2008cc0
	mov	r3, #2
	str	r3, [sp]
	mov	r0, #42
	mov	r1, #83
	mov	r2, #16
	mov	r3, #5
	str	r6, [sp, #4]
	str	r5, [sp, #8]
	bl	OvlFunc_947_2008cc0
.L4:
	ldr	r5, .L11
	mov	r6, #0
	mov	r1, #200
	lsl	r1, r1, #4
	str	r6, [r5]
	ldr	r0, .L11+4
	bl	__StartTask
	mov	r0, #1
	bl	__WaitFrames
	ldr	r2, .L11+8
	mov	r0, #1
	mov	r1, #0
	bl	__SetIntrHandler
	mov	r0, #231
	bl	__PlaySound
	str	r6, [r5]
.L8:
	mov	r0, #1
	bl	__WaitFrames
	ldr	r3, [r5]
	add	r3, r3, #1
	str	r3, [r5]
	cmp	r3, #100
	ble	.L8
	ldr	r0, .L11+12
	bl	__PlaySound
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	bne	.L9
	mov	r5, #32
	mov	r0, #0
	mov	r1, #32
	mov	r2, #32
	mov	r3, #0
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #32
	mov	r1, #32
	mov	r2, #64
	mov	r3, #0
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	b	.L10
.L9:
	mov	r5, #32
	mov	r0, #0
	mov	r1, #64
	mov	r2, #32
	mov	r3, #0
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #32
	mov	r1, #64
	mov	r2, #64
	mov	r3, #0
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
.L10:
	mov	r0, #1
	bl	__WaitFrames
	mov	r1, #0
	mov	r2, #0
	mov	r0, #1
	bl	__SetIntrHandler
	mov	r0, #1
	bl	__WaitFrames
	ldr	r0, .L11+4
	bl	__StopTask
	bl	__Func_800fe9c
	mov	r0, #30
	bl	__WaitFrames
	add	sp, sp, #12
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	.L3738
	.word	OvlFunc_947_20095cc
	.word	OvlFunc_947_2009578
	.word	289
.Lfe1:
	.size	 OvlFunc_947_20095fc,.Lfe1-OvlFunc_947_20095fc

	.text
	.align	2, 0
