@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_2009428
	.thumb_func
	.type	 OvlFunc_947_2009428,function
OvlFunc_947_2009428:
	push	{lr}
	mov	r3, r0
	add	r3, r3, #100
	ldrh	r3, [r3]
	mov	r1, #15
	and	r1, r1, r3
	bl	__Func_80929d8
	mov	r0, #0
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_947_2009428,.Lfe1-OvlFunc_947_2009428

	.text
	.align	2, 0
