@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_1528_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_947_20095cc
	.thumb_func
	.type	 OvlFunc_947_20095cc,function
OvlFunc_947_20095cc:
	ldr	r3, .L3
	ldr	r2, .L3+4
	ldmia	r3!, {r1}
	stmia	r2!, {r1}
	ldmia	r3!, {r1}
	stmia	r2!, {r1}
	ldr	r3, [r3]
	str	r3, [r2]
	ldr	r2, .L3+4
	ldrh	r3, [r2, #2]
	add	r3, r3, #192
	strh	r3, [r2, #2]
	ldrh	r3, [r2, #6]
	add	r3, r3, #192
	strh	r3, [r2, #6]
	ldrh	r3, [r2, #10]
	add	r3, r3, #192
	strh	r3, [r2, #10]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001ad4
	.word	.L372c
.Lfe1:
	.size	 OvlFunc_947_20095cc,.Lfe1-OvlFunc_947_20095cc

	.text
	.align	2, 0
