@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_a_c_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_921_2008384
	.thumb_func
	.type	 OvlFunc_921_2008384,function
OvlFunc_921_2008384:
	push	{lr}
	ldr	r0, .L5
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	bl	__CutsceneStart
	mov	r1, #0
	mov	r2, #0
	mov	r0, #9
	bl	__Func_809280c
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r0, .L5+4
	bl	__MessageID
	mov	r1, #0
	mov	r0, #9
	bl	__Func_8093054
	bl	__CutsceneEnd
	b	.L2
.L3:
	ldr	r0, .L5+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	bl	__CutsceneStart
	mov	r0, #9
	mov	r1, #7
	bl	__MapActor_SetAnim
	mov	r2, #69
	mov	r1, #10
	ldr	r0, .L5+12
	bl	__Func_8010560
	ldr	r0, .L5+16
	bl	__MessageID
	mov	r0, #9
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #9
	mov	r1, #8
	bl	__MapActor_SetAnim
	ldr	r0, .L5+20
	mov	r1, #10
	mov	r2, #69
	bl	__Func_8010560
	bl	__CutsceneEnd
	b	.L2
.L4:
	bl	__CutsceneStart
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r3, #10
	add	r0, r0, #100
	strh	r3, [r0]
	ldr	r1, .L5+24
	mov	r0, #9
	bl	__MapActor_SetBehavior
	ldr	r0, .L5+28
	bl	__MessageID
	mov	r1, #0
	mov	r0, #9
	bl	__ActorMessage
	mov	r0, #8
	bl	__MapActor_SetIdle
	mov	r1, #128
	mov	r0, #8
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #208
	mov	r2, #10
	mov	r0, #8
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, #2
	bl	__Func_809259c
	mov	r2, #20
	mov	r0, #8
	mov	r1, #0
	bl	__Func_8093040
	ldr	r1, .L5+32
	mov	r0, #0
	bl	__MapActor_SetBehavior
	ldr	r2, .L5+36
	mov	r0, #8
	ldr	r1, .L5+40
	bl	__MapActor_SetSpeed
	ldr	r1, .L5+44
	mov	r0, #8
	bl	__MapActor_RunScript
	mov	r0, #40
	bl	__CutsceneWait
	mov	r2, #0
	mov	r0, #8
	mov	r1, #2
	bl	__MapActor_Jump
	mov	r0, #8
	mov	r1, #2
	bl	__Func_809259c
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #8
	bl	__MapActor_Surprise
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, #8
	mov	r1, #0
	mov	r2, #10
	bl	__Func_8093040
	mov	r1, #192
	mov	r2, #20
	mov	r0, #8
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r0, #8
	mov	r1, #2
	bl	__Func_809259c
	mov	r1, #0
	mov	r0, #8
	bl	__ActorMessage
	mov	r0, #8
	bl	__MapActor_GetActor
	add	r0, r0, #89
	ldrb	r3, [r0]
	mov	r2, #2
	eor	r3, r3, r2
	strb	r3, [r0]
	ldr	r0, .L5+48
	bl	__SetFlag
	bl	__CutsceneEnd
.L2:
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	2177
	.word	5700
	.word	2091
	.word	.L31c0
	.word	5484
	.word	.L31d6
	.word	gScript_921__0200a4f4
	.word	5428
	.word	gScript_921__0200a564
	.word	52428
	.word	104857
	.word	.L2508
	.word	2092
.Lfe1:
	.size	 OvlFunc_921_2008384,.Lfe1-OvlFunc_921_2008384

	.text
	.align	2, 0
