@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_a_a_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_921_2008974
	.thumb_func
	.type	 OvlFunc_921_2008974,function
OvlFunc_921_2008974:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r2, #6
	ldrsh	r5, [r0, r2]
	ldr	r0, .L9
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr	r2, .L9+4
	lsl	r3, r5, #16
	add	r3, r3, r2
	ldr	r2, .L9+8
	cmp	r3, r2
	bhi	.L4
	mov	r0, #12
	mov	r1, #15
	bl	__Func_80b0278
	b	.L6
.L4:
	bl	__CutsceneStart
	mov	r2, #0
	mov	r1, #0
	mov	r0, #15
	bl	__Func_809280c
	ldr	r0, .L9+12
	bl	__MessageID
	mov	r0, #15
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r0, #15
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	bl	__CutsceneEnd
	b	.L6
.L3:
	ldr	r2, .L9+4
	lsl	r3, r5, #16
	add	r3, r3, r2
	ldr	r2, .L9+8
	cmp	r3, r2
	bhi	.L7
	bl	__CutsceneStart
	ldr	r0, .L9+16
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #14
	mov	r0, #12
	bl	__Func_80b0278
	bl	__CutsceneEnd
	b	.L6
.L7:
	mov	r2, #10
	mov	r1, #0
	mov	r0, #14
	bl	__Func_809280c
	ldr	r0, .L9+20
	bl	__MessageID
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #160
	mov	r0, #14
	lsl	r1, r1, #7
	mov	r2, #10
	bl	__Func_8092adc
.L6:
	pop	{r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	2177
	.word	1610547200
	.word	1073610752
	.word	5711
	.word	5446
	.word	5447
.Lfe1:
	.size	 OvlFunc_921_2008974,.Lfe1-OvlFunc_921_2008974

	.text
	.align	2, 0
