@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_921_2009794
	.thumb_func
	.type	 OvlFunc_921_2009794,function
OvlFunc_921_2009794:
	push	{r5, r6, lr}
	ldr	r6, .L17
	mov	r1, #60
	ldr	r0, [r6]
	bl	__umodsi3
	cmp	r0, #0
	bne	.L3
	mov	r3, #146
	mov	r0, #222
	ldr	r1, .L17+4
	mov	r2, #0
	lsl	r3, r3, #17
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L3
	bl	OvlFunc_921_2009704
	mov	r3, #60
	str	r3, [r5, #104]
	ldr	r3, .L17+8
	mov	r0, r5
	str	r3, [r5, #108]
	mov	r1, #5
	bl	__Actor_SetAnim
.L3:
	ldr	r0, [r6]
	mov	r1, #60
	add	r0, r0, #30
	bl	__umodsi3
	cmp	r0, #0
	bne	.L5
	mov	r1, #160
	mov	r2, #128
	mov	r3, #178
	mov	r0, #222
	lsl	r1, r1, #17
	lsl	r2, r2, #14
	lsl	r3, r3, #17
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L5
	bl	OvlFunc_921_2009704
	mov	r3, #60
	str	r3, [r5, #104]
	ldr	r3, .L17+8
	mov	r0, r5
	str	r3, [r5, #108]
	mov	r1, #5
	bl	__Actor_SetAnim
.L5:
	ldr	r0, [r6]
	mov	r1, #60
	add	r0, r0, #10
	bl	__umodsi3
	cmp	r0, #0
	bne	.L7
	mov	r1, #236
	mov	r3, #140
	mov	r0, #222
	lsl	r1, r1, #15
	mov	r2, #0
	lsl	r3, r3, #15
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L7
	bl	OvlFunc_921_2009704
	mov	r3, #60
	str	r3, [r5, #104]
	ldr	r3, .L17+8
	mov	r0, r5
	str	r3, [r5, #108]
	mov	r1, #5
	bl	__Actor_SetAnim
.L7:
	ldr	r0, [r6]
	mov	r1, #60
	add	r0, r0, #50
	bl	__umodsi3
	cmp	r0, #0
	bne	.L9
	mov	r1, #171
	mov	r3, #248
	mov	r0, #222
	lsl	r1, r1, #17
	mov	r2, #0
	lsl	r3, r3, #15
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L9
	bl	OvlFunc_921_2009704
	mov	r3, #60
	str	r3, [r5, #104]
	ldr	r3, .L17+8
	mov	r0, r5
	str	r3, [r5, #108]
	mov	r1, #5
	bl	__Actor_SetAnim
.L9:
	ldr	r0, [r6]
	mov	r1, #60
	add	r0, r0, #80
	bl	__umodsi3
	cmp	r0, #0
	bne	.L11
	mov	r3, #171
	mov	r0, #222
	ldr	r1, .L17+12
	mov	r2, #0
	lsl	r3, r3, #16
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L11
	bl	OvlFunc_921_2009704
	mov	r3, #60
	str	r3, [r5, #104]
	ldr	r3, .L17+8
	mov	r0, r5
	str	r3, [r5, #108]
	mov	r1, #5
	bl	__Actor_SetAnim
.L11:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	iwram_3001e40
	.word	30343168
	.word	OvlFunc_921_200974c
	.word	28246016
.Lfe1:
	.size	 OvlFunc_921_2009794,.Lfe1-OvlFunc_921_2009794

	.text
	.align	2, 0
