@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_921_2009960
	.thumb_func
	.type	 OvlFunc_921_2009960,function
OvlFunc_921_2009960:
	push	{lr}
	ldr	r0, .L3
	sub	sp, sp, #8
	bl	__SetFlag
	mov	r0, #11
	mov	r1, #3
	bl	__Func_8092b08
	mov	r3, #15
	mov	r2, #7
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #15
	mov	r1, #6
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	515
.Lfe1:
	.size	 OvlFunc_921_2009960,.Lfe1-OvlFunc_921_2009960

	.text
	.align	2, 0
