@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_20093a4
	.thumb_func
	.type	 OvlFunc_964_20093a4,function
OvlFunc_964_20093a4:
	push	{lr}
	mov	r0, #0
	mov	r1, #6
	mov	r2, #0
	bl	__Func_8092708
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_964_20093a4,.Lfe1-OvlFunc_964_20093a4

	.text
	.align	2, 0
