@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_a_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_20098f8
	.thumb_func
	.type	 OvlFunc_964_20098f8,function
OvlFunc_964_20098f8:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_964_20080c4
	bl	__CutsceneEnd
	bl	OvlFunc_964_2009744
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_964_20098f8,.Lfe1-OvlFunc_964_20098f8

	.text
	.align	2, 0
