@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_2009270
	.thumb_func
	.type	 OvlFunc_964_2009270,function
OvlFunc_964_2009270:
	push	{lr}
	ldr	r3, .L5
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L5+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L5+8
	b	.L2
.L3:
	ldr	r3, .L5+12
	cmp	r2, r3
	bne	.L4
	ldr	r0, .L5+16
	b	.L2
.L4:
	ldr	r0, .L5+20
.L2:
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	gState
	.word	_AREA_ac
	.word	.L3474
	.word	_AREA_ad
	.word	.L3654
	.word	.L342c
.Lfe1:
	.size	 OvlFunc_964_2009270,.Lfe1-OvlFunc_964_2009270

	.text
	.align	2, 0
