@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_20099bc
	.thumb_func
	.type	 OvlFunc_964_20099bc,function
OvlFunc_964_20099bc:
	push	{lr}
	bl	__CutsceneStart
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_964_20099bc,.Lfe1-OvlFunc_964_20099bc

	.text
	.align	2, 0
