@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_a_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_964_2008fe8
	.thumb_func
	.type	 OvlFunc_964_2008fe8,function
OvlFunc_964_2008fe8:
	push	{r5, lr}
	mov	r5, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L6
	ldr	r3, [r0, #12]
	cmp	r3, r2
	ble	.L3
	mov	r0, #8
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	asr	r3, r3, #20
	cmp	r3, #10
	bne	.L3
	mov	r0, #8
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	str	r3, [r5, #8]
	ldr	r3, .L6+4
	mov	r0, #8
	str	r3, [r5, #12]
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	b	.L5
.L3:
	mov	r3, #0
	str	r3, [r5, #8]
	str	r3, [r5, #12]
.L5:
	str	r3, [r5, #16]
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	-3145728
	.word	-2097152
.Lfe1:
	.size	 OvlFunc_964_2008fe8,.Lfe1-OvlFunc_964_2008fe8

	.text
	.align	2, 0
