@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_955_2008258
	.thumb_func
	.type	 OvlFunc_955_2008258,function
OvlFunc_955_2008258:
	push	{lr}
	ldr	r0, .L3
	sub	sp, sp, #8
	bl	__SetFlag
	mov	r0, #20
	bl	__MapActor_GetActor
	mov	r3, #0
	add	r0, r0, #85
	strb	r3, [r0]
	mov	r2, #17
	mov	r3, #44
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #46
	mov	r1, #17
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	817
.Lfe1:
	.size	 OvlFunc_955_2008258,.Lfe1-OvlFunc_955_2008258

	.text
	.align	2, 0
