@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_22c4_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_924_200a844
	.thumb_func
	.type	 OvlFunc_924_200a844,function
OvlFunc_924_200a844:
	push	{r5, r6, lr}
	ldrh	r6, .L16
.L15:
	ldr	r0, .L16+4
	mov	r5, #0
	mov	r4, #0
	b	.L17
.L18:
	.align	2, 0
.L16:
	.word	31
	.word	83886160
.L17:
.L14:
	ldrh	r3, [r0]
	mov	r1, #31
	and	r1, r1, r3
	ldrh	r3, [r0]
	lsr	r2, r3, #5
	ldrh	r3, [r0]
	lsr	r3, r3, #10
	and	r2, r2, r6
	and	r3, r3, r6
	cmp	r1, #31
	bne	.L9
	cmp	r2, #31
	bne	.L9
	cmp	r3, #31
	bne	.L9
	add	r5, r5, #1
	b	.L10
.L9:
	cmp	r1, #30
	bgt	.L11
	add	r1, r1, #1
.L11:
	cmp	r2, #30
	bgt	.L12
	add	r2, r2, #1
.L12:
	cmp	r3, #30
	bgt	.L13
	add	r3, r3, #1
.L13:
	lsl	r3, r3, #10
	lsl	r2, r2, #5
	orr	r3, r3, r2
	orr	r3, r3, r1
	strh	r3, [r0]
.L10:
	add	r4, r4, #1
	add	r0, r0, #2
	cmp	r4, #7
	bls	.L14
	mov	r0, #2
	bl	__WaitFrames
	cmp	r5, #7
	bls	.L15
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_924_200a844,.Lfe1-OvlFunc_924_200a844

	.text
	.align	2, 0
