@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_f84_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_924_2009408
	.thumb_func
	.type	 OvlFunc_924_2009408,function
OvlFunc_924_2009408:
	push	{lr}
	bl	__CutsceneStart
	bl	OvlFunc_924_20083a8
	bl	__CutsceneEnd
	bl	OvlFunc_924_2009420
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_924_2009408,.Lfe1-OvlFunc_924_2009408

	.text
	.align	2, 0
