@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b0070_a_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b11a4
	.thumb_func
	.type	 Func_80b11a4,function
Func_80b11a4:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r6, r1
	cmp	r5, #0
	beq	.L3
	bl	_Func_8016498
	mov	r0, r6
	mov	r1, r5
	mov	r2, #0
	mov	r3, #0
	bl	_Func_801e7c0
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_80b11a4,.Lfe1-Func_80b11a4

	.text
	.align	2, 0
