@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b0070_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b00f4
	.thumb_func
	.type	 Func_80b00f4,function
Func_80b00f4:
	push	{lr}
	ldr	r3, .L3
	ldr	r0, [r3]
	mov	r3, #224
	lsl	r3, r3, #2
	add	r0, r0, r3
	bl	Func_80b08b8
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001f2c
.Lfe1:
	.size	 Func_80b00f4,.Lfe1-Func_80b00f4

	.text
	.align	2, 0
