@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b0070_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b3210
	.thumb_func
	.type	 Func_80b3210,function
Func_80b3210:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L10
	ldr	r1, .L10+4
	ldr	r6, [r3]
	ldr	r3, .L10+8
	ldrsb	r0, [r3, r0]
	add	r3, r6, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	mov	r2, #0
	sub	sp, sp, #4
	mov	sl, r0
	mov	r7, #0
	cmp	r2, r3
	bge	.L4
	add	r3, r6, #2
	mov	r5, #219
	mov	r8, r3
	lsl	r5, r5, #2
.L9:
	mov	r1, r8
	ldrsh	r0, [r1, r5]
	str	r2, [sp]
	bl	_GetUnit
	mov	r1, #56
	ldrsh	r3, [r0, r1]
	ldr	r2, [sp]
	cmp	r3, #0
	beq	.L8
	add	r2, r2, #1
.L8:
	ldr	r1, .L10+4
	add	r3, r6, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	add	r7, r7, #1
	add	r5, r5, #2
	cmp	r7, r3
	blt	.L9
.L4:
	mov	r0, sl
	mul	r0, r0, r2
	add	sp, sp, #4
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L11:
	.align	2, 0
.L10:
	.word	iwram_3001f2c
	.word	935
	.word	.Lb4ab6
.Lfe1:
	.size	 Func_80b3210,.Lfe1-Func_80b3210

	.text
	.align	2, 0
