@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b0070_c_c_a_a_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b280c
	.thumb_func
	.type	 Func_80b280c,function
Func_80b280c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L10
	ldr	r1, .L10+4
	ldr	r5, [r3]
	add	r3, r5, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	sub	r1, r1, #3
	mov	sl, r3
	add	r3, r5, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	mov	r2, #0
	sub	sp, sp, #4
	mov	r7, #0
	cmp	r2, r3
	bge	.L9
	add	r3, r5, #2
	mov	r6, #219
	mov	r8, r3
	lsl	r6, r6, #2
.L6:
	mov	r1, r8
	ldrsh	r0, [r1, r6]
	mov	r1, sl
	str	r2, [sp]
	bl	Func_80b27b0
	ldr	r2, [sp]
	cmp	r0, #0
	beq	.L5
	add	r2, r2, #1
.L5:
	ldr	r1, .L10+8
	add	r3, r5, r1
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	add	r7, r7, #1
	add	r6, r6, #2
	cmp	r7, r3
	blt	.L6
.L9:
	mov	r0, r2
	add	sp, sp, #4
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L11:
	.align	2, 0
.L10:
	.word	iwram_3001f2c
	.word	938
	.word	935
.Lfe1:
	.size	 Func_80b280c,.Lfe1-Func_80b280c

	.text
	.align	2, 0
