@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_901_2008e90
	.thumb_func
	.type	 OvlFunc_901_2008e90,function
OvlFunc_901_2008e90:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L5
	bl	__MessageID
	mov	r0, #18
	mov	r1, #0
	bl	__MapActor_SetAnim
	mov	r2, #0
	mov	r1, #0
	mov	r0, #18
	bl	__Func_8092848
	mov	r0, #2
	bl	__CutsceneWait
	mov	r0, #18
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #1
	mov	r0, #18
	bl	__MapActor_SetAnim
	mov	r0, #231
	bl	__CheckPartyItem
	mov	r1, #1
	neg	r1, r1
	cmp	r0, r1
	beq	.L3
	ldr	r0, .L5+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r3, .L5+8
	mov	r1, #185
	ldr	r3, [r3]
	lsl	r1, r1, #1
	add	r2, r3, r1
	mov	r3, #1
	strh	r3, [r2]
.L3:
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	4930
	.word	2136
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_901_2008e90,.Lfe1-OvlFunc_901_2008e90

	.text
	.align	2, 0
