@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_a_c_c_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_901_2008d4c
	.thumb_func
	.type	 OvlFunc_901_2008d4c,function
OvlFunc_901_2008d4c:
	push	{lr}
	mov	r0, #128
	lsl	r0, r0, #2
	sub	sp, sp, #8
	bl	__ClearFlag
	mov	r3, #23
	mov	r2, #26
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #23
	mov	r1, #23
	mov	r2, #4
	mov	r3, #2
	bl	__Func_8010704
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_901_2008d4c,.Lfe1-OvlFunc_901_2008d4c

	.text
	.align	2, 0
