@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_960_20083a4
	.thumb_func
	.type	 OvlFunc_960_20083a4,function
OvlFunc_960_20083a4:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020095c0
.Lfe1:
	.size	 OvlFunc_960_20083a4,.Lfe1-OvlFunc_960_20083a4

	.text
	.align	2, 0
