@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_911_2008030
	.thumb_func
	.type	 OvlFunc_911_2008030,function
OvlFunc_911_2008030:
	push	{r5, lr}
	ldr	r5, .L4
	ldr	r3, [r5]
	cmp	r3, #0
	beq	.L3
	mov	r1, #2
	bl	__Actor_SetAnim
	mov	r3, #0
	str	r3, [r5]
.L3:
	mov	r0, #1
	pop	{r5}
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	.L3698
.Lfe1:
	.size	 OvlFunc_911_2008030,.Lfe1-OvlFunc_911_2008030

	.text
	.align	2, 0
