@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_911_20081d4
	.thumb_func
	.type	 OvlFunc_911_20081d4,function
OvlFunc_911_20081d4:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200b040
.Lfe1:
	.size	 OvlFunc_911_20081d4,.Lfe1-OvlFunc_911_20081d4

	.text
	.align	2, 0
