@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_922_20086c0
	.thumb_func
	.type	 OvlFunc_922_20086c0,function
OvlFunc_922_20086c0:
	push	{lr}
	mov	r0, #241
	bl	__PlaySound
	mov	r0, #194
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L3
	bl	__ClearFlag
	mov	r1, #96
	mov	r2, #0
	mov	r0, #8
	bl	OvlFunc_922_2008180
	ldr	r0, .L3+4
	bl	__PlaySound
	mov	r0, #2
	bl	__WaitFrames
	bl	OvlFunc_922_20092cc
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	777
	.word	289
.Lfe1:
	.size	 OvlFunc_922_20086c0,.Lfe1-OvlFunc_922_20086c0

	.text
	.align	2, 0
