@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_bffb8_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c01bc
	.thumb_func
	.type	 Func_80c01bc,function
Func_80c01bc:
	push	{lr}
	ldr	r3, .L8
	ldr	r0, [r3]
	sub	r3, r3, #120
	ldr	r1, [r0]
	ldr	r4, [r3]
	mov	r3, #52
	sub	r2, r3, r1
	cmp	r2, #32
	ble	.L3
	mov	r2, #32
.L3:
	cmp	r2, #0
	bge	.L4
	mov	r2, #0
.L4:
	ldr	r3, .L8+4
	strh	r2, [r3, #2]
	cmp	r1, #80
	bhi	.L5
	lsl	r2, r1, #1
	add	r2, r2, r1
	lsl	r3, r2, #4
	sub	r3, r3, r2
	ldr	r2, .L8+8
	lsl	r3, r3, #3
	add	r3, r3, r2
	strh	r3, [r4, #54]
.L5:
	ldr	r3, [r0]
	add	r2, r3, #1
	str	r2, [r0]
	cmp	r2, #80
	bhi	.L6
	mov	r3, #180
	sub	r3, r3, r2
	mov	r0, #0
	mov	r1, #0
	mov	r2, #0
	bl	Func_80c0cec
	b	.L7
.L6:
	mov	r0, #0
	mov	r1, #0
	mov	r2, #0
	mov	r3, #100
	bl	Func_80c0cec
.L7:
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001ef8
	.word	iwram_3001ad0
	.word	44928
.Lfe1:
	.size	 Func_80c01bc,.Lfe1-Func_80c01bc

	.text
	.align	2, 0
