@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b7410_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b7514
	.thumb_func
	.type	 Func_80b7514,function
Func_80b7514:
	push	{r5, r6, lr}
	mov	r5, #0
	b	.L3
.L5:
	add	r5, r5, #1
.L3:
	cmp	r5, #5
	bgt	.L4
	mov	r6, r5
	add	r6, r6, #128
	mov	r0, r6
	bl	_GetUnit
	mov	r2, #149
	lsl	r2, r2, #1
	add	r3, r0, r2
	ldrb	r3, [r3]
	cmp	r3, #0
	bne	.L5
.L4:
	cmp	r5, #6
	bne	.L9
	mov	r0, #1
	neg	r0, r0
	b	.L2
.L9:
	mov	r0, r6
.L2:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80b7514,.Lfe1-Func_80b7514

	.text
	.align	2, 0
