@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_bbb0c_a_c_c_a_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80bf574
	.thumb_func
	.type	 Func_80bf574,function
Func_80bf574:
	push	{lr}
	bl	_GetUnit
	mov	r3, #163
	lsl	r3, r3, #1
	add	r1, r0, r3
	ldrb	r2, [r1]
	mov	r3, r2
	cmp	r3, #0
	beq	.L4
	add	r3, r3, #255
	strb	r3, [r1]
	lsl	r3, r3, #24
	lsr	r3, r3, #24
	cmp	r3, #0
	bne	.L4
	ldr	r1, .L6
	add	r2, r0, r1
	strb	r3, [r2]
	mov	r0, #1
	b	.L2
.L4:
	mov	r0, #0
.L2:
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	327
.Lfe1:
	.size	 Func_80bf574,.Lfe1-Func_80bf574

	.text
	.align	2, 0
