@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b8228_c_a_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b8f08
	.thumb_func
	.type	 Func_80b8f08,function
Func_80b8f08:
	push	{r5, r6, lr}
	mov	r2, #10
	ldrsh	r5, [r0, r2]
	mov	r0, r5
	sub	sp, sp, #28
	bl	_GetUnit
	mov	r2, #56
	ldrsh	r3, [r0, r2]
	mov	r0, r5
	cmp	r3, #0
	bne	.L2
	cmp	r5, #127
	ble	.L4
	mov	r6, sp
	mov	r0, #2
	b	.L7
.L4:
	mov	r6, sp
	mov	r0, #1
.L7:
	mov	r1, r6
	bl	Func_80b6b40
	mov	r5, r0
	cmp	r5, #0
	bne	.L6
	mov	r0, #128
	lsl	r0, r0, #1
	b	.L2
.L6:
	bl	Random
	mov	r3, r5
	mul	r3, r3, r0
	lsr	r3, r3, #16
	lsl	r3, r3, #1
	ldrsh	r0, [r6, r3]
.L2:
	add	sp, sp, #28
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80b8f08,.Lfe1-Func_80b8f08

	.text
	.align	2, 0

	.text
	.align	2, 0
