@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b9b30_c_a_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80ba978
	.thumb_func
	.type	 Func_80ba978,function
Func_80ba978:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L59
	mov	r7, r0
	ldr	r5, [r3]
	mov	r2, #128
	ldr	r3, [r7, #88]
	lsl	r2, r2, #11
	and	r3, r3, r2
	sub	sp, sp, #88
	mov	sl, r1
	cmp	r3, #0
	beq	.L3
	ldrb	r3, [r7]
	ldr	r2, .L59+4
	cmp	r3, #7
	bls	.L5
	mov	r2, #160
	lsl	r2, r2, #7
.L5:
	mov	r3, #60
	str	r2, [r5]
	str	r3, [r5, #4]
	b	.L6
.L3:
	ldrb	r0, [r7]
	bl	GetBattleActor
	ldr	r3, [r0]
	ldr	r1, [r3, #16]
	ldr	r0, [r3, #8]
	bl	atan2
	ldrb	r4, [r7]
	lsl	r0, r0, #16
	ldr	r2, .L59+8
	lsr	r0, r0, #16
	mov	r3, r4
	add	r1, r0, r2
	cmp	r3, #7
	bls	.L8
	mov	r3, #192
	lsl	r3, r3, #5
	add	r1, r0, r3
.L8:
	lsl	r3, r1, #16
	asr	r1, r3, #16
	mov	r3, r4
	cmp	r3, #7
	bhi	.L9
	mov	r3, #128
	lsl	r3, r3, #6
	b	.L58
.L9:
	ldr	r3, .L59+4
.L58:
	sub	r3, r3, r1
	lsl	r2, r3, #1
	add	r2, r2, r3
	cmp	r2, #0
	bge	.L12
	add	r2, r2, #3
.L12:
	asr	r3, r2, #2
	add	r1, r1, r3
	ldrb	r3, [r7, #2]
	mov	r2, r4
	cmp	r3, #7
	bhi	.L13
	mov	r3, #0
	cmp	r2, #7
	bhi	.L14
	mov	r3, #1
.L14:
	cmp	r3, #0
	bne	.L17
	b	.L16
.L13:
	mov	r3, #0
	cmp	r2, #7
	bls	.L18
	mov	r3, #1
.L18:
	cmp	r3, #0
	beq	.L16
.L17:
	mov	r1, #144
	mov	r3, r4
	lsl	r1, r1, #6
	cmp	r3, #7
	bls	.L16
	ldr	r1, .L59+12
.L16:
	ldr	r3, [r5]
	cmp	r3, r1
	beq	.L6
	str	r1, [r5]
.L6:
	ldr	r3, [r7, #88]
	mov	r2, #128
	lsl	r2, r2, #12
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L23
	ldrb	r3, [r7]
	ldr	r2, .L59+4
	cmp	r3, #7
	bls	.L25
	mov	r2, #128
	lsl	r2, r2, #6
.L25:
	mov	r3, #60
	str	r2, [r5]
	str	r3, [r5, #4]
.L23:
	add	r5, sp, #4
	mov	r0, r7
	mov	r1, r5
	bl	InitAnimContext
	mov	r6, sl
	mov	r3, #1
	and	r6, r6, r3
	cmp	r6, #0
	beq	.L26
	str	r3, [r5, #28]
.L26:
	mov	r1, #0
	mov	r0, #0
	bl	Func_80c10e8
	ldr	r3, .L59+16
	ldr	r3, [r3]
	add	r3, r3, #65
	ldrb	r0, [r3]
	mov	r3, #2
	neg	r3, r3
	and	r0, r0, r3
	bl	_Func_801f200
	ldr	r0, [r5, #8]
	bl	GetBattleActor
	ldr	r0, [r0]
	mov	r1, #3
	mov	r8, r0
	bl	_Actor_SetAnim
	mov	r1, #16
	mov	r0, r8
	bl	_Actor_SetAnimSpeed
	mov	r0, #154
	bl	_PlaySound
	mov	r3, #2
	mov	r1, sl
	and	r3, r3, r1
	cmp	r3, #0
	beq	.L27
	ldr	r0, [r5, #8]
	ldr	r1, [r7, #80]
	mov	r2, #1
	mov	r3, #0
	bl	Anim_MoveIntro
	b	.L28
.L27:
	cmp	r6, #0
	bne	.L28
	ldr	r0, [r5, #8]
	ldr	r1, [r7, #80]
	mov	r2, #0
	mov	r3, #0
	bl	Anim_MoveIntro
.L28:
	ldrb	r3, [r7, #2]
	cmp	r3, #7
	bhi	.L30
	mov	r3, #1
	b	.L57
.L30:
	mov	r3, #0
.L57:
	str	r3, [r5, #4]
	ldr	r3, [r5, #20]
	mov	r4, #0
	mov	r2, r5
	cmp	r3, #0
	beq	.L55
	mov	r6, #0
.L35:
	lsl	r3, r4, #1
	add	r3, r3, #36
	ldrsh	r0, [r2, r3]
	str	r4, [sp]
	bl	GetBattleActor
	mov	r1, #0
	ldr	r0, [r0]
	bl	Func_80b7f70
	mov	r3, r0
	add	r3, r3, #39
	ldrb	r3, [r3]
	sub	r3, r3, #1
	mov	r1, #0
	ldr	r4, [sp]
	cmp	r3, #0
	beq	.L56
	mov	ip, r3
	add	r3, r6, r5
	mov	r2, r3
	add	r2, r2, #52
	add	r0, r0, #40
.L39:
	ldmia	r0!, {r3}
	ldrb	r3, [r3, #5]
	add	r1, r1, #1
	strb	r3, [r2]
	add	r2, r2, #1
	cmp	r1, ip
	bne	.L39
.L56:
	ldr	r3, [r5, #20]
	add	r4, r4, #1
	add	r6, r6, #4
	mov	r2, r5
	cmp	r4, r3
	bne	.L35
.L55:
	ldr	r3, [r7, #92]
	cmp	r3, #0
	beq	.L42
	cmp	r3, #1
	bne	.L43
	ldrb	r1, [r7]
	mov	r0, #0
	bl	Func_80bbabc
	ldr	r1, .L59+20
	mov	r0, #4
	bl	Func_80bbabc
	b	.L44
.L43:
	ldr	r1, .L59+24
	mov	r0, #4
	bl	Func_80bbabc
.L44:
	bl	Func_80bb938
	bl	Func_80c1a14
	b	.L45
.L42:
	mov	r1, #200
	ldr	r0, .L59+28
	lsl	r1, r1, #4
	bl	StartTask
	ldr	r3, [r5]
	cmp	r3, #0
	beq	.L46
	ldr	r3, [r7, #88]
	mov	r2, #128
	lsl	r2, r2, #7
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L47
	mov	r0, r5
	bl	_Anim_Attack
	b	.L49
.L47:
	mov	r0, r5
	bl	_Anim_Func
	b	.L49
.L46:
	bl	Func_80c1a14
.L49:
	bl	Func_80be02c
	mov	r6, r5
	mov	r0, r8
	mov	r1, #1
	bl	_Actor_SetAnim
	ldr	r3, [r6, #20]
	mov	r4, #0
	cmp	r3, #0
	beq	.L45
	mov	r7, #36
.L53:
	ldrsh	r0, [r6, r7]
	str	r4, [sp]
	bl	Func_80b8000
	mov	r5, r6
	ldr	r4, [sp]
	ldr	r3, [r5, #20]
	add	r4, r4, #1
	add	r7, r7, #2
	cmp	r4, r3
	bne	.L53
.L45:
	mov	r0, #0
	add	sp, sp, #88
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L60:
	.align	2, 0
.L59:
	.word	iwram_3001f00
	.word	-8192
	.word	-6144
	.word	-9216
	.word	iwram_3001e74
	.word	2134
	.word	2133
	.word	Func_80bd898
.Lfe1:
	.size	 Func_80ba978,.Lfe1-Func_80ba978

	.text
	.align	2, 0
