@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_c1a34_a_a_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c23a0
	.thumb_func
	.type	 Func_80c23a0,function
Func_80c23a0:
	push	{lr}
	cmp	r0, #171
	bls	.L3
	ldr	r3, .L5
	ldrh	r0, [r3]
	b	.L4
.L3:
	ldr	r3, .L5
	lsl	r2, r0, #3
	add	r2, r2, r3
	ldrb	r0, [r2, #3]
	lsl	r0, r0, #27
	lsr	r0, r0, #28
.L4:
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	.Lc7420
.Lfe1:
	.size	 Func_80c23a0,.Lfe1-Func_80c23a0

	.text
	.align	2, 0

	.text
	.align	2, 0
