@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_b5a0c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80b6cdc
	.thumb_func
	.type	 Func_80b6cdc,function
Func_80b6cdc:
	push	{r5, lr}
	bl	Func_80c23c0
	ldr	r3, .L13
	ldr	r4, [r3]
	mov	r2, #4
	ldrsh	r3, [r4, r2]
	mov	r1, #0
	cmp	r3, #0
	bne	.L5
	cmp	r0, #0
	bne	.L4
	mov	r5, #6
	ldrsh	r3, [r4, r5]
	cmp	r3, #0
	beq	.L4
.L5:
	add	r1, r1, #1
	cmp	r1, #5
	bgt	.L4
	lsl	r2, r1, #1
	add	r3, r2, #4
	ldrsh	r3, [r4, r3]
	cmp	r3, #0
	bne	.L5
	cmp	r0, #0
	bne	.L4
	cmp	r1, #4
	bgt	.L5
	add	r3, r2, #6
	ldrsh	r3, [r4, r3]
	cmp	r3, #0
	bne	.L5
.L4:
	mov	r3, #6
	eor	r3, r3, r1
	neg	r0, r3
	orr	r0, r0, r3
	lsr	r0, r0, #31
	pop	{r5}
	pop	{r1}
	bx	r1
.L14:
	.align	2, 0
.L13:
	.word	iwram_3001e74
.Lfe1:
	.size	 Func_80b6cdc,.Lfe1-Func_80b6cdc

	.text
	.align	2, 0
