@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_bbb0c_a_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80be0b4
	.thumb_func
	.type	 Func_80be0b4,function
Func_80be0b4:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r5, r0
	mov	r6, r1
	mov	r1, #0
	sub	sp, sp, #20
	mov	fp, r1
	mov	r0, #1
	cmp	r5, #7
	bls	.L4
	mov	r0, #2
.L4:
	add	r2, sp, #4
	mov	r9, r2
	mov	r1, r9
	bl	Func_80b6c08
	mov	r7, r0
	mov	r0, #0
	cmp	r5, #7
	bls	.L5
	mov	r0, #1
.L5:
	bl	_Func_8077330
	add	r0, r0, #8
	mov	r8, r0
	cmp	r6, #0
	beq	.L6
	mov	r2, #0
	add	r3, r6, #3
	mov	ip, r6
.L10:
	strb	r2, [r3]
	sub	r3, r3, #1
	cmp	r3, ip
	bge	.L10
.L6:
	mov	r2, #128
	lsl	r2, r2, #1
	mov	r3, #0
	add	r2, r2, r8
	mov	sl, r3
	ldr	r3, [r2]
	cmp	r3, #0
	beq	.L26
	mov	r1, #0
	str	r2, [sp]
	mov	ip, r9
	mov	r5, r8
	mov	lr, r1
.L15:
	mov	r2, #1
	mov	r3, #3
	ldrsb	r3, [r5, r3]
	neg	r2, r2
	cmp	r3, r2
	bne	.L14
	mov	r4, #0
	cmp	r4, r7
	bge	.L18
	mov	r3, ip
	ldrh	r2, [r3]
	ldrb	r3, [r5, #2]
	cmp	r2, r3
	beq	.L18
	mov	r1, r5
	mov	r0, r9
.L19:
	add	r4, r4, #1
	cmp	r4, r7
	bge	.L18
	add	r0, r0, #2
	ldrh	r2, [r0]
	ldrb	r3, [r1, #2]
	cmp	r2, r3
	bne	.L19
.L18:
	cmp	r4, r7
	beq	.L14
	cmp	r6, #0
	beq	.L24
	mov	r3, r8
	mov	r1, lr
	ldrb	r2, [r1, r3]
	ldrb	r3, [r6, r2]
	add	r3, r3, #1
	strb	r3, [r6, r2]
.L24:
	mov	r1, #1
	add	fp, fp, r1
.L14:
	ldr	r1, [sp]
	mov	r3, #1
	add	sl, sl, r3
	ldr	r3, [r1]
	mov	r2, #4
	add	r5, r5, #4
	add	lr, lr, r2
	cmp	sl, r3
	bne	.L15
.L26:
	mov	r0, fp
	add	sp, sp, #20
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80be0b4,.Lfe1-Func_80be0b4

	.text
	.align	2, 0
