@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_914_20089e8
	.thumb_func
	.type	 OvlFunc_914_20089e8,function
OvlFunc_914_20089e8:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_02008fe0
.Lfe1:
	.size	 OvlFunc_914_20089e8,.Lfe1-OvlFunc_914_20089e8
	.align	2, 0
	.global	OvlFunc_914_20089f0
	.thumb_func
	.type	 OvlFunc_914_20089f0,function
OvlFunc_914_20089f0:
	ldr	r0, .L6
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	gOvl_02008ff0
.Lfe2:
	.size	 OvlFunc_914_20089f0,.Lfe2-OvlFunc_914_20089f0

	.text
	.align	2, 0
