@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_f6008_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80f7e34
	.thumb_func
	.type	 Func_80f7e34,function
Func_80f7e34:
	push	{lr}
	ldr	r3, .L5
	ldr	r1, [r3]
	lsl	r3, r0, #1
	add	r3, r3, r0
	lsl	r3, r3, #2
	add	r4, r3, #4
	ldr	r0, [r1, r4]
	cmp	r0, #0
	beq	.L2
	ldr	r2, [r1, r3]
	cmp	r2, #0
	beq	.L4
	str	r0, [r2, #4]
.L4:
	ldr	r2, [r1, r4]
	ldr	r3, [r1, r3]
	str	r3, [r2]
.L2:
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	ewram_2004c00
.Lfe1:
	.size	 Func_80f7e34,.Lfe1-Func_80f7e34

	.text
	.align	2, 0
