@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_f6008_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	StartLuckyWheels
	.thumb_func
	.type	 StartLuckyWheels,function
StartLuckyWheels:
	push	{lr}
	ldrh	r3, .L3
	mov	r2, #128
	lsl	r2, r2, #19
	strh	r3, [r2]
	ldr	r3, .L3+4
	ldr	r2, .L3+8
	ldr	r3, [r3, #4]
	mov	r0, #9
	str	r3, [r2]
	bl	_PlaySound
	bl	LuckyWheelsMain
	mov	r0, #0
	b	.L4
.L5:
	.align	2, 0
.L3:
	.word	64
	.word	gState
	.word	gRNGState
.L4:
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 StartLuckyWheels,.Lfe1-StartLuckyWheels

	.text
	.align	2, 0
