@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_f6008_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80f7db4
	.thumb_func
	.type	 Func_80f7db4,function
Func_80f7db4:
	push	{lr}
	ldr	r3, .L11
	ldr	r3, [r3]
	ldr	r0, .L11+4
	mov	r2, #0
	mov	r1, #0
	add	r3, r3, #4
.L6:
	str	r2, [r3, #4]
	add	r2, r2, #1
	str	r1, [r3]
	add	r3, r3, #12
	cmp	r2, r0
	ble	.L6
	ldr	r3, .L11
	mov	r2, #192
	ldr	r3, [r3]
	lsl	r2, r2, #6
	add	r3, r3, r2
	mov	r1, #0
	mov	r2, #255
.L10:
	sub	r2, r2, #1
	stmia	r3!, {r1}
	cmp	r2, #0
	bge	.L10
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	ewram_2004c00
	.word	1023
.Lfe1:
	.size	 Func_80f7db4,.Lfe1-Func_80f7db4

	.text
	.align	2, 0
