@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_4e4_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_933_2008cd0
	.thumb_func
	.type	 OvlFunc_933_2008cd0,function
OvlFunc_933_2008cd0:
	push	{r5, r6, lr}
	ldr	r0, .L10
	ldr	r3, .L10+4
	ldr	r2, .L10+8
	ldr	r6, [r3]
	add	r3, r2, r0
	mov	r0, #0
	ldrsh	r1, [r3, r0]
	mov	r3, #100
	mov	r0, r1
	mul	r0, r0, r3
	mov	r1, #139
	lsl	r1, r1, #2
	add	r2, r2, r1
	mov	r3, #0
	ldrsh	r1, [r2, r3]
	bl	__divsi3
	mov	r5, r0
	ldr	r0, .L10+12
	bl	__GetFlag
	cmp	r0, #0
	bne	.L2
	ldr	r0, .L10+16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	cmp	r5, #74
	bgt	.L4
	ldr	r0, .L10+16
	bl	__ClearFlag
	ldr	r0, .L10+20
	bl	__ClearFlag
	mov	r0, #193
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L10+24
	bl	__ClearFlag
.L4:
	ldr	r0, .L10+28
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	cmp	r5, #49
	bgt	.L5
	ldr	r0, .L10+28
	bl	__ClearFlag
	ldr	r0, .L10+20
	bl	__ClearFlag
	mov	r0, #193
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L10+24
	bl	__ClearFlag
.L5:
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	cmp	r5, #24
	bgt	.L6
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L10+20
	bl	__ClearFlag
	mov	r0, #193
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L10+24
	bl	__ClearFlag
.L6:
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	bne	.L7
	cmp	r5, #24
	ble	.L7
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__SetFlag
	mov	r0, #193
	lsl	r0, r0, #1
	add	r2, r6, r0
	mov	r3, #1
	strh	r3, [r2]
.L7:
	ldr	r0, .L10+28
	bl	__GetFlag
	cmp	r0, #0
	bne	.L8
	cmp	r5, #49
	ble	.L8
	ldr	r0, .L10+28
	bl	__SetFlag
	mov	r1, #193
	lsl	r1, r1, #1
	add	r2, r6, r1
	mov	r3, #2
	strh	r3, [r2]
.L8:
	ldr	r0, .L10+16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L2
	cmp	r5, #74
	ble	.L2
	ldr	r0, .L10+16
	bl	__SetFlag
	mov	r3, #193
	lsl	r3, r3, #1
	add	r2, r6, r3
	mov	r3, #3
	strh	r3, [r2]
.L2:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	562
	.word	iwram_3001ebc
	.word	gState
	.word	513
	.word	770
	.word	771
	.word	773
	.word	769
.Lfe1:
	.size	 OvlFunc_933_2008cd0,.Lfe1-OvlFunc_933_2008cd0

	.text
	.align	2, 0
