@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_926_2008484
	.thumb_func
	.type	 OvlFunc_926_2008484,function
OvlFunc_926_2008484:
	push	{r5, lr}
	bl	__CutsceneStart
	ldr	r0, .L6
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr	r0, .L6+4
	bl	__MessageID
	mov	r1, #0
	mov	r0, #12
	bl	__Func_8093054
	bl	__CutsceneEnd
	b	.L2
.L3:
	ldr	r0, .L6+8
	bl	__MessageID
	mov	r1, #0
	mov	r0, #12
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #1
	bne	.L4
	ldr	r5, .L6+12
	mov	r2, #236
	ldr	r3, [r5]
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldrh	r2, [r3]
	add	r2, r2, #1
	mov	r1, #0
	strh	r2, [r3]
	mov	r0, #12
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #1
	bne	.L4
	ldr	r2, [r5]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
.L4:
	mov	r0, #12
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
.L2:
	pop	{r5}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	2191
	.word	6102
	.word	6036
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_926_2008484,.Lfe1-OvlFunc_926_2008484

	.text
	.align	2, 0
