@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_c_c_c_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_926_2009334
	.thumb_func
	.type	 OvlFunc_926_2009334,function
OvlFunc_926_2009334:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r5, r0
	bl	__CutsceneStart
	mov	r1, #8
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r0, .L9
	ldrh	r2, [r5, #6]
	add	r3, r2, r0
	ldr	r0, .L9+4
	lsl	r3, r3, #16
	ldr	r1, .L9+8
	cmp	r3, r0
	bhi	.L3
	bl	OvlFunc_926_2008e94
	b	.L4
.L3:
	ldr	r0, .L9+12
	add	r3, r2, r0
	lsl	r3, r3, #16
	lsr	r3, r3, #16
	cmp	r3, r1
	bhi	.L5
	bl	OvlFunc_926_2008bf4
	b	.L4
.L5:
	mov	r0, #192
	lsl	r0, r0, #7
	add	r3, r2, r0
	lsl	r3, r3, #16
	lsr	r3, r3, #16
	cmp	r3, r1
	bhi	.L7
	bl	OvlFunc_926_2008db4
	b	.L4
.L7:
	bl	OvlFunc_926_2008cd4
.L4:
	mov	r1, #1
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #1
	bl	OvlFunc_926_200902c
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	-8192
	.word	1073676288
	.word	16383
	.word	-24576
.Lfe1:
	.size	 OvlFunc_926_2009334,.Lfe1-OvlFunc_926_2009334

	.text
	.align	2, 0
