@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_888_200805c
	.thumb_func
	.type	 OvlFunc_888_200805c,function
OvlFunc_888_200805c:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200baa8
.Lfe1:
	.size	 OvlFunc_888_200805c,.Lfe1-OvlFunc_888_200805c

	.text
	.align	2, 0
