@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_902_200806c
	.thumb_func
	.type	 OvlFunc_902_200806c,function
OvlFunc_902_200806c:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020086dc
.Lfe1:
	.size	 OvlFunc_902_200806c,.Lfe1-OvlFunc_902_200806c

	.text
	.align	2, 0
