@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_954_2008830
	.thumb_func
	.type	 OvlFunc_954_2008830,function
OvlFunc_954_2008830:
	push	{lr}
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__SetFlag
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_954_2008830,.Lfe1-OvlFunc_954_2008830

	.text
	.align	2, 0
