@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_970_20083f8
	.thumb_func
	.type	 OvlFunc_970_20083f8,function
OvlFunc_970_20083f8:
	push	{r5, lr}
	mov	r0, #3
	ldr	r5, .L3
	bl	__MapActor_GetActor
	ldr	r3, [r0, #12]
	mov	r0, #0
	str	r3, [r5]
	pop	{r5}
	pop	{r1}
	bx	r1
.L4:
	.align	2, 0
.L3:
	.word	gOvl_02009814
.Lfe1:
	.size	 OvlFunc_970_20083f8,.Lfe1-OvlFunc_970_20083f8

	.text
	.align	2, 0
