@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_970_200803c
	.thumb_func
	.type	 OvlFunc_970_200803c,function
OvlFunc_970_200803c:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_02009710
.Lfe1:
	.size	 OvlFunc_970_200803c,.Lfe1-OvlFunc_970_200803c
	.align	2, 0
	.global	OvlFunc_970_2008044
	.thumb_func
	.type	 OvlFunc_970_2008044,function
OvlFunc_970_2008044:
	ldr	r0, .L6
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	gOvl_0200971c
.Lfe2:
	.size	 OvlFunc_970_2008044,.Lfe2-OvlFunc_970_2008044

	.text
	.align	2, 0
