@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_970_2009188
	.thumb_func
	.type	 OvlFunc_970_2009188,function
OvlFunc_970_2009188:
	push	{lr}
	ldr	r0, .L3
	bl	__StopTask
	ldr	r0, .L3+4
	bl	__StopTask
	ldr	r2, .L3+8
	ldr	r3, .L3+12
	ldrh	r1, [r2, #10]
	and	r3, r3, r1
	strh	r3, [r2, #10]
	ldr	r3, .L3+16
	ldrh	r1, [r2, #10]
	and	r3, r3, r1
	strh	r3, [r2, #10]
	ldrh	r3, [r2, #10]
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	OvlFunc_970_2008f30
	.word	OvlFunc_970_2008f80
	.word	67109040
	.word	50687
	.word	32767
.Lfe1:
	.size	 OvlFunc_970_2009188,.Lfe1-OvlFunc_970_2009188

	.text
	.align	2, 0
