@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_a_a_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_884_200821c
	.thumb_func
	.type	 OvlFunc_884_200821c,function
OvlFunc_884_200821c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	bl	__MessageID
	mov	r2, #2
	mov	r0, #15
	mov	r1, #0
	bl	__Func_8092848
	mov	r1, #0
	mov	r0, #15
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	3908
.Lfe1:
	.size	 OvlFunc_884_200821c,.Lfe1-OvlFunc_884_200821c

	.text
	.align	2, 0
