@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_966_20087c4
	.thumb_func
	.type	 OvlFunc_966_20087c4,function
OvlFunc_966_20087c4:
	push	{r5, r6, lr}
	ldr	r0, .L11
	sub	sp, sp, #8
	bl	__SetFlag
	bl	__CutsceneStart
	ldr	r0, .L11+4
	bl	__MessageID
	mov	r2, #188
	mov	r0, #0
	mov	r1, #104
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r0, #0
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #32
	mov	r0, #1
	neg	r1, r1
	mov	r2, #0
	mov	r3, #0
	bl	__Func_809233c
	mov	r1, #16
	mov	r3, #224
	mov	r0, #3
	neg	r1, r1
	mov	r2, #16
	lsl	r3, r3, #8
	bl	__Func_809233c
	mov	r3, #192
	lsl	r3, r3, #8
	mov	r2, #16
	mov	r1, #0
	mov	r0, #2
	bl	__Func_809233c
	mov	r0, #1
	bl	__MapActor_WaitMovement
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__Func_8092c40
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #8
	mov	r0, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L3
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #3
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L11+8
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L4
.L12:
	.align	2, 0
.L11:
	.word	2490
	.word	10382
	.word	iwram_3001ebc
.L3:
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r3, .L13
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #3
	mov	r1, #0
	bl	__ActorMessage
.L4:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #132
	mov	r2, #40
	mov	r0, #2
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #16
	mov	r0, #0
	neg	r1, r1
	mov	r2, #0
	bl	__Func_8092304
	mov	r2, #16
	mov	r0, #2
	mov	r1, #0
	neg	r2, r2
	bl	__Func_80922c4
	mov	r2, #8
	mov	r0, #3
	mov	r1, #0
	neg	r2, r2
	bl	__Func_80922c4
	mov	r2, #16
	neg	r2, r2
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8092304
	mov	r0, #3
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #22
	bl	__Func_8092adc
	mov	r0, #80
	bl	__CutsceneWait
	ldr	r2, .L13+4
	ldr	r1, .L13+8
	mov	r0, #22
	bl	__MapActor_SetSpeed
	mov	r0, #22
	bl	__MapActor_GetActor
	mov	r3, #2
	add	r0, r0, #85
	strb	r3, [r0]
	mov	r1, #2
	mov	r0, #22
	bl	__Func_8092b08
	mov	r5, #4
	mov	r3, #2
	mov	r1, #0
	mov	r2, #1
	mov	r6, #18
	mov	r0, #34
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_8010788
	mov	r0, #158
	bl	__PlaySound
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #144
	mov	r2, #156
	lsl	r1, r1, #15
	lsl	r2, r2, #17
	mov	r0, #22
	bl	__MapActor_SetPos
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #22
	mov	r1, #0
	mov	r2, #16
	bl	__Func_8092304
	mov	r3, #2
	mov	r2, #1
	mov	r1, #0
	mov	r0, #32
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_8010788
	mov	r0, #159
	bl	__PlaySound
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #22
	mov	r1, #16
	mov	r2, #0
	bl	__Func_8092304
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #22
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #22
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #22
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #2
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r1, #2
	mov	r2, #0
	mov	r0, #3
	bl	__Func_8092848
	mov	r0, #60
	bl	__CutsceneWait
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #3
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #3
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #224
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L5
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L13
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L6
.L14:
	.align	2, 0
.L13:
	.word	iwram_3001ebc
	.word	26214
	.word	52428
.L5:
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r3, .L15
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
.L6:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #2
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #131
	mov	r2, #50
	mov	r0, #22
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #176
	mov	r2, #166
	lsl	r2, r2, #17
	mov	r0, #25
	lsl	r1, r1, #15
	bl	__MapActor_SetPos
	mov	r0, #1
	mov	r1, #0
	neg	r0, r0
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #3
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r0, #3
	mov	r1, #4
	mov	r2, #13
	bl	__MapActor_Jump
	mov	r2, #30
	mov	r0, #3
	mov	r1, #4
	bl	__MapActor_Jump
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #22
	mov	r1, #0
	bl	__ActorMessage
	ldr	r0, .L15+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	bl	OvlFunc_966_2009090
.L7:
	ldr	r0, .L15+8
	bl	__MessageID
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #22
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #1
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #22
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #25
	ldr	r1, .L15+12
	ldr	r2, .L15+16
	bl	__MapActor_SetSpeed
	mov	r0, #25
	mov	r1, #0
	mov	r2, #16
	bl	__Func_809228c
	mov	r1, #0
	mov	r2, #16
	mov	r0, #22
	bl	__Func_8092304
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #25
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r3, .L15
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r1, #0
	mov	r0, #242
	bl	__Func_8091a58
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #22
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r3, #254
	and	r3, r3, r2
	mov	r2, #16
	strb	r3, [r0]
	mov	r1, #0
	neg	r2, r2
	mov	r0, #22
	bl	__Func_8092304
	mov	r0, #22
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r3, #1
	orr	r3, r3, r2
	mov	r1, #130
	strb	r3, [r0]
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #22
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #22
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #50
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #16
	mov	r0, #22
	neg	r1, r1
	mov	r2, #0
	bl	__Func_8092304
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #22
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r5, #4
	mov	r3, #2
	mov	r1, #0
	mov	r2, #1
	mov	r6, #18
	mov	r0, #34
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_8010788
	mov	r0, #158
	bl	__PlaySound
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #16
	mov	r0, #22
	mov	r1, #0
	neg	r2, r2
	bl	__Func_8092304
	mov	r1, #0
	mov	r2, #0
	mov	r0, #22
	bl	__MapActor_SetPos
	mov	r0, #10
	bl	__CutsceneWait
	mov	r3, #2
	mov	r1, #0
	mov	r2, #1
	mov	r0, #32
	str	r5, [sp]
	str	r6, [sp, #4]
	bl	__Func_8010788
	mov	r0, #159
	bl	__PlaySound
	mov	r0, #50
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_809280c
	mov	r2, #0
	mov	r1, #0
	mov	r0, #2
	bl	__Func_809280c
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #3
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #0
	bl	__MapActor_SetAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #1
	ldr	r1, .L15+20
	ldr	r2, .L15+24
	bl	__MapActor_SetSpeed
	mov	r0, #3
	ldr	r1, .L15+20
	ldr	r2, .L15+24
	bl	__MapActor_SetSpeed
	mov	r0, #2
	ldr	r1, .L15+20
	ldr	r2, .L15+24
	bl	__MapActor_SetSpeed
	mov	r0, #1
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L8
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #1
	bl	__MapActor_TravelTo
	b	.L16
.L17:
	.align	2, 0
.L15:
	.word	iwram_3001ebc
	.word	2495
	.word	10405
	.word	52428
	.word	26214
	.word	78643
	.word	39321
.L16:
.L8:
	mov	r0, #1
	bl	__MapActor_WaitMovement
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #3
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L9
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #3
	bl	__MapActor_TravelTo
.L9:
	mov	r0, #3
	bl	__MapActor_WaitMovement
	mov	r0, #3
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #2
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L10
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #2
	bl	__MapActor_TravelTo
.L10:
	mov	r0, #2
	bl	__MapActor_WaitMovement
	mov	r1, #0
	mov	r2, #0
	mov	r0, #2
	bl	__MapActor_SetPos
	mov	r0, #10
	bl	__CutsceneWait
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_966_20087c4,.Lfe1-OvlFunc_966_20087c4

	.text
	.align	2, 0
