@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_966_200804c
	.thumb_func
	.type	 OvlFunc_966_200804c,function
OvlFunc_966_200804c:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020098c4
.Lfe1:
	.size	 OvlFunc_966_200804c,.Lfe1-OvlFunc_966_200804c

	.text
	.align	2, 0
