@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_966_200810c
	.thumb_func
	.type	 OvlFunc_966_200810c,function
OvlFunc_966_200810c:
	push	{lr}
	ldr	r0, .L3
	bl	__SetFlag
	ldr	r0, .L3+4
	bl	__MessageID
	mov	r0, #18
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r2, #128
	mov	r0, #18
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r1, #16
	mov	r0, #18
	neg	r1, r1
	mov	r2, #0
	bl	__Func_8092304
	mov	r0, #18
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	2491
	.word	10424
.Lfe1:
	.size	 OvlFunc_966_200810c,.Lfe1-OvlFunc_966_200810c

	.text
	.align	2, 0
