@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_170_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_935_20082cc
	.thumb_func
	.type	 OvlFunc_935_20082cc,function
OvlFunc_935_20082cc:
	push	{lr}
	ldr	r0, .L3
	mov	r1, #1
	bl	__Func_801776c
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	2387
.Lfe1:
	.size	 OvlFunc_935_20082cc,.Lfe1-OvlFunc_935_20082cc

	.text
	.align	2, 0
