@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_b8c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_935_2008c08
	.thumb_func
	.type	 OvlFunc_935_2008c08,function
OvlFunc_935_2008c08:
	push	{r5, r6, lr}
	mov	r5, #10
	mov	r6, #5
.L6:
	mov	r0, r5
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, r5
	bl	__MapActor_GetActor
	ldr	r3, .L7
	str	r3, [r0, #68]
	mov	r3, #0
	str	r3, [r0, #72]
	mov	r3, #255
	lsl	r3, r3, #16
	sub	r6, r6, #1
	str	r3, [r0, #12]
	add	r5, r5, #1
	cmp	r6, #0
	bge	.L6
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L7+4
	bl	__StartTask
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	6553
	.word	OvlFunc_935_2008aa0
.Lfe1:
	.size	 OvlFunc_935_2008c08,.Lfe1-OvlFunc_935_2008c08

	.text
	.align	2, 0
