@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_2e0_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_935_2008944
	.thumb_func
	.type	 OvlFunc_935_2008944,function
OvlFunc_935_2008944:
	push	{r5, r6, r7, lr}
	bl	__MapActor_GetActor
	mov	r5, #0
	mov	r6, r0
.L6:
	mov	r0, r5
	add	r0, r0, #11
	bl	__MapActor_GetActor
	ldr	r3, [r0, #12]
	ldr	r2, .L15
	sub	r3, r3, #1
	cmp	r3, r2
	bhi	.L5
	ldr	r3, [r0, #16]
	cmp	r3, #0
	bge	.L8
	ldr	r7, .L15+4
	add	r3, r3, r7
.L8:
	asr	r4, r3, #20
	ldr	r3, [r0, #8]
	cmp	r3, #0
	bge	.L9
	ldr	r2, .L15+4
	add	r3, r3, r2
.L9:
	asr	r1, r3, #20
	ldr	r3, [r6, #16]
	cmp	r3, #0
	bge	.L10
	ldr	r7, .L15+4
	add	r3, r3, r7
.L10:
	asr	r2, r3, #20
	ldr	r3, [r6, #8]
	cmp	r3, #0
	bge	.L11
	ldr	r7, .L15+4
	add	r3, r3, r7
.L11:
	asr	r3, r3, #20
	sub	r2, r2, r4
	cmp	r3, r1
	bne	.L5
	cmp	r2, #0
	bne	.L5
	mov	r3, #255
	lsl	r3, r3, #16
	str	r3, [r0, #12]
	str	r2, [r0, #72]
	str	r2, [r0, #40]
	mov	r0, #1
	b	.L2
.L5:
	add	r5, r5, #1
	cmp	r5, #3
	ble	.L6
	mov	r0, #0
.L2:
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	1048574
	.word	1048575
.Lfe1:
	.size	 OvlFunc_935_2008944,.Lfe1-OvlFunc_935_2008944

	.text
	.align	2, 0
