@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_905_200915c
	.thumb_func
	.type	 OvlFunc_905_200915c,function
OvlFunc_905_200915c:
	push	{lr}
	ldr	r0, .L3
	bl	__StopTask
	bl	__CutsceneStart
	mov	r1, #128
	mov	r2, #30
	mov	r0, #13
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r0, #13
	mov	r1, #2
	bl	__Func_80925cc
	mov	r1, #160
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #0
	bl	__Func_8092adc
	ldr	r0, .L3+4
	bl	__MessageID
	mov	r0, #13
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #3
	mov	r0, #13
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__MapActor_GetActor
	add	r0, r0, #35
	ldrb	r2, [r0]
	mov	r3, #253
	and	r3, r3, r2
	mov	r1, #128
	mov	r2, #128
	strb	r3, [r0]
	lsl	r1, r1, #10
	mov	r0, #13
	lsl	r2, r2, #9
	bl	__MapActor_SetSpeed
	mov	r1, #150
	mov	r0, #13
	lsl	r1, r1, #2
	mov	r2, #216
	bl	__Func_80921c4
	mov	r1, #150
	mov	r0, #13
	lsl	r1, r1, #2
	mov	r2, #248
	bl	__Func_80921c4
	mov	r1, #142
	mov	r2, #148
	mov	r0, #13
	lsl	r1, r1, #2
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r1, #0
	mov	r2, #0
	mov	r0, #13
	bl	__MapActor_SetPos
	mov	r0, #10
	bl	__MapActor_GetActor
	add	r0, r0, #35
	ldrb	r2, [r0]
	mov	r3, #2
	orr	r3, r3, r2
	strb	r3, [r0]
	ldr	r0, .L3+8
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	OvlFunc_905_20090c8
	.word	4911
	.word	2153
.Lfe1:
	.size	 OvlFunc_905_200915c,.Lfe1-OvlFunc_905_200915c

	.text
	.align	2, 0
