@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_905_2008a58
	.thumb_func
	.type	 OvlFunc_905_2008a58,function
OvlFunc_905_2008a58:
	push	{lr}
	mov	r1, #15
	bl	__Func_80929d8
	mov	r0, #0
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_905_2008a58,.Lfe1-OvlFunc_905_2008a58

	.text
	.align	2, 0
