@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_946_20099d8
	.thumb_func
	.type	 OvlFunc_946_20099d8,function
OvlFunc_946_20099d8:
	push	{lr}
	mov	r0, #12
	bl	OvlFunc_946_2009904
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_946_20099d8,.Lfe1-OvlFunc_946_20099d8

	.text
	.align	2, 0
