@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_946_200964c
	.thumb_func
	.type	 OvlFunc_946_200964c,function
OvlFunc_946_200964c:
	push	{lr}
	ldr	r0, .L3
	bl	__SetFlag
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	2245
.Lfe1:
	.size	 OvlFunc_946_200964c,.Lfe1-OvlFunc_946_200964c

	.text
	.align	2, 0
