@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_946_20092b4
	.thumb_func
	.type	 OvlFunc_946_20092b4,function
OvlFunc_946_20092b4:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r0, #8
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r5, r0
	ldr	r3, [r5, #8]
	asr	r3, r3, #20
	mov	r8, r3
	cmp	r3, #40
	bne	.L3
	ldr	r3, .L5
	mov	r2, #224
	lsl	r2, r2, #1
	add	r2, r2, r3
	mov	r3, #0
	ldrsh	r0, [r2, r3]
	mov	r9, r2
	ldr	r3, .L5+4
	ldr	r2, .L5+8
	sub	r2, r2, r3
	mov	sl, r2
	add	r0, r0, sl
	bl	__GetFlag
	mov	r7, r0
	cmp	r7, #0
	bne	.L3
	mov	r6, r5
	mov	r3, #3
	add	r6, r6, #85
	strb	r3, [r6]
	mov	r0, #8
	bl	__CutsceneWait
	mov	r0, #8
	bl	OvlFunc_946_2008e00
	mov	r0, #136
	bl	__PlaySound
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #8
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #8
	mov	r1, #3
	bl	__Func_8092b08
	strb	r7, [r6]
	mov	r1, r5
	add	r1, r1, #35
	ldrb	r2, [r1]
	mov	r3, #2
	orr	r3, r3, r2
	strb	r3, [r1]
	mov	r2, r8
	mov	r3, #10
	str	r2, [sp]
	str	r3, [sp, #4]
	mov	r0, #42
	mov	r2, #1
	mov	r3, #1
	mov	r1, #10
	bl	__Func_8010704
	mov	r2, r9
	mov	r3, #0
	ldrsh	r0, [r2, r3]
	add	r0, r0, sl
	bl	__SetFlag
.L3:
	add	sp, sp, #8
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	gState
	.word	_AREA_7e
	.word	2258
.Lfe1:
	.size	 OvlFunc_946_20092b4,.Lfe1-OvlFunc_946_20092b4

	.text
	.align	2, 0
