@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_946_2009a20
	.thumb_func
	.type	 OvlFunc_946_2009a20,function
OvlFunc_946_2009a20:
	push	{lr}
	mov	r0, #19
	bl	OvlFunc_946_2009904
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_946_2009a20,.Lfe1-OvlFunc_946_2009a20

	.text
	.align	2, 0
