@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_c_c_c_c_c_c_c_c_c_c_a_c_c_c_a_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_946_200a700
	.thumb_func
	.type	 OvlFunc_946_200a700,function
OvlFunc_946_200a700:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r0, #9
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	mov	r0, #9
	asr	r3, r3, #20
	mov	r8, r3
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	mov	r0, #19
	asr	r7, r3, #20
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	mov	r0, #14
	asr	r6, r3, #20
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	mov	r0, #16
	asr	r5, r3, #20
	bl	__MapActor_GetActor
	ldr	r3, [r0, #8]
	asr	r2, r3, #20
	cmp	r7, #19
	bne	.L3
	mov	r3, r6
	sub	r3, r3, #9
	cmp	r3, #2
	bhi	.L4
	mov	r2, #16
	b	.L35
.L4:
	mov	r3, r5
	sub	r3, r3, #9
	cmp	r3, #2
	bhi	.L6
	mov	r2, #64
	b	.L35
.L6:
	mov	r3, r2
	sub	r3, r3, #9
	cmp	r3, #2
	bhi	.L8
	mov	r2, #112
	b	.L35
.L8:
	mov	r2, #80
	neg	r2, r2
	mov	r0, #9
	mov	r1, #0
	bl	OvlFunc_946_2009774
	mov	r2, #96
	b	.L35
.L3:
	cmp	r7, #18
	bne	.L11
	mov	r3, r6
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L2
	mov	r3, r5
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L36
	mov	r3, r2
	sub	r3, r3, #9
	cmp	r3, #2
	bhi	.L15
	mov	r2, #96
	b	.L35
.L15:
	mov	r2, #96
	neg	r2, r2
	mov	r0, #9
	mov	r1, #0
	bl	OvlFunc_946_2009774
	mov	r2, #64
	b	.L35
.L11:
	cmp	r7, #15
	bne	.L18
	mov	r3, r5
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L2
	mov	r3, r2
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L36
	mov	r2, #112
	b	.L35
.L18:
	cmp	r7, #14
	bne	.L23
	mov	r3, r5
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L2
	mov	r3, r2
	sub	r3, r3, #9
	cmp	r3, #2
	bhi	.L25
	mov	r2, #32
	b	.L35
.L25:
	mov	r2, #96
	b	.L35
.L23:
	cmp	r7, #12
	bne	.L28
	mov	r3, r2
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L2
	mov	r2, #64
	b	.L35
.L28:
	cmp	r7, #11
	bne	.L31
	mov	r3, r2
	sub	r3, r3, #9
	cmp	r3, #2
	bls	.L2
.L36:
	mov	r2, #48
.L35:
	neg	r2, r2
	mov	r0, #9
	mov	r1, #0
	bl	OvlFunc_946_2009774
	b	.L10
.L31:
	cmp	r7, #9
	bls	.L2
.L10:
	mov	r0, #2
	bl	__WaitFrames
	mov	r0, #9
	bl	__MapActor_GetActor
	ldr	r3, [r0, #16]
	mov	r5, r8
	sub	r5, r5, #1
	asr	r3, r3, #20
	str	r3, [sp, #4]
	mov	r0, r5
	mov	r1, r7
	mov	r2, #3
	mov	r3, #1
	str	r5, [sp]
	bl	__Func_8010704
	mov	r0, #0
	mov	r1, #0
	mov	r2, #3
	mov	r3, #1
	str	r5, [sp]
	str	r7, [sp, #4]
	bl	__Func_8010704
.L2:
	add	sp, sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_946_200a700,.Lfe1-OvlFunc_946_200a700

	.text
	.align	2, 0
