@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_e90_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_923_2008fd0
	.thumb_func
	.type	 OvlFunc_923_2008fd0,function
OvlFunc_923_2008fd0:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200ad60
.Lfe1:
	.size	 OvlFunc_923_2008fd0,.Lfe1-OvlFunc_923_2008fd0

	.text
	.align	2, 0
