@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_1a3c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_923_2009fe8
	.thumb_func
	.type	 OvlFunc_923_2009fe8,function
OvlFunc_923_2009fe8:
	push	{r5, r6, r7, lr}
	ldr	r3, .L5
	ldr	r3, [r3]
	ldr	r6, [r3]
	ldr	r3, [r6]
	cmp	r3, #0
	beq	.L3
	mov	r7, #0
	str	r7, [r6]
	ldr	r0, .L5+4
	bl	__ClearFlag
	ldr	r5, [r6, #20]
	cmp	r5, #0
	beq	.L3
	mov	r3, r5
	add	r3, r3, #100
	strh	r7, [r3]
	ldr	r1, .L5+8
	mov	r0, r5
	bl	__Actor_SetScript
	mov	r0, r5
	mov	r1, #7
	bl	__Actor_SetAnim
	str	r7, [r6, #20]
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001edc
	.word	353
	.word	gScript_923__0200a7dc
.Lfe1:
	.size	 OvlFunc_923_2009fe8,.Lfe1-OvlFunc_923_2009fe8

	.text
	.align	2, 0
