@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_e90_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_923_2008e98
	.thumb_func
	.type	 OvlFunc_923_2008e98,function
OvlFunc_923_2008e98:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_923_2008e98,.Lfe1-OvlFunc_923_2008e98

	.text
	.align	2, 0
