@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_2008350
	.thumb_func
	.type	 OvlFunc_881_2008350,function
OvlFunc_881_2008350:
	push	{lr}
	add	r0, r0, #84
	ldrb	r2, [r0]
	mov	r1, #1
	mov	r3, r1
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L3
	ldr	r3, .L4
	ldr	r3, [r3]
	and	r3, r3, r1
	cmp	r3, #0
	beq	.L3
	mov	r3, #1
	eor	r3, r3, r2
	strb	r3, [r0]
.L3:
	mov	r0, #1
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001e40
.Lfe1:
	.size	 OvlFunc_881_2008350,.Lfe1-OvlFunc_881_2008350

	.text
	.align	2, 0
