@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_c_a_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200a768
	.thumb_func
	.type	 OvlFunc_881_200a768,function
OvlFunc_881_200a768:
	push	{r5, r6, r7, lr}
	ldr	r4, .L13
	mov	r3, #1
	neg	r3, r3
	ldr	r6, .L13+4
	mov	r0, r4
	mov	r7, #2
	mov	ip, r4
	mov	r1, #4
	mov	r2, #0
	mov	lr, r3
.L5:
	ldr	r3, [r2, r4]
	cmp	r3, #1
	bne	.L6
	ldrsh	r3, [r0, r1]
	cmp	r3, #138
	bne	.L6
	add	r3, r1, #4
	str	r7, [r0, r2]
	str	r6, [r0, r3]
	mov	r0, ip
.L6:
	ldr	r3, [r2, r4]
	cmp	r3, lr
	beq	.L4
	add	r1, r1, #12
	add	r2, r2, #12
	b	.L5
.L4:
	ldr	r0, .L13+8
	mov	r6, #192
	mov	r2, r0
	ldr	r4, .L13+12
	ldr	r5, .L13+16
	lsl	r6, r6, #6
	add	r2, r2, #8
	mov	r1, #0
.L9:
	ldrsh	r3, [r1, r0]
	cmp	r3, #57
	bne	.L11
	str	r4, [r2]
	str	r5, [r2, #8]
	strh	r6, [r2, #12]
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L11:
	add	r2, r2, #24
	add	r1, r1, #24
	b	.L9
.L14:
	.align	2, 0
.L13:
	.word	gOvl_0200e3f4
	.word	OvlFunc_881_200a858
	.word	.L5b84
	.word	395575296
	.word	222822400
.Lfe1:
	.size	 OvlFunc_881_200a768,.Lfe1-OvlFunc_881_200a768

	.text
	.align	2, 0
