@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200b448
	.thumb_func
	.type	 OvlFunc_881_200b448,function
OvlFunc_881_200b448:
	push	{r5, r6, lr}
	mov	r6, #0
	cmp	r0, #1
	beq	.L5
	cmp	r0, #1
	bcc	.L4
	cmp	r0, #2
	beq	.L6
	cmp	r0, #3
	beq	.L7
	b	.L3
.L4:
	ldr	r6, .L18
	b	.L3
.L5:
	ldr	r6, .L18+4
	b	.L3
.L6:
	ldr	r6, .L18+8
	b	.L3
.L17:
	ldr	r3, .L18+12
	lsl	r2, r5, #2
	ldr	r0, [r3, r2]
	b	.L2
.L7:
	mov	r6, #153
	lsl	r6, r6, #4
.L3:
	mov	r5, #0
.L13:
	add	r0, r6, r5
	bl	__GetFlag
	cmp	r0, #0
	bne	.L17
	add	r5, r5, #1
	cmp	r5, #8
	bls	.L13
	mov	r0, #0
.L2:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L19:
	.align	2, 0
.L18:
	.word	2348
	.word	2357
	.word	2327
	.word	.L6718
.Lfe1:
	.size	 OvlFunc_881_200b448,.Lfe1-OvlFunc_881_200b448

	.text
	.align	2, 0
