@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200b7d8
	.thumb_func
	.type	 OvlFunc_881_200b7d8,function
OvlFunc_881_200b7d8:
	push	{r5, lr}
	ldr	r3, .L16
	mov	r1, #193
	ldr	r3, [r3]
	lsl	r1, r1, #1
	add	r2, r3, r1
	mov	r1, #0
	ldrsh	r3, [r2, r1]
	cmp	r3, #99
	bne	.L3
	mov	r3, #0
	strh	r3, [r2]
.L3:
	mov	r0, #188
	lsl	r0, r0, #2
	bl	__ClearFlag
	ldr	r0, .L16+4
	bl	__SetFlag
	mov	r0, #190
	lsl	r0, r0, #2
	mov	r1, #0
	bl	__SetFlagByte
	mov	r0, #98
	mov	r1, #5
	bl	__Func_8091eb0
	ldr	r5, .L16+8
	ldr	r3, .L16+12
	add	r2, r5, r3
	mov	r3, #3
	strb	r3, [r2]
	mov	r0, #98
	mov	r1, #7
	bl	__Func_8091eb0
	mov	r1, #250
	lsl	r1, r1, #1
	add	r5, r5, r1
	ldr	r0, [r5]
	bl	__MapActor_GetActor
	mov	r3, #2
	add	r0, r0, #85
	strb	r3, [r0]
	pop	{r5}
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	iwram_3001ebc
	.word	753
	.word	gState
	.word	555
.Lfe1:
	.size	 OvlFunc_881_200b7d8,.Lfe1-OvlFunc_881_200b7d8

	.text
	.align	2, 0
