@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200bf88
	.thumb_func
	.type	 OvlFunc_881_200bf88,function
OvlFunc_881_200bf88:
	push	{r5, lr}
	mov	r5, r0
	ldr	r0, .L4
	ldr	r3, [r0]
	mov	r2, #1
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L3
	ldr	r0, [r0]
	mov	r1, #6
	lsr	r0, r0, #1
	bl	_umodsi3_RAM
	mov	r1, r0
	mov	r0, r5
	bl	__Actor_SetColorswap
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001e40
.Lfe1:
	.size	 OvlFunc_881_200bf88,.Lfe1-OvlFunc_881_200bf88

	.text
	.align	2, 0
