@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_881_200b41c
	.thumb_func
	.type	 OvlFunc_881_200b41c,function
OvlFunc_881_200b41c:
	push	{r5, r6, lr}
	mov	r0, #0
	bl	OvlFunc_881_200b448
	mov	r6, r0
	mov	r0, #2
	bl	OvlFunc_881_200b448
	add	r6, r6, r0
	mov	r0, #1
	bl	OvlFunc_881_200b448
	mov	r5, r0
	mov	r0, #3
	bl	OvlFunc_881_200b448
	add	r5, r5, r0
	sub	r6, r6, r5
	mov	r0, r6
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_881_200b41c,.Lfe1-OvlFunc_881_200b41c

	.text
	.align	2, 0
