@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_951_2008e44
	.thumb_func
	.type	 OvlFunc_951_2008e44,function
OvlFunc_951_2008e44:
	push	{r5, lr}
	mov	r5, r1
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L3
	mov	r3, r0
	add	r3, r3, #84
	strb	r5, [r3]
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_951_2008e44,.Lfe1-OvlFunc_951_2008e44

	.text
	.align	2, 0
