@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_971_2009228
	.thumb_func
	.type	 OvlFunc_971_2009228,function
OvlFunc_971_2009228:
	push	{r5, lr}
	mov	r0, #85
	bl	__PlaySound
	ldr	r0, .L11
	mov	r1, #5
	mov	r2, #4
	mov	r3, #1
	bl	__Func_8017658
	mov	r5, r0
	b	.L3
.L5:
	mov	r0, #1
	bl	__WaitFrames
.L3:
	bl	__Func_8017364
	cmp	r0, #0
	beq	.L5
	bl	__Func_801faa8
	mov	r0, r5
	mov	r1, #1
	bl	__CloseUIBox
	mov	r0, #1
	bl	__WaitFrames
	ldr	r0, .L11+4
	mov	r1, #5
	mov	r2, #4
	mov	r3, #1
	bl	__Func_8017658
	mov	r5, r0
	b	.L7
.L9:
	mov	r0, #1
	bl	__WaitFrames
.L7:
	bl	__Func_8017364
	cmp	r0, #0
	beq	.L9
	mov	r0, r5
	mov	r1, #1
	bl	__CloseUIBox
	pop	{r5}
	pop	{r1}
	bx	r1
.L12:
	.align	2, 0
.L11:
	.word	10540
	.word	10541
.Lfe1:
	.size	 OvlFunc_971_2009228,.Lfe1-OvlFunc_971_2009228

	.text
	.align	2, 0
