@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_919_2008048
	.thumb_func
	.type	 OvlFunc_919_2008048,function
OvlFunc_919_2008048:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_919_2008048,.Lfe1-OvlFunc_919_2008048

	.text
	.align	2, 0
