@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_919_20080d8
	.thumb_func
	.type	 OvlFunc_919_20080d8,function
OvlFunc_919_20080d8:
	push	{lr}
	mov	r0, #0
	mov	r1, #5
	bl	OvlFunc_919_200805c
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_919_20080d8,.Lfe1-OvlFunc_919_20080d8

	.text
	.align	2, 0
