@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_79460_c_c_c_c_a_c_c_a_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8079bf8
	.thumb_func
	.type	 Func_8079bf8,function
Func_8079bf8:
	push	{r5, r6, lr}
	mov	r5, r0
	sub	r5, r5, r1
	mov	r6, r2
	mov	r0, r3
	cmp	r5, #0
	bge	.L3
	mov	r5, #0
.L3:
	mov	r1, #1
	bl	Func_8079b24
	lsl	r3, r6, #1
	add	r3, r5, r3
	mul	r0, r0, r3
	cmp	r0, #0
	bge	.L4
	ldr	r3, .L6
	add	r0, r0, r3
.L4:
	asr	r0, r0, #9
	cmp	r0, #0
	bge	.L5
	mov	r0, #0
.L5:
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	511
.Lfe1:
	.size	 Func_8079bf8,.Lfe1-Func_8079bf8

	.text
	.align	2, 0
