@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_79460_c_c_c_c_a_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetDjinniInfo
	.thumb_func
	.type	 GetDjinniInfo,function
GetDjinniInfo:
	push	{lr}
	mov	r3, #0
	cmp	r0, #3
	bhi	.L3
	cmp	r1, #19
	bhi	.L3
	lsl	r3, r0, #2
	add	r3, r3, r0
	lsl	r3, r3, #2
	add	r3, r3, r1
.L3:
	lsl	r0, r3, #1
	add	r0, r0, r3
	ldr	r3, .L4
	lsl	r0, r0, #2
	add	r0, r0, r3
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	.L8926c
.Lfe1:
	.size	 GetDjinniInfo,.Lfe1-GetDjinniInfo

	.text
	.align	2, 0
