@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_79460_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_807a628
	.thumb_func
	.type	 Func_807a628,function
Func_807a628:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r7, r0
	mov	r8, r1
	bl	GetUnit
	mov	r1, r8
	mov	r5, r0
	mov	r0, r7
	bl	GiveItemTo
	mov	r6, #0
	add	r5, r5, #216
.L5:
	ldrh	r3, [r5]
	add	r5, r5, #2
	cmp	r3, r8
	bne	.L6
	mov	r0, r7
	mov	r1, r6
	bl	EquipItem
.L6:
	add	r6, r6, #1
	cmp	r6, #14
	ble	.L5
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_807a628,.Lfe1-Func_807a628

	.text
	.align	2, 0
