@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_78b9c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GiveInnateMove
	.thumb_func
	.type	 GiveInnateMove,function
GiveInnateMove:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	mov	r7, r0
	bl	GetUnit
	ldr	r3, .L23
	mov	r5, r0
	mov	r0, #88
	mov	ip, r3
	and	r6, r6, r3
	ldrh	r3, [r0, r5]
	mov	r2, ip
	mov	r4, #1
	and	r2, r2, r3
	neg	r4, r4
	mov	r1, #0
	cmp	r2, r6
	bne	.L5
	strh	r2, [r0, r5]
	mov	r4, #0
	b	.L4
.L5:
	add	r1, r1, #1
	add	r0, r0, #4
	cmp	r1, #30
	bgt	.L4
	ldrh	r3, [r0, r5]
	mov	r2, ip
	and	r2, r2, r3
	cmp	r2, r6
	bne	.L5
	strh	r2, [r0, r5]
	mov	r4, r1
.L4:
	cmp	r4, #0
	bge	.L9
	mov	r2, #88
	ldrh	r3, [r5, r2]
	mov	r1, #0
	cmp	r3, #0
	bne	.L12
	strh	r6, [r5, r2]
	mov	r4, #0
	b	.L11
.L12:
	add	r1, r1, #1
	cmp	r1, #30
	bgt	.L11
	lsl	r3, r1, #2
	mov	r2, r3
	add	r2, r2, #88
	ldrh	r3, [r5, r2]
	cmp	r3, #0
	bne	.L12
	strh	r6, [r5, r2]
	mov	r4, r1
.L11:
	cmp	r4, #0
	bge	.L9
	mov	r0, #1
	neg	r0, r0
	b	.L2
.L9:
	mov	r0, r7
	bl	Func_8078bf0
	mov	r3, #88
	ldrh	r3, [r5, r3]
	mov	r1, #0
	cmp	r3, r6
	beq	.L18
	mov	r0, r5
	add	r0, r0, #88
.L19:
	add	r1, r1, #1
	cmp	r1, #31
	bgt	.L18
	add	r0, r0, #4
	ldrh	r3, [r0]
	cmp	r3, r6
	bne	.L19
.L18:
	mov	r0, r1
.L2:
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L24:
	.align	2, 0
.L23:
	.word	16383
.Lfe1:
	.size	 GiveInnateMove,.Lfe1-GiveInnateMove

	.text
	.align	2, 0
