@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_79460_c_c_c_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetNumDjinn
	.thumb_func
	.type	 GetNumDjinn,function
GetNumDjinn:
	push	{r5, r6, r7, lr}
	sub	sp, sp, #36
	add	r6, sp, #4
	mov	r7, r0
	mov	r0, r6
	mov	r5, #0
	bl	Func_80796c4
	cmp	r5, r0
	bge	.L10
	mov	r1, r6
	mov	r6, r0
.L6:
	ldrh	r0, [r1]
	add	r1, r1, #2
	str	r1, [sp]
	bl	GetUnit
	mov	r2, r0
	mov	r0, #1
	neg	r0, r0
	ldr	r1, [sp]
	cmp	r7, r0
	bne	.L7
	mov	r0, #140
	lsl	r0, r0, #1
	add	r3, r2, r0
	ldrb	r3, [r3]
	add	r0, r0, #1
	add	r5, r5, r3
	add	r3, r2, r0
	ldrb	r3, [r3]
	add	r0, r0, #1
	add	r5, r5, r3
	add	r3, r2, r0
	ldrb	r3, [r3]
	add	r0, r0, #1
	add	r5, r5, r3
	add	r3, r2, r0
	ldrb	r3, [r3]
	b	.L11
.L7:
	mov	r0, #140
	lsl	r0, r0, #1
	add	r3, r7, r0
	ldrb	r3, [r2, r3]
.L11:
	add	r5, r5, r3
	sub	r6, r6, #1
	cmp	r6, #0
	bne	.L6
.L10:
	mov	r0, r5
	add	sp, sp, #36
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 GetNumDjinn,.Lfe1-GetNumDjinn

	.text
	.align	2, 0
