@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_79338_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetFlag
	.thumb_func
	.type	 GetFlag,function
GetFlag:
	mov	r3, #7
	and	r3, r3, r0
	mov	r2, #1
	lsl	r2, r2, r3
	lsl	r3, r0, #20
	.code	16
	lsr	r0, r3, #23
	ldr	r3, .L3
	ldrb	r3, [r3, r0]
	and	r3, r3, r2
	neg	r0, r3
	orr	r0, r0, r3
	lsr	r0, r0, #31
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gFlags
.Lfe1:
	.size	 GetFlag,.Lfe1-GetFlag
	.align	2, 0
	.global	SetFlag
	.thumb_func
	.type	 SetFlag,function
SetFlag:
	mov	r3, #7
	and	r3, r3, r0
	mov	r2, #1
	ldr	r1, .L6
	.code	16
	lsl	r2, r2, r3
	lsl	r3, r0, #20
	.code	16
	lsr	r0, r3, #23
	ldrb	r3, [r1, r0]
	orr	r2, r2, r3
	strb	r2, [r1, r0]
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	gFlags
.Lfe2:
	.size	 SetFlag,.Lfe2-SetFlag
	.align	2, 0
	.global	ClearFlag
	.thumb_func
	.type	 ClearFlag,function
ClearFlag:
	mov	r3, #7
	and	r3, r3, r0
	mov	r2, #1
	lsl	r2, r2, r3
	ldr	r1, .L9
	lsl	r3, r0, #20
	.code	16
	lsr	r0, r3, #23
	ldrb	r3, [r1, r0]
	bic	r3, r3, r2
	strb	r3, [r1, r0]
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	gFlags
.Lfe3:
	.size	 ClearFlag,.Lfe3-ClearFlag

	.text
	.align	2, 0
