@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_918_2009224
	.thumb_func
	.type	 OvlFunc_918_2009224,function
OvlFunc_918_2009224:
	ldr	r2, .L10
	mov	r0, #160
	ldr	r1, [r2]
	ldr	r3, .L10+4
	lsl	r0, r0, #19
	ldr	r2, .L10+8
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	bx	lr
.L11:
	.align	2, 0
.L10:
	.word	iwram_3001ed0
	.word	67109076
	.word	-2080374672
.Lfe1:
	.size	 OvlFunc_918_2009224,.Lfe1-OvlFunc_918_2009224

	.text
	.align	2, 0
