@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_17ec_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_918_200984c
	.thumb_func
	.type	 OvlFunc_918_200984c,function
OvlFunc_918_200984c:
	push	{lr}
	ldr	r0, .L3
	bl	__StopTask
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	OvlFunc_918_2009244
.Lfe1:
	.size	 OvlFunc_918_200984c,.Lfe1-OvlFunc_918_200984c

	.text
	.align	2, 0
