@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_949_200859c
	.thumb_func
	.type	 OvlFunc_949_200859c,function
OvlFunc_949_200859c:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	bl	__MessageID
	mov	r0, #27
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	8099
.Lfe1:
	.size	 OvlFunc_949_200859c,.Lfe1-OvlFunc_949_200859c

	.text
	.align	2, 0
