@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_200a290
	.thumb_func
	.type	 OvlFunc_948_200a290,function
OvlFunc_948_200a290:
	push	{r5, lr}
	mov	r0, #8
	bl	__MapActor_GetActor
	mov	r5, #1
	add	r0, r0, #89
	strb	r5, [r0]
	mov	r0, #9
	bl	__MapActor_GetActor
	add	r0, r0, #89
	strb	r5, [r0]
	mov	r0, #10
	bl	__MapActor_GetActor
	add	r0, r0, #89
	strb	r5, [r0]
	mov	r0, #11
	bl	__MapActor_GetActor
	add	r0, r0, #89
	strb	r5, [r0]
	mov	r0, #8
	bl	__MapActor_GetActor
	ldr	r5, .L3
	str	r5, [r0, #24]
	mov	r0, #9
	bl	__MapActor_GetActor
	str	r5, [r0, #24]
	mov	r0, #10
	bl	__MapActor_GetActor
	str	r5, [r0, #24]
	mov	r0, #11
	bl	__MapActor_GetActor
	str	r5, [r0, #24]
	mov	r0, #12
	bl	__MapActor_GetActor
	mov	r1, #200
	str	r5, [r0, #24]
	lsl	r1, r1, #4
	ldr	r0, .L3+4
	bl	__StartTask
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L3+8
	bl	__StartTask
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L3+12
	bl	__StartTask
	ldr	r2, .L3+16
	ldr	r3, .L3+20
	strh	r2, [r3]
	ldr	r2, .L3+24
	add	r3, r3, #2
	strh	r2, [r3]
	pop	{r5}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	45875
	.word	OvlFunc_948_20097ac
	.word	OvlFunc_948_200941c
	.word	OvlFunc_948_2009308
	.word	16194
	.word	67108944
	.word	1543
.Lfe1:
	.size	 OvlFunc_948_200a290,.Lfe1-OvlFunc_948_200a290

	.text
	.align	2, 0
