@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_2009bc4
	.thumb_func
	.type	 OvlFunc_948_2009bc4,function
OvlFunc_948_2009bc4:
	push	{lr}
	ldr	r0, .L5
	sub	sp, sp, #8
	bl	__StopTask
	mov	r0, #14
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	ldr	r0, .L5+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r3, #45
	mov	r2, #43
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #58
	mov	r1, #36
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	b	.L4
.L3:
	mov	r3, #45
	mov	r2, #43
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #46
	mov	r1, #43
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
.L4:
	bl	OvlFunc_948_2009ec0
	ldr	r0, .L5+8
	bl	__SetFlag
	add	sp, sp, #8
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	OvlFunc_948_2009e94
	.word	519
	.word	518
.Lfe1:
	.size	 OvlFunc_948_2009bc4,.Lfe1-OvlFunc_948_2009bc4

	.text
	.align	2, 0
