@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_200a188
	.thumb_func
	.type	 OvlFunc_948_200a188,function
OvlFunc_948_200a188:
	push	{lr}
	mov	r0, #1
	bl	__WaitFrames
	mov	r0, #12
	mov	r1, #243
	bl	OvlFunc_948_200a0c4
	mov	r0, #11
	mov	r1, #244
	bl	OvlFunc_948_200a0c4
	mov	r0, #10
	mov	r1, #244
	bl	OvlFunc_948_200a0c4
	mov	r0, #9
	mov	r1, #244
	bl	OvlFunc_948_200a0c4
	mov	r0, #8
	mov	r1, #244
	bl	OvlFunc_948_200a0c4
	ldr	r0, .L12
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	mov	r1, #232
	mov	r2, #218
	mov	r0, #8
	lsl	r1, r1, #16
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
.L3:
	ldr	r0, .L12+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L4
	mov	r1, #148
	mov	r2, #206
	mov	r0, #9
	lsl	r1, r1, #17
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
.L4:
	ldr	r0, .L12+8
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	mov	r1, #164
	mov	r2, #190
	mov	r0, #10
	lsl	r1, r1, #17
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
.L5:
	ldr	r0, .L12+12
	bl	__GetFlag
	cmp	r0, #0
	bne	.L6
	mov	r1, #180
	mov	r2, #218
	mov	r0, #11
	lsl	r1, r1, #17
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
.L6:
	mov	r0, #156
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	mov	r0, #0
	bl	OvlFunc_948_2008f40
.L7:
	ldr	r0, .L12+16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L8
	mov	r0, #1
	bl	OvlFunc_948_2008f40
.L8:
	ldr	r0, .L12+20
	bl	__GetFlag
	cmp	r0, #0
	beq	.L9
	mov	r0, #2
	bl	OvlFunc_948_2008f40
.L9:
	ldr	r0, .L12+24
	bl	__GetFlag
	cmp	r0, #0
	beq	.L10
	mov	r0, #3
	bl	OvlFunc_948_2008f40
.L10:
	ldr	r0, .L12+28
	bl	__GetFlag
	cmp	r0, #0
	beq	.L11
	mov	r0, #0
	bl	OvlFunc_948_2008fdc
.L11:
	pop	{r0}
	bx	r0
.L13:
	.align	2, 0
.L12:
	.word	3815
	.word	3816
	.word	3817
	.word	3818
	.word	2497
	.word	2498
	.word	2499
	.word	2500
.Lfe1:
	.size	 OvlFunc_948_200a188,.Lfe1-OvlFunc_948_200a188

	.text
	.align	2, 0
