@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_c_a_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_948_2008e50
	.thumb_func
	.type	 OvlFunc_948_2008e50,function
OvlFunc_948_2008e50:
	push	{r5, r6, lr}
	ldr	r3, .L5
	ldr	r0, .L5+4
	ldr	r5, [r3]
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr	r2, .L5+8
	ldr	r3, .L5+12
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #15
	beq	.L3
	mov	r2, #182
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r0, #15
	mov	r2, #0
	ldrsh	r5, [r3, r2]
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #48]
	mov	r0, #15
	str	r3, [r6, #48]
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r3, [r0, #48]
	sub	r5, r5, #30
	str	r3, [r6, #52]
	ldr	r2, .L5+16
	lsl	r5, r5, #3
	add	r3, r5, #4
	ldr	r1, [r2, r5]
	mov	r0, #15
	ldr	r2, [r2, r3]
	bl	__Func_809218c
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001ebc
	.word	2506
	.word	586
	.word	gState
	.word	.L2808
.Lfe1:
	.size	 OvlFunc_948_2008e50,.Lfe1-OvlFunc_948_2008e50

	.text
	.align	2, 0
