@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_200d5a4
	.thumb_func
	.type	 OvlFunc_883_200d5a4,function
OvlFunc_883_200d5a4:
	push	{lr}
	bl	__Func_8097194
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_883_200d5a4,.Lfe1-OvlFunc_883_200d5a4

	.text
	.align	2, 0
