@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_200d8f0
	.thumb_func
	.type	 OvlFunc_883_200d8f0,function
OvlFunc_883_200d8f0:
	push	{r5, r6, lr}
	mov	r6, r0
	sub	sp, sp, #12
	mov	r0, r1
	mov	r1, r2
	cmp	r6, #0
	beq	.L3
	ldr	r3, [r6, #8]
	mov	r5, sp
	str	r3, [r5]
	ldr	r3, [r6, #12]
	str	r3, [r5, #4]
	ldr	r3, [r6, #16]
	mov	r2, r5
	str	r3, [r5, #8]
	bl	__vec3_translate
	ldr	r1, [r5]
	ldr	r2, [r5, #4]
	ldr	r3, [r5, #8]
	mov	r0, r6
	bl	__Actor_TravelTo
.L3:
	add	sp, sp, #12
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_883_200d8f0,.Lfe1-OvlFunc_883_200d8f0

	.text
	.align	2, 0
