@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_883_200d600
	.thumb_func
	.type	 OvlFunc_883_200d600,function
OvlFunc_883_200d600:
	push	{lr}
	mov	r0, #25
	bl	__MapActor_GetActor
	bl	OvlFunc_883_200dc98
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_883_200d600,.Lfe1-OvlFunc_883_200d600

	.text
	.align	2, 0
