@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"common2_c_c_c_c_c_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common2_41c
	.thumb_func
	.type	 OvlFunc_common2_41c,function
OvlFunc_common2_41c:
	push	{r4, r5, r6, lr}
	mov	r6, r2
	cmp	r6, #0
	beq	.L2
	mov	r3, #32
	sub	r3, r3, r6
	cmp	r3, #0
	bgt	.L4
	neg	r3, r3
	mov	r4, r1
	mov	r5, #0
	lsr	r4, r4, r3
	b	.L5
.L4:
	mov	r2, r1
	lsl	r2, r2, r3
	mov	r3, r0
	lsr	r3, r3, r6
	mov	r5, r1
	mov	r4, r3
	lsr	r5, r5, r6
	orr	r4, r4, r2
.L5:
	add	r1, r5, #0
	add	r0,  r4,  #0
.L2:
	pop	{r4, r5, r6, pc}
.Lfe1:
	.size	 OvlFunc_common2_41c,.Lfe1-OvlFunc_common2_41c
	.align	2, 0
	.global	OvlFunc_common2_44c
	.thumb_func
	.type	 OvlFunc_common2_44c,function
OvlFunc_common2_44c:
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r4, r0
	ldr	r3, [r4, #4]
	sub	sp, sp, #8
	ldr	r5, [r4, #12]
	ldr	r6, [r4, #16]
	mov	sl, r3
	mov	r7, #0
	bl	OvlFunc_common2_5e8
	cmp	r0, #0
	beq	.L7
	ldr	r2, .L33+4
	ldr	r1, .L33
	mov	r4, r6
	mov	r3, r5
	orr	r4, r4, r2
	ldr	r7, .L33+8
	b	.L29
.L7:
	mov	r0, r4
	bl	OvlFunc_common2_5f8
	cmp	r0, #0
	bne	.L30
	mov	r0, r4
	bl	OvlFunc_common2_608
	cmp	r0, #0
	beq	.L11
	mov	r5, #0
	mov	r6, #0
	b	.L8
.L11:
	mov	r3, r6
	orr	r3, r3, r5
	cmp	r3, #0
	beq	.L8
	ldr	r0, [r4, #8]
	ldr	r2, .L33+12
	cmp	r0, r2
	bge	.L14
	sub	r2, r2, r0
	cmp	r2, #56
	ble	.L15
	mov	r5, #0
	mov	r6, #0
	b	.L16
.L15:
	mov	r3, #0
	mov	r8, r3
	mov	r3, #1
	lsl	r3, r3, r2
	sub	r3, r3, #1
	asr	r4, r3, #31
	and	r4, r4, r6
	and	r3, r3, r5
	orr	r3, r3, r4
	cmp	r3, #0
	beq	.L17
	mov	r3, #1
	mov	r8, r3
.L17:
	add	r1, r6, #0
	add	r0,  r5,  #0
	bl	OvlFunc_common2_41c
	mov	r4, #0
	mov	r3, r8
	mov	r5, r0
	mov	r6, r1
	orr	r5, r5, r3
	orr	r6, r6, r4
.L16:
	mov	r3, #255
	mov	r1, r5
	and	r1, r1, r3
	mov	r2, #0
	cmp	r1, #128
	bne	.L18
	cmp	r2, #0
	bne	.L18
	add	r3, r3, #1
	mov	r1, r5
	and	r1, r1, r3
	mov	r3, r2
	orr	r3, r3, r1
	cmp	r3, #0
	beq	.L20
	mov	r3, #128
	mov	r4, #0
	b	.L31
.L18:
	mov	r3, #127
	mov	r4, #0
.L31:
	add	r5, r5, r3
	adc	r6, r6, r4
.L20:
	ldr	r3, .L33+16
	cmp	r6, r3
	bls	.L28
	mov	r7, #1
	b	.L28
.L14:
	mov	r3, #128
	lsl	r3, r3, #3
	cmp	r0, r3
	blt	.L23
.L30:
	ldr	r7, .L33+8
	mov	r5, #0
	mov	r6, #0
	b	.L8
.L23:
	ldr	r3, .L33+20
	mov	r1, r5
	add	r7, r0, r3
	mov	r3, #255
	and	r1, r1, r3
	mov	r2, #0
	cmp	r1, #128
	bne	.L25
	cmp	r2, #0
	bne	.L25
	add	r3, r3, #1
	mov	r1, r5
	and	r1, r1, r3
	mov	r3, r2
	orr	r3, r3, r1
	cmp	r3, #0
	beq	.L27
	mov	r3, #128
	mov	r4, #0
	b	.L32
.L34:
	.align	2, 0
.L33:
	.word	0
	.word	524288
	.word	2047
	.word	-1022
	.word	268435455
	.word	1023
.L25:
	mov	r3, #127
	mov	r4, #0
.L32:
	add	r5, r5, r3
	adc	r6, r6, r4
.L27:
	ldr	r3, .L35+4
	cmp	r6, r3
	bls	.L28
	lsl	r1, r6, #31
	lsr	r2, r5, #1
	mov	r3, r1
	orr	r3, r3, r2
	lsr	r4, r6, #1
	add	r6, r4, #0
	add	r5,  r3,  #0
	add	r7, r7, #1
.L28:
	lsl	r1, r6, #24
	lsr	r2, r5, #8
	mov	r3, r1
	orr	r3, r3, r2
	lsr	r4, r6, #8
.L29:
	add	r6, r4, #0
	add	r5,  r3,  #0
.L8:
	mov	r0, sp
	ldr	r3, [r0, #4]
	ldr	r2, .L35+8
	ldr	r1, .L35+12
	and	r3, r3, r2
	and	r1, r1, r6
	orr	r3, r3, r1
	str	r3, [r0, #4]
	ldrh	r3, .L35
	ldrh	r2, [r0, #6]
	and	r7, r7, r3
	ldr	r3, .L35+16
	lsl	r1, r7, #4
	and	r3, r3, r2
	orr	r3, r3, r1
	strh	r3, [r0, #6]
	mov	r3, sl
	ldrb	r2, [r0, #7]
	lsl	r1, r3, #7
	mov	r3, #127
	and	r3, r3, r2
	orr	r3, r3, r1
	strb	r3, [r0, #7]
	ldr	r3, [r0, #4]
	str	r5, [r0, #4]
	str	r3, [r0]
	ldr	r1, [r0, #4]
	ldr	r0, [r0]
	add	sp, sp, #8
	b	.L36
.L37:
	.align	2, 0
.L35:
	.word	2047
	.word	536870911
	.word	-1048576
	.word	1048575
	.word	-32753
.L36:
	pop	{r3, r4}
	mov	r8, r3
	mov	sl, r4
	pop	{r4, r5, r6, r7, pc}
.Lfe2:
	.size	 OvlFunc_common2_44c,.Lfe2-OvlFunc_common2_44c

	.text
	.align	2, 0
