@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"common1_c_a_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common1_1814
	.thumb_func
	.type	 OvlFunc_common1_1814,function
OvlFunc_common1_1814:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r3, .L15
	mov	sl, r0
	ldr	r0, .L15+4
	mov	r8, r1
	ldr	r5, [r3]
	bl	__GetFlag
	ldr	r3, .L15+8
	mov	r7, r0
	mov	r0, #250
	lsl	r0, r0, #1
	add	r3, r3, r0
	ldr	r0, [r3]
	bl	__MapActor_GetActor
	mov	r3, r5
	mov	r6, r0
	add	r3, r3, #232
	ldr	r2, [r3]
	mov	r0, #192
	ldr	r3, [r6, #8]
	lsl	r0, r0, #12
	add	r1, r2, r0
	cmp	r2, r3
	blt	.L4
	ldr	r3, .L15+12
	add	r1, r2, r3
.L4:
	cmp	r7, #0
	beq	.L5
	mov	r3, r5
	add	r3, r3, #236
	ldr	r3, [r3]
	mov	r0, #128
	lsl	r0, r0, #13
	add	r4, r3, r0
	mov	r3, r5
	add	r3, r3, #228
	b	.L14
.L5:
	mov	r3, r5
	add	r3, r3, #236
	ldr	r3, [r3]
	ldr	r2, .L15+16
	add	r4, r3, r2
	mov	r3, r5
	add	r3, r3, #226
.L14:
	ldrh	r3, [r3]
	mov	r5, r6
	add	r5, r5, #100
	strh	r3, [r5]
	mov	r3, #128
	lsl	r3, r3, #7
	str	r3, [r6, #52]
	mov	r3, #128
	lsl	r3, r3, #9
	mov	r2, #0
	str	r3, [r6, #48]
	mov	r0, r6
	mov	r3, r4
	bl	__Actor_TravelTo
	ldr	r0, .L15+4
	bl	__SetFlag
	mov	r0, r6
	ldr	r1, .L15+20
	bl	__Actor_SetScript
	mov	r0, #0
	ldrsh	r3, [r5, r0]
	cmp	r3, #0
	beq	.L13
.L9:
	mov	r0, #1
	bl	__WaitFrames
	mov	r2, #0
	ldrsh	r3, [r5, r2]
	cmp	r3, #0
	bne	.L9
.L13:
	cmp	r7, #0
	bne	.L11
	mov	r1, sl
	mov	r0, #0
	bl	OvlFunc_common1_850
	mov	r0, sl
	mov	r1, #2
	bl	__Func_8019908
	b	.L12
.L11:
	mov	r1, r8
	mov	r0, #0
	bl	OvlFunc_common1_850
	mov	r0, r8
	mov	r1, #2
	bl	__Func_8019908
.L12:
	ldr	r3, .L15+8
	mov	r0, #250
	lsl	r0, r0, #1
	add	r3, r3, r0
	ldr	r0, [r3]
	mov	r1, #1
	bl	__Func_8019908
	mov	r1, #3
	ldr	r0, .L15+24
	bl	__Func_801776c
	mov	r0, r6
	bl	__Actor_WaitScript
	mov	r0, r7
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	iwram_3001f3c
	.word	529
	.word	gState
	.word	-786432
	.word	-1048576
	.word	_TBL_L16
	.word	2410
.Lfe1:
	.size	 OvlFunc_common1_1814,.Lfe1-OvlFunc_common1_1814

	.text
	.align	2, 0
