@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"common2_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common2_380
	.thumb_func
	.type	 OvlFunc_common2_380,function
OvlFunc_common2_380:
	push	{r4, lr}
	sub	sp, sp, #28
	mov	r3, sp
	add	r4, sp, #8
	str	r0, [r3]
	str	r1, [r3, #4]
	mov	r0, r3
	mov	r1, r4
	bl	OvlFunc_common2_618
	mov	r0, r4
	bl	OvlFunc_common2_40c
	cmp	r0, #0
	bne	.L13
	mov	r0, r4
	bl	OvlFunc_common2_3ec
	cmp	r0, #0
	beq	.L4
.L13:
	mov	r0, #0
	b	.L2
.L4:
	mov	r0, r4
	bl	OvlFunc_common2_3fc
	cmp	r0, #0
	bne	.L5
	ldr	r3, [r4, #8]
	mov	r0, #0
	cmp	r3, #0
	blt	.L2
	cmp	r3, #30
	ble	.L8
.L5:
	ldr	r3, [r4, #4]
	neg	r0, r3
	orr	r0, r0, r3
	ldr	r3, .L14
	lsr	r0, r0, #31
	add	r0, r0, r3
	b	.L2
.L8:
	mov	r2, #60
	sub	r2, r2, r3
	ldr	r0, [r4, #12]
	ldr	r1, [r4, #16]
	bl	OvlFunc_common2_41c
	ldr	r3, [r4, #4]
	cmp	r3, #0
	beq	.L2
	neg	r0, r0
.L2:
	add	sp, sp, #28
	pop	{r4, pc}
.L15:
	.align	2, 0
.L14:
	.word	2147483647
.Lfe1:
	.size	 OvlFunc_common2_380,.Lfe1-OvlFunc_common2_380

	.text
	.align	2, 0
