@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"common1_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common1_1578
	.thumb_func
	.type	 OvlFunc_common1_1578,function
OvlFunc_common1_1578:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	mov	r7, r2
	bl	__GetFieldActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L3
	mov	r3, #128
	lsl	r3, r3, #10
	str	r3, [r5, #48]
	asr	r3, r3, #1
	str	r3, [r5, #52]
	.code	16
	mov	r3, r5
	mov	r2, #0
	.code	16
	add	r3, r3, #91
	strb	r2, [r3]
	bl	__Actor_Stop
	mov	r0, r5
	mov	r1, #5
	bl	__Actor_SetAnim
	lsl	r1, r6, #16
	ldr	r2, [r5, #12]
	lsl	r3, r7, #16
	mov	r0, r5
	bl	__Actor_TravelTo
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_common1_1578,.Lfe1-OvlFunc_common1_1578

	.text
	.align	2, 0
