@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"common1_a_a_a_a_c_c_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_common1_88c
	.thumb_func
	.type	 OvlFunc_common1_88c,function
OvlFunc_common1_88c:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r5, r0
	mov	r0, #229
	lsl	r0, r0, #5
	bl	__Func_8004970
	ldr	r7, .L16
	mov	r2, #0
	ldrsh	r3, [r7, r2]
	mov	r2, #1
	neg	r2, r2
	mov	r6, r0
	cmp	r3, r2
	bne	.L10
	bl	__AllocSpriteSlot
	strh	r0, [r7]
.L10:
	ldr	r3, .L16+4
	ldrb	r3, [r3, r5]
	mov	r8, r3
	cmp	r5, #8
	bne	.L11
	mov	r5, #4
.L11:
	ldr	r0, .L16+8
	bl	__GetFile
	mov	r1, r6
	bl	__DecompressLZ
	mov	r2, r8
	add	r0, r6, r2
	ldr	r3, .L16+12
	ldr	r1, .L16+16
	ldr	r2, .L16+20
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	lsl	r2, r5, #10
	add	r2, r2, r6
	mov	r1, #128
	add	r2, r2, #160
	lsl	r1, r1, #3
	mov	r3, #0
	ldrsh	r0, [r7, r3]
	bl	__UploadSpriteGFX
	mov	r2, #128
	ldr	r1, .L16+12
	lsl	r2, r2, #24
.L15:
	ldr	r3, [r1, #8]
	and	r3, r3, r2
	cmp	r3, #0
	bne	.L15
	mov	r0, r6
	bl	__free
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L17:
	.align	2, 0
.L16:
	.word	_TBL_L10
	.word	.L1
	.word	_FILE_e7
	.word	67109076
	.word	83887072
	.word	-2080374776
.Lfe1:
	.size	 OvlFunc_common1_88c,.Lfe1-OvlFunc_common1_88c

	.text
	.align	2, 0
