@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_a_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_952_200a014
	.thumb_func
	.type	 OvlFunc_952_200a014,function
OvlFunc_952_200a014:
	push	{r5, lr}
	mov	r0, #30
	bl	__PlaySound
	bl	__CutsceneStart
	ldr	r0, .L22
	bl	__MessageID
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	mov	r0, #216
	mov	r1, #1
	mov	r2, #184
	mov	r3, #1
	lsl	r2, r2, #18
	neg	r1, r1
	lsl	r0, r0, #16
	bl	__Func_80933f8
	bl	__Func_8093530
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #14
	ldr	r1, .L22+4
	ldr	r2, .L22+8
	bl	__MapActor_SetSpeed
	mov	r2, #16
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8092304
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #1
	mov	r0, #0
	bl	__SetCameraTarget
	bl	__Func_8093530
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #128
	mov	r0, #0
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r2, #190
	mov	r1, #208
	lsl	r2, r2, #2
	mov	r0, #0
	bl	__Func_80921c4
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #216
	mov	r1, #1
	mov	r2, #184
	lsl	r0, r0, #16
	neg	r1, r1
	lsl	r2, r2, #18
	mov	r3, #1
	bl	__Func_80933f8
	mov	r1, #16
	mov	r3, #192
	mov	r0, #1
	neg	r1, r1
	mov	r2, #16
	lsl	r3, r3, #8
	bl	__Func_809233c
	mov	r3, #192
	mov	r0, #3
	mov	r1, #0
	mov	r2, #24
	lsl	r3, r3, #8
	bl	__Func_809233c
	mov	r3, #192
	mov	r2, #16
	lsl	r3, r3, #8
	mov	r1, #16
	mov	r0, #2
	bl	__Func_809233c
	mov	r0, #1
	bl	__MapActor_WaitMovement
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	ldr	r0, .L22+12
	bl	__GetFlag
	cmp	r0, #0
	bne	.LCB135
	b	.L3	@long jump
.LCB135:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #160
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #128
	mov	r0, #20
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r2, #16
	neg	r2, r2
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8092304
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	mov	r2, #32
	bl	__Func_8092304
	mov	r1, #128
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #0
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r1, .L22+4
	ldr	r2, .L22+8
	mov	r0, #20
	bl	__MapActor_SetSpeed
	mov	r0, #20
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r3, #254
	and	r3, r3, r2
	mov	r2, #16
	strb	r3, [r0]
	mov	r1, #0
	neg	r2, r2
	mov	r0, #20
	bl	__Func_8092304
	mov	r0, #20
	bl	__MapActor_GetActor
	add	r0, r0, #90
	ldrb	r2, [r0]
	mov	r3, #1
	orr	r3, r3, r2
	mov	r1, #128
	strb	r3, [r0]
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #14
	ldr	r1, .L22+4
	ldr	r2, .L22+8
	bl	__MapActor_SetSpeed
	mov	r2, #16
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8092304
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #164
	mov	r1, #2
	bl	__Func_8019908
	mov	r0, #1
	neg	r0, r0
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #164
	mov	r1, #3
	bl	__Func_808f1c0
	mov	r1, #0
	mov	r0, #164
	bl	__Func_8091a58
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #0
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r2, #16
	mov	r0, #14
	mov	r1, #0
	neg	r2, r2
	bl	__Func_8092304
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #14
	mov	r1, #0
	bl	__Func_8092c40
	ldr	r3, .L22+16
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #2
	strh	r3, [r2]
	b	.L4
.L3:
	ldr	r3, .L22+16
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #5
	strh	r3, [r2]
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #160
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #14
	mov	r1, #0
	bl	__Func_8092c40
.L4:
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L5
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L22+16
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L6
.L23:
	.align	2, 0
.L22:
	.word	8900
	.word	52428
	.word	26214
	.word	2385
	.word	iwram_3001ebc
.L5:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r3, .L24
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
.L6:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #160
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #4
	mov	r2, #13
	bl	__MapActor_Jump
	mov	r2, #30
	mov	r0, #1
	mov	r1, #4
	bl	__MapActor_Jump
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	mov	r0, #14
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #14
	ldr	r1, .L24+4
	ldr	r2, .L24+8
	bl	__MapActor_SetSpeed
	mov	r1, #0
	mov	r2, #16
	mov	r0, #20
	bl	__Func_8092304
	mov	r0, #2
	bl	__WaitFrames
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #6
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r2, #30
	mov	r0, #14
	mov	r1, #20
	bl	__Func_809280c
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #0
	mov	r1, #1
	mov	r0, #14
	bl	__Func_8092848
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r2, #30
	mov	r1, #2
	mov	r0, #1
	bl	__Func_809280c
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #30
	mov	r0, #2
	mov	r1, #1
	bl	__Func_809280c
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #131
	mov	r2, #50
	lsl	r1, r1, #1
	mov	r0, #1
	bl	__MapActor_Emote
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #3
	mov	r1, #2
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #2
	ldr	r1, .L24+12
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L7
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L24
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L8
.L25:
	.align	2, 0
.L24:
	.word	iwram_3001ebc
	.word	104857
	.word	52428
	.word	257
.L7:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r3, .L26
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
.L8:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #50
	bl	__CutsceneWait
	mov	r0, #14
	mov	r1, #20
	mov	r2, #60
	bl	__Func_809280c
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	lsl	r1, r1, #1
	mov	r0, #0
	bl	__MapActor_Emote
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #1
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #3
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r0, #14
	lsl	r1, r1, #1
	mov	r2, #50
	bl	__MapActor_Emote
	mov	r2, #50
	mov	r1, #14
	mov	r0, #20
	bl	__Func_809280c
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #3
	mov	r1, #2
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #50
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #6
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r2, #60
	mov	r0, #14
	ldr	r1, .L26+4
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #2
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	mov	r1, #2
	bl	__Func_8092848
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #3
	mov	r1, #2
	mov	r2, #60
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #50
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #1
	mov	r1, #0
	bl	__Func_8092848
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L9
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L26
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #3
	strh	r3, [r2]
	b	.L10
.L9:
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r5, .L26
	mov	r2, #236
	ldr	r3, [r5]
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldrh	r2, [r3]
	add	r2, r2, #1
	mov	r1, #0
	strh	r2, [r3]
	
	.code	16
	mov	r0, #1
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L11
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	ldr	r2, [r5]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L10
.L27:
	.align	2, 0
.L26:
	.word	iwram_3001ebc
	.word	261
.L11:
	ldr	r2, [r5]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
.L10:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #3
	ldr	r1, .L28
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	mov	r1, #14
	bl	__Func_809280c
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #70
	mov	r0, #14
	ldr	r1, .L28+4
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	ldr	r1, .L28
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #1
	ldr	r1, .L28
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #3
	ldr	r1, .L28
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r2, #40
	ldr	r1, .L28
	mov	r0, #2
	bl	__MapActor_Emote
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #1
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #2
	ldr	r1, .L28
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #2
	mov	r2, #0
	bl	__Func_809280c
	mov	r0, #1
	mov	r1, #2
	mov	r2, #0
	bl	__Func_809280c
	mov	r0, #3
	mov	r1, #2
	mov	r2, #0
	bl	__Func_809280c
	mov	r2, #0
	mov	r1, #2
	mov	r0, #20
	bl	__Func_809280c
	mov	r0, #50
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	ldr	r1, .L28
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #14
	mov	r2, #30
	bl	__Func_809280c
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #3
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #2
	bl	__Func_809259c
	mov	r0, #1
	mov	r1, #2
	bl	__Func_809259c
	mov	r0, #3
	mov	r1, #2
	bl	__Func_809259c
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #3
	mov	r1, #2
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #14
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	mov	r1, #20
	bl	__Func_8092848
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #20
	ldr	r1, .L28+8
	ldr	r2, .L28+12
	bl	__MapActor_SetSpeed
	mov	r0, #20
	mov	r1, #0
	mov	r2, #24
	bl	__Func_8092304
	mov	r0, #0
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r0, #1
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r0, #3
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r0, #2
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r1, #128
	mov	r2, #0
	mov	r0, #14
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	b	.L29
.L30:
	.align	2, 0
.L28:
	.word	257
	.word	261
	.word	104857
	.word	52428
.L29:
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #20
	lsl	r1, r1, #1
	mov	r2, #60
	bl	__MapActor_Emote
	mov	r0, #20
	mov	r1, #14
	mov	r2, #0
	bl	__Func_809280c
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #30
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	ldr	r1, .L31
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #20
	ldr	r1, .L31+4
	mov	r2, #60
	bl	__MapActor_Emote
	mov	r0, #20
	ldr	r1, .L31+8
	ldr	r2, .L31+12
	bl	__MapActor_SetSpeed
	mov	r2, #24
	mov	r0, #20
	mov	r1, #0
	neg	r2, r2
	bl	__Func_8092304
	mov	r2, #0
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #3
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #3
	mov	r1, #2
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	ldr	r1, .L31+4
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #1
	ldr	r1, .L31+4
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #3
	ldr	r1, .L31+4
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r2, #50
	ldr	r1, .L31+4
	mov	r0, #2
	bl	__MapActor_Emote
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #30
	mov	r0, #14
	mov	r1, #20
	bl	__Func_8092848
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #1
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	ldr	r1, .L31+4
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #2
	ldr	r1, .L31+4
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #14
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #6
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #3
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #14
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #60
	mov	r0, #14
	ldr	r1, .L31
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	b	.L32
.L33:
	.align	2, 0
.L31:
	.word	261
	.word	257
	.word	78643
	.word	39321
.L32:
	mov	r0, #1
	ldr	r1, .L34
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #1
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #14
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #3
	ldr	r1, .L34
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	ldr	r1, .L34
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #1
	ldr	r1, .L34
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #2
	ldr	r1, .L34
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r2, #40
	ldr	r1, .L34
	mov	r0, #3
	bl	__MapActor_Emote
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #2
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #2
	bl	__Func_8092c40
	mov	r0, #14
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L13
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #2
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L34+4
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L14
.L13:
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r3, .L34+4
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #2
	mov	r1, #0
	bl	__ActorMessage
.L14:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #0
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	mov	r1, #20
	bl	__Func_809280c
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #1
	mov	r1, #0
	bl	__Func_8092848
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r0, #14
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #6
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #3
	mov	r1, #2
	mov	r2, #60
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #3
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #2
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #14
	mov	r2, #60
	bl	__Func_8092848
	mov	r1, #128
	mov	r0, #20
	lsl	r1, r1, #6
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L15
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #1
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L34+4
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L16
.L35:
	.align	2, 0
.L34:
	.word	257
	.word	iwram_3001ebc
.L15:
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r3, .L36
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
.L16:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #14
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #14
	mov	r2, #40
	mov	r0, #20
	bl	__Func_809280c
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	mov	r1, #20
	bl	__Func_809280c
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #0
	ldr	r1, .L36+4
	mov	r2, #80
	bl	__MapActor_Emote
	mov	r1, #129
	mov	r2, #70
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092848
	mov	r0, #3
	mov	r1, #2
	mov	r2, #50
	bl	__Func_8092848
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	lsl	r1, r1, #8
	mov	r2, #0
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #131
	mov	r2, #50
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	mov	r0, #20
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #132
	mov	r0, #14
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L17
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #14
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
	ldr	r3, .L36
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	b	.L18
.L37:
	.align	2, 0
.L36:
	.word	iwram_3001ebc
	.word	257
.L17:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #14
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	ldr	r3, .L38
	ldr	r2, [r3]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
	mov	r0, #14
	mov	r1, #0
	bl	__ActorMessage
.L18:
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #14
	mov	r1, #20
	bl	__Func_809280c
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	mov	r1, #14
	bl	__Func_809280c
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #14
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #14
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #6
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #20
	bl	__MapActor_SetExtra
	mov	r0, #1
	mov	r1, #20
	bl	__MapActor_SetExtra
	mov	r0, #3
	mov	r1, #20
	bl	__MapActor_SetExtra
	mov	r0, #2
	mov	r1, #20
	bl	__MapActor_SetExtra
	mov	r1, #128
	mov	r2, #128
	mov	r0, #20
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r0, #20
	mov	r1, #0
	mov	r2, #32
	bl	__Func_8092304
	mov	r0, #20
	mov	r1, #0
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #1
	mov	r1, #16
	mov	r2, #0
	bl	__Func_8092304
	mov	r1, #0
	mov	r2, #80
	mov	r0, #20
	bl	__Func_80922c4
	mov	r0, #40
	bl	__CutsceneWait
	mov	r1, #16
	mov	r0, #1
	neg	r1, r1
	mov	r2, #0
	bl	__Func_8092304
	mov	r1, #128
	mov	r0, #1
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #3
	bl	__Func_8092adc
	mov	r0, #20
	bl	__MapActor_WaitMovement
	mov	r0, #80
	bl	__CutsceneWait
	mov	r0, #20
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #2
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #14
	bl	__MapActor_SetExtra
	mov	r0, #1
	mov	r1, #14
	bl	__MapActor_SetExtra
	mov	r0, #3
	mov	r1, #14
	bl	__MapActor_SetExtra
	mov	r1, #14
	mov	r0, #2
	bl	__MapActor_SetExtra
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #14
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #14
	ldr	r1, .L38+4
	ldr	r2, .L38+8
	bl	__MapActor_SetSpeed
	mov	r0, #14
	mov	r1, #0
	mov	r2, #24
	bl	__Func_8092304
	mov	r1, #80
	neg	r1, r1
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092304
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #0
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #14
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #14
	mov	r1, #0
	mov	r2, #48
	bl	__Func_8092304
	mov	r1, #64
	neg	r1, r1
	mov	r2, #0
	mov	r0, #14
	bl	__Func_8092304
	mov	r0, #0
	bl	__MapActor_SetIdle
	mov	r0, #1
	bl	__MapActor_SetIdle
	mov	r0, #3
	bl	__MapActor_SetIdle
	mov	r0, #2
	bl	__MapActor_SetIdle
	mov	r1, #0
	mov	r2, #0
	mov	r0, #14
	bl	__MapActor_SetPos
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	mov	r2, #0
	bl	__Func_8092848
	mov	r2, #0
	mov	r1, #2
	mov	r0, #1
	bl	__Func_8092848
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #17
	bl	__PlaySound
	mov	r0, #1
	ldr	r1, .L38+12
	ldr	r2, .L38+16
	bl	__MapActor_SetSpeed
	mov	r0, #2
	ldr	r1, .L38+12
	ldr	r2, .L38+16
	bl	__MapActor_SetSpeed
	mov	r0, #3
	ldr	r1, .L38+12
	ldr	r2, .L38+16
	bl	__MapActor_SetSpeed
	mov	r0, #1
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L19
	mov	r2, #10
	ldrsh	r1, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #1
	bl	__MapActor_TravelTo
.L19:
	mov	r0, #1
	bl	__MapActor_WaitMovement
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #2
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L20
	mov	r2, #10
	ldrsh	r1, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #2
	bl	__MapActor_TravelTo
.L20:
	mov	r0, #2
	bl	__MapActor_WaitMovement
	mov	r0, #2
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #3
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L21
	mov	r2, #10
	ldrsh	r1, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #3
	bl	__MapActor_TravelTo
	b	.L39
.L40:
	.align	2, 0
.L38:
	.word	iwram_3001ebc
	.word	52428
	.word	26214
	.word	78643
	.word	39321
.L39:
.L21:
	mov	r0, #3
	bl	__MapActor_WaitMovement
	mov	r1, #0
	mov	r2, #0
	mov	r0, #3
	bl	__MapActor_SetPos
	mov	r0, #10
	bl	__CutsceneWait
	bl	__PlayMapMusic
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_952_200a014,.Lfe1-OvlFunc_952_200a014

	.text
	.align	2, 0
