@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_952_200c034
	.thumb_func
	.type	 OvlFunc_952_200c034,function
OvlFunc_952_200c034:
	push	{lr}
	ldr	r3, .L9
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L9+4
	cmp	r2, r3
	bne	.L4
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	ldr	r0, .L9+8
	b	.L2
.L5:
	ldr	r0, .L9+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	ldr	r0, .L9+16
	b	.L2
.L6:
	ldr	r0, .L9+20
	b	.L2
.L4:
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	ldr	r0, .L9+24
	b	.L2
.L7:
	ldr	r0, .L9+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L8
	ldr	r0, .L9+28
	b	.L2
.L8:
	ldr	r0, .L9+32
.L2:
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	gState
	.word	_AREA_8b
	.word	.L5ad8
	.word	2402
	.word	.L5a48
	.word	.L59e8
	.word	.L5688
	.word	.L5394
	.word	.L5004
.Lfe1:
	.size	 OvlFunc_952_200c034,.Lfe1-OvlFunc_952_200c034

	.text
	.align	2, 0
