@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_a_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_952_20083b0
	.thumb_func
	.type	 OvlFunc_952_20083b0,function
OvlFunc_952_20083b0:
	push	{r5, r6, lr}
	mov	r6, sl
	mov	r5, r8
	push	{r5, r6}
	mov	r5, r0
	bl	__MapActor_GetActor
	mov	r8, r0
	bl	__CutsceneStart
	ldr	r3, .L3
	mov	sl, r3
	mov	r1, sl
	mov	r0, r5
	bl	__MapActor_SetBehavior
	ldr	r0, .L3+4
	bl	__MessageID
	mov	r1, #0
	mov	r0, r5
	bl	__ActorMessage
	mov	r6, #128
	mov	r0, r5
	bl	__MapActor_SetIdle
	lsl	r6, r6, #9
	mov	r3, r8
	str	r6, [r3, #28]
	str	r6, [r3, #24]
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #60
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #60
	mov	r0, r5
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r0, r5
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, #2
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	mov	r1, sl
	bl	__MapActor_SetBehavior
	mov	r0, r5
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #224
	mov	r2, #0
	mov	r0, r5
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #10
	bl	__CutsceneWait
	mov	r3, r8
	str	r6, [r3, #28]
	str	r6, [r3, #24]
	mov	r0, r5
	mov	r1, sl
	bl	__MapActor_SetBehavior
	bl	__CutsceneEnd
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	gScript_952__0200c570
	.word	8201
.Lfe1:
	.size	 OvlFunc_952_20083b0,.Lfe1-OvlFunc_952_20083b0

	.text
	.align	2, 0
