@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_a_c_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_952_2008ff8
	.thumb_func
	.type	 OvlFunc_952_2008ff8,function
OvlFunc_952_2008ff8:
	push	{lr}
	ldr	r0, .L3
	bl	__SetFlag
	bl	__CutsceneStart
	bl	__Func_808e118
	ldr	r0, .L3+4
	bl	__MessageID
	mov	r1, #130
	mov	r2, #212
	mov	r0, #0
	lsl	r1, r1, #2
	lsl	r2, r2, #1
	bl	__Func_80921c4
	mov	r1, #224
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #140
	mov	r1, #1
	mov	r2, #184
	mov	r3, #1
	lsl	r0, r0, #18
	neg	r1, r1
	lsl	r2, r2, #17
	bl	__Func_80933f8
	bl	__Func_8093530
	mov	r1, #128
	mov	r2, #128
	mov	r0, #20
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r0, #20
	mov	r1, #40
	mov	r2, #0
	bl	__Func_8092304
	mov	r1, #146
	mov	r2, #180
	lsl	r2, r2, #1
	mov	r0, #20
	lsl	r1, r1, #2
	bl	__Func_80921c4
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #20
	ldr	r1, .L3+8
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r0, #20
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r2, #128
	mov	r0, #21
	lsl	r1, r1, #10
	lsl	r2, r2, #9
	bl	__MapActor_SetSpeed
	mov	r1, #128
	mov	r2, #128
	mov	r0, #22
	lsl	r1, r1, #10
	lsl	r2, r2, #9
	bl	__MapActor_SetSpeed
	mov	r1, #132
	mov	r2, #176
	mov	r0, #21
	lsl	r1, r1, #2
	lsl	r2, r2, #1
	bl	__Func_809218c
	mov	r1, #132
	mov	r2, #184
	lsl	r2, r2, #1
	lsl	r1, r1, #2
	mov	r0, #22
	bl	__Func_80921c4
	mov	r0, #3
	bl	__WaitFrames
	mov	r1, #1
	mov	r0, #21
	bl	__MapActor_SetAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #16
	mov	r2, #0
	neg	r1, r1
	mov	r0, #20
	bl	__Func_8092304
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #21
	mov	r1, #4
	bl	__MapActor_SetAnim
	mov	r1, #4
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	ldr	r1, .L3+12
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r0, #21
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r2, #128
	mov	r0, #21
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r2, #0
	mov	r1, #8
	mov	r0, #21
	bl	__Func_8092304
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r1, .L3+8
	mov	r2, #80
	mov	r0, #20
	bl	__MapActor_Emote
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r0, #22
	lsl	r1, r1, #1
	mov	r2, #40
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r2, #128
	mov	r0, #22
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r2, #0
	mov	r1, #8
	mov	r0, #22
	bl	__Func_8092304
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r0, #21
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #21
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	ldr	r1, .L3+12
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #21
	ldr	r1, .L3+8
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #22
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #21
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #21
	mov	r1, #22
	mov	r2, #60
	bl	__Func_8092848
	mov	r0, #21
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r2, #0
	mov	r1, #20
	mov	r0, #22
	bl	__Func_809280c
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #21
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #21
	ldr	r1, .L3+8
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #22
	ldr	r1, .L3+8
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	b	.L4
.L5:
	.align	2, 0
.L3:
	.word	2411
	.word	8225
	.word	257
	.word	261
.L4:
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #21
	mov	r1, #22
	mov	r2, #60
	bl	__Func_8092848
	mov	r0, #21
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r1, #20
	mov	r2, #0
	mov	r0, #22
	bl	__Func_809280c
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	ldr	r1, .L6
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #21
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #22
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #21
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #40
	mov	r0, #22
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r2, #40
	mov	r0, #20
	lsl	r1, r1, #1
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #21
	ldr	r1, .L6+4
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #21
	mov	r1, #22
	mov	r2, #60
	bl	__Func_8092848
	mov	r0, #21
	mov	r1, #20
	mov	r2, #0
	bl	__Func_809280c
	mov	r2, #0
	mov	r1, #20
	mov	r0, #22
	bl	__Func_809280c
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #129
	mov	r0, #21
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r1, #129
	mov	r0, #22
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	mov	r0, #21
	mov	r1, #2
	bl	__Func_809259c
	mov	r1, #2
	mov	r0, #22
	bl	__Func_80925cc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #10
	bl	__CutsceneWait
	mov	r2, #0
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #21
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #8
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #21
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #21
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #40
	mov	r0, #20
	ldr	r1, .L6
	bl	__MapActor_Emote
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #22
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r2, #60
	mov	r0, #21
	mov	r1, #22
	bl	__Func_8092848
	mov	r1, #3
	mov	r0, #21
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #3
	mov	r0, #22
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #22
	bl	__Func_8092adc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #21
	ldr	r1, .L6+8
	ldr	r2, .L6+12
	bl	__MapActor_SetSpeed
	mov	r0, #22
	ldr	r1, .L6+8
	ldr	r2, .L6+12
	bl	__MapActor_SetSpeed
	mov	r0, #21
	mov	r1, #0
	mov	r2, #120
	bl	__Func_80922c4
	mov	r0, #22
	mov	r1, #0
	mov	r2, #120
	bl	__Func_8092304
	mov	r0, #21
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r2, #0
	mov	r1, #0
	mov	r0, #22
	bl	__MapActor_SetPos
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #20
	ldr	r1, .L6+16
	ldr	r2, .L6+20
	bl	__MapActor_SetSpeed
	mov	r1, #16
	mov	r2, #0
	neg	r1, r1
	mov	r0, #20
	bl	__Func_8092304
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	mov	r1, #4
	mov	r0, #20
	bl	__MapActor_DoAnim
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #0
	mov	r2, #0
	mov	r0, #20
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #128
	mov	r2, #128
	mov	r0, #20
	lsl	r1, r1, #9
	lsl	r2, r2, #8
	bl	__MapActor_SetSpeed
	mov	r0, #20
	mov	r1, #120
	mov	r2, #0
	bl	__Func_8092304
	mov	r0, #20
	mov	r1, #60
	mov	r2, #0
	bl	__Func_8092304
	mov	r0, #20
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	261
	.word	257
	.word	85196
	.word	42598
	.word	52428
	.word	26214
.Lfe1:
	.size	 OvlFunc_952_2008ff8,.Lfe1-OvlFunc_952_2008ff8

	.text
	.align	2, 0
