@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_963_2008030
	.thumb_func
	.type	 OvlFunc_963_2008030,function
OvlFunc_963_2008030:
	push	{lr}
	mov	r0, #13
	mov	r1, #26
	bl	__Func_8091f14
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_963_2008030,.Lfe1-OvlFunc_963_2008030

	.text
	.align	2, 0
