@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_c_a_c_c_a_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_898_200936c
	.thumb_func
	.type	 OvlFunc_898_200936c,function
OvlFunc_898_200936c:
	push	{r5, r6, r7, lr}
	ldr	r0, .L36
	sub	sp, sp, #8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r0, #14
	bl	__Func_8091e9c
.L3:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r3, #23
	mov	r2, #26
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #55
	mov	r1, #26
	mov	r2, #4
	mov	r3, #2
	bl	__Func_8010704
.L4:
	mov	r0, #128
	mov	r2, #210
	lsl	r2, r2, #17
	mov	r1, #0
	mov	r3, #223
	lsl	r0, r0, #16
	bl	OvlFunc_common0_70
	mov	r0, #14
	bl	__MapActor_GetActor
	ldr	r5, .L36+4
	mov	r3, r0
	add	r3, r3, #100
	mov	r7, #1
	strh	r7, [r3]
	str	r5, [r0, #108]
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r3, r0
	mov	r6, #0
	add	r3, r3, #100
	strh	r6, [r3]
	str	r5, [r0, #108]
	ldr	r0, .L36+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	mov	r1, #216
	mov	r2, #196
	mov	r0, #19
	lsl	r1, r1, #16
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
.L5:
	ldr	r0, .L36+12
	bl	__GetFlag
	mov	r5, r0
	ldr	r0, .L36+16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L10
	mov	r3, r7
	and	r3, r3, r5
	cmp	r3, #0
	beq	.L10
	mov	r0, #21
	bl	__MapActor_GetActor
	ldr	r3, .L36+20
	str	r3, [r0, #108]
.L10:
	ldr	r3, .L36+24
	mov	r2, #225
	lsl	r2, r2, #1
	add	r5, r3, r2
	mov	r2, #0
	ldrsh	r3, [r5, r2]
	cmp	r3, #2
	bgt	.L11
	ldr	r0, .L36+28
	bl	__GetFlag
	cmp	r0, #0
	bne	.L11
	ldr	r0, .L36+32
	bl	__ClearFlag
	ldr	r0, .L36+16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L11
	ldr	r0, .L36+36
	bl	__GetFlag
	cmp	r0, #0
	beq	.L11
	bl	__CutsceneStart
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L13
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, #2
	bl	__MapActor_SetPos
.L13:
	mov	r2, #0
	ldrsh	r3, [r5, r2]
	cmp	r3, #1
	bne	.L14
	mov	r1, #200
	mov	r2, #224
	mov	r0, #2
	lsl	r1, r1, #17
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
	b	.L19
.L14:
	mov	r1, #224
	mov	r2, #162
	mov	r0, #2
	lsl	r1, r1, #16
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
.L19:
	mov	r2, #0
	mov	r1, #0
	mov	r0, #2
	bl	__Func_8092848
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	ldr	r0, .L36+40
	bl	__MessageID
	mov	r2, #20
	mov	r0, #2
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #2
	ldr	r1, .L36+44
	ldr	r2, .L36+48
	bl	__MapActor_SetSpeed
	mov	r0, #2
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L24
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #2
	bl	__MapActor_TravelTo
.L24:
	mov	r0, #2
	bl	__MapActor_WaitMovement
	mov	r0, #2
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #2
	mov	r1, #0
	bl	__Func_80917d0
	bl	__CutsceneEnd
.L11:
	ldr	r0, .L36+32
	bl	__GetFlag
	cmp	r0, #0
	beq	.L25
	mov	r1, #204
	mov	r2, #240
	mov	r0, #23
	lsl	r1, r1, #17
	lsl	r2, r2, #15
	bl	__MapActor_SetPos
.L25:
	ldr	r3, .L36+24
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #11
	bne	.L30
	ldr	r0, .L36+16
	bl	__GetFlag
	cmp	r0, #0
	bne	.L31
	ldr	r0, .L36+36
	bl	__GetFlag
	cmp	r0, #0
	beq	.L31
	mov	r0, #2
	bl	__GetFlag
	cmp	r0, #0
	bne	.L31
	bl	__CutsceneStart
	mov	r1, #160
	mov	r2, #155
	mov	r0, #2
	lsl	r1, r1, #14
	lsl	r2, r2, #17
	bl	__MapActor_SetPos
	mov	r2, #0
	mov	r1, #0
	mov	r0, #2
	bl	__Func_8092848
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	ldr	r0, .L36+40
	bl	__MessageID
	mov	r2, #20
	mov	r0, #2
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #2
	ldr	r1, .L36+44
	ldr	r2, .L36+48
	bl	__MapActor_SetSpeed
	mov	r0, #2
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L32
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #2
	bl	__MapActor_TravelTo
.L32:
	mov	r0, #2
	bl	__MapActor_WaitMovement
	mov	r0, #2
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #2
	mov	r1, #0
	bl	__Func_80917d0
	bl	__CutsceneEnd
.L31:
	ldr	r0, .L36+52
	bl	__ClearFlag
	b	.L33
.L30:
	cmp	r3, #13
	bne	.L33
	ldr	r0, .L36+16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L33
	mov	r0, #20
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
.L33:
	mov	r0, #0
	add	sp, sp, #8
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L37:
	.align	2, 0
.L36:
	.word	2170
	.word	OvlFunc_898_2008314
	.word	2136
	.word	2131
	.word	2133
	.word	OvlFunc_898_20083ac
	.word	gState
	.word	265
	.word	2151
	.word	2134
	.word	4904
	.word	52428
	.word	26214
	.word	303
.Lfe1:
	.size	 OvlFunc_898_200936c,.Lfe1-OvlFunc_898_200936c

	.text
	.align	2, 0
