@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_898_2009198
	.thumb_func
	.type	 OvlFunc_898_2009198,function
OvlFunc_898_2009198:
	push	{lr}
	mov	r0, #123
	bl	__PlaySound
	mov	r1, #132
	lsl	r1, r1, #1
	mov	r0, #152
	mov	r2, #13
	bl	OvlFunc_898_2008ef4
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_898_2009198,.Lfe1-OvlFunc_898_2009198

	.text
	.align	2, 0
