@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_a_c_a_c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_898_20087b8
	.thumb_func
	.type	 OvlFunc_898_20087b8,function
OvlFunc_898_20087b8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L7
	bl	__MessageID
	mov	r0, #19
	mov	r1, #0
	bl	__MapActor_SetAnim
	mov	r2, #2
	mov	r0, #19
	mov	r1, #0
	bl	OvlFunc_898_200973c
	mov	r0, #19
	mov	r1, #0
	bl	__ActorMessage
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	4661
.Lfe1:
	.size	 OvlFunc_898_20087b8,.Lfe1-OvlFunc_898_20087b8

	.text
	.align	2, 0
