@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_c_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_898_2008dd4
	.thumb_func
	.type	 OvlFunc_898_2008dd4,function
OvlFunc_898_2008dd4:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L5
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r0, .L5+4
	bl	__MessageID
	b	.L4
.L3:
	ldr	r0, .L5+8
	bl	__MessageID
.L4:
	mov	r0, #16
	bl	OvlFunc_898_2008938
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	2133
	.word	4670
	.word	4940
.Lfe1:
	.size	 OvlFunc_898_2008dd4,.Lfe1-OvlFunc_898_2008dd4

	.text
	.align	2, 0
