@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_931_20082f8
	.thumb_func
	.type	 OvlFunc_931_20082f8,function
OvlFunc_931_20082f8:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L3
	bl	__MessageID
	mov	r1, #0
	mov	r0, #14
	bl	__Func_8093054
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	6369
.Lfe1:
	.size	 OvlFunc_931_20082f8,.Lfe1-OvlFunc_931_20082f8

	.text
	.align	2, 0
