@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_931_2008338
	.thumb_func
	.type	 OvlFunc_931_2008338,function
OvlFunc_931_2008338:
	push	{lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L4
	ldrh	r3, [r0, #6]
	add	r3, r3, r2
	ldr	r2, .L4+4
	lsl	r3, r3, #16
	mov	r0, #1
	cmp	r3, r2
	bls	.L2
	mov	r0, #0
.L2:
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	24575
	.word	1073610752
.Lfe1:
	.size	 OvlFunc_931_2008338,.Lfe1-OvlFunc_931_2008338

	.text
	.align	2, 0
