@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_c_c_c_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_931_2008d58
	.thumb_func
	.type	 OvlFunc_931_2008d58,function
OvlFunc_931_2008d58:
	push	{lr}
	bl	__CutsceneStart
	ldr	r0, .L3
	ldr	r1, .L3+4
	bl	__Func_80933d4
	mov	r0, #252
	mov	r1, #1
	mov	r2, #225
	mov	r3, #1
	lsl	r2, r2, #17
	neg	r1, r1
	lsl	r0, r0, #14
	bl	__Func_80933f8
	bl	__Func_8093530
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #1
	mov	r0, #18
	bl	__MapActor_SetAnim
	mov	r0, #1
	neg	r0, r0
	bl	__Func_8091ff0
	ldr	r0, .L3+8
	bl	__StopTask
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #18
	mov	r2, #0
	bl	__Func_809280c
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r0, #18
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8092adc
	mov	r1, #208
	mov	r2, #40
	lsl	r1, r1, #8
	mov	r0, #18
	bl	__Func_8092adc
	mov	r0, #147
	bl	__PlaySound
	mov	r1, #2
	mov	r0, #18
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #176
	mov	r2, #40
	mov	r0, #18
	lsl	r1, r1, #8
	bl	__Func_8092adc
	bl	OvlFunc_931_20087b8
	mov	r0, #0
	mov	r1, #1
	bl	__SetCameraTarget
	bl	__Func_8093530
	mov	r1, #4
	mov	r0, #14
	bl	__MapActor_DoAnim
	ldr	r0, .L3+12
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	26214
	.word	3276
	.word	OvlFunc_931_2008d08
	.word	2303
.Lfe1:
	.size	 OvlFunc_931_2008d58,.Lfe1-OvlFunc_931_2008d58

	.text
	.align	2, 0
