@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_944_20081c8
	.thumb_func
	.type	 OvlFunc_944_20081c8,function
OvlFunc_944_20081c8:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020095c0
.Lfe1:
	.size	 OvlFunc_944_20081c8,.Lfe1-OvlFunc_944_20081c8
	.align	2, 0
	.global	OvlFunc_944_20081d0
	.thumb_func
	.type	 OvlFunc_944_20081d0,function
OvlFunc_944_20081d0:
	ldr	r0, .L6
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	gOvl_02009680
.Lfe2:
	.size	 OvlFunc_944_20081d0,.Lfe2-OvlFunc_944_20081d0
	.align	2, 0
	.global	OvlFunc_944_20081d8
	.thumb_func
	.type	 OvlFunc_944_20081d8,function
OvlFunc_944_20081d8:
	ldr	r0, .L9
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	gScript_928__020096a0
.Lfe3:
	.size	 OvlFunc_944_20081d8,.Lfe3-OvlFunc_944_20081d8
	.align	2, 0
	.global	OvlFunc_944_20081e0
	.thumb_func
	.type	 OvlFunc_944_20081e0,function
OvlFunc_944_20081e0:
	ldr	r0, .L12
	bx	lr
.L13:
	.align	2, 0
.L12:
	.word	gOvl_020096c4
.Lfe4:
	.size	 OvlFunc_944_20081e0,.Lfe4-OvlFunc_944_20081e0
	.align	2, 0
	.global	OvlFunc_944_20081e8
	.thumb_func
	.type	 OvlFunc_944_20081e8,function
OvlFunc_944_20081e8:
	ldr	r0, .L15
	bx	lr
.L16:
	.align	2, 0
.L15:
	.word	gOvl_0200988c
.Lfe5:
	.size	 OvlFunc_944_20081e8,.Lfe5-OvlFunc_944_20081e8

	.text
	.align	2, 0
