@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_944_2009130
	.thumb_func
	.type	 OvlFunc_944_2009130,function
OvlFunc_944_2009130:
	push	{r5, r6, lr}
	mov	r0, #0
	bl	OvlFunc_944_200915c
	mov	r6, r0
	mov	r0, #2
	bl	OvlFunc_944_200915c
	add	r6, r6, r0
	mov	r0, #1
	bl	OvlFunc_944_200915c
	mov	r5, r0
	mov	r0, #3
	bl	OvlFunc_944_200915c
	add	r5, r5, r0
	sub	r6, r6, r5
	mov	r0, r6
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_944_2009130,.Lfe1-OvlFunc_944_2009130

	.text
	.align	2, 0
