@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_944_20081f0
	.thumb_func
	.type	 OvlFunc_944_20081f0,function
OvlFunc_944_20081f0:
	push	{lr}
	bl	__Func_8093e28
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_944_20081f0,.Lfe1-OvlFunc_944_20081f0

	.text
	.align	2, 0
