@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_a_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_969_2008894
	.thumb_func
	.type	 OvlFunc_969_2008894,function
OvlFunc_969_2008894:
	push	{lr}
	mov	r1, #0
	bl	__ActorMessage
	mov	r0, #10
	bl	__CutsceneWait
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_969_2008894,.Lfe1-OvlFunc_969_2008894

	.text
	.align	2, 0
