@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_969_2008470
	.thumb_func
	.type	 OvlFunc_969_2008470,function
OvlFunc_969_2008470:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200e464
.Lfe1:
	.size	 OvlFunc_969_2008470,.Lfe1-OvlFunc_969_2008470
	.align	2, 0
	.global	OvlFunc_969_2008478
	.thumb_func
	.type	 OvlFunc_969_2008478,function
OvlFunc_969_2008478:
	ldr	r0, .L6
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	gOvl_0200e478
.Lfe2:
	.size	 OvlFunc_969_2008478,.Lfe2-OvlFunc_969_2008478

	.text
	.align	2, 0
