@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_969_200846c
	.thumb_func
	.type	 OvlFunc_969_200846c,function
OvlFunc_969_200846c:
	mov	r0, #0
	bx	lr
.Lfe1:
	.size	 OvlFunc_969_200846c,.Lfe1-OvlFunc_969_200846c

	.text
	.align	2, 0
