@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_a_a_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_969_20083a0
	.thumb_func
	.type	 OvlFunc_969_20083a0,function
OvlFunc_969_20083a0:
	push	{r5, r6, lr}
	mov	r5, r0
	ldr	r4, [r5, #68]
	ldr	r3, [r5, #8]
	add	r3, r3, r4
	ldr	r2, [r5, #72]
	str	r3, [r5, #8]
	ldr	r3, [r5, #12]
	add	r3, r3, r2
	ldr	r6, [r5, #76]
	str	r3, [r5, #12]
	ldr	r3, [r5, #16]
	add	r3, r3, r6
	sub	sp, sp, #4
	str	r3, [r5, #16]
	mov	r0, r4
	mov	r1, #22
	str	r4, [sp]
	bl	__divsi3
	ldr	r4, [sp]
	sub	r4, r4, r0
	str	r4, [r5, #68]
	mov	r0, r6
	mov	r1, #20
	bl	__divsi3
	ldr	r3, [r5, #24]
	ldr	r2, [r5, #48]
	add	r3, r3, r2
	str	r3, [r5, #24]
	ldr	r2, [r5, #52]
	ldr	r3, [r5, #28]
	sub	r6, r6, r0
	add	r3, r3, r2
	str	r6, [r5, #76]
	str	r3, [r5, #28]
	ldr	r1, [r5, #80]
	add	r5, r5, #100
	ldrh	r3, [r1, #30]
	ldrh	r2, [r5]
	add	r3, r3, r2
	strh	r3, [r1, #30]
	add	sp, sp, #4
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_969_20083a0,.Lfe1-OvlFunc_969_20083a0

	.text
	.align	2, 0
