@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_969_200db90
	.thumb_func
	.type	 OvlFunc_969_200db90,function
OvlFunc_969_200db90:
	push	{r5, r6, lr}
	mov	r6, sl
	mov	r5, r8
	push	{r5, r6}
	mov	r5, r0
	mov	r6, r5
	add	r6, r6, #100
	ldrh	r2, [r6]
	ldr	r1, [r5, #104]
	mov	r8, r2
	mov	r0, r8
	mov	sl, r1
	bl	__cos
	ldr	r3, [r5, #48]
	add	r3, r3, #28
	mov	r2, r3
	mul	r2, r2, r0
	mov	r1, sl
	ldr	r3, [r1, #8]
	mov	r0, r8
	add	r3, r3, r2
	str	r3, [r5, #8]
	bl	__sin
	mov	r2, #164
	ldr	r3, [r5, #8]
	lsl	r2, r2, #16
	lsl	r0, r0, #4
	add	r0, r0, r2
	str	r0, [r5, #16]
	str	r3, [r5, #56]
	str	r0, [r5, #64]
	ldr	r1, .L3
	ldrh	r3, [r6]
	add	r3, r3, r1
	strh	r3, [r6]
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	-512
.Lfe1:
	.size	 OvlFunc_969_200db90,.Lfe1-OvlFunc_969_200db90

	.text
	.align	2, 0
