@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_c_a_c_c_c_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_969_200cb28
	.thumb_func
	.type	 OvlFunc_969_200cb28,function
OvlFunc_969_200cb28:
	push	{lr}
	ldr	r0, .L3
	bl	__MessageID
	mov	r0, #21
	bl	OvlFunc_969_2008894
	mov	r0, #62
	bl	__PlaySound
	mov	r0, #128
	.code	16
	mov	r1, #128
	.code	16
	mov	r2, #128
	lsl	r2, r2, #9
	lsl	r0, r0, #9
	lsl	r1, r1, #9
	bl	__Func_8012330
	ldr	r0, .L3+4
	ldr	r1, .L3+8
	bl	__Func_80933d4
	mov	r0, #128
	mov	r1, #128
	lsl	r0, r0, #11
	lsl	r1, r1, #8
	bl	__Func_80933d4
	mov	r0, #192
	.code	16
	mov	r2, #238
	mov	r3, #1
	lsl	r2, r2, #16
	ldr	r1, .L3+12
	lsl	r0, r0, #16
	bl	__Func_80933f8
	bl	__Func_8093530
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #21
	mov	r1, #1
	bl	__Func_80925cc
	mov	r2, #40
	ldr	r0, .L3+16
	mov	r1, #0
	bl	__Func_8093040
	mov	r1, #3
	mov	r0, #6
	bl	__Func_80925cc
	mov	r0, #6
	bl	OvlFunc_969_2008894
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #21
	bl	__MapActor_Surprise
	mov	r0, #60
	bl	__CutsceneWait
	mov	r2, #80
	ldr	r0, .L3+16
	mov	r1, #0
	bl	__Func_8093040
	mov	r1, #129
	lsl	r1, r1, #1
	mov	r0, #6
	bl	__MapActor_Surprise
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #6
	mov	r1, #2
	bl	__Func_809259c
	mov	r0, #6
	bl	OvlFunc_969_2008894
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	10281
	.word	314572
	.word	39321
	.word	-4194304
	.word	8213
.Lfe1:
	.size	 OvlFunc_969_200cb28,.Lfe1-OvlFunc_969_200cb28

	.text
	.align	2, 0
