@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_917_20091e8
	.thumb_func
	.type	 OvlFunc_917_20091e8,function
OvlFunc_917_20091e8:
	push	{lr}
	ldr	r3, [r0, #24]
	ldr	r2, .L6
	add	r3, r3, r2
	str	r3, [r0, #24]
	mov	r2, #128
	ldr	r3, [r0, #56]
	lsl	r2, r2, #24
	cmp	r3, r2
	bne	.L3
	ldr	r2, [r0, #60]
	cmp	r2, r3
	bne	.L3
	ldr	r3, [r0, #64]
	cmp	r3, r2
	bne	.L3
	bl	__DeleteActor
.L3:
	mov	r0, #1
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	7864
.Lfe1:
	.size	 OvlFunc_917_20091e8,.Lfe1-OvlFunc_917_20091e8

	.text
	.align	2, 0
