@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_a_a_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_917_20092f4
	.thumb_func
	.type	 OvlFunc_917_20092f4,function
OvlFunc_917_20092f4:
	push	{lr}
	cmp	r0, #10
	beq	.LCB6
	b	.L3	@long jump
.LCB6:
	cmp	r1, #11
	bls	.LCB8
	b	.L19	@long jump
.LCB8:
	ldr	r2, .L33
	lsl	r3, r1, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L17:
	.word	.L5
	.word	.L6
	.word	.L7
	.word	.L8
	.word	.L9
	.word	.L10
	.word	.L11
	.word	.L16
	.word	.L12
	.word	.L13
	.word	.L14
	.word	.L16
.L5:
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	b	.L29
.L6:
	mov	r0, #8
	b	.L30
.L7:
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	b	.L31
.L8:
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	b	.L32
.L9:
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #3
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #3
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	b	.L30
.L10:
	mov	r1, #1
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	mov	r1, #2
	bl	__MapActor_SetAnim
	b	.L19
.L11:
	mov	r1, #6
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	mov	r1, #8
	bl	__MapActor_SetAnim
	b	.L19
.L12:
	mov	r1, #6
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	mov	r1, #9
	bl	__MapActor_SetAnim
	b	.L19
.L13:
	mov	r1, #6
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #8
	mov	r1, #10
	bl	__MapActor_SetAnim
	b	.L19
.L14:
	mov	r1, #6
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #8
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #6
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #8
	mov	r0, #8
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
.L16:
	mov	r0, #8
	mov	r1, #6
	bl	__MapActor_SetAnim
	b	.L19
.L3:
	cmp	r1, #5
	bhi	.L19
	ldr	r2, .L33+4
	lsl	r3, r1, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L27:
	.word	.L21
	.word	.L25
	.word	.L22
	.word	.L23
	.word	.L24
	.word	.L26
.L21:
	mov	r1, #1
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #9
.L29:
	mov	r1, #3
	bl	__MapActor_SetAnim
	b	.L19
.L22:
	mov	r1, #1
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #9
.L31:
	mov	r1, #5
	bl	__MapActor_SetAnim
	b	.L19
.L23:
	mov	r1, #1
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #9
.L32:
	mov	r1, #4
	bl	__MapActor_SetAnim
	b	.L19
.L24:
	mov	r1, #1
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #3
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #1
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r1, #3
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
.L25:
	mov	r0, #9
.L30:
	mov	r1, #1
	bl	__MapActor_SetAnim
	b	.L19
.L26:
	mov	r1, #1
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r0, #6
	bl	__WaitFrames
	mov	r0, #9
	mov	r1, #2
	bl	__MapActor_SetAnim
.L19:
	mov	r0, #12
	bl	__WaitFrames
	pop	{r0}
	bx	r0
.L34:
	.align	2, 0
.L33:
	.word	.L17
	.word	.L27
.Lfe1:
	.size	 OvlFunc_917_20092f4,.Lfe1-OvlFunc_917_20092f4

	.text
	.align	2, 0
