@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_917_200972c
	.thumb_func
	.type	 OvlFunc_917_200972c,function
OvlFunc_917_200972c:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	mov	r6, r0
	mov	r8, r1
	bl	__CheckPartyItem
	mov	r7, #1
	mov	r5, r0
	neg	r7, r7
	cmp	r5, r7
	beq	.L2
	mov	r1, r6
	bl	__CheckItem
	mov	r6, r0
	cmp	r6, r7
	beq	.L2
	mov	r0, r5
	bl	__GetUnit
	lsl	r3, r6, #1
	add	r3, r3, #216
	mov	r2, r8
	strh	r2, [r0, r3]
.L2:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_917_200972c,.Lfe1-OvlFunc_917_200972c

	.text
	.align	2, 0
