@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_917_2008030
	.thumb_func
	.type	 OvlFunc_917_2008030,function
OvlFunc_917_2008030:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_02009ba4
.Lfe1:
	.size	 OvlFunc_917_2008030,.Lfe1-OvlFunc_917_2008030
	.align	2, 0
	.global	OvlFunc_917_2008038
	.thumb_func
	.type	 OvlFunc_917_2008038,function
OvlFunc_917_2008038:
	ldr	r0, .L6
	bx	lr
.L7:
	.align	2, 0
.L6:
	.word	gScript_887__02009c04
.Lfe2:
	.size	 OvlFunc_917_2008038,.Lfe2-OvlFunc_917_2008038
	.align	2, 0
	.global	OvlFunc_917_2008040
	.thumb_func
	.type	 OvlFunc_917_2008040,function
OvlFunc_917_2008040:
	ldr	r0, .L9
	bx	lr
.L10:
	.align	2, 0
.L9:
	.word	gOvl_02009c24
.Lfe3:
	.size	 OvlFunc_917_2008040,.Lfe3-OvlFunc_917_2008040
	.align	2, 0
	.global	OvlFunc_917_2008048
	.thumb_func
	.type	 OvlFunc_917_2008048,function
OvlFunc_917_2008048:
	ldr	r0, .L12
	bx	lr
.L13:
	.align	2, 0
.L12:
	.word	MapEntrance_ARRAY_941__02009c34
.Lfe4:
	.size	 OvlFunc_917_2008048,.Lfe4-OvlFunc_917_2008048

	.text
	.align	2, 0
