@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_895_2008a24
	.thumb_func
	.type	 OvlFunc_895_2008a24,function
OvlFunc_895_2008a24:
	push	{r5, r6, lr}
	ldr	r3, .L29
	mov	r0, #224
	ldr	r3, [r3]
	lsl	r0, r0, #1
	mov	r2, #129
	add	r3, r3, r0
	lsl	r2, r2, #2
	str	r2, [r3]
	ldr	r0, .L29+4
	sub	sp, sp, #8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r0, #141
	bl	__Func_8091ff0
	mov	r0, #128
	mov	r1, #128
	mov	r2, #128
	lsl	r0, r0, #9
	lsl	r1, r1, #9
	lsl	r2, r2, #9
	bl	__Func_8012330
	bl	__StartEarthquake
.L3:
	ldr	r1, .L29+8
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r1, r2
	mov	r0, #0
	ldrsh	r3, [r3, r0]
	sub	r3, r3, #1
	cmp	r3, #15
	bls	.LCB43
	b	.L4	@long jump
.LCB43:
	ldr	r2, .L29+12
	lsl	r3, r3, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L26:
	.word	.L6
	.word	.L6
	.word	.L8
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L4
	.word	.L9
	.word	.L4
	.word	.L4
	.word	.L13
	.word	.L13
	.word	.L13
	.word	.L23
	.word	.L23
	.word	.L23
.L6:
	ldr	r0, .L29+16
	bl	__GetFlag
	cmp	r0, #0
	bne	.LCB61
	b	.L4	@long jump
.LCB61:
	mov	r5, #1
	mov	r0, #1
	mov	r1, #109
	mov	r2, #4
	mov	r3, #81
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r0, #0
	mov	r1, #70
	mov	r2, #30
	mov	r3, #42
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r3, #2
	str	r3, [sp, #4]
	mov	r6, #3
	mov	r0, #0
	mov	r1, #29
	mov	r2, #3
	mov	r3, #1
	str	r6, [sp]
	bl	__CopyMapTiles
	mov	r0, #0
	mov	r1, #29
	mov	r2, #3
	mov	r3, #2
	str	r6, [sp]
	str	r5, [sp, #4]
	bl	__Func_8010704
	bl	__Func_800fe9c
	b	.L4
.L8:
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	b	.L4
.L9:
	mov	r0, #144
	ldr	r2, .L29+20
	lsl	r0, r0, #2
	add	r3, r1, r0
	strh	r2, [r3]
	ldr	r3, .L29+24
	add	r2, r1, r3
	mov	r3, #8
	strh	r3, [r2]
	ldr	r0, .L29+28
	bl	__GetFlag
	cmp	r0, #0
	beq	.LCB124
	b	.L4	@long jump
.LCB124:
	bl	OvlFunc_895_2008d1c
	b	.L4
.L13:
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #11
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #12
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #13
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #16
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #17
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #18
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #19
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r0, .L29+32
	bl	__GetFlag
	cmp	r0, #0
	bne	.L14
	bl	OvlFunc_895_2008f8c
.L14:
	ldr	r0, .L29+36
	bl	__GetFlag
	cmp	r0, #0
	beq	.L15
	mov	r1, #187
	mov	r2, #136
	mov	r0, #9
	lsl	r1, r1, #19
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	b	.L16
.L15:
	ldr	r0, .L29+40
	bl	__GetFlag
	cmp	r0, #0
	beq	.L16
	mov	r1, #191
	mov	r2, #136
	mov	r0, #9
	lsl	r1, r1, #19
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
.L16:
	ldr	r0, .L29+44
	bl	__GetFlag
	cmp	r0, #0
	beq	.L18
	mov	r1, #227
	b	.L28
.L18:
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r1, #231
.L28:
	mov	r2, #136
	mov	r0, #10
	lsl	r1, r1, #19
	lsl	r2, r2, #16
	bl	__MapActor_SetPos
	b	.L4
.L23:
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #11
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #12
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #13
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	ldr	r0, .L29+48
	bl	__GetFlag
	cmp	r0, #0
	bne	.L24
	bl	OvlFunc_895_200961c
.L24:
	mov	r0, #1
	bl	OvlFunc_895_20097c0
	mov	r0, #141
	lsl	r0, r0, #2
	bl	__SetFlag
	ldr	r0, .L29+52
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r5, #1
	mov	r0, #0
	mov	r1, #71
	mov	r2, #100
	mov	r3, #71
	str	r5, [sp]
	str	r5, [sp, #4]
	bl	__CopyMapTiles
	mov	r3, #2
	str	r3, [sp, #4]
	mov	r0, #122
	mov	r1, #20
	mov	r2, #120
	mov	r3, #30
	str	r5, [sp]
	bl	__CopyMapTiles
	mov	r3, #120
	mov	r2, #30
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #122
	mov	r1, #20
	mov	r2, #1
	mov	r3, #2
	bl	__Func_8010704
	bl	__Func_800fe9c
.L4:
	add	sp, sp, #8
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L30:
	.align	2, 0
.L29:
	.word	iwram_3001ebc
	.word	2068
	.word	gState
	.word	.L26
	.word	2074
	.word	_AREA_10
	.word	578
	.word	2050
	.word	2052
	.word	771
	.word	770
	.word	769
	.word	2085
	.word	2081
.Lfe1:
	.size	 OvlFunc_895_2008a24,.Lfe1-OvlFunc_895_2008a24

	.text
	.align	2, 0
