@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_895_200807c
	.thumb_func
	.type	 OvlFunc_895_200807c,function
OvlFunc_895_200807c:
	push	{r5, lr}
	ldr	r1, .L14
	mov	r0, #224
	lsl	r0, r0, #1
	add	r3, r1, r0
	mov	r0, #0
	ldrsh	r2, [r3, r0]
	ldr	r3, .L14+4
	cmp	r2, r3
	bne	.L3
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r1, r2
	mov	r0, #0
	ldrsh	r3, [r3, r0]
	cmp	r3, #11
	blt	.L11
	cmp	r3, #13
	ble	.L10
	cmp	r3, #16
	bgt	.L11
	ldr	r0, .L14+8
	b	.L2
.L10:
	ldr	r0, .L14+12
	b	.L2
.L11:
	ldr	r5, .L14+16
	mov	r0, r5
	bl	__Func_808b868
	mov	r0, r5
	b	.L2
.L3:
	ldr	r3, .L14+20
	cmp	r2, r3
	bne	.L13
	ldr	r0, .L14+24
	b	.L2
.L13:
	ldr	r0, .L14+28
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L15:
	.align	2, 0
.L14:
	.word	gState
	.word	_AREA_10
	.word	.L21b8
	.word	.L2050
	.word	.L1fd8
	.word	_AREA_13
	.word	.L22a8
	.word	.L1fc0
.Lfe1:
	.size	 OvlFunc_895_200807c,.Lfe1-OvlFunc_895_200807c
	.align	2, 0
	.global	OvlFunc_895_20080ec
	.thumb_func
	.type	 OvlFunc_895_20080ec,function
OvlFunc_895_20080ec:
	push	{lr}
	ldr	r1, .L28
	mov	r0, #224
	lsl	r0, r0, #1
	add	r3, r1, r0
	mov	r0, #0
	ldrsh	r2, [r3, r0]
	ldr	r3, .L28+4
	cmp	r2, r3
	bne	.L17
	ldr	r0, .L28+8
	b	.L16
.L17:
	ldr	r3, .L28+12
	cmp	r2, r3
	bne	.L18
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r1, r2
	mov	r0, #0
	ldrsh	r3, [r3, r0]
	cmp	r3, #11
	blt	.L26
	cmp	r3, #13
	ble	.L22
	cmp	r3, #16
	bgt	.L26
	ldr	r0, .L28+16
	b	.L16
.L22:
	ldr	r0, .L28+20
	b	.L16
.L26:
	ldr	r0, .L28+24
	b	.L16
.L18:
	ldr	r0, .L28+28
.L16:
	pop	{r1}
	bx	r1
.L29:
	.align	2, 0
.L28:
	.word	gState
	.word	_AREA_13
	.word	.L22e4
	.word	_AREA_10
	.word	.L2524
	.word	.L241c
	.word	.L232c
	.word	.L22d8
.Lfe2:
	.size	 OvlFunc_895_20080ec,.Lfe2-OvlFunc_895_20080ec

	.text
	.align	2, 0
