@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_950_200809c
	.thumb_func
	.type	 OvlFunc_950_200809c,function
OvlFunc_950_200809c:
	push	{lr}
	ldr	r3, .L3
	ldr	r1, [r3]
	mov	r3, #224
	lsl	r3, r3, #1
	add	r2, r1, r3
	add	r3, r3, #65
	str	r3, [r2]
	sub	r3, r3, #57
	add	r2, r1, r3
	mov	r3, #24
	str	r3, [r2]
	bl	__Func_8091e9c
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_950_200809c,.Lfe1-OvlFunc_950_200809c

	.text
	.align	2, 0
