@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_a_a_c_a_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_950_20083dc
	.thumb_func
	.type	 OvlFunc_950_20083dc,function
OvlFunc_950_20083dc:
	push	{r5, r6, lr}
	mov	r6, r8
	push	{r6}
	ldr	r3, .L8
	mov	r2, #224
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r0, #149
	add	r2, r2, #73
	str	r2, [r3]
	lsl	r0, r0, #4
	sub	sp, sp, #8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r3, #51
	mov	r2, #45
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r1, #47
	mov	r2, #3
	mov	r3, #1
	mov	r0, #51
	bl	__Func_8010704
	mov	r0, #31
	bl	__MapActor_GetActor
	mov	r2, #0
	mov	r3, r0
	mov	r8, r2
	add	r3, r3, #35
	mov	r2, r8
	strb	r2, [r3]
	ldr	r1, [r0, #80]
	mov	r5, #13
	ldrb	r2, [r1, #9]
	neg	r5, r5
	mov	r3, r5
	and	r3, r3, r2
	mov	r6, #8
	orr	r3, r3, r6
	strb	r3, [r1, #9]
	mov	r0, #32
	bl	__MapActor_GetActor
	mov	r3, r0
	add	r3, r3, #35
	mov	r2, r8
	strb	r2, [r3]
	ldr	r2, [r0, #80]
	ldrb	r3, [r2, #9]
	and	r5, r5, r3
	orr	r5, r5, r6
	strb	r5, [r2, #9]
	ldr	r0, .L8+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r1, #140
	mov	r2, #170
	mov	r0, #25
	lsl	r1, r1, #18
	lsl	r2, r2, #18
	bl	__MapActor_SetPos
	mov	r1, #128
	mov	r0, #25
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
.L4:
	ldr	r5, .L8+8
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #19
	bne	.L5
	ldr	r0, .L8+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	ldr	r0, .L8+4
	bl	__SetFlag
	bl	__MapTransitionIn
	bl	OvlFunc_950_200813c
.L5:
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #16
	bne	.L6
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	bne	.L6
	mov	r0, #192
	lsl	r0, r0, #2
	bl	__SetFlag
	bl	__MapTransitionIn
	bl	OvlFunc_950_2008328
.L6:
	ldr	r0, .L8+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r0, #35
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #36
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
.L3:
	mov	r0, #0
	add	sp, sp, #8
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001ebc
	.word	2236
	.word	gState
	.word	2219
.Lfe1:
	.size	 OvlFunc_950_20083dc,.Lfe1-OvlFunc_950_20083dc

	.text
	.align	2, 0
