@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_957_2008b0c
	.thumb_func
	.type	 OvlFunc_957_2008b0c,function
OvlFunc_957_2008b0c:
	push	{lr}
	mov	r0, #3
	bl	OvlFunc_957_2008abc
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_957_2008b0c,.Lfe1-OvlFunc_957_2008b0c

	.text
	.align	2, 0
