@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_cc0_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_958_2009040
	.thumb_func
	.type	 OvlFunc_958_2009040,function
OvlFunc_958_2009040:
	push	{lr}
	mov	r0, #149
	lsl	r0, r0, #4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	ldr	r0, .L5
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r0, .L5+4
	bl	__MessageID
	b	.L4
.L3:
	ldr	r0, .L5+8
	bl	__MessageID
.L4:
	mov	r0, #9
	mov	r1, #0
	bl	__ActorMessage
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	2415
	.word	9173
	.word	9170
.Lfe1:
	.size	 OvlFunc_958_2009040,.Lfe1-OvlFunc_958_2009040

	.text
	.align	2, 0
