@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_897_200b00c
	.thumb_func
	.type	 OvlFunc_897_200b00c,function
OvlFunc_897_200b00c:
	push	{lr}
	mov	r0, #15
	bl	__MapActor_GetActor
	bl	OvlFunc_897_200add0
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_897_200b00c,.Lfe1-OvlFunc_897_200b00c

	.text
	.align	2, 0
