@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_9dc_c_a_c_c_a_a_a_a_a_a_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_2009a44
	.thumb_func
	.type	 OvlFunc_959_2009a44,function
OvlFunc_959_2009a44:
	push	{r5, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #214
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	ldr	r3, [r5, #8]
	cmp	r3, #0
	bge	.L4
	ldr	r1, .L8
	add	r3, r3, r1
.L4:
	asr	r2, r3, #20
	ldr	r3, [r5, #16]
	cmp	r3, #0
	bge	.L5
	ldr	r1, .L8
	add	r3, r3, r1
.L5:
	asr	r3, r3, #20
	cmp	r2, #16
	bne	.L3
	cmp	r3, #55
	ble	.L3
	cmp	r3, #58
	bgt	.L3
	mov	r2, #192
	ldrh	r0, [r5, #6]
	lsl	r2, r2, #8
	cmp	r0, r2
	beq	.L7
	mov	r3, #128
	lsl	r3, r3, #7
	cmp	r0, r3
	bne	.L3
.L7:
	ldr	r3, .L8+4
	mov	r1, #182
	ldr	r3, [r3]
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r2, #40
	strh	r2, [r3]
	bl	OvlFunc_959_2008e80
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	1048575
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_959_2009a44,.Lfe1-OvlFunc_959_2009a44

	.text
	.align	2, 0
