@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_9dc_c_a_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_200969c
	.thumb_func
	.type	 OvlFunc_959_200969c,function
OvlFunc_959_200969c:
	push	{r5, lr}
	ldr	r3, .L8
	mov	r0, #133
	lsl	r0, r0, #2
	.code	16
	ldr	r5, [r3]
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	bl	OvlFunc_959_2009660
	cmp	r0, #0
	bne	.L3
	ldr	r3, .L8+4
	mov	r2, #147
	lsl	r2, r2, #2
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #0
	bne	.L5
	mov	r0, #17
	bl	OvlFunc_959_20098e4
	cmp	r0, #0
	beq	.L5
	ldr	r0, .L8+8
	bl	__SetFlag
	mov	r0, #133
	lsl	r0, r0, #2
	.code	16
	bl	__SetFlag
.L5:
	mov	r0, #133
	lsl	r0, r0, #2
	.code	16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r3, #193
	lsl	r3, r3, #1
	add	r2, r5, r3
	mov	r3, #94
	strh	r3, [r2]
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001ebc
	.word	gState
	.word	533
.Lfe1:
	.size	 OvlFunc_959_200969c,.Lfe1-OvlFunc_959_200969c

	.text
	.align	2, 0
