@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_9dc_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_200d470
	.thumb_func
	.type	 OvlFunc_959_200d470,function
OvlFunc_959_200d470:
	push	{lr}
	ldr	r0, .L6
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r0, #0
	bl	OvlFunc_959_2008ee0
.L3:
	ldr	r0, .L6+4
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	mov	r0, #1
	bl	OvlFunc_959_2008ee0
.L4:
	mov	r0, #215
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	mov	r0, #2
	bl	OvlFunc_959_2008ee0
.L5:
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	858
	.word	859
.Lfe1:
	.size	 OvlFunc_959_200d470,.Lfe1-OvlFunc_959_200d470

	.text
	.align	2, 0
