@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_9dc_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_20089dc
	.thumb_func
	.type	 OvlFunc_959_20089dc,function
OvlFunc_959_20089dc:
	push	{lr}
	ldr	r3, .L6
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L6+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L6+8
	b	.L2
.L3:
	ldr	r3, .L6+12
	cmp	r2, r3
	bne	.L4
	ldr	r0, .L6+16
	b	.L2
.L4:
	ldr	r3, .L6+20
	cmp	r2, r3
	bne	.L5
	ldr	r0, .L6+24
	b	.L2
.L5:
	ldr	r0, .L6+28
.L2:
	pop	{r1}
	bx	r1
.L7:
	.align	2, 0
.L6:
	.word	gState
	.word	_ID_a0
	.word	.L62a4
	.word	_ID_a1
	.word	.L64b4
	.word	_ID_a2
	.word	.L6754
	.word	.L6814
.Lfe1:
	.size	 OvlFunc_959_20089dc,.Lfe1-OvlFunc_959_20089dc

	.text
	.align	2, 0
