@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_9dc_a_c_c_a_a_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_959_2008e80
	.thumb_func
	.type	 OvlFunc_959_2008e80,function
OvlFunc_959_2008e80:
	push	{r5, r6, lr}
	ldr	r3, .L4
	mov	r0, #234
	ldr	r5, [r3]
	bl	__CheckPartyItem
	mov	r6, #1
	neg	r6, r6
	cmp	r0, r6
	beq	.L3
	mov	r2, #182
	lsl	r2, r2, #1
	add	r3, r5, r2
	mov	r2, #0
	ldrsh	r5, [r3, r2]
	mov	r0, r5
	sub	r0, r0, #40
	bl	OvlFunc_959_2008e30
	mov	r0, #157
	bl	__PlaySound
	mov	r0, #192
	mov	r1, #192
	mov	r2, #128
	lsl	r0, r0, #10
	lsl	r1, r1, #10
	lsl	r2, r2, #9
	bl	__Func_8012330
	mov	r0, r6
	mov	r1, r6
	ldr	r2, .L4+4
	bl	__Func_8012330
	mov	r3, #204
	lsl	r3, r3, #2
	add	r0, r5, r3
	bl	__SetFlag
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ebc
	.word	58982
.Lfe1:
	.size	 OvlFunc_959_2008e80,.Lfe1-OvlFunc_959_2008e80

	.text
	.align	2, 0
