@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_a_c_c_a_a_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_200a5c0
	.thumb_func
	.type	 OvlFunc_932_200a5c0,function
OvlFunc_932_200a5c0:
	push	{r5, lr}
	ldr	r3, .L9
	mov	r2, #225
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	sub	sp, sp, #8
	cmp	r3, #2
	bne	.L3
	ldr	r0, .L9+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L3
	mov	r1, #179
	mov	r2, #208
	mov	r0, #8
	lsl	r1, r1, #17
	lsl	r2, r2, #15
	bl	__MapActor_SetPos
.L3:
	mov	r0, #9
	bl	OvlFunc_932_200b460
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r1, #5
	mov	r5, r0
	mov	r0, #9
	bl	__MapActor_SetAnim
	mov	r3, #43
	mov	r2, #41
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r3, #1
	mov	r2, #1
	add	r5, r5, #35
	mov	r0, #45
	mov	r1, #41
	bl	__Func_8010704
	ldrb	r2, [r5]
	mov	r3, #2
	orr	r3, r3, r2
	strb	r3, [r5]
.L5:
	ldr	r0, .L9+8
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	ldr	r3, .L9+12
	ldr	r1, [r3]
	ldr	r3, .L9+16
	ldrh	r2, [r1, #20]
	and	r3, r3, r2
	strh	r3, [r1, #20]
.L6:
	ldr	r0, .L9+20
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	mov	r3, #16
	mov	r2, #92
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #17
	mov	r1, #93
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	mov	r3, #1
	mov	r2, #2
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #46
	mov	r1, #29
	mov	r2, #16
	mov	r3, #28
	bl	__CopyMapTiles
	b	.L8
.L7:
	mov	r3, #16
	mov	r2, #92
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #15
	mov	r1, #93
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	mov	r3, #1
	mov	r2, #2
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #47
	mov	r1, #29
	mov	r2, #16
	mov	r3, #28
	bl	__CopyMapTiles
.L8:
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	gState
	.word	265
	.word	2311
	.word	iwram_3001e70
	.word	65023
	.word	806
.Lfe1:
	.size	 OvlFunc_932_200a5c0,.Lfe1-OvlFunc_932_200a5c0

	.text
	.align	2, 0
