@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_2008a64
	.thumb_func
	.type	 OvlFunc_932_2008a64,function
OvlFunc_932_2008a64:
	push	{lr}
	bl	__CutsceneStart
	mov	r1, #1
	ldr	r0, .L3
	bl	__Func_801776c
	mov	r0, #125
	bl	__PlaySound
	bl	OvlFunc_932_20089ec
	mov	r0, #20
	bl	__WaitFrames
	bl	__Func_809202c
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	5416
.Lfe1:
	.size	 OvlFunc_932_2008a64,.Lfe1-OvlFunc_932_2008a64

	.text
	.align	2, 0
