@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_c_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_200b028
	.thumb_func
	.type	 OvlFunc_932_200b028,function
OvlFunc_932_200b028:
	push	{r5, r6, lr}
	bl	__CutsceneStart
	mov	r1, #164
	mov	r2, #176
	mov	r0, #8
	lsl	r1, r1, #17
	lsl	r2, r2, #15
	bl	__MapActor_SetPos
	mov	r1, #164
	mov	r2, #176
	lsl	r2, r2, #15
	mov	r0, #9
	lsl	r1, r1, #17
	bl	__MapActor_SetPos
	mov	r0, #8
	mov	r1, #0
	bl	__MapActor_SetAnim
	ldr	r5, .L8
	mov	r3, #224
	ldr	r1, [r5]
	lsl	r3, r3, #1
	add	r2, r1, r3
	sub	r3, r3, #192
	str	r3, [r2]
	add	r3, r3, #200
	add	r2, r1, r3
	mov	r3, #40
	str	r3, [r2]
	bl	__MapTransitionIn
	bl	__WaitMapTransition
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L3
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, #1
	bl	__MapActor_SetPos
.L3:
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L4
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, #2
	bl	__MapActor_SetPos
.L4:
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L5
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, #3
	bl	__MapActor_SetPos
.L5:
	mov	r0, #1
	ldr	r1, .L8+4
	ldr	r2, .L8+8
	bl	__MapActor_SetSpeed
	mov	r0, #2
	ldr	r1, .L8+4
	ldr	r2, .L8+8
	bl	__MapActor_SetSpeed
	ldr	r2, .L8+8
	mov	r0, #3
	ldr	r1, .L8+4
	bl	__MapActor_SetSpeed
	ldr	r1, .L8+12
	mov	r0, #1
	bl	__MapActor_SetBehavior
	ldr	r1, .L8+16
	mov	r0, #2
	bl	__MapActor_SetBehavior
	ldr	r1, .L8+20
	mov	r0, #3
	bl	__MapActor_RunScript
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #40
	mov	r0, #3
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #1
	mov	r1, #1
	bl	__Func_80925cc
	mov	r1, #224
	lsl	r1, r1, #8
	mov	r2, #10
	mov	r0, #1
	bl	__Func_8092adc
	ldr	r0, .L8+24
	bl	__MessageID
	mov	r2, #10
	mov	r0, #1
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #2
	mov	r1, #1
	bl	__Func_80925cc
	mov	r1, #160
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #10
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #6
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #0
	mov	r0, #2
	bl	__Func_8092c40
	mov	r0, #0
	mov	r1, #0
	bl	__Func_8091c7c
	cmp	r0, #0
	bne	.L6
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_DoAnim
	b	.L7
.L6:
	mov	r0, #2
	mov	r1, #4
	bl	__MapActor_DoAnim
	ldr	r2, [r5]
	mov	r3, #236
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldrh	r3, [r2]
	add	r3, r3, #1
	strh	r3, [r2]
.L7:
	mov	r2, #20
	mov	r0, #2
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #0
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #3
	bl	__Func_80925cc
	ldr	r0, .L8+28
	bl	__MessageID
	mov	r0, #3
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #10
	bl	__Func_8092adc
	mov	r1, #129
	mov	r0, #1
	lsl	r1, r1, #1
	mov	r2, #60
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r2, #40
	mov	r0, #1
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #10
	bl	__Func_8092adc
	mov	r0, #0
	ldr	r1, .L8+32
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #1
	ldr	r1, .L8+32
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r0, #2
	ldr	r1, .L8+32
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r2, #40
	ldr	r1, .L8+32
	mov	r0, #3
	bl	__MapActor_Emote
	mov	r0, #190
	bl	__PlaySound
	mov	r1, #7
	mov	r0, #8
	bl	__Func_8092950
	mov	r0, #10
	bl	__CutsceneWait
	ldr	r0, .L8+36
	bl	__PlaySound
	mov	r1, #192
	mov	r0, #0
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #2
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r0, #3
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #1
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r0, #1
	lsl	r1, r1, #1
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r0, #2
	lsl	r1, r1, #1
	mov	r2, #0
	bl	__MapActor_Emote
	mov	r1, #128
	mov	r2, #40
	lsl	r1, r1, #1
	mov	r0, #3
	bl	__MapActor_Emote
	mov	r0, #103
	bl	__PlaySound
	ldr	r6, .L8+40
	mov	r1, #200
	mov	r0, r6
	lsl	r1, r1, #4
	bl	__StartTask
	ldr	r5, .L8+44
	mov	r0, #9
	mov	r1, r5
	bl	__MapActor_SetBehavior
	mov	r1, r5
	mov	r0, #8
	bl	__MapActor_RunScript
	mov	r0, r6
	bl	__StopTask
	mov	r0, #60
	bl	__CutsceneWait
	mov	r1, #2
	mov	r0, #2
	bl	__Func_80925cc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #2
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #224
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #160
	mov	r2, #20
	mov	r0, #2
	lsl	r1, r1, #8
	bl	__Func_8092adc
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #3
	mov	r1, #1
	bl	__Func_80925cc
	mov	r0, #3
	mov	r1, #0
	mov	r2, #20
	bl	__Func_8093040
	mov	r1, #224
	mov	r0, #1
	lsl	r1, r1, #8
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #192
	mov	r2, #40
	mov	r0, #0
	lsl	r1, r1, #7
	bl	__Func_8092adc
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r2, #10
	mov	r0, #1
	mov	r1, #0
	bl	__Func_8093040
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r5, .L8+48
	mov	r0, #1
	mov	r1, r5
	bl	__MapActor_SetBehavior
	mov	r1, r5
	mov	r0, #2
	bl	__MapActor_SetBehavior
	mov	r1, r5
	mov	r0, #3
	bl	__MapActor_RunScript
	mov	r0, #20
	bl	__CutsceneWait
	ldr	r5, .L8
	mov	r2, #224
	ldr	r3, [r5]
	lsl	r2, r2, #1
	add	r3, r3, r2
	add	r2, r2, #68
	str	r2, [r3]
	ldr	r0, .L8+52
	bl	__ClearFlag
	ldr	r3, [r5]
	mov	r2, #228
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r2, #16
	str	r2, [r3]
	ldr	r0, .L8+56
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001ebc
	.word	39321
	.word	19660
	.word	gScript_932__0200c054
	.word	gScript_932__0200c084
	.word	gScript_932__0200c0b4
	.word	6412
	.word	6416
	.word	257
	.word	289
	.word	OvlFunc_932_200affc
	.word	gScript_932__0200c0e4
	.word	gScript_932__0200c12c
	.word	303
	.word	2313
.Lfe1:
	.size	 OvlFunc_932_200b028,.Lfe1-OvlFunc_932_200b028

	.text
	.align	2, 0
