@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_200b738
	.thumb_func
	.type	 OvlFunc_932_200b738,function
OvlFunc_932_200b738:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	mov	r7, r0
	mov	r0, #192
	lsl	r0, r0, #8
	mov	r9, r0
	ldrh	r3, [r7, #6]
	mov	r1, r9
	ldr	r0, [r7, #12]
	and	r1, r1, r3
	sub	sp, sp, #12
	mov	r9, r1
	cmp	r0, #0
	bge	.L4
	ldr	r2, .L15
	add	r0, r0, r2
.L4:
	mov	r3, r7
	asr	r0, r0, #16
	add	r3, r3, #100
	mov	sl, r0
	mov	r0, #0
	ldrsh	r3, [r3, r0]
	mov	r1, sl
	sub	r3, r3, r1
	ldr	r2, .L15+4
	lsl	r3, r3, #2
	add	r3, r3, #64
	ldr	r2, [r2, r3]
	mov	sl, r2
	mov	r2, #102
	add	r2, r2, r7
	mov	r8, r2
	mov	r1, r8
	mov	r0, #0
	ldrsh	r3, [r1, r0]
	ldrh	r2, [r2]
	cmp	r3, #0
	beq	.L5
	sub	r3, r2, #1
	mov	r0, #160
	mov	r2, r8
	strh	r3, [r2]
	lsl	r0, r0, #13
	lsl	r3, r3, #16
	cmp	r3, r0
	bne	.L6
	mov	r0, #184
	bl	__PlaySound
.L6:
	mov	r2, r8
	mov	r1, #0
	ldrsh	r3, [r2, r1]
	cmp	r3, #0
	bne	.L5
	mov	r0, #233
	bl	__PlaySound
.L5:
	ldr	r3, [r7, #8]
	mov	r5, sp
	str	r3, [r5]
	ldr	r3, [r7, #12]
	str	r3, [r5, #4]
	ldr	r3, [r7, #16]
	mov	r1, #192
	str	r3, [r5, #8]
	mov	r0, sl
	lsl	r1, r1, #8
	ldr	r3, .L15+8
		.align	2, 0
	mov	r12, pc
	bx	r3
	.code	16
	mov	r1, r9
	mov	r2, r5
	bl	__vec3_translate
	ldr	r1, [r5]
	str	r1, [r7, #8]
	ldr	r2, [r5, #8]
	mov	r0, #2
	str	r2, [r7, #16]
	bl	__Func_8011f54
	mov	r1, #192
	mov	r6, r0
	lsl	r1, r1, #9
	mov	r0, sl
	ldr	r3, .L15+8
		.align	2, 0
	mov	r12, pc
	bx	r3
	.code	16
	neg	r0, r0
	mov	r1, r9
	mov	r2, r5
	bl	__vec3_translate
	ldr	r1, [r5]
	ldr	r2, [r5, #8]
	mov	r0, #2
	bl	__Func_8011f54
	mov	r2, r8
	mov	r1, #0
	ldrsh	r3, [r2, r1]
	cmp	r3, #20
	bgt	.L10
	cmp	r6, r0
	bne	.L11
	mov	r0, r7
	mov	r1, #2
	bl	__Actor_SetAnim
	b	.L10
.L11:
	cmp	r6, r0
	ble	.L13
	mov	r0, r7
	mov	r1, #3
	bl	__Actor_SetAnim
	b	.L10
.L13:
	mov	r0, r7
	mov	r1, #4
	bl	__Actor_SetAnim
.L10:
	add	sp, sp, #12
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L16:
	.align	2, 0
.L15:
	.word	65535
	.word	.L51b4
	.word	Func_8000888
.Lfe1:
	.size	 OvlFunc_932_200b738,.Lfe1-OvlFunc_932_200b738
	.align	2, 0
	.global	OvlFunc_932_200b850
	.thumb_func
	.type	 OvlFunc_932_200b850,function
OvlFunc_932_200b850:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, sp, #12
	mov	r8, r1
	mov	r9, r0
	bl	__MapActor_GetActor
	ldr	r3, .L39
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	mov	r6, r0
	ldr	r0, [r3]
	bl	__GetFieldActor
	mov	sl, r0
	bl	__CutsceneStart
	mov	r3, #1
	neg	r3, r3
	cmp	r8, r3
	bne	.L18
	ldrh	r2, [r6, #6]
	mov	r8, r2
.L18:
	mov	r7, #0
	mov	r5, sp
	b	.L19
.L40:
	.align	2, 0
.L39:
	.word	gState
.L23:
	mov	r3, #128
	lsl	r3, r3, #7
	add	r8, r8, r3
	add	r7, r7, #1
.L19:
	cmp	r7, #3
	bgt	.L20
	ldr	r3, [r6, #8]
	str	r3, [r5]
	ldr	r3, [r6, #12]
	str	r3, [r5, #4]
	ldr	r3, [r6, #16]
	mov	r0, #128
	str	r3, [r5, #8]
	lsl	r0, r0, #13
	mov	r1, r8
	mov	r2, r5
	bl	__vec3_translate
	ldr	r1, [r5]
	ldr	r2, [r5, #8]
	mov	r0, #2
	bl	__Func_8011f54
	ldr	r3, [r6, #12]
	cmp	r0, r3
	bne	.L23
.L20:
	cmp	r7, #4
	beq	.L25
	mov	r2, r6
	mov	r3, #2
	add	r2, r2, #34
	strb	r3, [r2]
	mov	r5, #0
	mov	r2, sl
	str	r5, [r2, #8]
	str	r5, [r2, #16]
	mov	r1, #16
	ldr	r0, [r6, #80]
	bl	__Sprite_AddLayer
	mov	r0, r9
	mov	r1, #1
	bl	__SetCameraTarget
	bl	__Func_8093530
	mov	r0, #128
	mov	r1, #128
	lsl	r0, r0, #13
	lsl	r1, r1, #10
	bl	__Func_80933d4
	mov	r3, r8
	strh	r3, [r6, #6]
	mov	r3, #128
	lsl	r3, r3, #10
	str	r3, [r6, #48]
	ldr	r3, .L41+4
	ldrh	r2, .L41
	str	r3, [r6, #52]
	mov	r3, r6
	add	r3, r3, #91
	strb	r2, [r3]
	ldr	r2, [r6, #12]
	cmp	r2, #0
	bge	.L26
	ldr	r3, .L41+8
	add	r2, r2, r3
	b	.L42
.L43:
	.align	2, 0
.L41:
	.word	0
	.word	3276
	.word	65535
.L42:
.L26:
	mov	r3, r6
	asr	r2, r2, #16
	add	r3, r3, #100
	strh	r2, [r3]
	add	r3, r3, #2
	strh	r5, [r3]
	ldr	r3, [r6, #8]
	mov	r5, sp
	str	r3, [r5]
	ldr	r3, [r6, #12]
	str	r3, [r5, #4]
	ldr	r3, [r6, #16]
	mov	r0, #192
	str	r3, [r5, #8]
	lsl	r0, r0, #13
	mov	r1, r8
	mov	r2, r5
	bl	__vec3_translate
	ldr	r1, [r5]
	ldr	r2, [r6, #12]
	ldr	r3, [r5, #8]
	mov	r0, r6
	bl	__Actor_TravelTo
	mov	r0, r6
	bl	__Actor_WaitMovement
	mov	r0, #233
	bl	__PlaySound
.L27:
	ldr	r1, [r6, #8]
	ldr	r2, [r6, #16]
	mov	r0, #2
	bl	__Func_8012038
	cmp	r0, #98
	beq	.L31
	cmp	r0, #98
	bgt	.L38
	cmp	r0, #96
	beq	.L33
	cmp	r0, #97
	beq	.L32
	b	.L30
.L38:
	cmp	r0, #99
	beq	.L35
	b	.L30
.L31:
	mov	r0, r6
	bl	OvlFunc_932_200b5ac
	b	.L30
.L32:
	mov	r0, r6
	bl	OvlFunc_932_200b668
	b	.L30
.L33:
	mov	r0, r6
	bl	OvlFunc_932_200b724
.L30:
	mov	r0, r6
	bl	OvlFunc_932_200b738
	mov	r0, #1
	bl	__WaitFrames
	b	.L27
.L35:
	mov	r0, r6
	bl	OvlFunc_932_200b484
	bl	__CutsceneEnd
.L25:
	add	sp, sp, #12
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe2:
	.size	 OvlFunc_932_200b850,.Lfe2-OvlFunc_932_200b850

	.text
	.align	2, 0
