@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_932_20081c8
	.thumb_func
	.type	 OvlFunc_932_20081c8,function
OvlFunc_932_20081c8:
	push	{lr}
	ldr	r3, .L5
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L5+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L5+8
	b	.L2
.L3:
	ldr	r3, .L5+12
	mov	r0, #0
	cmp	r2, r3
	bne	.L2
	ldr	r0, .L5+16
.L2:
	pop	{r1}
	bx	r1
.L6:
	.align	2, 0
.L5:
	.word	gState
	.word	_AREA_55
	.word	gScript_943__0200c80c
	.word	_AREA_56
	.word	gOvl_0200c83c
.Lfe1:
	.size	 OvlFunc_932_20081c8,.Lfe1-OvlFunc_932_20081c8

	.text
	.align	2, 0
