@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_887_2009638
	.thumb_func
	.type	 OvlFunc_887_2009638,function
OvlFunc_887_2009638:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r2, r5
	add	r2, r2, #100
	ldrh	r3, [r2]
	add	r3, r3, #1
	ldr	r6, [r5, #104]
	strh	r3, [r2]
	lsl	r3, r3, #16
	asr	r0, r3, #16
	cmp	r0, #31
	ble	.L3
	mov	r0, r5
	bl	__DeleteActor
	b	.L2
.L3:
	lsl	r0, r0, #10
	bl	__sin
	neg	r3, r0
	str	r0, [r5, #24]
	str	r3, [r5, #28]
	ldr	r3, [r6, #8]
	mov	r1, #128
	str	r3, [r5, #8]
	ldr	r3, [r5, #12]
	lsl	r1, r1, #9
	add	r3, r3, r1
	str	r3, [r5, #12]
	sub	r1, r1, r0
	ldr	r3, [r6, #16]
	lsl	r2, r1, #2
	add	r2, r2, r1
	sub	r3, r3, r2
	mov	r2, #128
	lsl	r2, r2, #13
	add	r3, r3, r2
	str	r3, [r5, #16]
.L2:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_887_2009638,.Lfe1-OvlFunc_887_2009638

	.text
	.align	2, 0
