@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_913_200a7c8
	.thumb_func
	.type	 OvlFunc_913_200a7c8,function
OvlFunc_913_200a7c8:
	push	{r5, r6, lr}
	ldr	r3, .L6
	ldr	r6, [r3]
	mov	r3, #7
	and	r6, r6, r3
	cmp	r6, #0
	bne	.L3
	ldr	r3, .L6+4
	ldr	r3, [r3]
	cmp	r3, #0
	beq	.L4
	mov	r0, #200
	bl	__PlaySound
.L4:
	mov	r1, #231
	mov	r3, #230
	mov	r0, #26
	lsl	r1, r1, #16
	mov	r2, #0
	lsl	r3, r3, #17
	bl	__CreateActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L3
	ldr	r1, [r5, #80]
	add	r0, r0, #35
	mov	r3, r1
	ldrb	r2, [r0]
	add	r3, r3, #38
	strb	r6, [r3]
	mov	r3, #254
	and	r3, r3, r2
	strb	r3, [r0]
	ldrb	r2, [r1, #9]
	mov	r3, #13
	neg	r3, r3
	and	r3, r3, r2
	mov	r2, #4
	orr	r3, r3, r2
	strb	r3, [r1, #9]
	ldr	r3, .L6+8
	str	r3, [r5, #24]
	mov	r3, #128
	lsl	r3, r3, #12
	str	r3, [r5, #48]
	str	r3, [r5, #52]
	mov	r3, r5
	add	r3, r3, #85
	strb	r6, [r3]
	mov	r0, r5
	mov	r1, #2
	bl	__Actor_SetAnim
	mov	r1, #231
	mov	r3, #156
	mov	r0, r5
	lsl	r1, r1, #16
	mov	r2, #0
	lsl	r3, r3, #18
	bl	__Actor_TravelTo
	ldr	r1, .L6+12
	mov	r0, r5
	bl	__Actor_SetScript
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	iwram_3001e40
	.word	.L3398
	.word	6553
	.word	gScript_913__0200b2d0
.Lfe1:
	.size	 OvlFunc_913_200a7c8,.Lfe1-OvlFunc_913_200a7c8

	.text
	.align	2, 0
