@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_913_2008c60
	.thumb_func
	.type	 OvlFunc_913_2008c60,function
OvlFunc_913_2008c60:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_0200b294
.Lfe1:
	.size	 OvlFunc_913_2008c60,.Lfe1-OvlFunc_913_2008c60

	.text
	.align	2, 0
