@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_908_200811c
	.thumb_func
	.type	 OvlFunc_908_200811c,function
OvlFunc_908_200811c:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_020088f0
.Lfe1:
	.size	 OvlFunc_908_200811c,.Lfe1-OvlFunc_908_200811c

	.text
	.align	2, 0
