@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_200c048
	.thumb_func
	.type	 OvlFunc_968_200c048,function
OvlFunc_968_200c048:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L14
	mov	r9, r0
	ldr	r2, [r3]
	mov	r0, #250
	ldr	r3, .L14+4
	lsl	r0, r0, #1
	add	r3, r3, r0
	ldr	r3, [r3]
	sub	sp, sp, #88
	mov	r1, #240
	str	r3, [sp, #32]
	lsl	r1, r1, #1
	add	r2, r2, r1
	ldr	r2, [r2]
	mov	r0, r3
	str	r2, [sp, #28]
	bl	__MapActor_GetActor
	mov	r7, r0
	mov	r0, r9
	ldr	r3, [r0]
	add	r2, sp, #76
	mov	fp, r2
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #8]
	lsl	r2, r2, #15
	mov	r1, fp
	add	r3, r3, r2
	str	r3, [r1]
	ldr	r3, [r7, #12]
	str	r3, [r1, #4]
	ldr	r3, [r0, #8]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #16]
	lsl	r2, r2, #15
	add	r3, r3, r2
	str	r3, [r1, #8]
	mov	r0, r7
	bl	__TestCollision
	ldr	r3, .L14+8
	ldr	r3, [r3]
	str	r3, [sp, #24]
	ldr	r2, [sp, #24]
	mov	r3, #4
	and	r2, r2, r3
	mov	sl, r0
	str	r2, [sp, #24]
	cmp	r2, #0
	bne	.L3
	bl	__Random
	mov	r1, #248
	mov	r3, sp
	lsl	r0, r0, #12
	add	r3, r3, #36
	lsl	r1, r1, #8
	lsr	r0, r0, #16
	mov	r2, r3
	add	r0, r0, r1
	str	r3, [sp, #20]
	strh	r0, [r2, #34]
	bl	__Random
	lsl	r3, r0, #1
	add	r3, r3, r0
	lsl	r3, r3, #2
	ldr	r5, [r7, #8]
	lsr	r3, r3, #16
	lsl	r3, r3, #16
	add	r5, r5, r3
	ldr	r3, .L14+12
	add	r5, r5, r3
	bl	__Random
	lsl	r3, r0, #2
	add	r3, r3, r0
	ldr	r0, .L14+16
	lsr	r3, r3, #16
	mov	r8, r0
	mov	r1, r8
	mul	r1, r1, r3
	ldr	r6, .L14+20
	mov	r0, r9
	ldr	r2, [r0]
	mov	r3, r1
	add	r3, r3, r6
	mov	r1, r2
	mul	r1, r1, r3
	str	r1, [sp, #16]
	bl	__Random
	lsl	r3, r0, #2
	add	r3, r3, r0
	lsr	r3, r3, #16
	mov	r2, r8
	mul	r2, r2, r3
	mov	r0, r9
	mov	r3, r2
	ldr	r2, [r0, #8]
	add	r3, r3, r6
	mul	r3, r3, r2
	ldr	r1, [r7, #12]
	ldr	r2, [r7, #16]
	str	r3, [sp, #4]
	mov	r3, #128
	lsl	r3, r3, #16
	ldr	r0, [sp, #24]
	str	r3, [sp, #8]
	ldr	r3, [sp, #20]
	str	r0, [sp]
	str	r3, [sp, #12]
	mov	r0, r5
	ldr	r3, [sp, #16]
	bl	OvlFunc_968_2008118
.L3:
	mov	r0, sl
	cmp	r0, #0
	bge	.L4
	mov	r1, #129
	ldr	r0, [sp, #32]
	lsl	r1, r1, #1
	bl	__MapActor_Surprise
	ldr	r3, [r7, #16]
	mov	r0, #128
	lsl	r0, r0, #12
	add	r3, r3, r0
	ldr	r1, [r7, #8]
	ldr	r2, [r7, #12]
	mov	r0, r7
	bl	__Actor_TravelTo
	mov	r0, r7
	mov	r1, #7
	bl	__Actor_SetAnim
	mov	r0, r7
	bl	__Actor_WaitMovement
.L8:
	mov	r0, #1
	bl	__WaitFrames
	ldr	r2, [r7, #12]
	ldr	r3, [r7, #20]
	cmp	r2, r3
	bne	.L8
	mov	r0, r7
	mov	r1, #6
	bl	__Actor_SetAnim
	mov	r0, #3
	bl	__WaitFrames
	b	.L2
.L4:
	mov	r1, r9
	ldr	r2, [r1]
	ldr	r3, [r7, #8]
	lsl	r2, r2, #19
	add	r3, r3, r2
	mov	r2, fp
	str	r3, [r2]
	ldr	r3, [r7, #12]
	str	r3, [r2, #4]
	ldr	r2, [r1, #8]
	ldr	r3, [r7, #16]
	lsl	r2, r2, #19
	add	r3, r3, r2
	mov	r0, fp
	str	r3, [r0, #8]
	mov	r1, fp
	mov	r0, r7
	bl	__TestCollision
	mov	sl, r0
	cmp	r0, #0
	bgt	.L2
	mov	r1, r9
	ldr	r3, [r1]
	ldr	r5, .L14+24
	mov	r0, r9
	ldr	r2, [r0, #8]
	mov	r1, r3
	mul	r1, r1, r5
	mul	r2, r2, r5
	ldr	r3, [r7, #8]
	add	r3, r3, r1
	mov	r0, fp
	sub	r3, r3, r2
	str	r3, [r0]
	ldr	r3, [r7, #12]
	str	r3, [r0, #4]
	ldr	r3, [r7, #16]
	add	r3, r3, r2
	sub	r3, r3, r1
	str	r3, [r0, #8]
	mov	r1, fp
	mov	r0, r7
	bl	__TestCollision
	mov	sl, r0
	cmp	r0, #0
	ble	.L10
	mov	r1, r9
	ldr	r3, [r1, #8]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #8]
	lsl	r2, r2, #15
	add	r3, r3, r2
	str	r3, [r7, #8]
	ldr	r3, [r1]
	b	.L12
.L10:
	mov	r2, r9
	ldr	r3, [r2]
	ldr	r2, [r2, #8]
	add	r3, r3, r2
	mov	r2, r3
	mul	r2, r2, r5
	ldr	r3, [r7, #8]
	mov	r0, fp
	add	r3, r2, r3
	str	r3, [r0]
	ldr	r3, [r7, #12]
	str	r3, [r0, #4]
	ldr	r3, [r7, #16]
	add	r2, r2, r3
	str	r2, [r0, #8]
	mov	r1, fp
	mov	r0, r7
	bl	__TestCollision
	mov	sl, r0
	cmp	r0, #0
	ble	.L11
	mov	r1, r9
	ldr	r3, [r1, #8]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #8]
	lsl	r2, r2, #15
	sub	r3, r3, r2
	str	r3, [r7, #8]
	ldr	r3, [r1]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #16]
	lsl	r2, r2, #15
	sub	r3, r3, r2
	b	.L13
.L11:
	mov	r2, r9
	ldr	r3, [r2]
	ldr	r0, [sp, #28]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r0, #8]
	lsl	r2, r2, #15
	add	r3, r3, r2
	str	r3, [r0, #8]
	mov	r1, r9
	ldr	r3, [r1]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #8]
	lsl	r2, r2, #15
	add	r3, r3, r2
	str	r3, [r7, #8]
	ldr	r3, [r1, #8]
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r0, #16]
	lsl	r2, r2, #15
	add	r3, r3, r2
	str	r3, [r0, #16]
	ldr	r3, [r1, #8]
.L12:
	lsl	r2, r3, #1
	add	r2, r2, r3
	ldr	r3, [r7, #16]
	lsl	r2, r2, #15
	add	r3, r3, r2
.L13:
	str	r3, [r7, #16]
.L2:
	add	sp, sp, #88
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L15:
	.align	2, 0
.L14:
	.word	iwram_3001ebc
	.word	gState
	.word	iwram_3001e40
	.word	-393216
	.word	6553
	.word	32765
	.word	373555
.Lfe1:
	.size	 OvlFunc_968_200c048,.Lfe1-OvlFunc_968_200c048

	.text
	.align	2, 0
