@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_200a6f8
	.thumb_func
	.type	 OvlFunc_968_200a6f8,function
OvlFunc_968_200a6f8:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L14
	mov	r1, #178
	ldr	r3, [r3]
	lsl	r1, r1, #1
	mov	r0, #0
	add	r7, r3, r1
	sub	sp, sp, #56
	bl	__MapActor_GetActor
	ldr	r1, .L14+4
	mov	r2, #10
	ldrsh	r6, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r3, #0
	str	r3, [r0, #12]
	add	r3, r6, r1
	cmp	r3, #7
	bls	.LCB29
	b	.L3	@long jump
.LCB29:
	mov	r3, #162
	lsl	r3, r3, #1
	cmp	r2, r3
	bge	.LCB34
	b	.L3	@long jump
.LCB34:
	mov	r1, #166
	lsl	r1, r1, #1
	cmp	r2, r1
	blt	.LCB39
	b	.L3	@long jump
.LCB39:
	ldr	r3, .L14+8
	str	r3, [r0, #12]
	ldr	r0, .L14+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.LCB47
	b	.L3	@long jump
.LCB47:
	bl	__CutsceneStart
	mov	r3, #1
	str	r3, [sp]
	str	r3, [sp, #4]
	mov	r1, #29
	mov	r2, #33
	mov	r3, #20
	mov	r0, #63
	bl	__CopyMapTiles
	mov	r0, #161
	bl	__PlaySound
	mov	r3, #3
	str	r3, [sp]
	str	r3, [sp, #4]
	mov	r1, #83
	mov	r3, #80
	mov	r2, #44
	mov	r0, #44
	bl	__CopyMapTiles
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #128
	mov	r1, #128
	mov	r2, #128
	lsl	r1, r1, #9
	lsl	r2, r2, #9
	lsl	r0, r0, #9
	bl	__Func_8012330
	mov	r0, #239
	bl	__PlaySound
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #154
	ldr	r1, .L14+16
	lsl	r2, r2, #18
	mov	r6, #0
	mov	r3, #60
	mov	r9, r2
	mov	sl, r3
	mov	r8, r6
	add	r5, sp, #16
	mov	fp, r1
.L8:
	ldr	r3, [r7, #8]
	ldr	r2, .L14+20
	add	r3, r3, r2
	str	r3, [r7, #8]
	ldr	r3, .L14+24
	cmp	r9, r3
	ble	.L9
	mov	r1, r8
	cmp	r1, #40
	bls	.L9
	ldr	r2, .L14+28
	mov	r3, #2
	add	r9, r9, r2
	str	r3, [r5]
	bl	__Random
	lsl	r2, r0, #1
	add	r2, r2, r0
	lsr	r2, r2, #16
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r2, r3, #4
	add	r3, r3, r2
	lsl	r2, r3, #8
	add	r3, r3, r2
	add	r3, r3, fp
	str	r3, [r5, #8]
	bl	__Random
	lsl	r2, r0, #1
	add	r2, r2, r0
	lsr	r2, r2, #16
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r2, r3, #4
	add	r3, r3, r2
	lsl	r2, r3, #8
	add	r3, r3, r2
	add	r3, r3, fp
	str	r3, [r5, #12]
	bl	__Random
	mov	r3, #248
	lsl	r0, r0, #12
	lsl	r3, r3, #8
	lsr	r0, r0, #16
	add	r0, r0, r3
	strh	r0, [r5, #34]
	ldr	r3, .L14+32
	ldr	r2, [r3]
	mov	r3, #1
	and	r2, r2, r3
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #16
	neg	r3, r3
	str	r3, [sp]
	mov	r3, #138
	lsl	r3, r3, #16
	mov	r2, #144
	mov	r1, #0
	str	r3, [sp, #8]
	lsl	r2, r2, #17
	mov	r0, r9
	mov	r3, #0
	str	r1, [sp, #4]
	str	r5, [sp, #12]
	bl	OvlFunc_968_2008118
	mov	r2, sl
	cmp	r2, #0
	bne	.L9
	mov	r3, #40
	mov	r2, #4
	mov	sl, r3
	add	r6, r6, #4
	mov	r3, #3
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, r6
	mov	r1, #56
	mov	r2, #36
	mov	r3, #17
	bl	__CopyMapTiles
.L9:
	mov	r0, #1
	bl	__WaitFrames
	mov	r1, #1
	mov	r2, #1
	ldr	r3, .L14+36
	neg	r2, r2
	add	r8, r8, r1
	add	sl, sl, r2
	cmp	r8, r3
	bls	.L8
	ldr	r2, [r7, #8]
	mov	r1, #128
	lsl	r1, r1, #8
	add	r3, r2, r1
	str	r3, [r7, #8]
	cmp	r3, #0
	bge	.L12
	ldr	r1, .L14+40
	add	r3, r2, r1
.L12:
	asr	r3, r3, #16
	lsl	r3, r3, #16
	mov	r0, #144
	str	r3, [r7, #8]
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #188
	bl	__PlaySound
	mov	r0, #1
	mov	r1, #1
	neg	r0, r0
	neg	r1, r1
	ldr	r2, .L14+44
	bl	__Func_8012330
	bl	__Func_8012350
	ldr	r3, .L14+48
	mov	r2, #224
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	add	r2, r2, #66
	str	r2, [r3]
	mov	r0, #18
	bl	__Func_8091e9c
	bl	__CutsceneEnd
.L3:
	add	sp, sp, #56
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L15:
	.align	2, 0
.L14:
	.word	iwram_3001e70
	.word	-532
	.word	-131072
	.word	774
	.word	52428
	.word	13107
	.word	37748735
	.word	-13107
	.word	iwram_3001e40
	.word	319
	.word	98303
	.word	58982
	.word	iwram_3001ebc
.Lfe1:
	.size	 OvlFunc_968_200a6f8,.Lfe1-OvlFunc_968_200a6f8
	.align	2, 0
	.global	OvlFunc_968_200a90c
	.thumb_func
	.type	 OvlFunc_968_200a90c,function
OvlFunc_968_200a90c:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L28
	mov	r1, #178
	ldr	r3, [r3]
	lsl	r1, r1, #1
	mov	r0, #0
	add	r7, r3, r1
	sub	sp, sp, #56
	bl	__MapActor_GetActor
	ldr	r1, .L28+4
	mov	r2, #10
	ldrsh	r6, [r0, r2]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r3, #0
	str	r3, [r0, #12]
	add	r3, r6, r1
	cmp	r3, #7
	bls	.LCB301
	b	.L17	@long jump
.LCB301:
	mov	r3, #162
	lsl	r3, r3, #1
	cmp	r2, r3
	bge	.LCB306
	b	.L17	@long jump
.LCB306:
	mov	r1, #166
	lsl	r1, r1, #1
	cmp	r2, r1
	blt	.LCB311
	b	.L17	@long jump
.LCB311:
	ldr	r3, .L28+8
	str	r3, [r0, #12]
	ldr	r0, .L28+12
	bl	__GetFlag
	cmp	r0, #0
	beq	.LCB319
	b	.L17	@long jump
.LCB319:
	bl	__CutsceneStart
	mov	r3, #1
	str	r3, [sp]
	str	r3, [sp, #4]
	mov	r1, #29
	mov	r3, #20
	mov	r2, #49
	mov	r0, #63
	bl	__CopyMapTiles
	mov	r0, #161
	bl	__PlaySound
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #128
	mov	r1, #128
	mov	r2, #128
	lsl	r1, r1, #9
	lsl	r2, r2, #9
	lsl	r0, r0, #9
	bl	__Func_8012330
	mov	r0, #239
	bl	__PlaySound
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #176
	lsl	r2, r2, #18
	mov	sl, r2
	ldr	r2, .L28+16
	mov	r3, #60
	mov	r1, #0
	mov	r6, #61
	mov	r8, r3
	mov	r9, r1
	add	r5, sp, #16
	mov	fp, r2
.L22:
	ldr	r3, [r7, #8]
	ldr	r1, .L28+20
	ldr	r2, .L28+24
	add	r3, r3, r1
	str	r3, [r7, #8]
	ldr	r3, .L28+28
	add	sl, sl, r2
	ldr	r1, .L28+32
	add	r3, r3, sl
	cmp	r3, r1
	bhi	.L23
	mov	r3, #2
	str	r3, [r5]
	bl	__Random
	lsl	r2, r0, #1
	add	r2, r2, r0
	lsr	r2, r2, #16
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r2, r3, #4
	add	r3, r3, r2
	lsl	r2, r3, #8
	add	r3, r3, r2
	add	r3, r3, fp
	str	r3, [r5, #8]
	bl	__Random
	lsl	r2, r0, #1
	add	r2, r2, r0
	lsr	r2, r2, #16
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r2, r3, #4
	add	r3, r3, r2
	lsl	r2, r3, #8
	add	r3, r3, r2
	add	r3, r3, fp
	str	r3, [r5, #12]
	bl	__Random
	mov	r2, #248
	lsl	r0, r0, #12
	lsl	r2, r2, #8
	lsr	r0, r0, #16
	add	r0, r0, r2
	strh	r0, [r5, #34]
	ldr	r3, .L28+36
	ldr	r2, [r3]
	mov	r3, #1
	and	r2, r2, r3
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #16
	neg	r3, r3
	str	r3, [sp]
	mov	r3, #0
	str	r3, [sp, #4]
	mov	r3, #138
	lsl	r3, r3, #16
	mov	r2, #144
	str	r3, [sp, #8]
	mov	r1, #0
	mov	r0, sl
	lsl	r2, r2, #17
	mov	r3, #0
	str	r5, [sp, #12]
	bl	OvlFunc_968_2008118
	mov	r1, r8
	cmp	r1, #0
	bne	.L23
	mov	r2, #40
	mov	r3, #3
	mov	r8, r2
	sub	r6, r6, #4
	mov	r2, #4
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, r6
	mov	r1, #56
	mov	r2, #44
	mov	r3, #17
	bl	__CopyMapTiles
.L23:
	mov	r0, #1
	bl	__WaitFrames
	mov	r3, #1
	mov	r1, #1
	ldr	r2, .L28+40
	neg	r1, r1
	add	r9, r9, r3
	add	r8, r8, r1
	cmp	r9, r2
	bls	.L22
	ldr	r2, [r7, #8]
	mov	r1, #128
	lsl	r1, r1, #8
	add	r3, r2, r1
	str	r3, [r7, #8]
	cmp	r3, #0
	bge	.L26
	ldr	r1, .L28+44
	add	r3, r2, r1
.L26:
	asr	r3, r3, #16
	lsl	r3, r3, #16
	mov	r0, #144
	str	r3, [r7, #8]
	lsl	r0, r0, #1
	bl	__PlaySound
	mov	r0, #188
	bl	__PlaySound
	mov	r0, #1
	mov	r1, #1
	neg	r0, r0
	neg	r1, r1
	ldr	r2, .L28+48
	bl	__Func_8012330
	bl	__Func_8012350
	ldr	r3, .L28+52
	mov	r2, #224
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	add	r2, r2, #66
	str	r2, [r3]
	mov	r0, #19
	bl	__Func_8091e9c
	bl	__CutsceneEnd
.L17:
	add	sp, sp, #56
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L29:
	.align	2, 0
.L28:
	.word	iwram_3001e70
	.word	-788
	.word	-131072
	.word	775
	.word	52428
	.word	-13107
	.word	13107
	.word	-46661632
	.word	2621439
	.word	iwram_3001e40
	.word	319
	.word	98303
	.word	58982
	.word	iwram_3001ebc
.Lfe2:
	.size	 OvlFunc_968_200a90c,.Lfe2-OvlFunc_968_200a90c
	.align	2, 0
	.global	OvlFunc_968_200ab14
	.thumb_func
	.type	 OvlFunc_968_200ab14,function
OvlFunc_968_200ab14:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #16
	mov	r1, #0
	mov	r0, #0
	str	r1, [sp, #12]
	bl	__MapActor_GetActor
	str	r0, [sp, #8]
	bl	__CutsceneStart
	mov	r3, #5
	mov	r2, #48
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #69
	mov	r1, #48
	mov	r2, #4
	mov	r3, #2
	bl	__Func_8010704
	mov	r3, #9
	mov	r2, #37
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #73
	mov	r2, #9
	mov	r1, #37
	mov	r3, #13
	bl	__Func_8010704
	mov	r2, #15
	mov	sl, r2
.L34:
	mov	r0, sl
	bl	__MapActor_GetActor
	mov	r3, #35
	mov	r8, r0
	add	r3, r3, r8
	mov	fp, r3
	ldrb	r3, [r3]
	cmp	r3, #2
	beq	.L35
	ldr	r2, [r0, #8]
	ldr	r3, [r0, #16]
	asr	r2, r2, #20
	asr	r3, r3, #20
	str	r2, [sp]
	str	r3, [sp, #4]
	mov	r0, #72
	mov	r1, #48
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	b	.L36
.L35:
	mov	r1, r8
	ldr	r2, [r1, #8]
	ldr	r3, [r1, #16]
	asr	r2, r2, #20
	asr	r3, r3, #20
	str	r2, [sp]
	str	r3, [sp, #4]
	mov	r0, #73
	mov	r1, #48
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
.L36:
	mov	r2, r8
	ldr	r4, .L78
	mov	r6, #0
	ldr	r0, [r2, #8]
	ldr	r3, [r4, r6]
	asr	r2, r0, #20
	mov	r5, #8
	cmp	r2, r3
	bne	.L39
	mov	r1, r8
	ldr	r3, [r1, #16]
	ldr	r2, [r4, #4]
	asr	r3, r3, #20
	cmp	r3, r2
	bne	.L39
	ldr	r3, [r1, #12]
	cmp	r3, #0
	blt	.L39
	mov	r5, #0
	b	.L38
.L39:
	add	r6, r6, #1
	cmp	r6, #7
	bhi	.L38
	lsl	r1, r6, #3
	ldr	r3, [r4, r1]
	asr	r2, r0, #20
	cmp	r2, r3
	bne	.L39
	mov	r2, r8
	ldr	r3, [r2, #16]
	add	r2, r1, #4
	ldr	r2, [r4, r2]
	asr	r3, r3, #20
	cmp	r3, r2
	bne	.L39
	mov	r1, r8
	ldr	r3, [r1, #12]
	cmp	r3, #0
	blt	.L39
	mov	r5, r6
.L38:
	cmp	r5, #8
	bne	.LCB669
	b	.L33	@long jump
.LCB669:
	mov	r6, #15
	b	.L44
.L46:
	add	r6, r6, #1
.L44:
	cmp	r6, #18
	bhi	.L45
	mov	r0, r6
	bl	__MapActor_GetActor
	cmp	sl, r6
	beq	.L46
	mov	r3, r8
	ldr	r2, [r3, #8]
	ldr	r3, [r0, #8]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L46
	mov	r1, r8
	ldr	r2, [r1, #16]
	ldr	r3, [r0, #16]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L46
	mov	r5, #8
.L45:
	cmp	r5, #8
	bne	.LCB706
	b	.L33	@long jump
.LCB706:
	ldr	r2, [sp, #8]
	ldr	r3, [r2, #80]
	ldrb	r3, [r3, #9]
	lsl	r3, r3, #28
	lsr	r3, r3, #30
	lsl	r7, r5, #3
	ldr	r1, .L78
	mov	r9, r3
	ldr	r2, [r2, #16]
	add	r3, r7, #4
	ldr	r3, [r1, r3]
	asr	r2, r2, #20
	cmp	r2, r3
	bhi	.L51
	mov	r2, r8
	ldr	r1, [r2, #12]
	ldr	r0, [r2, #8]
	ldr	r3, .L78+4
	ldr	r2, [r2, #16]
	add	r2, r2, r3
	mov	r3, #20
	bl	OvlFunc_968_2008098
	mov	r1, #3
	str	r0, [sp, #12]
	mov	r0, #0
	bl	__Func_8092b08
.L51:
	mov	r6, #15
.L55:
	mov	r0, r6
	bl	__MapActor_GetActor
	cmp	sl, r6
	beq	.L54
	mov	r1, r8
	ldr	r2, [r1, #8]
	ldr	r3, [r0, #8]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L54
	ldr	r2, [r1, #16]
	ldr	r3, [r0, #16]
	asr	r2, r2, #20
	sub	r2, r2, #1
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L54
	mov	r0, r6
	mov	r1, #3
	bl	__Func_8092b08
.L54:
	add	r6, r6, #1
	cmp	r6, #18
	bls	.L55
	mov	r0, sl
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r3, r8
	add	r3, r3, #34
	mov	r2, #0
	mov	r6, r8
	strb	r2, [r3]
	add	r6, r6, #85
	mov	r3, #3
	strb	r3, [r6]
	ldr	r3, .L78+8
	mov	r1, r8
	mov	r2, #0
	str	r3, [r1, #72]
	str	r2, [r1, #68]
	ldr	r1, .L78
	add	r5, r7, #4
	ldr	r3, [r1, r7]
	ldr	r2, [r1, r5]
	mov	r0, #6
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r1, #44
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	mov	r0, r8
	bl	OvlFunc_968_200894c
	mov	r0, #188
	bl	__PlaySound
	mov	r3, r8
	mov	r2, #0
	add	r3, r3, #89
	strb	r2, [r3]
	ldr	r3, .L78+12
	mov	r1, r8
	strb	r2, [r6]
	mov	r0, sl
	str	r3, [r1, #12]
	mov	r1, #3
	bl	__Func_8092b08
	mov	r3, #2
	mov	r2, fp
	strb	r3, [r2]
	ldr	r1, .L78
	ldr	r3, [r1, r7]
	ldr	r2, [r1, r5]
	mov	r0, #73
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r3, #1
	mov	r2, #1
	mov	r1, #48
	bl	__Func_8010704
	mov	r0, #0
	mov	r1, r9
	bl	__Func_8092b08
	mov	r0, #0
	bl	__MapActor_GetActor
	add	r0, r0, #35
	ldrb	r3, [r0]
	mov	r2, #1
	orr	r3, r3, r2
	strb	r3, [r0]
	mov	r6, #15
.L61:
	mov	r0, r6
	bl	__MapActor_GetActor
	cmp	sl, r6
	beq	.L60
	mov	r3, r8
	ldr	r2, [r3, #8]
	ldr	r3, [r0, #8]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L60
	mov	r1, r8
	ldr	r2, [r1, #16]
	ldr	r3, [r0, #16]
	asr	r2, r2, #20
	sub	r2, r2, #1
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L60
	mov	r0, r6
	mov	r1, #1
	bl	__Func_8092b08
	mov	r0, r6
	bl	__MapActor_GetActor
	add	r0, r0, #35
	ldrb	r3, [r0]
	mov	r2, #1
	orr	r3, r3, r2
	strb	r3, [r0]
.L60:
	add	r6, r6, #1
	cmp	r6, #18
	bls	.L61
	ldr	r0, [sp, #12]
	bl	__DeleteActor
	mov	r0, #194
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L64
	bl	__CutsceneEnd
	b	.L30
.L64:
	mov	r0, #15
	bl	__MapActor_GetActor
	mov	r8, r0
	mov	r0, #16
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, #17
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, #18
	bl	__MapActor_GetActor
	mov	r2, #35
	add	r8, r8, r2
	mov	r3, r8
	add	r5, r5, #35
	ldrb	r2, [r3]
	ldrb	r3, [r5]
	add	r6, r6, #35
	and	r3, r3, r2
	ldrb	r2, [r6]
	add	r0, r0, #35
	and	r3, r3, r2
	ldrb	r2, [r0]
	and	r3, r3, r2
	mov	r2, #2
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L33
	mov	r0, #128
	mov	r1, #128
	lsl	r0, r0, #9
	lsl	r1, r1, #6
	bl	__Func_80933d4
	mov	r0, #14
	mov	r1, #1
	bl	__Func_8093500
	bl	__Func_8093530
	mov	r1, #194
	ldr	r2, .L78+16
	lsl	r1, r1, #2
	mov	r0, #136
	bl	OvlFunc_968_2008c5c
	mov	r6, r0
	mov	r0, #30
	bl	__CutsceneWait
	ldr	r0, .L78+20
	ldr	r1, .L78+24
	bl	__Func_80933d4
	mov	r0, #216
	mov	r1, #1
	mov	r2, #158
	mov	r3, #1
	lsl	r2, r2, #18
	neg	r1, r1
	lsl	r0, r0, #16
	bl	__Func_80933f8
	mov	r0, r6
	bl	__Actor_WaitScript
	mov	r0, r6
	ldr	r1, .L78+28
	bl	__Actor_SetScript
	mov	r1, #190
	lsl	r1, r1, #2
	mov	r0, #216
	ldr	r2, .L78+32
	bl	OvlFunc_968_2008c5c
	mov	r1, #99
	ldr	r3, [r6]
	add	r1, r1, r6
	mov	r5, r0
	mov	r8, r1
	b	.L77
.L68:
	mov	r1, r8
	ldrb	r3, [r1]
	cmp	r3, #0
	bne	.L70
	mov	r3, r5
	add	r3, r3, #99
	ldrb	r3, [r3]
	cmp	r3, #0
	beq	.L69
.L70:
	mov	r0, #30
	bl	__CutsceneWait
	ldr	r0, .L78+36
	mov	r1, #77
	mov	r2, #35
	bl	__Func_8010560
	mov	r3, #13
	mov	r2, #36
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #13
	mov	r1, #35
	mov	r2, #1
	mov	r3, #1
	bl	__Func_8010704
	mov	r0, #194
	lsl	r0, r0, #2
	bl	__SetFlag
	b	.L33
.L69:
	mov	r0, #1
	bl	__WaitFrames
	ldr	r3, [r6]
.L77:
	cmp	r3, #0
	bne	.L68
	ldr	r3, [r5]
	cmp	r3, #0
	bne	.L68
.L33:
	mov	r2, #1
	add	sl, sl, r2
	mov	r3, sl
	cmp	r3, #18
	bhi	.LCB1056
	b	.L34	@long jump
.LCB1056:
	bl	__CutsceneEnd
.L30:
	add	sp, sp, #16
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L79:
	.align	2, 0
.L78:
	.word	.L5164
	.word	-262144
	.word	6553
	.word	-1048576
	.word	.L577c
	.word	26214
	.word	3276
	.word	gScript_968__0200d7c8
	.word	gScript_968__0200dac8
	.word	.L5d3c
.Lfe3:
	.size	 OvlFunc_968_200ab14,.Lfe3-OvlFunc_968_200ab14

	.text
	.align	2, 0
