@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_a_c_c_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_2009644
	.thumb_func
	.type	 OvlFunc_968_2009644,function
OvlFunc_968_2009644:
	push	{r5, lr}
	mov	r0, #13
	sub	sp, sp, #8
	bl	__MapActor_GetActor
	mov	r5, r0
	bl	__CutsceneStart
	ldr	r3, [r5, #8]
	asr	r3, r3, #20
	cmp	r3, #42
	bne	.L3
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #188
	bl	__PlaySound
	mov	r2, r5
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	ldr	r3, .L4
	mov	r0, #128
	str	r3, [r5, #20]
	str	r3, [r5, #12]
	lsl	r0, r0, #2
	bl	__SetFlag
	mov	r3, #3
	mov	r2, #5
	str	r3, [sp]
	str	r2, [sp, #4]
	mov	r0, #44
	mov	r1, #117
	mov	r2, #41
	mov	r3, #117
	bl	__CopyMapTiles
.L3:
	bl	__CutsceneEnd
	add	sp, sp, #8
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	-131072
.Lfe1:
	.size	 OvlFunc_968_2009644,.Lfe1-OvlFunc_968_2009644

	.text
	.align	2, 0
