@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_2008910
	.thumb_func
	.type	 OvlFunc_968_2008910,function
OvlFunc_968_2008910:
	push	{r5, r6, lr}
	mov	r5, r1
	bl	__MapActor_GetActor
	mov	r6, r0
	mov	r0, r5
	bl	__MapActor_GetActor
	ldr	r2, [r6, #16]
	ldr	r3, [r0, #16]
	cmp	r2, r3
	bgt	.L3
	ldr	r3, [r0, #8]
	ldr	r2, [r6, #8]
	str	r3, [r6, #8]
	str	r2, [r0, #8]
	ldr	r3, [r0, #12]
	ldr	r2, [r6, #12]
	str	r3, [r6, #12]
	str	r2, [r0, #12]
	ldr	r3, [r0, #16]
	ldr	r2, [r6, #16]
	str	r3, [r6, #16]
	str	r2, [r0, #16]
	mov	r0, #1
	bl	__WaitFrames
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_968_2008910,.Lfe1-OvlFunc_968_2008910

	.text
	.align	2, 0
