@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_2008e88
	.thumb_func
	.type	 OvlFunc_968_2008e88,function
OvlFunc_968_2008e88:
	push	{r5, lr}
	ldr	r3, .L15
	mov	r1, #224
	lsl	r1, r1, #1
	add	r3, r3, r1
	mov	r1, #0
	ldrsh	r2, [r3, r1]
	ldr	r3, .L15+4
	cmp	r2, r3
	bne	.L3
	ldr	r0, .L15+8
	b	.L2
.L3:
	ldr	r3, .L15+12
	cmp	r2, r3
	bne	.L4
	ldr	r5, .L15+16
	b	.L5
.L4:
	ldr	r3, .L15+20
	cmp	r2, r3
	bne	.L6
	ldr	r5, .L15+24
	b	.L5
.L6:
	ldr	r3, .L15+28
	cmp	r2, r3
	bne	.L8
	ldr	r5, .L15+32
	b	.L5
.L8:
	ldr	r3, .L15+36
	cmp	r2, r3
	bne	.L10
	ldr	r5, .L15+40
	b	.L5
.L10:
	ldr	r3, .L15+44
	cmp	r2, r3
	bne	.L14
	ldr	r5, .L15+48
.L5:
	mov	r0, r5
	bl	__Func_808b868
	mov	r0, r5
	b	.L2
.L14:
	ldr	r0, .L15+52
.L2:
	pop	{r5}
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	gState
	.word	_AREA_b5
	.word	gScript_945__0200e904
	.word	_AREA_b6
	.word	.L69c4
	.word	_AREA_b7
	.word	.L6b74
	.word	_AREA_b8
	.word	.L6c04
	.word	_AREA_b9
	.word	.L6c64
	.word	_AREA_ba
	.word	.L6cf4
	.word	.L68ec
.Lfe1:
	.size	 OvlFunc_968_2008e88,.Lfe1-OvlFunc_968_2008e88

	.text
	.align	2, 0
