@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_968_200a3d4
	.thumb_func
	.type	 OvlFunc_968_200a3d4,function
OvlFunc_968_200a3d4:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r2, .L13
	sub	sp, sp, #4
	mov	r8, r0
	mov	sl, r2
	mov	r7, #0
	mov	r1, #0
.L6:
	mov	r6, r1
	add	r6, r6, #8
	cmp	r6, r8
	beq	.L5
	mov	r0, r6
	str	r1, [sp]
	bl	__MapActor_GetActor
	mov	r5, r0
	mov	r0, r8
	bl	__MapActor_GetActor
	mov	r7, r0
	ldr	r2, [r5, #8]
	ldr	r3, [r7, #8]
	asr	r2, r2, #20
	asr	r3, r3, #20
	ldr	r1, [sp]
	cmp	r2, r3
	bne	.L5
	ldr	r2, [r5, #16]
	ldr	r3, [r7, #16]
	asr	r2, r2, #20
	asr	r3, r3, #20
	cmp	r2, r3
	bne	.L5
	ldr	r3, [r5, #12]
	mov	r2, #128
	lsl	r2, r2, #13
	add	r0, r3, r2
	cmp	sl, r0
	bgt	.L5
	mov	r3, r7
	add	r3, r3, #100
	strh	r6, [r3]
	mov	sl, r0
.L5:
	add	r1, r1, #1
	cmp	r1, #5
	bls	.L6
	mov	r1, #128
	mov	r2, #128
	mov	r0, r8
	lsl	r1, r1, #11
	lsl	r2, r2, #10
	bl	__MapActor_SetSpeed
	ldr	r1, [r7, #8]
	ldr	r3, [r7, #16]
	mov	r2, sl
	mov	r0, r7
	bl	__Actor_TravelTo
	mov	r0, r8
	bl	__MapActor_WaitMovement
	mov	r0, #188
	bl	__PlaySound
	mov	r0, r8
	bl	OvlFunc_968_2008b08
	mov	r0, #30
	bl	__CutsceneWait
	add	sp, sp, #4
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	-5242880
.Lfe1:
	.size	 OvlFunc_968_200a3d4,.Lfe1-OvlFunc_968_200a3d4

	.text
	.align	2, 0
