import glob, re
FUNC = re.compile(r"\.thumb_func_start\s+(\S+)[^\n]*\n(.*?)\.func_end", re.S)
known = set()
for c in glob.glob("src/**/*.c", recursive=True):
    if "non_matching" in c: continue
    known.update(re.findall(r"\b(\w+)\s*\(", open(c, errors="replace").read()))
rows = []
for p in sorted(glob.glob("asm/**/*.s", recursive=True)):
    if p.startswith("asm/rom_f9000/"): continue
    txt = open(p, errors="replace").read()
    if "Generated by gcc" in txt[:400]: continue
    for m in FUNC.finditer(txt):
        n, b = m.group(1), m.group(2)
        lines = [l for l in b.split("\n") if l.startswith("\t")]
        if not (23 <= len(lines) <= 30): continue
        calls = re.findall(r"\tbl\t(\S+)", b)
        if not calls or any(c not in known for c in calls): continue
        rows.append((len(lines), n, p, len(calls)))
rows.sort()
for insn, n, p, nc in rows[:14]:
    print("%3d insn %2d calls  %-24s %s" % (insn, nc, n, p))
