@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_974_2009170
	.thumb_func
	.type	 OvlFunc_974_2009170,function
OvlFunc_974_2009170:
	push	{lr}
	bl	__Debug_IconTest
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 OvlFunc_974_2009170,.Lfe1-OvlFunc_974_2009170

	.text
	.align	2, 0
