@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_d6504_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_Summon
	.thumb_func
	.type	 Anim_Summon,function
Anim_Summon:
	push	{r5, lr}
	mov	r5, r0
	ldr	r1, .L20
	mov	r0, #41
	bl	galloc_iwram
	ldr	r1, .L20+4
	mov	r0, #39
	bl	galloc_iwram
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r0, #40
	bl	galloc_iwram
	ldr	r3, [r5]
	cmp	r3, #0
	beq	.L16
	sub	r3, r3, #1
	cmp	r3, #11
	bhi	.L4
	ldr	r2, .L20+8
	lsl	r3, r3, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L18:
	.word	.L6
	.word	.L7
	.word	.L8
	.word	.L9
	.word	.L10
	.word	.L11
	.word	.L12
	.word	.L13
	.word	.L14
	.word	.L15
	.word	.L16
	.word	.L17
.L6:
	mov	r0, r5
	bl	Anim_Ramses
	b	.L4
.L7:
	mov	r0, r5
	bl	Anim_Nereid
	b	.L4
.L8:
	mov	r0, r5
	bl	Anim_Kirin
	b	.L4
.L9:
	mov	r0, r5
	bl	Anim_Atalanta
	b	.L4
.L10:
	mov	r0, r5
	bl	Anim_Cybele
	b	.L4
.L11:
	mov	r0, r5
	bl	Anim_Neptune
	b	.L4
.L12:
	mov	r0, r5
	bl	Anim_Tiamat
	b	.L4
.L13:
	mov	r0, r5
	bl	Anim_Procne
	b	.L4
.L14:
	mov	r0, r5
	bl	Anim_Judgment
	b	.L4
.L15:
	mov	r0, r5
	bl	Anim_Boreas
	b	.L4
.L16:
	mov	r0, r5
	bl	Anim_Meteor
	b	.L4
.L17:
	mov	r0, r5
	bl	Anim_Thor
.L4:
	mov	r0, #40
	bl	gfree
	mov	r0, #39
	bl	gfree
	mov	r0, #41
	bl	gfree
	pop	{r5}
	pop	{r0}
	bx	r0
.L21:
	.align	2, 0
.L20:
	.word	770
	.word	30764
	.word	.L18
.Lfe1:
	.size	 Anim_Summon,.Lfe1-Anim_Summon

	.text
	.align	2, 0
