@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_d82b0_b.c"
	.code	16
.gcc2_compiled.:
	.global	.Lee9f8
	.section .rodata
	.align	2, 0
	.type	 .Lee9f8,object
	.size	 .Lee9f8,16
.Lee9f8:
	.word	16384
	.word	8192
	.word	16384
	.word	32768
.text
	.align	2, 0
	.global	Anim_Break
	.thumb_func
	.type	 Anim_Break,function
Anim_Break:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r5, .L35
	mov	r3, r5
	ldmia	r3!, {r1}
	sub	sp, sp, #56
	str	r1, [sp, #28]
	ldr	r3, [r3]
	str	r3, [sp, #24]
	ldr	r2, [r5, #8]
	ldr	r4, .L35+4
	str	r2, [sp, #16]
	mov	r3, r5
	sub	r3, r3, #108
	ldr	r6, [r3]
	add	r3, r1, r4
	str	r0, [r3]
	mov	r0, #1
	bl	AnimStart
	mov	r2, #0
	ldr	r1, [sp, #16]
	mov	r3, #0
	ldr	r0, .L35+8
	bl	LoadVFXFile
	ldr	r0, .L35+12
	bl	GetFile
	mov	r1, r0
	mov	r0, #160
	ldr	r3, .L35+16
	mov	r2, #128
	lsl	r0, r0, #19
	bl	_call_via_r3
	mov	r3, #2
	str	r3, [sp]
	mov	r1, #7
	mov	r2, #7
	mov	r3, #3
	mov	r0, #46
	bl	BuildDraw2DFuncEx
	ldr	r5, [r5, #28]
	mov	r0, #0
	mov	r1, #1
	mov	r2, #128
	str	r5, [sp, #20]
	ldr	r3, .L35+20
	mov	r8, r0
	neg	r1, r1
	lsl	r2, r2, #3
.L6:
	mov	r4, #1
	add	r8, r8, r4
	str	r1, [r3]
	add	r3, r3, #28
	cmp	r8, r2
	bne	.L6
	bl	InitMatrixStack
	mov	r1, r6
	add	r1, r1, #12
	mov	r0, r6
	bl	MatrixSetLook
	ldr	r2, .L35+4
	ldr	r1, [sp, #28]
	ldr	r3, [r1, r2]
	ldr	r3, [r3, #20]
	mov	r0, #0
	mov	fp, r0
	cmp	r3, #0
	beq	.L34
	mov	r3, #44
	mov	r4, #32
	mov	r0, #36
	mov	r1, #0
	add	r3, r3, sp
	add	r4, r4, sp
	str	r0, [sp, #12]
	str	r1, [sp, #8]
	mov	r9, r3
	mov	sl, r4
.L9:
	ldr	r3, [sp, #28]
	add	r5, r3, r2
	ldr	r4, [sp, #12]
	ldr	r3, [r5]
	ldrsh	r0, [r3, r4]
	bl	_GetBattleActor
	ldr	r3, [r5]
	ldr	r2, [sp, #12]
	ldr	r6, [r0]
	ldrsh	r0, [r3, r2]
	bl	_Func_80b8530
	lsr	r3, r0, #31
	add	r0, r0, r3
	ldr	r3, [r6, #8]
	mov	r1, r9
	asr	r0, r0, #1
	str	r0, [r1, #4]
	str	r3, [r1]
	ldr	r3, [r6, #16]
	mov	r0, r9
	str	r3, [r1, #8]
	mov	r1, sl
	bl	Func_80e3944
	mov	r2, sl
	ldr	r3, [r2]
	asr	r3, r3, #1
	str	r3, [r2]
	ldr	r4, [sp, #8]
	ldr	r0, .L35+24
	mov	r3, #0
	mov	r8, r3
	add	r7, r4, r0
.L13:
	bl	Random
	mov	r1, #255
	mov	r6, r0
	and	r6, r6, r1
	bl	Random
	ldr	r3, .L35+28
	mov	r5, r0
	and	r5, r5, r3
	mov	r0, r5
	bl	sin
	mov	r2, r6
	mul	r2, r2, r0
	mov	r4, sl
	ldr	r3, [r4]
	asr	r2, r2, #7
	lsl	r3, r3, #16
	add	r2, r2, r3
	str	r2, [r7]
	mov	r0, r5
	bl	cos
	mov	r2, r6
	mul	r2, r2, r0
	mov	r0, sl
	ldr	r3, [r0, #4]
	asr	r2, r2, #3
	lsl	r3, r3, #16
	add	r2, r2, r3
	str	r2, [r7, #4]
	bl	Random
	mov	r1, #255
	and	r0, r0, r1
	mov	r3, #128
	sub	r3, r3, r0
	lsl	r3, r3, #9
	str	r3, [r7, #12]
	bl	Random
	mov	r2, #255
	mov	r3, #0
	and	r0, r0, r2
	str	r3, [r7, #24]
	neg	r0, r0
	mov	r3, #1
	sub	r0, r0, #128
	add	r8, r8, r3
	lsl	r0, r0, #10
	mov	r4, r8
	str	r0, [r7, #16]
	add	r7, r7, #28
	cmp	r4, #128
	bne	.L13
	ldr	r0, [sp, #12]
	ldr	r1, [sp, #8]
	mov	r2, #224
	lsl	r2, r2, #4
	add	r1, r1, r2
	add	r0, r0, #2
	str	r0, [sp, #12]
	str	r1, [sp, #8]
	ldr	r2, .L35+4
	ldr	r4, [sp, #28]
	add	fp, fp, r3
	ldr	r3, [r4, r2]
	ldr	r3, [r3, #20]
	cmp	fp, r3
	bne	.L9
.L34:
	ldr	r0, [sp, #28]
	mov	r1, #239
	lsl	r1, r1, #7
	add	r2, r0, r1
	mov	r3, #2
	str	r3, [r2]
	ldr	r3, .L35+32
	mov	r1, #144
	add	r2, r0, r3
	mov	r3, #50
	str	r3, [r2]
	lsl	r1, r1, #3
	ldr	r0, .L35+36
	bl	StartTask
	ldr	r1, .L35+4
	ldr	r0, [sp, #28]
	add	r3, r0, r1
	ldr	r3, [r3]
	ldr	r2, [r3, #20]
	lsl	r3, r2, #2
	add	r3, r3, r2
	mov	r2, #56
	mov	r4, #0
	lsl	r3, r3, #2
	neg	r2, r2
	mov	r9, r4
	cmp	r3, r2
	bne	.LCB263
	b	.L15	@long jump
.LCB263:
	add	r6, r0, r1
.L33:
	mov	r3, r9
	cmp	r3, #32
	bne	.L19
	mov	r0, #0
	bl	_Func_80bd7dc
.L19:
	ldr	r3, [r6]
	ldr	r3, [r3, #20]
	mov	r4, #0
	mov	fp, r4
	cmp	r3, #0
	beq	.L20
	mov	r0, #0
	mov	r7, #0
	mov	sl, r0
.L32:
	cmp	r9, r7
	bne	.L24
	mov	r0, #143
	bl	_PlaySound
	mov	r1, fp
	ldr	r2, [r6]
	lsl	r3, r1, #1
	add	r3, r3, #36
	ldrsh	r0, [r2, r3]
	mov	r3, #20
	mov	r2, #1
	str	r3, [sp]
	mov	r1, #7
	neg	r2, r2
	mov	r3, fp
	bl	Func_80d6888
.L24:
	cmp	r9, r7
	ble	.L25
	ldr	r5, .L35+24
	mov	r0, #0
	mov	r8, r0
	add	r5, r5, sl
.L31:
	ldr	r3, [r5, #24]
	cmp	r3, #0
	blt	.L29
	mov	r1, #3
	mov	r0, r8
	bl	__modsi3
	add	r0, r0, #1
	lsl	r4, r0, #1
	ldr	r2, .L35+40
	sub	r3, r4, #2
	ldrh	r1, [r2, r3]
	ldr	r2, [sp, #16]
	add	r1, r2, r1
	mov	r3, #2
	ldrsh	r2, [r5, r3]
	lsr	r3, r0, #31
	add	r3, r0, r3
	asr	r3, r3, #1
	sub	r2, r2, r3
	mov	lr, r2
	mov	r3, #6
	ldrsh	r2, [r5, r3]
	str	r0, [sp]
	sub	r3, r2, r0
	str	r4, [sp, #4]
	mov	r2, lr
	ldr	r0, [sp, #24]
	ldr	r4, [sp, #20]
	bl	_call_via_r4
	mov	r0, #3
	mov	r3, r8
	ldr	r2, .L35+44
	and	r3, r3, r0
	lsl	r3, r3, #2
	ldr	r2, [r2, r3]
	mov	r0, r5
	mov	r1, #62
	bl	Func_80e3908
	ldr	r3, [r5, #24]
	add	r3, r3, #1
	str	r3, [r5, #24]
	ldr	r3, [r5, #16]
	cmp	r3, #0
	ble	.L29
	mov	r1, #6
	ldrsh	r3, [r5, r1]
	cmp	r3, #112
	ble	.L29
	mov	r3, #1
	neg	r3, r3
	str	r3, [r5, #24]
.L29:
	mov	r2, #1
	add	r8, r8, r2
	mov	r3, r8
	add	r5, r5, #28
	cmp	r3, #128
	bne	.L31
.L25:
	ldr	r3, [r6]
	mov	r4, #224
	mov	r0, #1
	ldr	r3, [r3, #20]
	lsl	r4, r4, #4
	add	fp, fp, r0
	add	r7, r7, #20
	add	sl, sl, r4
	cmp	fp, r3
	bne	.L32
.L20:
	bl	Func_80cd52c
	ldr	r3, .L35+48
	ldr	r1, [sp, #28]
	add	r2, r1, r3
	mov	r3, #1
	str	r3, [r2]
	mov	r0, #1
	bl	WaitFrames
	ldr	r3, [r6]
	ldr	r2, [r3, #20]
	lsl	r3, r2, #2
	add	r3, r3, r2
	mov	r4, #1
	lsl	r3, r3, #2
	add	r9, r9, r4
	add	r3, r3, #56
	cmp	r9, r3
	beq	.LCB431
	b	.L33	@long jump
.LCB431:
.L15:
	ldr	r0, .L35+36
	bl	StopTask
	mov	r0, #46
	bl	gfree
	bl	AnimEnd
	add	sp, sp, #56
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L36:
	.align	2, 0
.L35:
	.word	iwram_3001eec
	.word	30760
	.word	_FILE_73
	.word	_FILE_b9
	.word	Func_8001af8
	.word	ewram_2010018
	.word	gBuffer
	.word	65535
	.word	30596
	.word	Task_BlitAnim
	.word	Data_ede48
	.word	.Lee9f8
	.word	30756
.Lfe1:
	.size	 Anim_Break,.Lfe1-Anim_Break

	.text
	.align	2, 0
