@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_e3958_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetBattleActorPos3
	.thumb_func
	.type	 GetBattleActorPos3,function
GetBattleActorPos3:
	push	{r5, lr}
	mov	r5, r1
	bl	_Func_80b7f20
	ldr	r3, [r5, #4]
	sub	r3, r3, #16
	str	r3, [r5, #4]
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 GetBattleActorPos3,.Lfe1-GetBattleActorPos3

	.text
	.align	2, 0
