@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_d6504_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Task_SpinCamera
	.thumb_func
	.type	 Task_SpinCamera,function
Task_SpinCamera:
	push	{lr}
	ldr	r3, .L8
	ldr	r2, [r3]
	sub	r3, r3, #108
	ldr	r1, [r3]
	ldr	r3, .L8+4
	add	r0, r2, r3
	ldr	r3, [r0]
	cmp	r3, #1
	bne	.L3
	ldr	r4, .L8+8
	add	r3, r2, r4
	ldr	r2, [r3]
	ldrh	r3, [r1, #54]
	add	r3, r3, r2
	mov	r2, #0
	strh	r3, [r1, #54]
	str	r2, [r0]
	b	.L4
.L3:
	ldr	r4, .L8+8
	add	r3, r2, r4
	ldr	r2, [r3]
	lsr	r3, r2, #31
	add	r2, r2, r3
	ldrh	r3, [r1, #54]
	asr	r2, r2, #1
	add	r3, r3, r2
	strh	r3, [r1, #54]
	ldr	r3, [r0]
	cmp	r3, #2
	bne	.L5
	mov	r3, #0
	b	.L7
.L5:
	mov	r3, #2
.L7:
	str	r3, [r0]
.L4:
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001eec
	.word	30640
	.word	30636
.Lfe1:
	.size	 Task_SpinCamera,.Lfe1-Task_SpinCamera

	.text
	.align	2, 0
