@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_dfa18_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_BruteForce
	.thumb_func
	.type	 Anim_BruteForce,function
Anim_BruteForce:
	push	{lr}
	mov	r1, #1
	bl	BaseAnim_Tackle
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_BruteForce,.Lfe1-Anim_BruteForce

	.text
	.align	2, 0

	.text
	.align	2, 0
