@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_d8948_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_Tonic
	.thumb_func
	.type	 Anim_Tonic,function
Anim_Tonic:
	push	{lr}
	mov	r1, #5
	bl	BaseAnim_Heal
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_Tonic,.Lfe1-Anim_Tonic

	.text
	.align	2, 0
