@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_e28f4_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_MadDash
	.thumb_func
	.type	 Anim_MadDash,function
Anim_MadDash:
	push	{lr}
	mov	r1, #0
	bl	BaseAnim_RapidSlash
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_MadDash,.Lfe1-Anim_MadDash

	.text
	.align	2, 0

	.text
	.align	2, 0
