@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_ca57c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_CannibalFang
	.thumb_func
	.type	 Anim_CannibalFang,function
Anim_CannibalFang:
	push	{lr}
	mov	r1, #3
	bl	BaseAnim_Bite_Sting
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_CannibalFang,.Lfe1-Anim_CannibalFang

	.text
	.align	2, 0
