@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_d9ab8_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_Impair
	.thumb_func
	.type	 Anim_Impair,function
Anim_Impair:
	push	{lr}
	mov	r1, #1
	bl	BaseAnim_StatDown
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_Impair,.Lfe1-Anim_Impair

	.text
	.align	2, 0
