@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_db6c8_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_Blast
	.thumb_func
	.type	 Anim_Blast,function
Anim_Blast:
	push	{lr}
	mov	r1, #0
	bl	BaseAnim_Blast
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_Blast,.Lfe1-Anim_Blast

	.text
	.align	2, 0
