@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_ca57c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_ElectricBite
	.thumb_func
	.type	 Anim_ElectricBite,function
Anim_ElectricBite:
	push	{lr}
	mov	r1, #5
	bl	BaseAnim_Bite_Sting
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_ElectricBite,.Lfe1-Anim_ElectricBite

	.text
	.align	2, 0

	.text
	.align	2, 0
