@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_cf2a0_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_Revive
	.thumb_func
	.type	 Anim_Revive,function
Anim_Revive:
	push	{lr}
	mov	r1, #0
	bl	BaseAnim_Revive
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_Revive,.Lfe1-Anim_Revive

	.text
	.align	2, 0
