@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_ceb30_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_Haunting
	.thumb_func
	.type	 Anim_Haunting,function
Anim_Haunting:
	push	{lr}
	mov	r1, #2
	bl	BaseAnim_HauntAttack
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_Haunting,.Lfe1-Anim_Haunting

	.text
	.align	2, 0

	.text
	.align	2, 0
