@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_e28f4_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80e3944
	.thumb_func
	.type	 Func_80e3944,function
Func_80e3944:
	push	{r5, lr}
	mov	r5, r1
	bl	PhysMove
	ldr	r3, [r5, #4]
	sub	r3, r3, #16
	str	r3, [r5, #4]
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80e3944,.Lfe1-Func_80e3944

	.text
	.align	2, 0

	.text
	.align	2, 0
