@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_e0564_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	UpdateScreenShake
	.thumb_func
	.type	 UpdateScreenShake,function
UpdateScreenShake:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L5
	mov	r6, r0
	mov	r7, r1
	ldr	r0, .L5+4
	ldr	r1, [r3]
	add	r0, r0, r1
	ldr	r3, [r0]
	mov	r8, r0
	cmp	r3, #0
	ble	.L3
	bl	Random
	sub	r6, r6, #1
	and	r6, r6, r0
	bl	Random
	lsr	r5, r7, #31
	add	r5, r7, r5
	sub	r2, r7, #1
	asr	r5, r5, #1
	and	r2, r2, r0
	sub	r2, r2, r5
	ldr	r1, .L5+8
	mov	r3, r2
	sub	r6, r6, r5
	add	r3, r3, #32
	strh	r6, [r1, #4]
	strh	r3, [r1, #6]
	ldr	r1, .L5+12
	mov	r3, #120
	sub	r6, r3, r6
	sub	r3, r3, r2
	str	r6, [r1, #12]
	str	r3, [r1, #16]
	mov	r2, r8
	ldr	r3, [r2]
	sub	r3, r3, #1
	str	r3, [r2]
	b	.L4
.L3:
	ldr	r0, .L5+16
	add	r3, r1, r0
	ldr	r3, [r3]
	ldr	r2, .L5+8
	add	r0, r0, #4
	strh	r3, [r2, #4]
	add	r3, r1, r0
	ldr	r3, [r3]
	strh	r3, [r2, #6]
	ldr	r2, .L5+12
	mov	r3, #120
	str	r3, [r2, #12]
	str	r3, [r2, #16]
.L4:
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001eec
	.word	30632
	.word	iwram_3001ad0
	.word	gPhysVec
	.word	30624
.Lfe1:
	.size	 UpdateScreenShake,.Lfe1-UpdateScreenShake

	.text
	.align	2, 0
