@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_e28f4_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Anim_RapidSmash
	.thumb_func
	.type	 Anim_RapidSmash,function
Anim_RapidSmash:
	push	{lr}
	ldr	r3, [r0, #24]
	cmp	r3, #0
	bne	.L3
	mov	r1, #6
	bl	BaseAnim_RapidSlash
	b	.L4
.L3:
	cmp	r3, #1
	bne	.L5
	mov	r1, #7
	bl	BaseAnim_RapidSlash
	b	.L4
.L5:
	mov	r1, #8
	bl	BaseAnim_RapidSlash
.L4:
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Anim_RapidSmash,.Lfe1-Anim_RapidSmash

	.text
	.align	2, 0
