@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_200950c
	.thumb_func
	.type	 OvlFunc_882_200950c,function
OvlFunc_882_200950c:
	push	{r5, lr}
	bl	__CutsceneStart
	mov	r1, #131
	mov	r0, #0
	lsl	r1, r1, #1
	ldr	r2, .L7
	bl	__Func_80921c4
	mov	r1, #131
	mov	r0, #20
	lsl	r1, r1, #17
	ldr	r2, .L7+4
	bl	__MapActor_SetPos
	mov	r1, #131
	mov	r0, #20
	lsl	r1, r1, #1
	ldr	r2, .L7+8
	bl	__Func_809218c
	mov	r1, #128
	mov	r2, #128
	mov	r0, #0
	lsl	r1, r1, #10
	lsl	r2, r2, #9
	bl	__MapActor_SetSpeed
	mov	r0, #0
	mov	r1, #2
	mov	r2, #0
	bl	__MapActor_Jump
	mov	r1, #141
	ldr	r2, .L7+12
	mov	r0, #0
	lsl	r1, r1, #1
	bl	__Func_80921c4
	mov	r0, #20
	mov	r1, #1
	bl	__MapActor_SetAnim
	mov	r0, #0
	mov	r1, #4
	mov	r2, #0
	bl	__MapActor_Jump
	mov	r2, #0
	mov	r1, #20
	mov	r0, #0
	bl	__Func_8092848
	bl	__Func_809202c
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #2
	bl	__Func_80925cc
	mov	r1, #128
	mov	r2, #20
	lsl	r1, r1, #1
	mov	r0, #20
	bl	__MapActor_Emote
	ldr	r5, .L7+16
	mov	r0, r5
	bl	__MessageID
	mov	r1, #0
	mov	r0, #20
	bl	__ActorMessage
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #0
	mov	r0, #20
	bl	__Func_8093054
	add	r5, r5, #4
	mov	r1, #2
	mov	r0, #20
	bl	__Func_80925cc
	mov	r0, r5
	bl	__MessageID
	mov	r2, #20
	mov	r0, #20
	mov	r1, #0
	bl	__Func_8093040
	ldr	r1, .L7+20
	mov	r0, #20
	bl	__MapActor_RunScript
	ldr	r0, .L7+24
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r5}
	pop	{r0}
	bx	r0
.L8:
	.align	2, 0
.L7:
	.word	810
	.word	52756480
	.word	825
	.word	855
	.word	3687
	.word	gScript_882__0200c8c0
	.word	2101
.Lfe1:
	.size	 OvlFunc_882_200950c,.Lfe1-OvlFunc_882_200950c

	.text
	.align	2, 0
