@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_200c5b8
	.thumb_func
	.type	 OvlFunc_882_200c5b8,function
OvlFunc_882_200c5b8:
	push	{r5, r6, lr}
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r6, [r0, #80]
	mov	r0, #22
	bl	__MapActor_GetActor
	ldr	r0, [r0, #80]
	ldrb	r3, [r6, #9]
	mov	r5, #13
	ldrb	r1, [r0, #9]
	neg	r5, r5
	mov	r2, #12
	and	r2, r2, r3
	mov	r3, r5
	and	r3, r3, r1
	orr	r3, r3, r2
	strb	r3, [r0, #9]
	mov	r0, #8
	bl	__MapActor_GetActor
	ldrb	r2, [r6, #9]
	ldr	r1, [r0, #80]
	mov	r3, #12
	and	r3, r3, r2
	ldrb	r2, [r1, #9]
	and	r5, r5, r2
	orr	r5, r5, r3
	strb	r5, [r1, #9]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_882_200c5b8,.Lfe1-OvlFunc_882_200c5b8

	.text
	.align	2, 0
