@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_c_c_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_2009348
	.thumb_func
	.type	 OvlFunc_882_2009348,function
OvlFunc_882_2009348:
	push	{r5, lr}
	ldr	r0, .L10
	bl	__GetFlag
	cmp	r0, #0
	beq	.LCB8
	b	.L3	@long jump
.LCB8:
	bl	__CutsceneStart
	ldr	r0, .L10+4
	bl	__GetFlag
	cmp	r0, #0
	bne	.L4
	mov	r0, #14
	bl	__MapActor_GetActor
	mov	r1, #128
	mov	r5, r0
	mov	r2, #128
	mov	r0, #128
	lsl	r1, r1, #11
	lsl	r2, r2, #9
	lsl	r0, r0, #11
	bl	__Func_8012330
	mov	r0, #141
	bl	__PlaySound
	mov	r0, #40
	bl	__WaitFrames
	mov	r0, #145
	bl	__PlaySound
	mov	r1, #237
	mov	r0, #14
	lsl	r1, r1, #17
	ldr	r2, .L10+8
	bl	__MapActor_SetPos
	mov	r3, #128
	lsl	r3, r3, #9
	str	r3, [r5, #48]
	str	r3, [r5, #52]
	mov	r2, #144
	ldr	r3, [r5, #12]
	lsl	r2, r2, #15
	add	r3, r3, r2
	str	r3, [r5, #12]
	str	r3, [r5, #60]
	mov	r3, #128
	lsl	r3, r3, #8
	mov	r1, #216
	str	r3, [r5, #68]
	lsl	r1, r1, #1
	ldr	r2, .L10+12
	mov	r0, #14
	bl	__Func_80921c4
	mov	r0, #40
	bl	__CutsceneWait
	ldr	r0, .L10+16
	bl	__PlaySound
	mov	r0, #1
	mov	r1, #1
	neg	r0, r0
	neg	r1, r1
	ldr	r2, .L10+20
	bl	__Func_8012330
	bl	__Func_8012350
	bl	__Func_809202c
	ldr	r0, .L10+4
	bl	__SetFlag
.L4:
	bl	OvlFunc_882_2009498
	ldr	r0, .L10
	bl	__SetFlag
	ldr	r0, .L10+24
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	ldr	r0, .L10+28
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	mov	r0, #195
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	bne	.L5
	mov	r0, #0
	bl	__MapActor_GetActor
	ldr	r2, .L10+32
	ldr	r3, [r0, #16]
	cmp	r3, r2
	bgt	.L8
	mov	r0, #206
	mov	r1, #140
	lsl	r0, r0, #1
	lsl	r1, r1, #3
	bl	OvlFunc_882_2009a64
	mov	r1, #207
	mov	r0, #0
	lsl	r1, r1, #1
	ldr	r2, .L10+36
	bl	__Func_80921c4
	b	.L9
.L8:
	ldr	r0, .L10+40
	ldr	r1, .L10+44
	bl	OvlFunc_882_2009a64
	mov	r0, #0
	ldr	r1, .L10+48
	ldr	r2, .L10+52
	bl	__Func_80921c4
.L9:
	mov	r0, #195
	lsl	r0, r0, #2
	bl	__SetFlag
.L5:
	bl	__CutsceneEnd
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	787
	.word	2099
	.word	75169792
	.word	1147
	.word	289
	.word	58982
	.word	2103
	.word	2113
	.word	75104255
	.word	1068
	.word	445
	.word	1172
	.word	447
	.word	1227
.Lfe1:
	.size	 OvlFunc_882_2009348,.Lfe1-OvlFunc_882_2009348

	.text
	.align	2, 0
