@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_200c278
	.thumb_func
	.type	 OvlFunc_882_200c278,function
OvlFunc_882_200c278:
	push	{lr}
	bl	__CutsceneStart
	ldr	r3, .L3
	ldr	r1, [r3]
	mov	r3, #224
	lsl	r3, r3, #1
	add	r2, r1, r3
	add	r3, r3, #64
	str	r3, [r2]
	sub	r3, r3, #56
	add	r2, r1, r3
	mov	r3, #64
	str	r3, [r2]
	ldr	r0, .L3+4
	bl	__SetFlag
	mov	r1, #3
	mov	r0, #12
	bl	__Func_8091eb0
	mov	r0, #144
	lsl	r0, r0, #4
	bl	__SetFlag
	bl	__CutsceneEnd
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001ebc
	.word	2175
.Lfe1:
	.size	 OvlFunc_882_200c278,.Lfe1-OvlFunc_882_200c278

	.text
	.align	2, 0
