@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_882_2008328
	.thumb_func
	.type	 OvlFunc_882_2008328,function
OvlFunc_882_2008328:
	push	{lr}
	mov	r0, #158
	bl	__PlaySound
	ldr	r0, .L3
	mov	r1, #49
	mov	r2, #69
	bl	__Func_8010560
	mov	r1, #163
	lsl	r1, r1, #1
	ldr	r2, .L3+4
	mov	r0, #0
	bl	__Func_809218c
	mov	r0, #3
	bl	__CutsceneWait
	mov	r0, #8
	bl	OvlFunc_882_200815c
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	.L57a0
	.word	1126
.Lfe1:
	.size	 OvlFunc_882_2008328,.Lfe1-OvlFunc_882_2008328

	.text
	.align	2, 0
