@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_97384_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Field_MindRead
	.thumb_func
	.type	 Field_MindRead,function
Field_MindRead:
	push	{r5, r6, lr}
	mov	r6, r8
	push	{r6}
	mov	r8, r1
	mov	r1, #166
	lsl	r1, r1, #2
	mov	r6, r0
	mov	r0, #22
	sub	sp, sp, #4
	bl	galloc_ewram
	mov	r5, r0
	bl	Func_8097384
	mov	r3, #0
	mov	r0, sp
	str	r3, [r0]
	mov	r1, r5
	ldr	r3, .L11
	ldr	r2, .L11+4
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	ldr	r3, .L11+8
	ldr	r0, [r3]
	mov	r1, #180
	lsl	r1, r1, #1
	lsl	r0, r0, #1
	bl	__umodsi3
	ldr	r2, .L11+12
	add	r3, r5, r2
	strh	r0, [r3]
	bl	Func_80978c4
	ldr	r2, .L11+16
	add	r3, r5, r2
	sub	r2, r2, #1
	mov	r0, #0
	ldrsb	r0, [r3, r0]
	add	r3, r5, r2
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	sub	r2, r2, #1
	lsl	r3, r3, #5
	lsl	r0, r0, #10
	orr	r0, r0, r3
	add	r3, r5, r2
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	orr	r0, r0, r3
	mov	r3, #128
	lsl	r3, r3, #14
	orr	r0, r0, r3
	mov	r1, #1
	bl	Func_8091200
	mov	r0, #8
	bl	Func_8091254
	mov	r2, #164
	lsl	r2, r2, #2
	add	r3, r5, r2
	add	r2, r2, #2
	strh	r6, [r3]
	add	r3, r5, r2
	mov	r2, r8
	strh	r2, [r3]
	mov	r3, #165
	lsl	r3, r3, #2
	add	r5, r5, r3
	mov	r3, #8
	strb	r3, [r5]
	bl	Func_8097a7c
	mov	r1, #200
	lsl	r1, r1, #4
	ldr	r0, .L11+20
	bl	StartTask
	add	sp, sp, #4
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	67109076
	.word	-2063597402
	.word	iwram_3001e40
	.word	654
	.word	653
	.word	Task_08097644
.Lfe1:
	.size	 Field_MindRead,.Lfe1-Field_MindRead

	.text
	.align	2, 0
