@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	MapActor_TravelTo
	.thumb_func
	.type	 MapActor_TravelTo,function
MapActor_TravelTo:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	mov	r7, r2
	bl	GetFieldActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L3
	mov	r2, r5
	add	r2, r2, #91
	mov	r3, #0
	strb	r3, [r2]
	bl	_Actor_Stop
	lsl	r1, r6, #16
	ldr	r2, [r5, #12]
	lsl	r3, r7, #16
	mov	r0, r5
	bl	_Actor_TravelTo
.L3:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 MapActor_TravelTo,.Lfe1-MapActor_TravelTo
	.align	2, 0
	.global	Func_8092158
	.thumb_func
	.type	 Func_8092158,function
Func_8092158:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	mov	r7, r2
	bl	GetFieldActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L5
	mov	r2, r5
	add	r2, r2, #91
	mov	r3, #0
	strb	r3, [r2]
	bl	_Actor_Stop
	mov	r0, r5
	lsl	r1, r6, #16
	ldr	r2, [r5, #12]
	lsl	r3, r7, #16
	bl	_Actor_TravelTo
	mov	r0, r5
	bl	_Actor_WaitMovement
.L5:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe2:
	.size	 Func_8092158,.Lfe2-Func_8092158
	.align	2, 0
	.global	Func_809218c
	.thumb_func
	.type	 Func_809218c,function
Func_809218c:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	mov	r7, r2
	bl	GetFieldActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L7
	mov	r2, r5
	add	r2, r2, #91
	mov	r3, #0
	strb	r3, [r2]
	bl	_Actor_Stop
	mov	r0, r5
	mov	r1, #2
	bl	_Actor_SetAnim
	lsl	r1, r6, #16
	ldr	r2, [r5, #12]
	lsl	r3, r7, #16
	mov	r0, r5
	bl	_Actor_TravelTo
.L7:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe3:
	.size	 Func_809218c,.Lfe3-Func_809218c
	.align	2, 0
	.global	Func_80921c4
	.thumb_func
	.type	 Func_80921c4,function
Func_80921c4:
	push	{r5, r6, r7, lr}
	mov	r6, r1
	mov	r7, r2
	bl	GetFieldActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L9
	mov	r2, r5
	add	r2, r2, #91
	mov	r3, #0
	strb	r3, [r2]
	bl	_Actor_Stop
	mov	r0, r5
	mov	r1, #2
	bl	_Actor_SetAnim
	lsl	r1, r6, #16
	ldr	r2, [r5, #12]
	lsl	r3, r7, #16
	mov	r0, r5
	bl	_Actor_TravelTo
	mov	r0, r5
	bl	_Actor_WaitMovement
	mov	r0, r5
	mov	r1, #1
	bl	_Actor_SetAnim
.L9:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe4:
	.size	 Func_80921c4,.Lfe4-Func_80921c4

	.text
	.align	2, 0
