@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8d9a4_c_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8091240
	.thumb_func
	.type	 Func_8091240,function
Func_8091240:
	push	{lr}
	ldr	r3, .L4
	ldr	r3, [r3]
	cmp	r3, #0
	beq	.L3
	strh	r0, [r3]
.L3:
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ed0
.Lfe1:
	.size	 Func_8091240,.Lfe1-Func_8091240

	.text
	.align	2, 0
