@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_944ec_a_c_a_c_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	GetMercuryDjinni
	.thumb_func
	.type	 GetMercuryDjinni,function
GetMercuryDjinni:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #52
	mov	r5, r0
	bl	MapActor_GetActor
	mov	r6, r0
	cmp	r6, #0
	bne	.LCB11
	b	.L2	@long jump
.LCB11:
	bl	Func_80958a8
	ldr	r3, .L17
	ldr	r3, [r3]
	ldr	r0, .L17+4
	str	r3, [sp, #4]
	bl	_Func_80b0840
	mov	r0, #30
	bl	WaitFrames
	mov	r2, r6
	mov	r3, #0
	add	r2, r2, #91
	strb	r3, [r2]
	mov	r0, #173
	bl	_PlaySound
	mov	r1, #1
	mov	r0, r5
	bl	Func_80925cc
	mov	r0, #175
	bl	_PlaySound
	mov	r1, #1
	mov	r0, r5
	bl	Func_80925cc
	mov	r0, #20
	bl	WaitFrames
	mov	r0, #152
	bl	_PlaySound
	mov	r1, #3
	mov	r2, #14
	mov	r0, r5
	bl	MapActor_Jump
	mov	r0, #152
	bl	_PlaySound
	mov	r1, #5
	mov	r2, #16
	mov	r0, r5
	bl	MapActor_Jump
	mov	r0, #152
	bl	_PlaySound
	mov	r1, #7
	mov	r2, #18
	mov	r0, r5
	bl	MapActor_Jump
	mov	r0, #20
	bl	WaitFrames
	ldr	r3, [r6, #80]
	ldr	r3, [r3, #40]
	mov	r2, #0
	ldrsh	r1, [r3, r2]
	mov	r9, r1
	add	r1, sp, #20
	mov	r3, #0
	str	r1, [sp]
	mov	sl, r3
	mov	r8, r6
	mov	fp, r1
	mov	r7, #7
.L4:
	ldr	r2, [r6, #12]
	ldr	r3, [r6, #16]
	ldr	r1, [r6, #8]
	mov	r0, r9
	bl	_CreateActor
	ldr	r3, [sp]
	mov	r5, r0
	stmia	r3!, {r5}
	mov	r2, r3
	str	r2, [sp]
	cmp	r5, #0
	beq	.L5
	mov	r3, #240
	lsl	r3, r3, #8
	mov	r2, r5
	str	r3, [r5, #28]
	str	r3, [r5, #24]
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	sub	r2, r2, #50
	mov	r3, #2
	strb	r3, [r2]
	mov	r1, r5
	add	r1, r1, #90
	ldrb	r3, [r1]
	mov	r2, #1
	orr	r3, r3, r2
	strb	r3, [r1]
	ldr	r3, .L17+8
	str	r3, [r5, #108]
	ldrh	r3, [r6, #6]
	mov	r1, #9
	strh	r3, [r5, #6]
	bl	_Actor_SetColorswap
	mov	r0, r5
	mov	r1, #0
	bl	_Actor_SetAnim
	mov	r0, r5
	mov	r1, #0
	bl	_Actor_SetSpriteFlags
	mov	r1, sl
	ldr	r0, [r5, #80]
	bl	Func_8096c48
	mov	r1, r8
	str	r1, [r5, #104]
	mov	sl, r0
	mov	r8, r5
.L5:
	sub	r7, r7, #1
	cmp	r7, #0
	bge	.L4
	mov	r2, sl
	ldrb	r2, [r2, #28]
	mov	r0, #153
	mov	r8, r2
	bl	_PlaySound
	mov	r2, r6
	add	r2, r2, #85
	mov	r3, #0
	strb	r3, [r2]
	mov	r7, #14
.L7:
	ldr	r3, [r6, #12]
	mov	r1, #128
	lsl	r1, r1, #12
	add	r3, r3, r1
	str	r3, [r6, #12]
	mov	r0, #1
	sub	r7, r7, #1
	bl	WaitFrames
	cmp	r7, #0
	bge	.L7
	mov	r0, r6
	bl	_DeleteActor
	mov	r5, fp
	mov	r7, #7
.L9:
	ldmia	r5!, {r0}
	sub	r7, r7, #1
	bl	_DeleteActor
	cmp	r7, #0
	bge	.L9
	mov	r2, r8
	cmp	r2, #96
	beq	.L11
	mov	r0, r8
	bl	Func_8003f3c
.L11:
	mov	r0, #10
	bl	WaitFrames
	ldr	r5, .L17+12
	mov	r3, #250
	lsl	r3, r3, #1
	add	r5, r5, r3
	mov	r1, #128
	mov	r2, #0
	lsl	r1, r1, #7
	ldr	r0, [r5]
	bl	Func_8092adc
	mov	r0, #20
	bl	WaitFrames
	ldr	r0, [r5]
	bl	MapActor_GetActor
	mov	r1, #28
	bl	_Actor_SetAnim
	mov	r0, #20
	bl	WaitFrames
	ldr	r3, [r6, #8]
	add	r5, sp, #8
	str	r3, [r5]
	ldr	r3, [r6, #12]
	str	r3, [r5, #4]
	ldr	r3, [r6, #16]
	mov	r0, r5
	str	r3, [r5, #8]
	bl	Func_80974d8
	ldr	r6, [sp, #4]
	mov	r7, #23
	add	r6, r6, #88
.L12:
	ldr	r2, [r5]
	ldr	r3, [r5, #8]
	mov	r0, r6
	mov	r1, #240
	bl	Func_809ba90
	mov	r0, r6
	ldr	r1, .L17+16
	bl	Func_809ba7c
	mov	r0, r6
	mov	r1, #7
	bl	Func_809ba70
	ldr	r0, [r6]
	mov	r1, #9
	bl	_Sprite_SetColorswap
	sub	r7, r7, #1
	mov	r0, #1
	bl	WaitFrames
	add	r6, r6, #72
	cmp	r7, #0
	bge	.L12
	mov	r0, #120
	bl	WaitFrames
	ldr	r2, [sp, #4]
	mov	r1, #2
	add	r2, r2, #152
	mov	r7, #23
.L14:
	mov	r3, #5
	ldrsb	r3, [r2, r3]
	cmp	r3, #0
	beq	.L15
	strb	r1, [r2]
.L15:
	sub	r7, r7, #1
	add	r2, r2, #72
	cmp	r7, #0
	bge	.L14
	mov	r0, #50
	bl	WaitFrames
	bl	_Func_80b0894
	bl	Func_80958e4
.L2:
	add	sp, sp, #52
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	iwram_3001f30
	.word	2113668
	.word	Func_8096574
	.word	gState
	.word	Func_809641c
.Lfe1:
	.size	 GetMercuryDjinni,.Lfe1-GetMercuryDjinni

	.text
	.align	2, 0
