@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_a_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	CutsceneWait
	.thumb_func
	.type	 CutsceneWait,function
CutsceneWait:
	push	{lr}
	ldr	r3, .L4
	mov	r2, #230
	ldr	r3, [r3]
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r3, [r3]
	cmp	r3, #0
	bne	.L3
	cmp	r0, #0
	beq	.L3
	bl	WaitFrames
.L3:
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ebc
.Lfe1:
	.size	 CutsceneWait,.Lfe1-CutsceneWait

	.text
	.align	2, 0
