@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_c_c_c_c_a_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_809233c
	.thumb_func
	.type	 Func_809233c,function
Func_809233c:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r6, r0
	mov	r7, r1
	mov	r8, r2
	mov	sl, r3
	bl	GetFieldActor
	mov	r5, r0
	cmp	r5, #0
	beq	.L3
	ldr	r2, .L5
	mov	r0, r6
	ldr	r1, .L5+4
	bl	MapActor_SetSpeed
	ldr	r3, .L5+8
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r0, [r3]
	bl	MapActor_GetActor
	cmp	r0, #0
	beq	.L4
	ldr	r1, [r0, #8]
	ldr	r2, [r0, #16]
	mov	r0, r6
	bl	MapActor_SetPos
.L4:
	mov	r2, r5
	mov	r3, #0
	add	r2, r2, #91
	strb	r3, [r2]
	mov	r0, r5
	mov	r1, #2
	bl	_Actor_SetAnim
	mov	r2, r8
	mov	r0, r6
	mov	r1, r7
	bl	Func_809228c
	ldr	r1, .L5+12
	mov	r0, r5
	bl	_Actor_SetScript
	mov	r3, r5
	add	r3, r3, #100
	mov	r2, sl
	strh	r2, [r3]
.L3:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	19660
	.word	39321
	.word	gState
	.word	.L9fbcc
.Lfe1:
	.size	 Func_809233c,.Lfe1-Func_809233c

	.text
	.align	2, 0
