@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_96cdc_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8096f50
	.thumb_func
	.type	 Func_8096f50,function
Func_8096f50:
	push	{r5, r6, lr}
	ldr	r5, .L5
	ldr	r3, [r5]
	mov	r2, #1
	and	r3, r3, r2
	mov	r6, r0
	cmp	r3, #0
	beq	.L3
	ldr	r0, [r5]
	mov	r1, #6
	lsr	r0, r0, #1
	bl	__umodsi3
	mov	r1, r0
	mov	r0, r6
	bl	_Actor_SetColorswap
.L3:
	ldr	r3, [r5]
	mov	r2, #15
	and	r3, r3, r2
	cmp	r3, #0
	bne	.L4
	mov	r0, r6
	bl	Func_8096ddc
.L4:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001e40
.Lfe1:
	.size	 Func_8096f50,.Lfe1-Func_8096f50

	.text
	.align	2, 0
