@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8d9a4_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_808f304
	.thumb_func
	.type	 Func_808f304,function
Func_808f304:
	push	{lr}
	ldr	r3, .L4
	ldr	r3, [r3]
	mov	r0, #0
	cmp	r3, #0
	beq	.L3
	ldr	r2, .L4+4
	add	r3, r3, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	neg	r0, r3
	orr	r0, r0, r3
	lsr	r0, r0, #31
.L3:
	pop	{r1}
	bx	r1
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ebc
	.word	3256
.Lfe1:
	.size	 Func_808f304,.Lfe1-Func_808f304

	.text
	.align	2, 0
