@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_925e0_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_809294c
	.thumb_func
	.type	 Func_809294c,function
Func_809294c:
	bx	lr
.Lfe1:
	.size	 Func_809294c,.Lfe1-Func_809294c

	.text
	.align	2, 0
