@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8d9a4_a_a_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_808df1c
	.thumb_func
	.type	 Func_808df1c,function
Func_808df1c:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	sub	sp, sp, #12
	mov	r8, r1
	mov	r1, #1
	str	r0, [sp, #8]
	neg	r1, r1
	mov	r0, r8
	str	r1, [sp, #4]
	bl	Func_808ddb8
	str	r0, [sp]
	ldr	r0, [sp, #8]
	bl	GetFieldActor
	mov	r7, r0
	cmp	r7, #0
	bne	.LCB17
	b	.L3	@long jump
.LCB17:
	ldrh	r3, [r7, #6]
	mov	r2, #128
	lsl	r2, r2, #6
	add	r2, r2, r3
	mov	r3, #192
	lsl	r3, r3, #8
	and	r2, r2, r3
	mov	r3, #0
	mov	fp, r2
	mov	r9, r3
.L7:
	ldr	r1, [sp, #8]
	cmp	r9, r1
	beq	.L6
	mov	r0, r9
	bl	GetFieldActor
	mov	r6, r0
	cmp	r6, #0
	beq	.L6
	mov	r2, #89
	add	r2, r2, r6
	mov	sl, r2
	ldrb	r2, [r2]
	mov	r3, #8
	and	r3, r3, r2
	cmp	r3, #0
	bne	.L6
	mov	r0, #128
	mov	r3, r8
	lsl	r0, r0, #12
	cmp	r3, #13
	bne	.L11
	mov	r0, #192
	lsl	r0, r0, #14
.L11:
	mov	r1, r8
	cmp	r1, #5
	bne	.L12
	mov	r0, #128
	lsl	r0, r0, #15
.L12:
	mov	r2, r8
	cmp	r2, #2
	bne	.L13
	mov	r0, #128
	lsl	r0, r0, #13
.L13:
	ldr	r1, [r6, #12]
	ldr	r3, [r7, #12]
	sub	r2, r1, r3
	cmp	r2, #0
	blt	.L14
	cmp	r2, r0
	ble	.L16
	b	.L6
.L14:
	sub	r3, r3, r1
	cmp	r3, r0
	bgt	.L6
.L16:
	ldr	r2, [r6, #8]
	ldr	r3, [r7, #8]
	sub	r0, r2, r3
	cmp	r0, #0
	bge	.L18
	ldr	r3, .L28
	add	r0, r0, r3
.L18:
	ldr	r2, [r6, #16]
	ldr	r3, [r7, #16]
	sub	r2, r2, r3
	asr	r0, r0, #16
	cmp	r2, #0
	bge	.L19
	ldr	r1, .L28
	add	r2, r2, r1
.L19:
	asr	r3, r2, #16
	mov	r1, r3
	mul	r1, r1, r3
	mov	r2, r0
	mul	r2, r2, r0
	mov	r3, r1
	mov	r0, r2
	add	r0, r0, r3
	ldr	r3, .L28+4
	bl	_call_via_r3
	mov	r3, sl
	ldrb	r2, [r3]
	mov	r3, #16
	and	r3, r3, r2
	mov	r5, r0
	cmp	r3, #0
	beq	.L20
	lsl	r0, r5, #1
	mov	r1, #3
	bl	__divsi3
	mov	r5, r0
.L20:
	ldr	r1, [sp]
	cmp	r5, r1
	bge	.L6
	ldr	r3, [r7, #16]
	ldr	r0, [r6, #16]
	ldr	r1, [r6, #8]
	sub	r0, r0, r3
	ldr	r3, [r7, #8]
	sub	r1, r1, r3
	bl	atan2
	mov	r2, #192
	lsl	r0, r0, #16
	lsr	r0, r0, #16
	lsl	r2, r2, #5
	cmp	r5, #19
	ble	.L22
	mov	r2, #128
	lsl	r2, r2, #5
.L22:
	mov	r3, r8
	cmp	r3, #2
	bne	.L23
	mov	r2, #128
	lsl	r2, r2, #6
.L23:
	cmp	r5, #11
	ble	.L24
	mov	r1, fp
	sub	r3, r0, r1
	lsl	r3, r3, #16
	asr	r0, r3, #16
	cmp	r0, #0
	bge	.L25
	neg	r0, r0
.L25:
	cmp	r0, r2
	bge	.L6
.L24:
	mov	r2, r9
	str	r2, [sp, #4]
	str	r5, [sp]
.L6:
	mov	r3, #1
	add	r9, r9, r3
	mov	r1, r9
	cmp	r1, #66
	ble	.L7
.L3:
	ldr	r0, [sp, #4]
	add	sp, sp, #12
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L29:
	.align	2, 0
.L28:
	.word	65535
	.word	Func_8000948
.Lfe1:
	.size	 Func_808df1c,.Lfe1-Func_808df1c

	.text
	.align	2, 0
