@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_c_c_c_c_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	MapActor_SetAnimSpeed
	.thumb_func
	.type	 MapActor_SetAnimSpeed,function
MapActor_SetAnimSpeed:
	push	{r5, lr}
	mov	r5, r1
	bl	GetFieldActor
	cmp	r0, #0
	beq	.L2
	mov	r1, r5
	bl	_Actor_SetAnimSpeed
.L2:
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 MapActor_SetAnimSpeed,.Lfe1-MapActor_SetAnimSpeed

	.text
	.align	2, 0
