@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_97b54_a_c_c_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80992f0
	.thumb_func
	.type	 Func_80992f0,function
Func_80992f0:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r6, r5
	add	r6, r6, #100
	mov	r3, #0
	ldrsh	r0, [r6, r3]
	lsl	r0, r0, #9
	bl	sin
	mov	r1, r0
	mov	r0, #128
	ldr	r3, .L6
	lsl	r0, r0, #11
		.align	2, 0
	mov	r12, pc
	bx	r3
	.code	16
	ldr	r3, [r5, #56]
	add	r3, r3, r0
	str	r3, [r5, #8]
	ldrh	r3, [r6]
	add	r3, r3, #1
	strh	r3, [r6]
	lsl	r3, r3, #16
	asr	r1, r3, #16
	mov	r2, r1
	add	r2, r2, #128
	mov	r3, r2
	cmp	r2, #0
	bge	.L5
	mov	r3, r1
	add	r3, r3, #255
.L5:
	asr	r3, r3, #7
	lsl	r3, r3, #7
	sub	r3, r2, r3
	strh	r3, [r6]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L7:
	.align	2, 0
.L6:
	.word	Func_8000888
.Lfe1:
	.size	 Func_80992f0,.Lfe1-Func_80992f0

	.text
	.align	2, 0
