@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_9bb64_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_809c3a4
	.thumb_func
	.type	 Func_809c3a4,function
Func_809c3a4:
	push	{r5, r6, lr}
	ldr	r1, .L9
	mov	r0, #27
	bl	galloc_ewram
	mov	r2, #207
	lsl	r2, r2, #1
	add	r3, r0, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #3
	bne	.L3
	bl	Func_800430c
	bl	Func_809c314
	bl	Func_8091660
	mov	r1, #6
	ldr	r0, .L9+4
	bl	Func_80936a0
	ldr	r1, .L9+8
	mov	r2, #128
	ldr	r3, [r1]
	lsl	r2, r2, #2
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L8
	mov	r6, r1
	mov	r5, r2
.L6:
	mov	r0, #1
	bl	WaitFrames
	ldr	r3, [r6]
	and	r3, r3, r5
	cmp	r3, #0
	bne	.L6
.L8:
	mov	r0, #128
	lsl	r0, r0, #9
	mov	r1, #6
	bl	Func_80936a0
	bl	Func_80043e0
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L10:
	.align	2, 0
.L9:
	.word	3276
	.word	40329
	.word	gKeyHeld
.Lfe1:
	.size	 Func_809c3a4,.Lfe1-Func_809c3a4

	.text
	.align	2, 0
