@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_c_c_c_c_a_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8092504
	.thumb_func
	.type	 Func_8092504,function
Func_8092504:
	push	{r5, r6, r7, lr}
	sub	sp, sp, #4
	bl	GetFieldActor
	cmp	r0, #0
	beq	.L2
	mov	r3, r0
	add	r3, r3, #84
	ldrb	r3, [r3]
	cmp	r3, #1
	bne	.L2
	ldr	r3, [r0, #80]
	mov	r6, r3
	add	r6, r6, #36
	ldrb	r3, [r6]
	mov	r7, sp
	mov	r5, #0
	str	r3, [r7]
	b	.L5
.L7:
	add	r5, r5, #1
.L5:
	cmp	r5, #89
	bgt	.L2
	mov	r0, #1
	bl	WaitFrames
	ldrb	r2, [r6]
	ldr	r3, [r7]
	cmp	r3, r2
	beq	.L7
.L2:
	add	sp, sp, #4
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8092504,.Lfe1-Func_8092504

	.text
	.align	2, 0
