@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8d9a4_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_808ed1c
	.thumb_func
	.type	 Func_808ed1c,function
Func_808ed1c:
	push	{lr}
	bl	GetMapActorIndex
	mov	r2, #1
	neg	r2, r2
	cmp	r0, r2
	beq	.L3
	ldr	r3, .L5
	ldr	r3, [r3]
	lsl	r2, r0, #3
	add	r3, r3, r2
	mov	r2, #142
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r0, [r3]
	cmp	r0, #0
	beq	.L3
	mov	r1, #2
	bl	_Actor_SetAnim
.L3:
	pop	{r0}
	bx	r0
.L6:
	.align	2, 0
.L5:
	.word	iwram_3001ebc
.Lfe1:
	.size	 Func_808ed1c,.Lfe1-Func_808ed1c

	.text
	.align	2, 0
