@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_9b698_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_809ba34
	.thumb_func
	.type	 Func_809ba34,function
Func_809ba34:
	push	{lr}
	mov	r3, r0
	add	r3, r3, #65
	ldrb	r3, [r3, #0]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	cmp	r3, #0
	bne	.L3
	mov	r0, #0
	b	.L2
.L3:
	ldr	r3, [r0, #12]
	mov	r2, #128
	lsl	r2, r2, #24
	eor	r3, r3, r2
	neg	r0, r3
	orr	r0, r0, r3
	lsr	r0, r0, #31
.L2:
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_809ba34,.Lfe1-Func_809ba34

	.text
	.align	2, 0
