@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8d9a4_c_c_c_a_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8091254
	.thumb_func
	.type	 Func_8091254,function
Func_8091254:
	push	{r5, lr}
	ldr	r3, .L4
	ldr	r4, [r3]
	mov	r5, r0
	cmp	r4, #0
	beq	.L3
	ldr	r1, .L4+4
	add	r3, r4, r1
	add	r1, r1, #1
	mov	r2, #0
	strb	r5, [r3]
	add	r3, r4, r1
	strb	r2, [r3]
	mov	r3, #224
	lsl	r3, r3, #4
	mov	r2, #224
	add	r1, r4, r3
	mov	r3, #196
	lsl	r2, r2, #2
	lsl	r3, r3, #5
	add	r0, r4, r2
	add	r2, r4, r3
	mov	r3, r5
	bl	Func_809088c
.L3:
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ed0
	.word	10753
.Lfe1:
	.size	 Func_8091254,.Lfe1-Func_8091254

	.text
	.align	2, 0
