@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_a_c_c_a_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8091ff0
	.thumb_func
	.type	 Func_8091ff0,function
Func_8091ff0:
	push	{r5, lr}
	ldr	r3, .L4
	ldr	r2, .L4+4
	ldr	r3, [r3]
	mov	r5, r0
	add	r3, r3, r2
	strh	r5, [r3]
	mov	r2, #1
	lsl	r3, r5, #16
	asr	r3, r3, #16
	neg	r2, r2
	cmp	r3, r2
	bne	.L3
	ldr	r5, .L4+8
.L3:
	mov	r0, #149
	lsl	r0, r0, #1
	bl	_PlaySound
	mov	r0, r5
	bl	_PlaySound
	pop	{r5}
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	iwram_3001ebc
	.word	3272
	.word	289
.Lfe1:
	.size	 Func_8091ff0,.Lfe1-Func_8091ff0

	.text
	.align	2, 0
