@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_9a44c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Field_Whirlwind_Target
	.thumb_func
	.type	 Field_Whirlwind_Target,function
Field_Whirlwind_Target:
	push	{lr}
	bl	Field_Whirlwind
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Field_Whirlwind_Target,.Lfe1-Field_Whirlwind_Target

	.text
	.align	2, 0
