@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_97384_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8097384
	.thumb_func
	.type	 Func_8097384,function
Func_8097384:
	push	{r5, lr}
	ldr	r3, .L24
	mov	r2, #154
	ldr	r5, [r3, #20]
	lsl	r2, r2, #5
	ldr	r4, [r3]
	add	r0, r5, r2
	ldr	r2, .L24+4
	ldr	r3, .L24+8
	add	r1, r4, r2
	ldr	r2, .L24+12
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	ldr	r2, .L24+16
	add	r3, r4, r2
	mov	r2, #0
	ldrsh	r3, [r3, r2]
	cmp	r3, #0
	bne	.L13
	mov	r2, #224
	lsl	r2, r2, #4
	add	r0, r5, r2
	ldr	r2, .L24+20
	ldr	r3, .L24+8
	add	r1, r4, r2
	ldr	r2, .L24+12
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
.L13:
	mov	r2, #224
	lsl	r2, r2, #4
	add	r0, r5, r2
	mov	r2, #224
	lsl	r2, r2, #2
	add	r1, r5, r2
	ldr	r3, .L24+8
	ldr	r2, .L24+24
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	ldr	r3, .L24+28
	mov	r0, #164
	ldr	r5, [r3]
	lsl	r0, r0, #1
	mov	r3, #7
	and	r5, r5, r3
	bl	_GetFlag
	cmp	r0, #0
	beq	.L16
	mov	r5, #0
.L16:
	ldr	r0, .L24+32
	bl	_GetFlag
	cmp	r0, #0
	beq	.L17
	mov	r5, #1
.L17:
	mov	r0, #165
	lsl	r0, r0, #1
	bl	_GetFlag
	cmp	r0, #0
	beq	.L18
	mov	r5, #2
.L18:
	ldr	r0, .L24+36
	bl	_GetFlag
	cmp	r0, #0
	beq	.L19
	mov	r5, #3
.L19:
	mov	r0, #166
	lsl	r0, r0, #1
	bl	_GetFlag
	cmp	r0, #0
	beq	.L20
	mov	r5, #4
.L20:
	ldr	r0, .L24+40
	bl	_GetFlag
	cmp	r0, #0
	beq	.L21
	mov	r5, #5
.L21:
	mov	r0, #167
	lsl	r0, r0, #1
	bl	_GetFlag
	cmp	r0, #0
	beq	.L22
	mov	r5, #6
.L22:
	ldr	r0, .L24+44
	bl	_GetFlag
	cmp	r0, #0
	beq	.L23
	mov	r5, #7
.L23:
	ldr	r3, .L24+48
	lsl	r2, r5, #2
	ldr	r0, [r3, r2]
	mov	r1, #1
	bl	Func_8091200
	mov	r0, #8
	bl	Func_8091254
	pop	{r5}
	pop	{r0}
	bx	r0
.L25:
	.align	2, 0
.L24:
	.word	iwram_3001ebc
	.word	1910
	.word	67109076
	.word	-2080374448
	.word	3256
	.word	566
	.word	-2080374112
	.word	iwram_3001e40
	.word	329
	.word	331
	.word	333
	.word	335
	.word	_TBL_a0108
.Lfe1:
	.size	 Func_8097384,.Lfe1-Func_8097384

	.text
	.align	2, 0
