@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_92950_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8092b08
	.thumb_func
	.type	 Func_8092b08,function
Func_8092b08:
	push	{r5, r6, lr}
	mov	r5, r1
	bl	GetFieldActor
	mov	r6, r0
	cmp	r6, #0
	beq	.L3
	mov	r3, r6
	add	r3, r3, #84
	ldrb	r2, [r3]
	mov	r3, #15
	and	r3, r3, r2
	cmp	r3, #1
	bne	.L3
	ldr	r1, [r6, #80]
	mov	r2, #13
	ldrb	r0, [r1, #9]
	mov	r3, #3
	neg	r2, r2
	and	r5, r5, r3
	mov	r3, r2
	lsl	r4, r5, #2
	and	r3, r3, r0
	orr	r3, r3, r4
	strb	r3, [r1, #9]
	ldrb	r3, [r1, #21]
	and	r2, r2, r3
	orr	r2, r2, r4
	strb	r2, [r1, #21]
	mov	r1, r6
	add	r1, r1, #35
	ldrb	r2, [r1]
	mov	r3, #254
	and	r3, r3, r2
	strb	r3, [r1]
.L3:
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8092b08,.Lfe1-Func_8092b08

	.text
	.align	2, 0
