@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8ace0_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_808b398
	.thumb_func
	.type	 Func_808b398,function
Func_808b398:
	push	{r5, lr}
	mov	r5, r0
	cmp	r5, #8
	bgt	.L3
	mov	r0, #32
	bl	_GetFlag
	cmp	r0, #0
	beq	.L4
	cmp	r5, #0
	bne	.L5
	mov	r5, #18
.L5:
	cmp	r5, #1
	bne	.L3
	mov	r5, #19
	b	.L3
.L4:
	mov	r0, #33
	bl	_GetFlag
	cmp	r0, #0
	beq	.L3
	cmp	r5, #0
	bne	.L3
	mov	r5, #17
.L3:
	mov	r0, r5
	pop	{r5}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_808b398,.Lfe1-Func_808b398

	.text
	.align	2, 0
