@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_97b54_a_c_a_c_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Field_Lift
	.thumb_func
	.type	 Field_Lift,function
Field_Lift:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L17
	ldr	r3, [r3]
	sub	sp, sp, #20
	mov	sl, r3
	bl	Func_8097384
	mov	r3, sl
	ldr	r0, [r3, #4]
	add	r5, sp, #8
	str	r0, [r5]
	ldr	r1, [r3, #8]
	mov	r3, #128
	lsl	r3, r3, #13
	add	r1, r1, r3
	str	r1, [r5, #4]
	mov	r3, sl
	ldr	r2, [r3, #12]
	mov	r3, #128
	lsl	r3, r3, #14
	add	r0, r0, r3
	mov	r3, #128
	str	r2, [r5, #8]
	lsl	r3, r3, #8
	bl	Func_8098a84
	ldr	r3, .L17+4
	str	r0, [sp]
	ldr	r0, [r5]
	ldr	r1, [r5, #4]
	add	r0, r0, r3
	ldr	r2, [r5, #8]
	mov	r3, #0
	bl	Func_8098a84
	str	r0, [sp, #4]
	mov	r0, #15
	mov	fp, sp
	bl	WaitFrames
	mov	r0, #1
	mov	r7, fp
	mov	r8, r0
.L6:
	ldmia	r7!, {r6}
	cmp	r6, #0
	beq	.L5
	mov	r1, #192
	ldrh	r2, [r6, #6]
	mov	r0, r6
	lsl	r1, r1, #13
	bl	Func_8096bec
.L5:
	mov	r3, #1
	neg	r3, r3
	add	r8, r8, r3
	mov	r0, r8
	cmp	r0, #0
	bge	.L6
	ldr	r0, [sp]
	bl	_Actor_WaitMovement
	mov	r0, #134
	bl	_PlaySound
	mov	r0, #128
	mov	r3, #23
	lsl	r0, r0, #10
	mov	r7, r5
	mov	r8, r3
	mov	r9, r0
.L12:
	mov	r3, sl
	ldr	r1, [r3, #4]
	str	r1, [r7]
	mov	r0, #128
	ldr	r2, [r3, #8]
	lsl	r0, r0, #13
	add	r2, r2, r0
	str	r2, [r7, #4]
	ldr	r3, [r3, #12]
	ldr	r0, .L17+8
	str	r3, [r7, #8]
	bl	CreateParticleActor
	mov	r6, r0
	cmp	r6, #0
	beq	.L11
	ldr	r1, .L17+12
	bl	_Actor_SetScript
	bl	Random
	mov	r3, r9
	mov	r2, r6
	add	r2, r2, #85
	str	r3, [r6, #52]
	add	r0, r0, r9
	mov	r3, #0
	str	r0, [r6, #48]
	strb	r3, [r2]
	bl	Random
	lsl	r5, r0, #1
	add	r5, r5, r0
	mov	r0, #128
	lsl	r0, r0, #12
	lsl	r5, r5, #3
	add	r5, r5, r0
	bl	Random
	mov	r1, r5
	mov	r2, r0
	mov	r0, r6
	bl	Func_8096bec
.L11:
	mov	r3, #1
	neg	r3, r3
	add	r8, r8, r3
	mov	r0, r8
	cmp	r0, #0
	bge	.L12
	ldr	r0, [sp]
	bl	_DeleteActor
	mov	r3, fp
	ldr	r0, [r3, #4]
	bl	_DeleteActor
	bl	Func_809748c
	add	sp, sp, #20
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L18:
	.align	2, 0
.L17:
	.word	iwram_3001f30
	.word	-2097152
	.word	285
	.word	.L9f0d4
.Lfe1:
	.size	 Field_Lift,.Lfe1-Field_Lift

	.text
	.align	2, 0
