@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_8d9a4_c_c_c_a_a_a_a_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Task_Transition300
	.thumb_func
	.type	 Task_Transition300,function
Task_Transition300:
	push	{r5, r6, r7, lr}
	ldr	r3, .L48
	ldr	r1, .L48+4
	ldr	r6, [r3]
	add	r4, r6, r1
	mov	r2, #0
	ldrsb	r2, [r4, r2]
	cmp	r2, #0
	beq	.L26
	ldr	r3, .L48+8
	add	r1, r6, r3
	mov	r3, #0
	ldrsb	r3, [r1, r3]
	ldrb	r0, [r1]
	cmp	r3, r2
	blt	.L27
	mov	r3, #0
	strb	r3, [r4]
	ldr	r0, .L48+12
	bl	StopTask
	ldr	r2, .L48+16
	ldr	r3, .L48+20
	ldrh	r1, [r2, #10]
	and	r3, r3, r1
	strh	r3, [r2, #10]
	ldr	r3, .L48+24
	ldrh	r1, [r2, #10]
	and	r3, r3, r1
	strh	r3, [r2, #10]
	ldrh	r3, [r2, #10]
	b	.L25
.L27:
	ldr	r7, .L48+28
	add	r3, r6, r7
	mov	r2, #0
	ldrsb	r2, [r3, r2]
	ldr	r3, .L48+32
	add	r5, r6, r3
	mov	r3, #0
	ldrsb	r3, [r5, r3]
	sub	r2, r2, r3
	add	r3, r0, #1
	strb	r3, [r1]
	lsl	r3, r3, #24
	asr	r3, r3, #24
	mov	r0, r3
	mul	r0, r0, r2
	mov	r1, #0
	ldrsb	r1, [r4, r1]
	ldr	r3, .L48+36
	bl	_call_via_r3
	mov	r3, #0
	ldrsb	r3, [r5, r3]
	sub	r7, r7, #17
	add	r3, r3, r0
	add	r2, r6, r7
	strh	r3, [r2]
.L26:
	ldr	r1, .L48+40
	ldr	r2, .L48+44
	add	r3, r6, r1
	ldrh	r3, [r3]
	add	r1, r6, r2
	sub	r0, r3, #1
	ldrb	r3, [r1]
	mov	r2, #1
	eor	r3, r3, r2
	strb	r3, [r1]
	mov	r3, #32
	and	r3, r3, r0
	mov	r5, #0
	cmp	r3, #0
	beq	.L29
	mov	r5, #15
.L29:
	mov	r3, #31
	and	r3, r3, r0
	lsl	r0, r3, #1
	ldr	r3, .L48+48
	mov	r7, #63
	mov	r4, #0
	mov	ip, r3
	mov	lr, r7
.L30:
	mov	r1, lr
	mov	r3, r0
	and	r3, r3, r1
	mov	r7, ip
	ldrb	r2, [r7, r3]
	mov	r7, #161
	lsr	r3, r2, #1
	add	r3, r6, r3
	lsl	r7, r7, #3
	add	r1, r3, r7
	mov	r3, #1
	and	r3, r3, r2
	cmp	r3, #0
	beq	.L31
	ldrb	r3, [r1]
	mov	r2, #15
	and	r2, r2, r3
	lsl	r3, r5, #4
	orr	r2, r2, r3
	strb	r2, [r1]
	b	.L32
.L31:
	ldrb	r2, [r1]
	mov	r3, #240
	and	r3, r3, r2
	orr	r3, r3, r5
	strb	r3, [r1]
.L32:
	add	r4, r4, #1
	add	r0, r0, #1
	cmp	r4, #1
	bls	.L30
	ldr	r1, .L48+52
	ldr	r0, .L48+56
	ldrh	r3, [r0]
	mov	r4, r3
	strh	r0, [r0]
	ldrh	r2, [r1]
	cmp	r2, #31
	bgt	.L42
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r2, r2, #1
	add	r3, r3, r1
	strh	r2, [r1]
	mov	r1, #161
	lsl	r1, r1, #3
	add	r3, r3, #4
	add	r2, r6, r1
	stmia	r3!, {r2}
	mov	r2, #192
	lsl	r2, r2, #19
	stmia	r3!, {r2}
	ldr	r2, .L48+60
	str	r2, [r3]
.L42:
	strh	r4, [r0]
.L25:
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L49:
	.align	2, 0
.L48:
	.word	iwram_3001ecc
	.word	1340
	.word	1341
	.word	Task_Transition300
	.word	67109040
	.word	50687
	.word	32767
	.word	1339
	.word	1338
	.word	divsi3_RAM
	.word	1322
	.word	1337
	.word	.L9e8ee
	.word	gDMATaskCount
	.word	67109384
	.word	-2080374776
.Lfe1:
	.size	 Task_Transition300,.Lfe1-Task_Transition300

	.text
	.align	2, 0
