@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_944ec_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8096bec
	.thumb_func
	.type	 Func_8096bec,function
Func_8096bec:
	push	{r5, r6, lr}
	mov	r6, r0
	sub	sp, sp, #12
	mov	r0, r1
	mov	r1, r2
	cmp	r6, #0
	beq	.L3
	ldr	r3, [r6, #8]
	mov	r5, sp
	str	r3, [r5]
	ldr	r3, [r6, #12]
	str	r3, [r5, #4]
	ldr	r3, [r6, #16]
	mov	r2, r5
	str	r3, [r5, #8]
	bl	vec3_translate
	ldr	r1, [r5]
	ldr	r2, [r5, #4]
	ldr	r3, [r5, #8]
	mov	r0, r6
	bl	_Actor_TravelTo
.L3:
	add	sp, sp, #12
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8096bec,.Lfe1-Func_8096bec

	.text
	.align	2, 0
