#!/usr/bin/env python3
"""elevation_candidates.py -- rank the remaining hand-written asm by tractability.

Picking elevation targets by instruction count alone does not work. The first
batch attempted that way (rom_79338_c_a.s, five 5-13 instruction flag
accessors) failed on all five: gcc-2.96 hoists the literal-pool load above the
shifts where the ROM emits it after, and no C formulation moves it. Their own
neighbouring ToggleFlag is in fakematch.txt using inline-asm barriers, so the
whole family was known-hard before we started.

What separates tractable from not is SHAPE, not size:

  * a function with a literal-pool load followed by arithmetic on the argument
    is scheduling-sensitive -- the load can float, and where it lands is the
    compiler's choice, not the C's
  * a function that is a pure forwarding call, a field read, or a small
    switch dispatch has one plausible schedule and tends to fall out
  * anything already in fakematch.txt / unmatchable.txt is a known fight;
    those stems and their siblings are deprioritised

So this ranks on structure and reports the features, and the ranking is only
a reading order -- the compiler is still the only authority on whether a
given .c matches.
"""
import glob
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Thumb mnemonics that indicate a construct with more than one plausible
# lowering, i.e. where the C -> asm mapping is not forced.
SCHEDULE_SENSITIVE = re.compile(r"^\s*(ldr)\s+r\d+,\s*(=|\.L)")
CALL = re.compile(r"^\s*bl\s")
MULDIV = re.compile(r"^\s*(mul|__(u|s)?divsi3|__modsi3)")


def is_generated(path):
    with open(path, errors="replace") as f:
        return "Generated by gcc" in (f.readline() or "")


def parked():
    """Function names already recorded as hard, plus the file stems they sit in.

    A sibling of a fakematch shares its translation unit and often its
    difficulty (the flag-accessor family is the case in point), so the stem is
    carried as a soft signal alongside the exact name.
    """
    names, stems = set(), set()
    for fn in ("fakematch.txt", "unmatchable.txt"):
        p = os.path.join(ROOT, fn)
        if not os.path.exists(p):
            continue
        for line in open(p, errors="replace"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            f = line.split()
            names.add(f[0])
            for tok in f[1:]:
                if tok.endswith(".c"):
                    # src/x/y_b.c -> the stem shared with y.c, y_a.c, ...
                    stems.add(re.sub(r"(_[abc])+\.c$", "", tok))
    return names, stems


def scan(path):
    """[(name, line index, body lines)] for each THUMB function in a .s file.

    ARM functions are skipped outright. The whole ROM is built -mthumb, so an
    `.arm_func_start` body cannot have come from C in this project at all --
    it is the BIOS-adjacent hand-asm (the interrupt dispatcher, the IWRAM
    divide helpers, DecompressLZ1_ROM). An earlier version of this ranked them
    top precisely because they are small, which was the ranking finding
    nothing but noise.
    """
    L = open(path, errors="replace").read().split("\n")
    out, cur, start, body = [], None, 0, []
    for i, l in enumerate(L):
        m = re.match(r"\s*\.(arm_func_start|thumb_func_start(?:_noalign)?)\s+(\S+)", l,
                     re.IGNORECASE)
        if m:
            if cur:
                out.append((cur, start, body))
            if m.group(1) == "arm_func_start":
                cur = None
                continue
            cur, start, body = m.group(2), i, []
        elif cur is not None:
            if re.match(r"^\s+[a-zA-Z]", l) and not l.strip().startswith("."):
                body.append(l)
    if cur:
        out.append((cur, start, body))
    return out


def blockers(body):
    """Known-unmatchable shapes visible in the assembly, from docs/elevation.md.

    Reading a function's shape costs seconds; writing the C, screening it and
    parking the result costs a round. These three are recognisable before any
    of that, and every one of them has already burned at least one round.

    Returned as a set of short names so the ranking can report them and
    --clean can drop them.
    """
    out = set()
    norm = [re.sub(r"\s+", " ", l.strip()) for l in body]

    for i, l in enumerate(norm):
        # 1. narrow constant materialisation -- the 34-function blocker. The
        #    ROM builds ~0xc in 32-bit width via mov/neg; gcc narrows to a
        #    byte immediate. Width is solved (a named int mask), ordering is
        #    not.
        if l.startswith("neg r") and i and norm[i - 1].startswith("mov r"):
            m = re.match(r"mov (r\d+), #(0x[0-9a-f]+|\d+)", norm[i - 1])
            if m and l == f"neg {m.group(1)}, {m.group(1)}":
                out.add("narrow-mask")

        # 2. small-constant pool tell -- a pooled value that would fit in an
        #    eight-bit mov means the operand was a SYMBOL reference. Blocked
        #    on naming, not technique. BOTH spellings matter: the disassembly
        #    uses `=0` for a literal pool word and `.Lxxx` for a labelled one,
        #    and an earlier version of this filter only caught the second.
        m = re.match(r"ldr r\d+, =(0x[0-9a-f]+|\d+)$", l)
        if m and int(m.group(1), 0) <= 0xFF:
            out.add("pool-tell")
        if re.match(r"ldr r\d+, \.L\w+$", l):
            out.add("pool-tell")

        # 4. stack-argument register reuse -- the ROM builds BOTH stack
        #    constants into separate registers before storing either; gcc
        #    builds one, stores it, and reuses the register for the second.
        #
        #        rom    mov r3, #0xa / mov r2, #0x54 / str r3, [sp] / str r2, [sp, #4]
        #        ours   mov r3, #0xa / str r3, [sp] / mov r3, #0x54 / str r3, [sp, #4]
        #
        #    Naming the two values as locals does not separate them; it costs
        #    an instruction instead. Seen in OvlFunc_946_2009624 and the
        #    five-member family at ovl_30_c_c_a_a.s.
        if l.startswith("str r") and l.endswith(", [sp]") and i >= 2:
            a = re.match(r"mov (r\d+), #", norm[i - 2])
            b = re.match(r"mov (r\d+), #", norm[i - 1])
            if a and b and a.group(1) != b.group(1):
                out.add("stack-arg-pair")

        # 5. argument fill order -- a pooled argument and an immediate
        #    argument set up in the opposite order from gcc's. The ROM builds
        #    the immediate first; gcc emits the pool load first.
        #
        #        rom    mov r1, #0x66 / ldr r2, =0x4b6
        #        ours   ldr r2, =0x4b6 / mov r1, #0x66
        #
        #    Naming both as locals costs two instructions rather than
        #    reordering. Seen in the OvlFunc_882_2008398 family and in
        #    Func_8078948 / LoadStatusIcon from the main ROM.
        if re.match(r"ldr r\d+, =", l) and i and re.match(r"mov r\d+, #", norm[i - 1]) \
                and i + 1 < len(norm) and norm[i + 1].startswith(("mov r", "bl ")):
            out.add("arg-fill-order")

        # 3. interleaved argument set-up -- a shifted constant's mov/lsl pair
        #    split by ANOTHER register's move. Nine formulations have failed
        #    against this; gcc always emits the pair contiguously.
        #
        #        mov r1, #0x81     <- builds the constant
        #        mov r0, #0xe      <- a different register, in between
        #        lsl r1, #1        <- finishes it
        m = re.match(r"lsl (r\d+),", l)
        if m and i >= 2:
            reg = m.group(1)
            starts_it = re.match(rf"mov {reg}, #", norm[i - 2])
            other = re.match(r"mov (r\d+), #", norm[i - 1])
            if starts_it and other and other.group(1) != reg:
                out.add("arg-interleave")
    return out


def classify(body):
    """Feature counts used for ranking."""
    return {
        "n": len(body),
        "calls": sum(1 for l in body if CALL.match(l)),
        "pool": sum(1 for l in body if SCHEDULE_SENSITIVE.match(l)),
        "muldiv": sum(1 for l in body if MULDIV.search(l)),
        "branches": sum(1 for l in body if re.match(r"^\s*b(?!l\b|x\b)\w*\s", l)),
    }


def score(f, is_parked, stem_parked):
    """Lower is more tractable. Heuristic, and only a reading order."""
    s = f["n"] * 0.5
    # a pool load that is not the whole point of the function is where
    # scheduling bites; one is normal, several compound
    s += f["pool"] * 6
    s += f["branches"] * 2
    s += f["muldiv"] * 8
    # calls are usually GOOD: a forwarding call pins the schedule around it
    s -= min(f["calls"], 3) * 2
    if is_parked:
        s += 200
    if stem_parked:
        s += 40
    return s


def main():
    limit = int(sys.argv[sys.argv.index("--limit") + 1]) if "--limit" in sys.argv else 40
    want_overlays = "--overlays" in sys.argv
    park_names, park_stems = parked()

    rows = []
    for p in sorted(glob.glob(os.path.join(ROOT, "asm", "**", "*.s"), recursive=True)):
        if is_generated(p):
            continue
        rel = os.path.relpath(p, ROOT)
        if ("overlays" in rel) != want_overlays:
            continue
        # rom_f9000 is stock m4a, built with old_agbcc from src/lib/m4a/;
        # elevating it here would diverge from the canonical stock source.
        if "rom_f9000" in rel:
            continue
        stem = re.sub(r"(_[abc])+\.s$", "", rel.replace("asm/", "src/"))
        fns = [x for x in scan(p) if x[2]]
        for name, idx, body in fns:
            f = classify(body)
            f["fns"] = len(fns)
            f["blocked"] = blockers(body)
            rows.append((score(f, name in park_names, stem in park_stems),
                         name, rel, f))

    # A .o is built from ONE source file, so a function inside a
    # multi-function .s cannot be elevated on its own -- the .s has to be
    # split into _a/_b/_c and all three wired into the linker script first.
    # 402 of the 1155 remaining hand-written .s files hold exactly one
    # function; those convert with nothing but an added .c and a deleted .s,
    # so they are the batch pool until the splitter exists.
    if "--single" in sys.argv:
        rows = [r for r in rows if r[3]["fns"] == 1]
    # --clean drops anything whose assembly already shows a known-unmatchable
    # shape. Screening against the blocker list BEFORE writing any C is the
    # cheapest filter available and it took twelve rounds to start using it.
    if "--clean" in sys.argv:
        rows = [r for r in rows if not r[3]["blocked"]]

    rows.sort()
    print(f"{'score':>6} {'insn':>5} {'call':>5} {'br':>4} {'fns':>4}  "
          f"{'blocked by':<26}name / file")
    for sc, name, rel, f in rows[:limit]:
        b = ",".join(sorted(f["blocked"])) or "-"
        print(f"{sc:6.1f} {f['n']:5d} {f['calls']:5d} {f['branches']:4d} {f['fns']:4d}  "
              f"{b:<26}{name}  {rel}")
    total = len(rows)
    clear = sum(1 for r in rows if not r[3]["blocked"])
    print(f"\n{total} candidates ({'overlays' if want_overlays else 'main ROM'}), "
          f"{clear} with no known blocker in their assembly")
    if "--clean" not in sys.argv:
        print("Pass --clean to list only those.")


if __name__ == "__main__":
    main()
