#!/usr/bin/env python3
"""find_fragments.py -- match a function's BLOCKS against the solved corpus.

WHY THIS AND NOT match_shapes.py

That tool compares WHOLE functions, so it can never reach a large one: a
400-instruction function will not share a whole-function skeleton with anything
already elevated. It drains at the small end and stops.

Blocks are different. Split a function at its labels and branches and the
resulting basic blocks repeat across the ROM constantly -- the same cutscene
call sequence, the same actor-field write, the same table dispatch. Measured
over the 678 remaining functions of 160+ instructions:

    43% of all blocks have an EXACT skeleton match in the solved corpus

and the distribution is bimodal rather than flat, which is what makes it worth
acting on:

    >=80% of blocks matched   104 functions    70,795 instructions
    60-80%                     92 functions    44,741 instructions
    <20%                      343 functions   152,225 instructions

343 large functions are genuinely novel. But 104 are four-fifths built out of
blocks somebody has already written C for, and those are 15% of everything
remaining. See reports/large-functions.md.

WHAT IT GIVES YOU

Per block: the exemplar function and .c file whose block has the same skeleton.
That is not a translation -- it is a pointer to C that produced these exact
instruction kinds, so the block can be written by reading a worked example
instead of from the instruction stream.

WHAT IT IS NOT. Skeletons collapse registers, immediates and callee names, so a
match means "the same shape of code", not "the same code". Two blocks that both
set up three arguments and call something will match even when they do entirely
different things. Read the exemplar; do not paste it.

    python3 tools/find_fragments.py --rank --real     # best-covered targets
    python3 tools/find_fragments.py --rank            # ...counting fakematches too
    python3 tools/find_fragments.py --show <function> # per-block exemplars
"""
import collections
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from match_shapes import skeleton, GEN_FUNC, ROM_FUNC   # noqa: E402

LABEL = re.compile(r"^\.L")
BRANCH = re.compile(r"^\tb\w*\t")
MIN_BLOCK = 4


def blocks(body):
    """Basic blocks, as (first-line-index, text). Split at labels and branches."""
    out, cur, start = [], [], 0
    for i, l in enumerate(body.split("\n")):
        if LABEL.match(l):
            if cur:
                out.append((start, "\n".join(cur)))
            cur, start = [], i + 1
            continue
        if not cur:
            start = i
        cur.append(l)
        if BRANCH.match(l):
            out.append((start, "\n".join(cur)))
            cur = []
    if cur:
        out.append((start, "\n".join(cur)))
    return [(s, b) for s, b in out
            if len([x for x in b.split("\n") if x.startswith("\t")]) >= MIN_BLOCK]


def solved_index():
    """skeleton -> (exemplar function, source file). First one wins; they are
    interchangeable by construction, and printing twenty is noise."""
    idx = {}
    for p in sorted(glob.glob(os.path.join(ROOT, "asm/**/*.s"), recursive=True)):
        txt = open(p, errors="replace").read()
        if not txt.startswith("@ Generated by gcc"):
            continue
        src = os.path.join("src", os.path.relpath(p, ROOT)[len("asm/"):])[:-2] + ".c"
        if not os.path.exists(os.path.join(ROOT, src)):
            continue
        fake = "fakematch" in open(os.path.join(ROOT, src), errors="replace").read()
        for m in GEN_FUNC.finditer(txt):
            for _, b in blocks(m.group(2)):
                idx.setdefault(skeleton(b), (m.group(1), src, fake))
    return idx


def targets(idx, lo, real_only=False):
    """--real counts only blocks whose exemplar is NOT a fakematch.

    THIS MATTERS MORE THAN IT SOUNDS. The first ranking put seven functions at
    100% coverage, and the best-covered one turned out to be 100% because nearly
    every block matched a fakematch exemplar -- inline-asm register pinning,
    which is not C anybody can learn the block from. Coverage counted that way
    measures "how much of this function is the arg-interleave shape", which is
    close to the OPPOSITE of what we want to work on.

    Counting only real exemplars is the metric that means what the tool claims.
    """
    rows = []
    for p in sorted(glob.glob(os.path.join(ROOT, "asm/**/*.s"), recursive=True)):
        txt = open(p, errors="replace").read()
        if txt.startswith("@ Generated by gcc"):
            continue
        rel = os.path.relpath(p, ROOT)
        for m in ROM_FUNC.finditer(txt):
            body = m.group(2)
            n = len([l for l in body.split("\n") if l.startswith("\t")])
            if n < lo:
                continue
            bs = blocks(body)
            if not bs:
                continue
            hit = sum(1 for _, b in bs
                      if skeleton(b) in idx
                      and not (real_only and idx[skeleton(b)][2]))
            rows.append((hit / len(bs), n, hit, len(bs), m.group(1), rel))
    rows.sort(reverse=True)
    return rows


def main():
    a = sys.argv[1:]
    lo = int(a[a.index("--min-insn") + 1]) if "--min-insn" in a else 160
    idx = solved_index()
    if "--show" in a:
        want = a[a.index("--show") + 1]
        for p in sorted(glob.glob(os.path.join(ROOT, "asm/**/*.s"), recursive=True)):
            txt = open(p, errors="replace").read()
            if txt.startswith("@ Generated by gcc"):
                continue
            for m in ROM_FUNC.finditer(txt):
                if m.group(1) != want:
                    continue
                print(f"{want}  {os.path.relpath(p, ROOT)}\n")
                for k, (_, b) in enumerate(blocks(m.group(2))):
                    ex = idx.get(skeleton(b))
                    ins = [x.strip() for x in b.split("\n") if x.startswith("\t")]
                    tag = (f"<- {ex[0]}  {ex[1]}" + ("  [FAKEMATCH]" if ex[2] else "")
                           ) if ex else "-- no exemplar"
                    print(f"  block {k:2d} ({len(ins):2d} insn)  {tag}")
                    for x in ins[:3]:
                        print(f"        {x}")
                    if len(ins) > 3:
                        print(f"        ... {len(ins) - 3} more")
                return 0
        print(f"{want} not found in asm/")
        return 1
    rows = targets(idx, lo, "--real" in a)
    lim = int(a[a.index("--limit") + 1]) if "--limit" in a else 20
    print(f"{'cov':>4} {'insn':>5} {'blocks':>9}  name / file")
    for c, n, hit, tot, name, rel in rows[:lim]:
        print(f"{100*c:3.0f}% {n:5d} {hit:4d}/{tot:<4d}  {name}  {rel}")
    print(f"\n{len(rows)} functions >= {lo} instructions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
