#!/usr/bin/env python3
"""find_solved_shape.py -- which ALREADY-ELEVATED C produced this instruction?

WHY THIS EXISTS

Batch 53 spent its whole cost on one question: what C produces
`stmia r3!, {r0, r1, r2}`? The answer was two files away -- a neighbouring
elevated function in the same overlay already used DMA3_COPY from include/dma.h,
and once that was found the C took one correction and four functions fell out.

The tree tracks the GENERATED .s beside every elevated .c (see the working
discipline in docs/elevation.md). That means the corpus of solved codegen is
sitting on disk, searchable, and it answers "how is this shape written in C"
directly rather than by derivation.

USE IT BEFORE INVENTING A CONSTRUCT. A shape that looks novel has often been
solved already in a file nobody thought to look at.

    python3 tools/find_solved_shape.py 'stmia'
    python3 tools/find_solved_shape.py 'neg r0, r3'      # regex, on one line
    python3 tools/find_solved_shape.py --seq 'mul' 'asr' # both, same function

WHAT IT SEARCHES

Only .s files carrying gcc's own banner AND having a sibling .c -- that pair is
the proof the C is what produced the assembly. Hand-written corpus is skipped,
because it answers the wrong question: it shows what the ROM does, which you
already have, not what C reproduces it.
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FUNC = re.compile(r"^(\w+):\n(.*?)(?=^\w+:|\Z)", re.S | re.M)


def solved_pairs():
    """(generated .s, its .c) for every elevated function in the tree."""
    for p in sorted(glob.glob(os.path.join(ROOT, "asm/**/*.s"), recursive=True)):
        rel = os.path.relpath(p, ROOT)
        with open(p, errors="replace") as fh:
            head = fh.read(400)
        if "Generated by gcc" not in head:
            continue
        c = os.path.join(ROOT, "src/" + rel[len("asm/"):-2] + ".c")
        if os.path.exists(c):
            yield p, c


def main():
    a = sys.argv[1:]
    if not a:
        sys.exit(__doc__)
    seq = "--seq" in a
    pats = [re.compile(x) for x in a if not x.startswith("--")]
    if not pats:
        sys.exit(__doc__)
    hits = 0
    for s, c in solved_pairs():
        body = open(s, errors="replace").read()
        if seq:
            if not all(p.search(body) for p in pats):
                continue
        elif not pats[0].search(body):
            continue
        hits += 1
        rel_c = os.path.relpath(c, ROOT)
        # show the matching line and which function it is in, so the .c can be
        # read at the right place rather than end to end
        for m in FUNC.finditer(body):
            fn, fbody = m.group(1), m.group(2)
            for line in fbody.split("\n"):
                if pats[0].search(line):
                    print(f"  {fn:<28s} {line.strip():<34s} {rel_c}")
                    break
        if hits >= 12:
            print("  ... (stopping at 12 files)")
            break
    if not hits:
        print("  no elevated .c produces that shape -- it is genuinely new")
    return 0


if __name__ == "__main__":
    sys.exit(main())
