#!/usr/bin/env python3
"""find_families.py -- group hand-written functions by identical shape.

Fourteen of the first forty-four functions elevated came from three families
of near-identical stubs, and all three were found by accident -- noticing that
two names in a candidate list looked similar. This finds them on purpose.

WHY FAMILIES MATTER

The overlays duplicate their cutscene and talk stubs PER MAP rather than
sharing them. So the same six-call sequence appears in a dozen overlays with
only a slot number changed. Once one member matches, the rest are mechanical:
same C, different constant. `OvlFunc_974` was seven functions from one
insight, `OvlFunc_970` four, `OvlFunc_920` three.

That also means a family member that FAILS is worth knowing about early --
whatever blocks one blocks all of them, so the cost of a wrong guess is
multiplied too.

HOW SHAPES ARE COMPARED

Every register is rewritten to `r`, every immediate to `#`, and every branch
target to `L`. What survives is the sequence of mnemonics and operand kinds,
which is what makes two stubs "the same function with a different slot".

Call targets are KEPT, because two stubs that call different functions are not
the same stub even if they look alike -- that distinction is the whole point
when deciding whether one solution transfers.
"""
import glob
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = re.compile(r"\s*\.thumb_func_start(?:_noalign)?\s+(\S+)", re.IGNORECASE)


def shape(body):
    out = []
    for l in body:
        s = re.sub(r"\s+", " ", l.strip())
        if s.startswith("bl "):
            out.append(s)          # keep the callee
            continue
        s = re.sub(r"\br\d+\b", "r", s)
        s = re.sub(r"#(0x)?[0-9a-f]+", "#", s)
        s = re.sub(r"\.?L[0-9a-fA-F]\w*", "L", s)
        s = re.sub(r"=\S+", "=", s)
        out.append(s)
    return "\n".join(out)


def main():
    want_overlays = "--main" not in sys.argv
    lo = int(sys.argv[sys.argv.index("--min") + 1]) if "--min" in sys.argv else 5
    hi = int(sys.argv[sys.argv.index("--max") + 1]) if "--max" in sys.argv else 30

    groups = defaultdict(list)
    pat = "asm/overlays/*/*.s" if want_overlays else "asm/rom_*/*.s"
    for p in sorted(glob.glob(os.path.join(ROOT, pat))):
        if "rom_f9000" in p:
            continue
        L = open(p, errors="replace").read().split("\n")
        if not L or "Generated by gcc" in L[0]:
            continue
        idx = [(i, m.group(1)) for i, l in enumerate(L) for m in [START.match(l)] if m]
        for k, (i, name) in enumerate(idx):
            end = idx[k + 1][0] if k + 1 < len(idx) else len(L)
            body = [l for l in L[i:end]
                    if re.match(r"^\s+[a-z]", l) and not l.strip().startswith(".")]
            if lo <= len(body) <= hi:
                groups[shape(body)].append((name, os.path.relpath(p, ROOT), len(body)))

    fams = sorted((v for v in groups.values() if len(v) > 1),
                  key=lambda v: (-len(v), v[0][2]))
    shown = 0
    for members in fams:
        if shown >= (int(sys.argv[sys.argv.index("--limit") + 1])
                     if "--limit" in sys.argv else 12):
            break
        shown += 1
        n = members[0][2]
        print(f"\n=== {len(members)} members, {n} instructions each")
        for name, p, _ in members[:8]:
            print(f"    {name:24s} {p}")
        if len(members) > 8:
            print(f"    ... and {len(members) - 8} more")

    total = sum(len(v) for v in fams)
    print(f"\n{len(fams)} families covering {total} functions "
          f"({'overlays' if want_overlays else 'main ROM'}, "
          f"{lo}-{hi} instructions)")
    print("One member solved usually gives the rest -- same C, different constant.")


if __name__ == "__main__":
    main()
