#!/usr/bin/env python3
"""shape_groups.py -- rank the UNELEVATED corpus by opcode-signature group.

WHY THIS EXISTS

Batch 49 elevated nine functions in two rounds by enumerating a shape that was
already solved, instead of reading down elevation_candidates/pick_candidates.
Those rank by tractability and hand back a mixed bag; enumerating a shape you
have already cracked hands back a worklist where the answer is known before you
start. This generalises that: group every remaining function by the SET of
opcodes it uses, and rank the groups by size.

WHAT A BIG GROUP ACTUALLY MEANS -- READ THIS BEFORE SPENDING A ROUND

A large group is NOT necessarily a rich vein. It may be large precisely because
it is BLOCKED: the candidate rankers refuse those functions round after round
and they accumulate. The first run put a 14-member group at the top and every
member is straight-line arg-interleave, which batch 42 showed is unreachable in
plain C. See src/non_matching/overlays/arg_interleave_flat.c.

So the workflow is: pick a group, SCREEN ONE MEMBER, and only then decide
whether to spend the round on it. One screen is cheap; fourteen are not.

The `branch` column is the single most useful field. The basic-block lever
(batch 43) needs a branch to work at all, so a `flat` group whose diff is an
argument-order problem is dead on arrival, while the same shape with a branch is
reachable.

    python3 tools/shape_groups.py                 # top 20 groups
    python3 tools/shape_groups.py --max-insn 40   # widen the size cut
    python3 tools/shape_groups.py --list N        # print members of group N
"""
import collections
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FUNC = re.compile(r"\.thumb_func_start\s+(\S+)[^\n]*\n(.*?)\.func_end", re.S)


def groups(max_insn):
    out = collections.defaultdict(list)
    for p in sorted(glob.glob(os.path.join(ROOT, "asm/**/*.s"), recursive=True)):
        rel = os.path.relpath(p, ROOT)
        # m4a is a different compiler entirely, and part of it is hand-written
        # assembly -- see tools/pick_candidates.py.
        if rel.startswith("asm/rom_f9000/"):
            continue
        txt = open(p, errors="replace").read()
        if "Generated by gcc" in txt[:400]:
            continue
        for m in FUNC.finditer(txt):
            name, body = m.group(1), m.group(2)
            lines = [l for l in body.split("\n") if l.startswith("\t")]
            if not lines or len(lines) > max_insn:
                continue
            if re.search(r"^\tmov\tr12, lr|^\tbx\tr12", body, re.M):
                continue
            ops = tuple(sorted({l.split("\t")[1] for l in lines
                                if len(l.split("\t")) > 1}))
            has_branch = bool(re.findall(r"^\tb\w*\t\.L", body, re.M))
            out[(ops, has_branch)].append((len(lines), name, rel))
    return sorted(out.items(), key=lambda kv: -len(kv[1]))


def main():
    a = sys.argv[1:]
    max_insn = int(a[a.index("--max-insn") + 1]) if "--max-insn" in a else 30
    rows = groups(max_insn)
    if "--list" in a:
        n = int(a[a.index("--list") + 1])
        (ops, br), members = rows[n]
        print(f"group {n}: {'branch' if br else 'flat'}  {' '.join(ops)}\n")
        for insn, name, rel in sorted(members):
            print(f"  {insn:3d}  {name:<24s} {rel}")
        return 0
    print(f"unelevated functions <= {max_insn} insn, grouped by opcode set")
    print("(a big group may be big because it is BLOCKED -- screen one first)\n")
    print(f"{'#':>3} {'n':>4}  {'kind':<6} opcodes")
    for i, ((ops, br), members) in enumerate(rows[:20]):
        print(f"{i:3d} {len(members):4d}  {'branch' if br else 'flat':<6} "
              f"{' '.join(ops)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
