#!/usr/bin/env python3
"""twin_finder.py -- find unelevated functions that are TWINS of solved ones.

WHY

Overlays duplicate code. `OvlFunc_916_200836c` and `OvlFunc_947_2009578` are the
same function compiled into two different overlays -- same instruction sequence,
different VCOUNT bound and different tables. Once one is elevated, the other is
its source with the constants changed, and it matches on the first screen.

That is the cheapest elevation available: no shape to work out, no lever to
find, just three constants to substitute.

WHAT IT DOES

Builds an OPCODE SIGNATURE for every function -- the mnemonic sequence with all
operands discarded -- and reports unelevated functions whose signature exactly
matches an already-elevated one.

    python3 tools/twin_finder.py

Elevated functions are read from the generated `.s` files, which are byte-equal
to the ROM for anything that matched, so a signature hit means the ROM streams
agree instruction for instruction.

WHAT A HIT DOES AND DOES NOT MEAN

A hit means: START from the twin's .c, substitute the constants, and screen.
It does NOT mean the twin's C is correct unedited -- the operands differ by
definition, and some of those operands are symbols that need their own extern
declarations.

Signatures ignore operands, so two functions that differ only in a register
allocation also collide. That is fine for this purpose: they still share a
source shape. It is NOT fine to assume the constants are the only difference --
read both streams before copying.

THE HIGHEST-VALUE OUTPUT is the first section: a PARKED function whose twin has
since been solved. `OvlFunc_931_2008c0c` sat parked from batch 53 at 1 of 24 with
a note concluding the blocker was unreachable; its twin was elevated in batch 61,
and that twin's source matched here unedited but for the name. A park note ages
badly -- re-run this after any batch that elevates anything.


UNELEVATED CLUSTERS are reported too, and they are the higher-value output.
Several copies of one function with none of them elevated means a single screen
is worth N elevations. The batch-65 cluster (OvlFunc_946_2008ab0,
OvlFunc_964_2008ab0, OvlFunc_965_2008ab0 -- byte-identical across three
overlays) was found by hand before this section existed.

MEASURED YIELD, so nobody expects more than it gives: across the whole corpus at
1620 elevated and 2685 unelevated functions, EXACT signature matching found
exactly ONE hit -- the parked OvlFunc_931_2008c0c above. Consuming it left zero.

That is worth knowing in both directions. Code duplication between overlays is
real but rare at whole-function granularity, so this is not a bulk lever. It IS
nearly free to run, and every batch that elevates something can create a new
twin, so re-run it after each batch rather than expecting a backlog.

SHORT FUNCTIONS COLLIDE BY ACCIDENT. A six-instruction wrapper has a signature
shared by dozens of unrelated functions. The floor below is 12 instructions,
which was chosen because at 10 the output was mostly noise.
"""
import glob
import re
import sys
from collections import defaultdict

MIN_INSN = 12
HAND = re.compile(r"\.thumb_func_start\s+(\S+)[^\n]*\n(.*?)\.func_end", re.S)
GEN = re.compile(r"\.type\s+(\w+),\s*function\s*\n\1:\n(.*?)(?=\n\t\.align|\n\t\.size|\Z)", re.S)
MNEM = re.compile(r"^\t(\w+)")


def signature(body):
    ops = [m.group(1) for m in (MNEM.match(l) for l in body.split("\n")) if m]
    return tuple(ops)


def main():
    solved, unsolved = {}, {}
    for p in sorted(glob.glob("asm/**/*.s", recursive=True)):
        if p.startswith("asm/rom_f9000/"):
            continue
        txt = open(p, errors="replace").read()
        gen = "Generated by gcc" in txt[:400]
        for m in (GEN if gen else HAND).finditer(txt):
            sig = signature(m.group(2))
            if len(sig) < MIN_INSN:
                continue
            (solved if gen else unsolved)[m.group(1)] = (sig, p)

    by_sig = defaultdict(list)
    for n, (sig, p) in solved.items():
        by_sig[sig].append((n, p))

    hits = []
    for n, (sig, p) in sorted(unsolved.items()):
        if sig in by_sig:
            hits.append((len(sig), n, p, by_sig[sig][0]))
    hits.sort()

    # Clusters of UNELEVATED twins: one screen elevates all of them.
    un_by_sig = defaultdict(list)
    for n, (sig, p) in sorted(unsolved.items()):
        if sig not in by_sig:
            un_by_sig[sig].append((n, p))
    clusters = sorted(((len(v), len(k), v) for k, v in un_by_sig.items()
                       if len(v) > 1), reverse=True)

    # Parked functions are the highest-value category: a park whose twin has
    # SINCE been solved is unparkable by copying, and its note may predate the
    # twin's solution by many batches.
    parked = set()
    for c in glob.glob("src/non_matching/**/*.c", recursive=True):
        m = re.match(r"/\*\s*(\w+)\s", open(c, errors="replace").read())
        if m:
            parked.add(m.group(1))

    stale = [h for h in hits if h[1] in parked]
    fresh = [h for h in hits if h[1] not in parked]

    print(f"{len(solved)} elevated, {len(unsolved)} unelevated "
          f"(>= {MIN_INSN} instructions), {len(parked)} parked")
    print(f"{len(hits)} share a signature with a solved function\n")

    print("=== PARKED, but the twin is now SOLVED -- copy the twin's .c ===")
    for insn, n, p, (tn, tp) in stale:
        print("%3d insn  %-24s %s" % (insn, n, p))
        print("          twin of %-16s %s" % (tn, tp))
    if not stale:
        print("  (none)")

    print("\n=== UNELEVATED CLUSTERS -- one screen elevates all members ===")
    for cnt, insn, members in clusters[:12]:
        print("%d copies, %3d insn each" % (cnt, insn))
        for n, p in members:
            print("        %-24s %s" % (n, p))
    if not clusters:
        print("  (none)")

    print("\n=== unelevated, twin solved -- start from the twin's .c ===")
    for insn, n, p, (tn, tp) in fresh[:40]:
        print("%3d insn  %-24s %s" % (insn, n, p))
        print("          twin of %-16s %s" % (tn, tp))
    if not fresh:
        print("  (none)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
