@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a8604_c_c_a_c_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a9cf8
	.thumb_func
	.type	 Func_80a9cf8,function
Func_80a9cf8:
	push	{r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r3, .L7
	ldr	r3, [r3]
	mov	r2, #168
	mov	r6, r3
	sub	sp, sp, #4
	mov	r7, r0
	mov	r5, #0
	mov	r8, r2
	add	r6, r6, #200
.L6:
	mov	r3, r8
	str	r3, [sp]
	mov	r1, r5
	mov	r0, #2
	mov	r2, r7
	mov	r3, #248
	bl	_Func_801eb64
	add	r5, r5, #1
	stmia	r6!, {r0}
	cmp	r5, #7
	ble	.L6
	mov	r0, #1
	add	sp, sp, #4
	pop	{r3}
	mov	r8, r3
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.L8:
	.align	2, 0
.L7:
	.word	iwram_3001f2c
.Lfe1:
	.size	 Func_80a9cf8,.Lfe1-Func_80a9cf8

	.text
	.align	2, 0
