@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a7380_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a7380
	.thumb_func
	.type	 Func_80a7380,function
Func_80a7380:
	push	{r5, r6, r7, lr}
	mov	r1, #167
	lsl	r1, r1, #4
	mov	r0, #55
	sub	sp, sp, #4
	bl	galloc_iwram
	ldr	r3, .L9+4
	ldr	r2, [r3]
	mov	r3, #1
	mov	r7, r0
	mov	r1, #0
	strh	r3, [r2, #4]
	mov	r0, #0
	mov	r3, #20
	mov	r2, #30
	bl	_Func_80170f8
	mov	r0, #1
	bl	WaitFrames
	mov	r0, #0
	bl	Func_80a1090
	mov	r2, #130
	lsl	r2, r2, #2
	add	r0, r7, r2
	bl	_Func_80796c4
	ldr	r2, .L9+8
	add	r3, r7, r2
	strb	r0, [r3]
	mov	r1, #3
	mov	r0, #0
	mov	r2, #0
	mov	r3, #7
	bl	Func_80a8034
	mov	r3, #2
	str	r3, [sp]
	mov	r1, #0
	mov	r2, #17
	mov	r3, #5
	mov	r0, #13
	bl	_CreateUIBox
	mov	r2, #134
	lsl	r2, r2, #1
	add	r3, r7, r2
	str	r0, [r3]
	mov	r0, #169
	lsl	r0, r0, #1
	ldrh	r1, .L9
	mov	r2, #7
	add	r3, r7, r0
.L6:
	sub	r2, r2, #1
	strh	r1, [r3]
	sub	r3, r3, #2
	cmp	r2, #0
	bge	.L6
	mov	r3, #136
	lsl	r3, r3, #2
	add	r2, r7, r3
	mov	r3, #3
	strh	r3, [r2]
	bl	Func_80a7440
	mov	r6, r0
	ldr	r0, [r7, #36]
	bl	_Func_80164ac
	bl	Func_80a34c0
	ldr	r3, .L9+4
	ldr	r3, [r3]
	mov	r5, #0
	strh	r5, [r3, #4]
	mov	r0, #1
	bl	WaitFrames
	b	.L10
.L11:
	.align	2, 0
.L9:
	.word	30
	.word	iwram_3001e68
	.word	537
.L10:
	mov	r0, #55
	bl	gfree
	mov	r0, r6
	add	sp, sp, #4
	pop	{r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80a7380,.Lfe1-Func_80a7380

	.text
	.align	2, 0
