@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a1814_c_a_a_c_a_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a22f4
	.thumb_func
	.type	 Func_80a22f4,function
Func_80a22f4:
	ldr	r3, .L13
	ldr	r0, .L13+4
	ldr	r1, .L13+8
	ldr	r2, .L13+12
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	add	r1, r1, #28
	ldr	r0, .L13+16
	ldr	r2, .L13+20
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	bx	lr
.L14:
	.align	2, 0
.L13:
	.word	67109076
	.word	83886592
	.word	83886528
	.word	-2147483632
	.word	83886568
	.word	-2147483647
.Lfe1:
	.size	 Func_80a22f4,.Lfe1-Func_80a22f4

	.text
	.align	2, 0
