@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a1814_c_a_a_c_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a21b0
	.thumb_func
	.type	 Func_80a21b0,function
Func_80a21b0:
	push	{r5, r6, r7, lr}
	mov	r7, fp
	mov	r6, sl
	mov	r5, r9
	push	{r5, r6, r7}
	mov	r7, r8
	push	{r7}
	mov	r5, r1
	mov	r6, r2
	sub	sp, sp, #4
	mov	r1, r6
	mov	r9, r0
	mov	fp, r3
	mov	r0, r5
	mov	r3, #49
	ldr	r7, [sp, #36]
	mov	sl, r3
	bl	__divsi3
	mov	r1, r6
	mov	r8, r0
	mov	r0, r5
	bl	__modsi3
	cmp	r0, #0
	beq	.L3
	mov	r3, #1
	add	r8, r8, r3
.L3:
	mov	r3, r8
	sub	r7, r7, r3
	cmp	r3, #1
	ble	.L4
	mov	r0, #0
	mov	r3, #1
	str	r0, [sp]
	ldr	r1, .L13
	sub	r2, r7, #1
	neg	r3, r3
	mov	r0, r9
	mov	r5, #0
	bl	_Func_8019000
	cmp	r5, r8
	bge	.L12
.L8:
	cmp	r5, fp
	bne	.L9
	mov	r3, #2
	str	r3, [sp]
	mov	r0, r9
	mov	r1, sl
	mov	r2, r7
	sub	r3, r3, #3
	bl	_Func_8019000
	b	.L10
.L9:
	mov	r3, #3
	str	r3, [sp]
	mov	r0, r9
	mov	r1, sl
	mov	r2, r7
	sub	r3, r3, #4
	bl	_Func_8019000
.L10:
	mov	r3, #1
	add	r5, r5, #1
	add	sl, sl, r3
	add	r7, r7, #1
	cmp	r5, r8
	blt	.L8
.L12:
	mov	r2, #0
	mov	r3, #1
	str	r2, [sp]
	ldr	r1, .L13+4
	neg	r3, r3
	mov	r0, r9
	mov	r2, r7
	bl	_Func_8019000
.L4:
	add	sp, sp, #4
	pop	{r3, r5, r6, r7}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	mov	fp, r7
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	61736
	.word	61737
.Lfe1:
	.size	 Func_80a21b0,.Lfe1-Func_80a21b0

	.text
	.align	2, 0
