@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a1050_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a10d0
	.thumb_func
	.type	 Func_80a10d0,function
Func_80a10d0:
	push	{r5, r6, lr}
	mov	r6, r0
	ldr	r0, [r6]
	sub	sp, sp, #4
	mov	r5, r3
	ldr	r4, [sp, #20]
	cmp	r0, #0
	beq	.L3
	mov	r3, #128
	lsl	r3, r3, #1
	and	r3, r3, r4
	cmp	r3, #0
	beq	.L4
	mov	r0, #0
	b	.L2
.L4:
	bl	_Func_8016498
	mov	r0, #0
	b	.L2
.L3:
	mov	r3, #255
	and	r4, r4, r3
	mov	r0, r1
	ldr	r3, [sp, #16]
	mov	r1, r2
	mov	r2, r5
	str	r4, [sp]
	bl	_CreateUIBox
	str	r0, [r6]
	mov	r0, #1
.L2:
	add	sp, sp, #4
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.Lfe1:
	.size	 Func_80a10d0,.Lfe1-Func_80a10d0

	.text
	.align	2, 0
