@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a1814_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a1bc8
	.thumb_func
	.type	 Func_80a1bc8,function
Func_80a1bc8:
	bx	lr
.Lfe1:
	.size	 Func_80a1bc8,.Lfe1-Func_80a1bc8

	.text
	.align	2, 0
