@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a172c_a_c_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a17c4
	.thumb_func
	.type	 Func_80a17c4,function
Func_80a17c4:
	push	{lr}
	cmp	r0, #0
	beq	.L2
	mov	r3, #1
	strb	r3, [r0, #5]
	ldr	r2, .L4
	ldrh	r3, [r0, #6]
	ldrh	r1, [r0, #22]
	and	r2, r2, r3
	ldr	r3, .L4+4
	and	r3, r3, r1
	orr	r3, r3, r2
	strh	r3, [r0, #22]
	ldrh	r3, [r0, #8]
	ldrb	r2, [r0, #23]
	strb	r3, [r0, #20]
	mov	r3, #63
	neg	r3, r3
	and	r3, r3, r2
	strb	r3, [r0, #23]
	ldrb	r2, [r0, #21]
	mov	r3, #4
	neg	r3, r3
	and	r3, r3, r2
	strb	r3, [r0, #21]
.L2:
	pop	{r0}
	bx	r0
.L5:
	.align	2, 0
.L4:
	.word	511
	.word	-512
.Lfe1:
	.size	 Func_80a17c4,.Lfe1-Func_80a17c4

	.text
	.align	2, 0
