@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a5534_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a5780
	.thumb_func
	.type	 Func_80a5780,function
Func_80a5780:
	mov	r0, #1
	bx	lr
.Lfe1:
	.size	 Func_80a5780,.Lfe1-Func_80a5780
	.align	2, 0
	.global	Func_80a5784
	.thumb_func
	.type	 Func_80a5784,function
Func_80a5784:
	bx	lr
.Lfe2:
	.size	 Func_80a5784,.Lfe2-Func_80a5784

	.text
	.align	2, 0
