@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_a1814_c_a_a_c_a_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80a1bdc
	.thumb_func
	.type	 Func_80a1bdc,function
Func_80a1bdc:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r3, .L8
	ldr	r3, [r3]
	mov	r5, r3
	add	r5, r5, #72
	sub	sp, sp, #4
	mov	r9, r0
	mov	sl, r1
	mov	r8, r2
	mov	r6, #0
	mov	r7, r5
.L7:
	ldmia	r7!, {r3}
	cmp	r3, #0
	beq	.L6
	mov	r3, r8
	str	r3, [sp]
	mov	r0, r5
	mov	r1, r6
	mov	r2, r9
	mov	r3, sl
	bl	Func_80a1c2c
.L6:
	add	r6, r6, #1
	add	r5, r5, #4
	cmp	r6, #31
	ble	.L7
	add	sp, sp, #4
	pop	{r3, r5, r6}
	mov	r8, r3
	mov	r9, r5
	mov	sl, r6
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L9:
	.align	2, 0
.L8:
	.word	iwram_3001f2c
.Lfe1:
	.size	 Func_80a1bdc,.Lfe1-Func_80a1bdc

	.text
	.align	2, 0
