@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_93304_a_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Actor_SetBehavior
	.thumb_func
	.type	 Actor_SetBehavior,function
Actor_SetBehavior:
	push	{r5, lr}
	sub	r3, r1, #1
	mov	r5, r0
	cmp	r3, #6
	bhi	.L3
	ldr	r2, .L13
	lsl	r3, r3, #2
	ldr	r3, [r3, r2]
	mov	pc, r3
	.align	2, 0
	.align	2, 0
.L11:
	.word	.L4
	.word	.L5
	.word	.L6
	.word	.L7
	.word	.L8
	.word	.L9
	.word	.L10
.L4:
	ldr	r1, .L13+4
	b	.L3
.L5:
	ldr	r1, .L13+8
	b	.L3
.L6:
	ldr	r1, .L13+12
	b	.L3
.L7:
	ldr	r1, .L13+16
	b	.L3
.L8:
	ldr	r1, .L13+20
	b	.L3
.L9:
	ldr	r3, .L13+24
	mov	r2, #250
	lsl	r2, r2, #1
	add	r3, r3, r2
	ldr	r0, [r3]
	bl	MapActor_GetActor
	ldr	r1, .L13+28
	str	r0, [r5, #104]
	b	.L3
.L10:
	ldr	r1, .L13+32
.L3:
	mov	r0, r5
	bl	_Actor_SetScript
	pop	{r5}
	pop	{r0}
	bx	r0
.L14:
	.align	2, 0
.L13:
	.word	.L11
	.word	.L9fe00
	.word	.L9fd44
	.word	.L9fe10
	.word	.L9fecc
	.word	.L9ff18
	.word	gState
	.word	.L9ff2c
	.word	.L9fe04
.Lfe1:
	.size	 Actor_SetBehavior,.Lfe1-Actor_SetBehavior
