@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_9b698_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_809ba70
	.thumb_func
	.type	 Func_809ba70,function
Func_809ba70:
	push	{lr}
	ldr	r0, [r0]
	bl	_Sprite_SetAnim
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_809ba70,.Lfe1-Func_809ba70
