@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_2e00_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	AgbMain
	.thumb_func
	.type	 AgbMain,function
AgbMain:
	push	{r5, lr}
	ldr	r2, .L20+4
	ldr	r3, .L20+8
	ldrh	r1, [r2, #10]
	and	r3, r3, r1
	strh	r3, [r2, #10]
	ldr	r3, .L20+12
	ldrh	r1, [r2, #10]
	and	r3, r3, r1
	strh	r3, [r2, #10]
	ldrh	r3, [r2, #10]
	sub	sp, sp, #4
	ldr	r2, .L20+16
	ldr	r3, .L20+20
	strh	r2, [r3]
	mov	r0, sp
	mov	r5, #0
	mov	r1, #192
	str	r5, [r0]
	ldr	r3, .L20+24
	lsl	r1, r1, #18
	ldr	r2, .L20+28
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	bl	ClearHeap
	bl	InitRAMLib
	ldr	r3, .L20+32
	str	r5, [r3]
	ldr	r3, .L20+36
	strb	r5, [r3]
	ldr	r3, .L20+40
	strb	r5, [r3]
	ldr	r3, .L20+44
	strb	r5, [r3]
	bl	SetRAMBuildDate
	bl	Func_800479c
	bl	ClearVRAM
	ldrh	r3, .L20
	mov	r2, #128
	lsl	r2, r2, #19
	strh	r3, [r2]
	mov	r0, #0
	ldr	r2, .L20+48
	mov	r1, #1
	bl	SetIntrHandler
	ldr	r2, .L20+52
	ldr	r3, .L20+56
	strh	r2, [r3]
	bl	_InitSoundEngine
	bl	ClearSprites
	bl	ClearTasks
	ldr	r3, .L20+60
	ldr	r2, .L20+64
	str	r5, [r3]
	mov	r3, #1
	strb	r3, [r2]
	ldr	r3, .L20+68
	mov	r0, #10
	strb	r5, [r3]
	bl	WaitFrames
	mov	r0, #0
	b	.L21
.L22:
	.align	2, 0
.L20:
	.word	320
	.word	67109040
	.word	50687
	.word	32767
	.word	16404
	.word	67109380
	.word	67109076
	.word	-2063589888
	.word	gDMATaskCount
	.word	iwram_3001ac4
	.word	gDebugMode
	.word	iwram_3001f58
	.word	VBlank
	.word	49167
	.word	67109170
	.word	gIWRAMHeap_end
	.word	iwram_3001d18
	.word	iwram_3001ca0
.L21:
	bl	_GameStart
	add	sp, sp, #4
	pop	{r5}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 AgbMain,.Lfe1-AgbMain
	.align	2, 0
	.global	Unused_WaitForever
	.thumb_func
	.type	 Unused_WaitForever,function
Unused_WaitForever:
	push	{r5, lr}
	ldr	r5, .L27
.L24:
	mov	r0, #1
	ldr	r3, [r5]
	bl	WaitFrames
	b	.L24
.L28:
	.align	2, 0
.L27:
	.word	gKeyPress
.Lfe2:
	.size	 Unused_WaitForever,.Lfe2-Unused_WaitForever
	.align	2, 0
	.global	Func_8002ef8
	.thumb_func
	.type	 Func_8002ef8,function
Func_8002ef8:
	bx	lr
.Lfe3:
	.size	 Func_8002ef8,.Lfe3-Func_8002ef8
	.align	2, 0
	.global	Func_8002efc
	.thumb_func
	.type	 Func_8002efc,function
Func_8002efc:
	bx	lr
.Lfe4:
	.size	 Func_8002efc,.Lfe4-Func_8002efc
	.align	2, 0
	.global	Func_8002f00
	.thumb_func
	.type	 Func_8002f00,function
Func_8002f00:
	bx	lr
.Lfe5:
	.size	 Func_8002f00,.Lfe5-Func_8002f00
	.align	2, 0
	.global	Func_8002f04
	.thumb_func
	.type	 Func_8002f04,function
Func_8002f04:
	bx	lr
.Lfe6:
	.size	 Func_8002f04,.Lfe6-Func_8002f04
	.align	2, 0
	.global	Func_8002f08
	.thumb_func
	.type	 Func_8002f08,function
Func_8002f08:
	bx	lr
.Lfe7:
	.size	 Func_8002f08,.Lfe7-Func_8002f08
	.align	2, 0
	.global	Func_8002f0c
	.thumb_func
	.type	 Func_8002f0c,function
Func_8002f0c:
	mov	r0, #0
	bx	lr
.Lfe8:
	.size	 Func_8002f0c,.Lfe8-Func_8002f0c
