@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_bffb8_a_c_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_80c08a8
	.thumb_func
	.type	 Func_80c08a8,function
Func_80c08a8:
	push	{r5, lr}
	mov	r1, #168
	lsl	r1, r1, #2
	mov	r0, #10
	sub	sp, sp, #4
	bl	galloc_ewram
	ldr	r3, .L11
	mov	r1, r0
	mov	r4, #0
	mov	r0, sp
	ldr	r5, [r3]
	str	r4, [r0]
	ldr	r3, .L11+4
	ldr	r2, .L11+8
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	str	r4, [r5, #8]
	add	sp, sp, #4
	pop	{r5}
	pop	{r0}
	bx	r0
.L12:
	.align	2, 0
.L11:
	.word	iwram_3001f00
	.word	67109076
	.word	-2063597400
.Lfe1:
	.size	 Func_80c08a8,.Lfe1-Func_80c08a8
