@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	LearnInnateMove
	.thumb_func
	.type	 LearnInnateMove,function
LearnInnateMove:
	push	{r5, r6, lr}
	mov	r6, r1
	mov	r5, r0
	bl	_GiveInnateMove
	mov	r0, #83
	bl	_PlaySound
	mov	r0, r5
	mov	r1, #1
	bl	_Func_8019908
	mov	r0, r6
	mov	r1, #4
	bl	_Func_8019908
	ldr	r0, .L3
	mov	r1, #3
	bl	_Func_801776c
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L4:
	.align	2, 0
.L3:
	.word	_MSG_LEARN_INNATE_MOVE
.Lfe1:
	.size	 LearnInnateMove,.Lfe1-LearnInnateMove
