@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_c_a.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8092208
	.thumb_func
	.type	 Func_8092208,function
Func_8092208:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	mov	r7, r0
	mov	r8, r1
	mov	sl, r2
	bl	GetFieldActor
	mov	r6, r0
	cmp	r6, #0
	beq	.L2
	mov	r2, #10
	ldrsh	r3, [r6, r2]
	mov	r5, r3
	cmp	r3, #0
	bge	.L4
	add	r5, r5, #15
.L4:
	asr	r5, r5, #4
	lsl	r5, r5, #4
	mov	r2, r6
	add	r2, r2, #91
	sub	r5, r3, r5
	mov	r3, #0
	strb	r3, [r2]
	mov	r0, r6
	bl	_Actor_Stop
	lsl	r5, r5, #16
	mov	r0, r6
	mov	r1, #2
	bl	_Actor_SetAnim
	asr	r5, r5, #16
	mov	r3, #8
	ldr	r1, [r6, #8]
	sub	r3, r3, r5
	lsl	r3, r3, #16
	add	r1, r1, r3
	ldr	r2, [r6, #12]
	ldr	r3, [r6, #16]
	mov	r0, r6
	bl	_Actor_TravelTo
	mov	r0, r6
	bl	_Actor_WaitMovement
	mov	r0, r7
	mov	r1, r8
	bl	Func_8092b08
	mov	r3, sl
	lsl	r0, r3, #16
	ldr	r3, [r6, #16]
	ldr	r1, [r6, #8]
	add	r3, r3, r0
	ldr	r2, [r6, #12]
	mov	r0, r6
	bl	_Actor_TravelTo
.L2:
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 Func_8092208,.Lfe1-Func_8092208
