@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_91584_c_c_a_c_a_c_c_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	SetDestMap2
	.thumb_func
	.type	 SetDestMap2,function
SetDestMap2:
	ldr	r3, .L3
	ldr	r2, [r3]
	ldr	r3, .L3+4
	mov	ip, r3
	mov	r3, #224
	lsl	r3, r3, #1
	add	r3, r3, ip
	strh	r0, [r3]
	mov	r3, #225
	lsl	r3, r3, #1
	add	r3, r3, ip
	strh	r1, [r3]
	mov	r3, #184
	lsl	r3, r3, #1
	add	r2, r2, r3
	ldr	r3, .L3+8
	strh	r3, [r2]
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	iwram_3001ebc
	.word	gState
	.word	999
.Lfe1:
	.size	 SetDestMap2,.Lfe1-SetDestMap2
