@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_5cf8_a_a_a_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8005e88
	.thumb_func
	.type	 Func_8005e88,function
Func_8005e88:
	ldr	r0, .L3+16
	ldrh	r4, .L3
	ldr	r1, .L3+20
	strh	r4, [r0]
	ldr	r3, .L3+24
	ldrh	r2, [r1]
	and	r3, r3, r2
	strh	r3, [r1]
	ldrh	r3, .L3+4
	ldr	r2, .L3+28
	strh	r3, [r0]
	ldrh	r3, .L3+8
	strh	r3, [r2]
	ldr	r3, .L3+32
	sub	r2, r2, #28
	str	r3, [r2]
	ldrh	r3, .L3+12
	add	r2, r2, #246
	strh	r3, [r2]
	ldr	r3, .L3+36
	strb	r4, [r3, #8]
	b	.L4
.L5:
	.align	2, 0
.L3:
	.word	0
	.word	1
	.word	8195
	.word	192
	.word	67109384
	.word	67109376
	.word	65343
	.word	67109160
	.word	51555
	.word	ewram_2002240
.L4:
	bx	lr
.Lfe1:
	.size	 Func_8005e88,.Lfe1-Func_8005e88
