@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_941_2009a0c
	.thumb_func
	.type	 OvlFunc_941_2009a0c,function
OvlFunc_941_2009a0c:
	push	{r5, lr}
	ldr	r3, .L9
	mov	r2, #224
	ldr	r3, [r3]
	mov	r5, #129
	lsl	r2, r2, #1
	lsl	r5, r5, #2
	str	r5, [r3, r2]
	ldr	r3, .L9+4
	ldrsh	r2, [r3, r2]
	ldr	r3, .L9+8
	cmp	r2, r3
	bne	.L3
	mov	r0, #8
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #9
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #10
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #11
	bl	__MapActor_GetActor
	mov	r1, #0
	bl	__Actor_SetSpriteFlags
	mov	r0, #11
	bl	__MapActor_GetActor
	ldr	r3, .L9+12
	str	r3, [r0, #28]
	ldr	r0, .L9+16
	bl	__GetFlag
	cmp	r0, #0
	beq	.L4
	bl	OvlFunc_941_2008210
.L4:
	ldr	r0, .L9+20
	bl	__GetFlag
	cmp	r0, #0
	beq	.L5
	bl	OvlFunc_941_2008384
.L5:
	mov	r0, #128
	lsl	r0, r0, #2
	bl	__GetFlag
	cmp	r0, #0
	beq	.L6
	bl	OvlFunc_941_20080d4
.L6:
	ldr	r0, .L9+24
	bl	__GetFlag
	cmp	r0, #0
	beq	.L7
	mov	r0, #11
	mov	r1, #5
	bl	__MapActor_SetAnim
.L7:
	mov	r0, r5
	bl	__GetFlag
	cmp	r0, #0
	beq	.L3
	mov	r0, #9
	mov	r1, #5
	bl	__MapActor_SetAnim
.L3:
	mov	r0, #0
	pop	{r5}
	pop	{r1}
	bx	r1
.L10:
	.align	2, 0
.L9:
	.word	iwram_3001ebc
	.word	gState
	.word	_AREA_6a
	.word	62259
	.word	513
	.word	514
	.word	515
.Lfe1:
	.size	 OvlFunc_941_2009a0c,.Lfe1-OvlFunc_941_2009a0c

	.text
	.align	2, 0
