@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_c_c_c_c_a_c.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_941_2009760
	.thumb_func
	.type	 OvlFunc_941_2009760,function
OvlFunc_941_2009760:
	push	{r5, lr}
	mov	r1, #160
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #1
	bl	__Func_8092adc
	ldr	r5, .L10
	mov	r0, r5
	bl	__MessageID
	mov	r0, #1
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #3
	mov	r0, #2
	bl	__MapActor_DoAnim
	add	r0, r5, #1
	bl	__MessageID
	mov	r0, #2
	mov	r1, #0
	bl	__ActorMessage
	mov	r2, #0
	mov	r0, #13
	mov	r1, #2
	bl	__Func_809280c
	mov	r1, #3
	mov	r0, #13
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	add	r0, r5, #2
	bl	__MessageID
	mov	r0, #13
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #192
	mov	r2, #0
	mov	r0, #12
	lsl	r1, r1, #6
	bl	__Func_8092adc
	mov	r1, #3
	mov	r0, #12
	bl	__MapActor_DoAnim
	add	r5, r5, #3
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, r5
	bl	__MessageID
	mov	r0, #12
	mov	r1, #0
	bl	__ActorMessage
	mov	r1, #3
	mov	r0, #13
	bl	__MapActor_DoAnim
	mov	r0, #20
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r1, #3
	mov	r0, #3
	bl	__MapActor_SetAnim
	mov	r0, #80
	bl	__CutsceneWait
	mov	r1, #16
	mov	r2, #0
	neg	r1, r1
	mov	r0, #13
	bl	__Func_809228c
	mov	r0, #13
	bl	__MapActor_WaitMovement
	mov	r1, #1
	mov	r0, #13
	bl	__MapActor_SetAnim
	mov	r0, #40
	bl	__CutsceneWait
	mov	r0, #13
	mov	r1, #3
	bl	__MapActor_DoAnim
	mov	r1, #160
	mov	r2, #0
	lsl	r1, r1, #7
	mov	r0, #13
	bl	__Func_8092adc
	mov	r0, #30
	bl	__CutsceneWait
	mov	r0, #0
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #1
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #2
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r0, #3
	mov	r1, #3
	bl	__MapActor_SetAnim
	mov	r2, #132
	mov	r1, #152
	lsl	r2, r2, #2
	mov	r0, #12
	bl	__Func_809218c
	mov	r0, #20
	bl	__CutsceneWait
	mov	r2, #132
	mov	r1, #160
	lsl	r2, r2, #2
	mov	r0, #13
	bl	__Func_809218c
	mov	r0, #12
	bl	__MapActor_WaitMovement
	mov	r2, #160
	mov	r1, #168
	lsl	r2, r2, #2
	mov	r0, #12
	bl	__Func_809218c
	mov	r0, #13
	bl	__MapActor_WaitMovement
	mov	r2, #160
	mov	r0, #13
	mov	r1, #168
	lsl	r2, r2, #2
	bl	__Func_809218c
	mov	r1, #160
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #160
	mov	r0, #2
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #160
	mov	r0, #3
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #160
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #20
	bl	__CutsceneWait
	mov	r1, #128
	mov	r0, #0
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #2
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	mov	r0, #3
	lsl	r1, r1, #7
	mov	r2, #0
	bl	__Func_8092adc
	mov	r1, #128
	lsl	r1, r1, #7
	mov	r2, #0
	mov	r0, #1
	bl	__Func_8092adc
	mov	r0, #200
	bl	__CutsceneWait
	mov	r0, #13
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #12
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #1
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L7
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #1
	bl	__MapActor_TravelTo
.L7:
	mov	r0, #1
	bl	__MapActor_WaitMovement
	mov	r0, #1
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #2
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L8
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #2
	bl	__MapActor_TravelTo
.L8:
	mov	r0, #2
	bl	__MapActor_WaitMovement
	mov	r0, #2
	mov	r1, #0
	mov	r2, #0
	bl	__MapActor_SetPos
	mov	r0, #3
	mov	r1, #2
	bl	__MapActor_SetAnim
	mov	r0, #0
	bl	__MapActor_GetActor
	cmp	r0, #0
	beq	.L9
	mov	r3, #10
	ldrsh	r1, [r0, r3]
	mov	r3, #18
	ldrsh	r2, [r0, r3]
	mov	r0, #3
	bl	__MapActor_TravelTo
.L9:
	mov	r0, #3
	bl	__MapActor_WaitMovement
	mov	r1, #0
	mov	r2, #0
	mov	r0, #3
	bl	__MapActor_SetPos
	mov	r0, #30
	bl	__CutsceneWait
	mov	r1, #16
	mov	r2, #0
	neg	r1, r1
	mov	r0, #0
	bl	__Func_809228c
	mov	r0, #0
	bl	__MapActor_WaitMovement
	mov	r0, #0
	mov	r1, #1
	bl	__Func_8093500
	mov	r2, #160
	mov	r1, #168
	lsl	r2, r2, #2
	mov	r0, #0
	bl	__Func_809218c
	mov	r0, #60
	bl	__CutsceneWait
	bl	__MapTransitionOut
	mov	r0, #3
	bl	__Func_8091e9c
	pop	{r5}
	pop	{r0}
	bx	r0
.L11:
	.align	2, 0
.L10:
	.word	9560
.Lfe1:
	.size	 OvlFunc_941_2009760,.Lfe1-OvlFunc_941_2009760

	.text
	.align	2, 0
