@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_56cc_a_a_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_8005810
	.thumb_func
	.type	 Func_8005810,function
Func_8005810:
	push	{r5, r6, lr}
	ldr	r3, .L14
	sub	sp, sp, #64
	ldr	r2, [r3]
	mov	r6, #0
	mov	r5, #0
	mov	r1, sp
.L6:
	ldrb	r3, [r2]
	add	r2, r2, #1
	cmp	r3, #0
	bne	.L5
	stmia	r1!, {r5}
	add	r6, r6, #1
.L5:
	add	r5, r5, #1
	cmp	r5, #15
	bls	.L6
	mov	r5, #16
	cmp	r6, #0
	beq	.L9
	cmp	r6, #1
	bne	.L10
	ldr	r5, [sp]
	bl	Func_8005b24
	cmp	r0, #16
	bne	.L9
	mov	r5, #16
	b	.L9
.L10:
	bl	Random
	mov	r1, r6
	bl	__umodsi3
	mov	r5, r0
	mov	r2, sp
	lsl	r3, r5, #2
	ldr	r5, [r2, r3]
.L9:
	mov	r0, r5
	add	sp, sp, #64
	pop	{r5, r6}
	pop	{r1}
	bx	r1
.L15:
	.align	2, 0
.L14:
	.word	iwram_3001f1c
.Lfe1:
	.size	 Func_8005810,.Lfe1-Func_8005810

	.text
	.align	2, 0
