@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"rom_3650_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	Func_800383c
	.thumb_func
	.type	 Func_800383c,function
Func_800383c:
	push	{r5, r6, lr}
	ldr	r4, .L29
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L29+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L23
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #128
	lsl	r2, r2, #9
	str	r2, [r3]
.L23:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L30:
	.align	2, 0
.L29:
	.word	gDMATaskCount
	.word	67109384
.Lfe1:
	.size	 Func_800383c,.Lfe1-Func_800383c
	.align	2, 0
	.global	SetRegAnimDest
	.thumb_func
	.type	 SetRegAnimDest,function
SetRegAnimDest:
	push	{r5, r6, lr}
	ldr	r4, .L42
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L42+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L36
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #128
	lsl	r2, r2, #10
	str	r2, [r3]
.L36:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L43:
	.align	2, 0
.L42:
	.word	gDMATaskCount
	.word	67109384
.Lfe2:
	.size	 SetRegAnimDest,.Lfe2-SetRegAnimDest
	.align	2, 0
	.global	Func_80038bc
	.thumb_func
	.type	 Func_80038bc,function
Func_80038bc:
	push	{r5, r6, lr}
	ldr	r4, .L55
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L55+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L49
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #192
	lsl	r2, r2, #10
	str	r2, [r3]
.L49:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L56:
	.align	2, 0
.L55:
	.word	gDMATaskCount
	.word	67109384
.Lfe3:
	.size	 Func_80038bc,.Lfe3-Func_80038bc
	.align	2, 0
	.global	Func_80038fc
	.thumb_func
	.type	 Func_80038fc,function
Func_80038fc:
	push	{r5, r6, lr}
	ldr	r4, .L68
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L68+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L62
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #160
	lsl	r2, r2, #11
	str	r2, [r3]
.L62:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L69:
	.align	2, 0
.L68:
	.word	gDMATaskCount
	.word	67109384
.Lfe4:
	.size	 Func_80038fc,.Lfe4-Func_80038fc
	.align	2, 0
	.global	Func_800393c
	.thumb_func
	.type	 Func_800393c,function
Func_800393c:
	push	{r5, r6, lr}
	ldr	r4, .L81
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L81+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L75
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #192
	lsl	r2, r2, #11
	str	r2, [r3]
.L75:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L82:
	.align	2, 0
.L81:
	.word	gDMATaskCount
	.word	67109384
.Lfe5:
	.size	 Func_800393c,.Lfe5-Func_800393c
	.align	2, 0
	.global	Func_800397c
	.thumb_func
	.type	 Func_800397c,function
Func_800397c:
	push	{r5, r6, lr}
	ldr	r4, .L94
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L94+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L88
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #224
	lsl	r2, r2, #11
	str	r2, [r3]
.L88:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L95:
	.align	2, 0
.L94:
	.word	gDMATaskCount
	.word	67109384
.Lfe6:
	.size	 Func_800397c,.Lfe6-Func_800397c
	.align	2, 0
	.global	Func_80039bc
	.thumb_func
	.type	 Func_80039bc,function
Func_80039bc:
	push	{r5, r6, lr}
	ldr	r4, .L107
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L107+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L101
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #144
	lsl	r2, r2, #12
	str	r2, [r3]
.L101:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L108:
	.align	2, 0
.L107:
	.word	gDMATaskCount
	.word	67109384
.Lfe7:
	.size	 Func_80039bc,.Lfe7-Func_80039bc
	.align	2, 0
	.global	Func_80039fc
	.thumb_func
	.type	 Func_80039fc,function
Func_80039fc:
	push	{r5, r6, lr}
	ldr	r4, .L120
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L120+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L114
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #160
	lsl	r2, r2, #12
	str	r2, [r3]
.L114:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L121:
	.align	2, 0
.L120:
	.word	gDMATaskCount
	.word	67109384
.Lfe8:
	.size	 Func_80039fc,.Lfe8-Func_80039fc
	.align	2, 0
	.global	Func_8003a3c
	.thumb_func
	.type	 Func_8003a3c,function
Func_8003a3c:
	push	{r5, r6, lr}
	ldr	r4, .L133
	.code	16
	mov	r6, r0
	mov	r0, r1
	ldr	r1, .L133+4
	ldrh	r3, [r1]
	mov	r5, r3
	strh	r1, [r1]
	ldrh	r2, [r4]
	cmp	r2, #31
	bgt	.L127
	lsl	r3, r2, #1
	add	r3, r3, r2
	lsl	r3, r3, #2
	add	r3, r3, r4
	add	r3, r3, #4
	stmia	r3!, {r0}
	add	r2, r2, #1
	strh	r2, [r4]
	stmia	r3!, {r6}
	mov	r2, #176
	lsl	r2, r2, #12
	str	r2, [r3]
.L127:
	strh	r5, [r1]
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.L134:
	.align	2, 0
.L133:
	.word	gDMATaskCount
	.word	67109384
.Lfe9:
	.size	 Func_8003a3c,.Lfe9-Func_8003a3c
	.align	2, 0
	.global	UploadPalette
	.thumb_func
	.type	 UploadPalette,function
UploadPalette:
	push	{r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r8
	push	{r6, r7}
	ldr	r6, .L138
	ldrh	r5, [r6]
	mov	r7, sp
	cmp	r5, #0
	beq	.L136
	ldr	r2, .L138+4
	mov	r1, #0
	lsr	r2, r2, #2
	lsl	r3, r2, #2
	mov	sl, r1
	mov	r4, #132
	mov	r1, sp
	sub	r1, r1, r3
	lsl	r4, r4, #24
	mov	r8, sp
	ldr	r3, .L138+8
	mov	sp, r1
	ldr	r0, .L138+12
	orr	r2, r2, r4
	stmia	r3!, {r0, r1, r2}
	sub	r3, #0xc
	.code	16
	mov	r0, r6
	mov	r1, r5
	bl	_call_via_sp
	mov	r3, sl
	strh	r3, [r6]
	mov	sp, r8
.L136:
	mov	sp, r7
	pop	{r3, r5}
	mov	r8, r3
	mov	sl, r5
	pop	{r5, r6, r7}
	pop	{r0}
	bx	r0
.L139:
	.align	2, 0
.L138:
	.word	gDMATaskCount
	.word	_UPLOAD_PALETTE_SIZE
	.word	67109076
	.word	UploadPalette_ROM
.Lfe10:
	.size	 UploadPalette,.Lfe10-UploadPalette

	.text
	.align	2, 0
