@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_30_c_a_c_c_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_973_20080a0
	.thumb_func
	.type	 OvlFunc_973_20080a0,function
OvlFunc_973_20080a0:
	push	{r5, r6, lr}
	mov	r5, r0
	mov	r6, r1
	bl	__GetUnit
	ldrb	r1, [r0, #15]
	mov	r0, r5
	add	r1, r1, r6
	bl	__SetMinLevel
	mov	r0, r5
	bl	__CalcStats
	pop	{r5, r6}
	pop	{r0}
	bx	r0
.Lfe1:
	.size	 OvlFunc_973_20080a0,.Lfe1-OvlFunc_973_20080a0

	.text
	.align	2, 0
