@ Generated by gcc 2.96 20000731 (experimental) for ARM/elf
	.file	"ovl_314_a_b.c"
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.global	OvlFunc_929_2008314
	.thumb_func
	.type	 OvlFunc_929_2008314,function
OvlFunc_929_2008314:
	ldr	r0, .L3
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gOvl_02008778
.Lfe1:
	.size	 OvlFunc_929_2008314,.Lfe1-OvlFunc_929_2008314

	.text
	.align	2, 0
